### DISCUSSION TITLE
Apply service timeout

### DISCUSSION THREAD

**Discussion by mbaylet** [Kong/kong#10042] [Help]
Hi,

I struggled to get my timeout configuration applied on the latest KIC (2.8) based on the current documentation:
https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/#konghqcomread-timeout
here is my service anotation:
```
apiVersion: v1
kind: Service
metadata:
  name: MyApp
  annotations:
    konghq.com/connect-timeout: "180000"
    konghq.com/write-timeout: "180000"
    konghq.com/read-timeout: "180000"
```
 Unfortunately, even with this settings, my request hit a 504 timeout after 60 seconds.
My ingress is managed by kong and the service is fully reachable.
Do i miss something ?
