### DISCUSSION TITLE
upgraded from 2.7 to 3.1, dictionary not found

### DISCUSSION THREAD

**Discussion by J1a-wei** [Kong/kong#10102] [Help]
We run kong in kubernetes.  Upgrade kong chart from 2.7 into 2.14 by helm. 

Our plugin does not work properly. 

It's seems can't load crd reousrces  

```
[kong] policies.lua:337 dictionary not found, client: 100.168.42.200, server: kong_admin

337 line code. 
```lua
        set_token = function(conf, params)
            local red, err = db.connect_redis_cluster(conf)
            if err then
                kong.log.err(err)  // 337 line
                return err
            end
            local key = util.key_prefix .. params.token
            red:set(key, params.politic)
            return nil
```
Our crd resources:  
```
apiVersion: configuration.konghq.com/v1
config:
  policy: redis-cluster
  redis_service_list:
  - ip: redis-cluster
    port: 6379
  svc_namespace: kong-cluster-headless.kong
kind: KongClusterPlugin
metadata:
  annotations:
plugin: web3-gateway
```

Previously it was working in 2.7,  where this incompatibility occurred, any suggestions are greatly appreciated!
