### DISCUSSION TITLE
[DBless] Define targets which can belong to many upstreams

### DISCUSSION THREAD

**Discussion by hoangphuocbk** [Kong/kong#10228] [Help] [answered]
Hi, Kong folks.

I am using DB-less mode to define Kong API gateway’s resources. I have M upstreams (for each service), and behind each of them are N targets (In our architecture, Kong and App are deployed on different K8s cluster, so N is presented to number of worker nodes on App cluster).

If I defined resources, as normally I need to declare M upstreams and then M x N targets. It’s hard to maintain these resource in DB-less mode with Helm chart’s values.

So my question is about how to define efficiently a target that can belong to multiple upstreams or something that relate to tag or label to simplify my Helm chart’s values.

Hope somebody give me advice about that.

**Comment by fffonion** [comment, marked as answer]
@hoangphuocbk Generally speaking, kong's dbless config format allows you to write either nested entities or refereneced ones:

```yaml
targets:
- id: target_uuid1
   upstream:
     name: upstream1
     id: upstream_uuid1
```

can also be written as

```yaml
targets:
- id: target_uuid1
   upstream:
     id: upstream_uuid1

upstreams:
- id: upstream_uuid1
  name: upstream1
```

so you don't need to redefine a same upstream in your config; but we don't allow a same target to belong to different upstreams.
