### DISCUSSION TITLE
ip-restriction: ipv6 support

### DISCUSSION THREAD

**Discussion by wataruian** [Kong/kong#10428] [Help] [answered]
Hi, 

Is `ipv6` now supported in `ip-restriction`?

The docs mentioned that ipv6 is now supported: https://docs.konghq.com/hub/kong-inc/ip-restriction

But when trying to deny/allow ipv6 it does not work; but works on ipv4.

I tested this on my kubernetes cluster after installing from helm chart: `kong-2.16.5` and added the plugin on my ingress annotation: `konghq.com/plugins: ip-restriction`

My plugin config looks like this:
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ip-restriction
  namespace: kong
config:
  deny:
    - '0.0.0.0/0' # This will work and I cannot access the said service
    # if I change it to '::/0', it won't work and I can access the service
plugin: ip-restriction
```
