### DISCUSSION TITLE
Proxy-cache generating new cache-key even path is rewritten to lowercase in pre-function

### DISCUSSION THREAD

**Discussion by tobiasehlert** [Kong/kong#10425] [Help] [answered]
I am a bit curious how the [proxy-cache](https://docs.konghq.com/hub/kong-inc/proxy-cache/) plugin handles the caching.

I've implemented rewriting of the path (explained in [#7821](https://github.com/Kong/kong/discussions/7821#discussioncomment-5207164)). The path itself gets rewritten to lowercase and arrives at the upstream server in the correct format, but the [proxy-cache](https://docs.konghq.com/hub/kong-inc/proxy-cache/) plugin doesn't seem to care that the request is rewritten at all.

When I send following requests, all get sent to the upstream server (`x-cache-status: Miss`):
```plain
/api/greeting/tobias
/api/greeting/Tobias
/api/greeting/tObIaS
```

But when requesting one of them again, the [proxy-cache](https://docs.konghq.com/hub/kong-inc/proxy-cache/) plugin handles the request as a cached request and sends cached content (`x-cache-status: Hit`).

When checking in the [cache-key](https://docs.konghq.com/hub/kong-inc/proxy-cache/#cache-key) section of the [proxy-cache](https://docs.konghq.com/hub/kong-inc/proxy-cache/) plugin it says that calculated it based on a couple of parameters and my understanding would be that the _UUID_,  _method_ and _request_ part should be exactly the same and therefore result in the same key.
But it doesn't seem to do.. how comes? 🤔

**Comment by ghost** [comment, marked as answer]
It seems that the `implemented rewriting of the path` you tried didn't work?

**Reply by tobiasehlert** [reply]
@sabertobihwy the rewrite works since I can see in my application log at the backend, that all requests are coming in with lowercase.

**Reply by ghost** [reply]
https://github.com/Kong/kong/blob/af72943b6931bdcd72e54fa48cae9ba0863f2f15/kong/plugins/proxy-cache/handler.lua#L270-L277

the `uri` is from `ngx.var.request`,  and I remember this Nginx builtin var is unchanged. so we need to use another way make it workaround.

**Reply by tobiasehlert** [reply]
Ah okej @sabertobihwy!

I basically thought that it would be working, since the pre-function is a higher priority in the execution order of plugins mentioned [here](https://docs.konghq.com/gateway/latest/plugin-development/custom-logic/#kong-plugins).

Maybe it's possible to inject some nginx configuration that gets added in the kong section? 🤔

**Reply by ghost** [reply]
let me think about it 🤔

**Reply by ghost** [reply]
I did a quick verification.

my kong deck config is:

```yaml
_format_version: "3.0"
_transform: true

services:
- name: my-service
  url: http://192.168.31.100:1980
  plugins:
  - name: proxy-cache
    route: my-route
    config:
      response_code:
      - 200
      request_method:
      - GET
      content_type:
      - text/plain
      cache_ttl: 300
      strategy: memory
  routes:
  - name: my-route
    paths:
    - /

plugins:
  - name: pre-function
    config:
      access:
      - kong.service.request.set_path(string.lower(kong.request.get_path()))
```

and I logout the `uri` in proxy-cache plugin code.


#### 1

if I use

```
 curl http://127.0.0.1:8000/kong
```

to access kong, and I get logs in kong:

```
[warn] 12774#0: *149 [lua] handler.lua:271: uri : "GET /kong HTTP/1.1", client: 127.0.0.1, server: kong, request: "GET /kong HTTP/1.1", host: "127.0.0.1:8000"
 [warn] 12774#0: *149 [lua] handler.lua:280: cache_key : "c262555e29fb71e9bb1134564c8e130f53767c15452c187d4b9dc2f923a3ca41", client: 127.0.0.1, server: kong, request: "GET /kong HTTP/1.1", host: "127.0.0.1:8000"
```

and the access log in upstream is

```
[06/Mar/2023:17:33:12 +0800] "GET /kong HTTP/1.1" 200 20 "-" "curl/7.81.0"
```

#### 2
and if I use

```
 curl http://127.0.0.1:8000/KONG
```

to access kong, and I get logs in kong:

```
 [warn] 12774#0: *151 [lua] handler.lua:271: uri : "GET /KONG HTTP/1.1", client: 127.0.0.1, server: kong, request: "GET /KONG HTTP/1.1", host: "127.0.0.1:8000"
[warn] 12774#0: *151 [lua] handler.lua:280: cache_key : "bdac7402d44955b55ff5dd17ff96c21061cef2f1318c020ef8efee3a1bd05107", client: 127.0.0.1, server: kong, request: "GET /KONG HTTP/1.1", host: "127.0.0.1:8000"
```

and the access log in upstream is

```
[06/Mar/2023:17:33:28 +0800] "GET /kong HTTP/1.1" 200 20 "-" "curl/7.81.0"
```

I think this confirms that the uri used in computing the cache key remains unchanged even after applying the pre-function to convert it to lowercase. We need to explore other ways to achieve this, such as modifying the parameters used in computing the cache key.
