### DISCUSSION TITLE
Would configuring a plugin on multiple routes be inefficient?

### DISCUSSION THREAD

**Discussion by shahamit** [Kong/kong#10526] [Help]
We have a use case where we want to configure a plugin differently for each http header value. So we define multiple routes with same path but with different header value. Each route then has a different configuration of the plugin. 

Taking an example of the rate-limiting plugin below is how the kong configuration looks like in the yaml file. Note based on the header `x-user-id` value we are varying the rate limits applied on the api. Its a hypothetical use case but just shared for a discussion.

My question is - if configuring the same plugin would mean loading multiple instances of the plugin in memory leading to inefficiencies in any way when the kong server is under load. Any insights into this? 

Thanks.

```yaml
services:
  - name: local-leads-app
    url: http://localhost:8080/api/leads/v1
    routes:
      - name: local-leads-app-route-1
        paths:
          - /api/leads/v1
        strip_path: true
        headers:
          x-user-id: [ "v1" ]
        plugins:
          - name: rate-limiting
            config:
              minute: 5
              policy: local
      - name: local-leads-app-route-2
        paths:
          - /api/leads/v1
        strip_path: true
        headers:
          x-user-id: [ "v2" ]
        plugins:
          - name: rate-limiting
            config:
              minute: 100
              policy: local
```
