### DISCUSSION TITLE
Install the kong with datadog plugin to push metrics to datadog

### DISCUSSION THREAD

**Discussion by sarathpantala** [Kong/kong#11467] [Help]
this is kong values.yaml 
```

kong:
  admin:
    enabled: true
  proxy:
    enabled: true
    service:
      type: LoadBalancer # Set to NodePort or LoadBalancer as needed
  env:
   database: "off"
   datadog_agent_host: 
     valueFrom:
       fieldRef:
         fieldPath: status.hostIP
```

this is my plugin configuration
 ```
apiVersion: configuration.konghq.com/v1
 kind: KongClusterPlugin
 plugin: datadog
 metadata:
   name: datadog
   annotations:
     kubernetes.io/ingress.class: kong
   labels:
     global: "true"
 config:
   host: "{vault://env/kong-datadog-agent-host}"
   port: 8125
```

i am not getting metrics to datadog. (datadog is running as daemonset) but kong proxy is working fine. can anyone send me righ configuration
