### DISCUSSION TITLE
Best way to enable gzip_static in kong?

### DISCUSSION THREAD

**Discussion by MIJohnson** [Kong/kong#11476] [Help] [answered]
What is the correct way to enable gzip_static in kong so that I can serve up pre-zipped files? I know its an nginx module but it doesn't seem to be bundled with kong?

**Comment by hanshuebner** [comment, marked as answer]
@MIJohnson ngx_http_gzip_static_module must be enabled when nginx is built, so you cannot retroactively enable it when you're using one of our Docker images.  If you build Kong using bazel, you can add `--with-http_gzip_static_module` to the openresty build file before you build.  See this draft PR: https://github.com/Kong/kong/pull/11479

**Reply by MIJohnson** [reply]
@hanshuebner
(apologies for the previous comments that didn't make sense, I have removed them and hopefully this is more coherent follow up question) 

I have enabled gzip_static and can see it in the **server** section of **/usr/local/kong/nginx-kong.conf**

however I now realise this wont work because gzip_static cannot work with proxy pass and kong has the following:
```
location / {
#...various config...
proxy_pass $upstream_schema://kong_upstream$upstream_uri;
}
```

given a service in kong.yml such as

```
services:
  - name: myapp
    url: http://my-app-container:18080/app
    routes:
      - name: myapp
        hosts: [myapp.host.com]
        paths:
          - /myapp
          - /myapp/
        preserve_host: true
        protocols:
          - https
```

is there somewhere else I apply gzip_static upstream in kong so that it will look for the gzip files, or is my only recourse to find a way on my application side?
