### DISCUSSION TITLE
Unable to route an http service

### DISCUSSION THREAD

**Discussion by blaze225** [Kong/kong#11510] [Help]
Hi, I am running kong via the docker in dbless and declarative mode.
I am trying to route a service but I get the following error:
```
kong_saad  | 2023/09/05 09:02:04 [warn] 1256#0: *18649 using uninitialized "kong_proxy_mode" variable while logging request, client: 172.22.0.1, server: kong, request: "POST <API> HTTP/1.1", host: "<host>:<KONG_PORT>"
kong_saad  | 2023/09/05 09:02:04 [warn] 1256#0: *18649 [lua] reports.lua:94: log(): [reports] could not determine log suffix (scheme=http, proxy_mode=) while logging request, client: 172.22.0.1, server: kong, request: "POST <API> HTTP/1.1", host: "<host>:<KONG_PORT>"
kong_saad  | 172.22.0.1 - - [05/Sep/2023:09:02:04 +0000] "POST <API> HTTP/1.1" 400 220 "-" "python-requests/2.28.2"
```

**The service definition in the declarative config looks like:**
```
- name: quickwit
    url: http://quickwit:7282/api/v1/
    protocol: http
    routes:
    - name: test
      paths:
      - /api/v1/
      protocols:
      - https
      - http
```
  
**And the docker-compose definition for kong looks like:**
```
  kong:
    image: kong:3.1.1-alpine
    user: "${KONG_USER:-kong}"
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yml"
      KONG_NGINX_WORKER_PROCESSES: 12
      KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE: "1024m"
    ports:
      - "0.0.0.0:${KONG_PORT:-8443}:8443/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
      - ./kong/config:/opt/kong
    security_opt:
      - no-new-privileges
    networks:
      - some_network
    
```

What am I missing?
Would really appreciate some feedback.
