### DISCUSSION TITLE
Discrepancies between logged requests by the Kong and metrics in the Datadog

### DISCUSSION THREAD

**Discussion by piotr-maslanka** [Kong/kong#11671] [Help]
Hello. 
Recently we set up [Datadog plugin ](https://docs.konghq.com/hub/kong-inc/datadog/) and noticed some discrepancies between Kong requests logs and Datadog metrics provided by it.

Data gathered in our logs:
<img width="154" alt="logs" src="https://github.com/Kong/kong/assets/146197377/e90fb6dd-cfdf-4f08-834a-c64910e14de0">

Data from DD metrics:
<img width="1383" alt="metrics" src="https://github.com/Kong/kong/assets/146197377/b759cb38-59c0-48a8-ba22-b0bfc7bea542">

As you can see we have two major problems:
- some types of requests are not available in the metrics at all (fe. ones with status 201, 308 etc.)
- number of requests in the logs and in the metrics are not the same

Our Kong version is 3.2 (upgraded from 3.1 to mitigate this issue: https://github.com/Kong/kong/pull/10044)
Metrics plugin definition that we use:
```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
 name: datadog-plugin
 annotations:
  kubernetes.io/ingress.class: kong
 labels:
  global: "true"
config:
 host: localhost
 port: 8125
 flush_timeout: 2
 retry_count: 10
 prefix: kong
 metrics:
  - name: request_count
    stat_type: meter
    consumer_identifier: username
plugin: datadog
```
We already changed `stat_type` from `counter` to `meter` since it seems to better represent the actual number of requests after sending metrics to DD (counter was automatically converted to rate).

Additionally, we also use these plugins: jwt, request-transformer, response-transformer, our own custom plugin.

Is it some kind of bug, misconfiguration on our side or maybe there is some kind of logic regarding which requests should be provided in the metrics (and which shouldn't)?
