### DISCUSSION TITLE
How about increase opentelemetry plugin's plugin ordering?

### DISCUSSION THREAD

**Discussion by DingGGu** [Kong/kong#11734] [Ideas and feature requests]
Hello there,

With OpenTelemetry plugin with `(header_type: aws)` option can extract and use `X-Amzn-Trace-Id` Header.

```yaml
- name: opentelemetry
  config:
    endpoint: 
    headers:
      api-key: 
    resource_attributes:
      service.name: ${CONFIG_OTEL_SERVICE_NAME}
    header_type: aws
```

This makes helpful for match between trace in APM tools and AWS LB access log.

However, My custom plugin has priority = 1000, So that plugin cannot get root's traceId, because opentelemtetry's plugin prioirty was 14. As you know, traceId was save `kong.ctx.plugin.trace_id` after opentelemetry plugin was executed.
In order to [Plugin ordering document](https://docs.konghq.com/konnect/reference/plugins/). Opentelemetry Plugin order was 14. I think this is too low.

1. What is your think about increasing opentelemetry plugin's priority?
In last days, zipkin plugin is the most highest priority.

2. How about your think about decrase my plugin to negative prioirity?
