### DISCUSSION TITLE
Unclear behavior when multiple JWTs are provided using different methods. Help?

### DISCUSSION THREAD

**Discussion by mikeholler** [Kong/kong#11760] [Help]
The [Kong JWT plugin](https://docs.konghq.com/hub/kong-inc/jwt/) describes three ways to provide JWTs: a cookie, a query string parameter, or a header. Unfortunately, it doesn't describe what happens when multiple are provided.

Take the following config:

```yaml
config:
  uri_param_names:
    - token1
    - token2
  header_names:
    - token3
    - token4
  cookie_names:
    - token5
    - token6
```

What happens when all locations are populated by a valid (but different) token? What is the priority on the order they are resolved and tested? What if an invalid token is found? Does it go through invalid tokens until it finds one invalid token (or runs out) or does it fail fast on the first invalid token?

We'd like to include this documentation in our product, but as it isn't documented in Kong, this is challenging. Can you help answer?
