### DISCUSSION TITLE
Kong GRPC-Gateway (helm) how to reload protofile lookup

### DISCUSSION THREAD

**Discussion by theocerutti** [Kong/kong#11770] [Help]
Hello,

I am using helm kong/ingress chart and every time I modify my proto files I have to completely delete my kong-proxy and restart it otherwise my grpc calls doesn't works.

My Kong helm config is:

```yml
...
gateway:
  enabled: true
  deployment:
    kong:
      enabled: true
    userDefinedVolumes:
     - name: "grpc-proto-shared-pvc"
       hostPath:
         path: "/usr/include/grpc-proto-shared/services"
    userDefinedVolumeMounts:
     - name: "grpc-proto-shared-pvc"
       mountPath: "/usr/include/"
...
```
