### DISCUSSION TITLE
Custom Plugin hierarchy configurations

### DISCUSSION THREAD

**Discussion by flowdopip** [Kong/kong#12047] [Help] [answered]
Hello,

How can I add this kind of setting? A few settings will be the same for all configurations, and we don´t want to repeat in each service/route.

Any idea for that.

```yaml
_format_version: "3.0"
_comment: "Global Plugins"
plugins:
  - name: my-custom
    config:
      generic_config1: xxx
      generic_config2: yyy
      generic_config3: 123
services:
- name: my-service
  url: http://echo-server/
  protocol:
  - http
  connect_timeout: 10000
  read_timeout: 10000
  write_timeout: 10000
  retries: 3
  routes:
  - name: my-service-route
    strip_path: true
    paths:
    - ~/(?i)v1/test
    protocols:
    - http
    methods:
    - GET
    - POST
    plugins:
      - name: my-custom
        config:
          specific_config1:
          - 123
          specific_config2:
          - XXX
          - YYY
```
