### DISCUSSION TITLE
Allow Header to be persist through out the session

### DISCUSSION THREAD

**Discussion by Ajeeshb** [Kong/kong#12177] [Help]
My configuration details:
EKS= v1.28.3-eks-e71965b
Kong=kong:3.4

I am in the process of migrating my API gateway from Emissary to Kong. I have successfully created an application migration. I have one scenario/issue like below,
After validating the user token on our JWT microservice we will add that user ID to the header for a particular session. How can I do that? in Emissary done it using the below steps.

```
apiVersion: getambassador.io/v3alpha1
kind: AuthService
metadata:
  name: my-auth
spec:
  auth_service: "my-custom-jwt-auth-svc"
  proto: http
  timeout_ms: 2000
  status_on_error:
    code: 403
  path_prefix: "/v1/validate"
  allowed_authorization_headers:
  - "myauth-userid"
  add_linkerd_headers: false
  failure_mode_allow: true
```
