### DISCUSSION TITLE
How to obtain latency information for Kong plugin execution time

### DISCUSSION THREAD

**Discussion by roskh** [Kong/kong#12178] [Help]
Greetings,

We have Kong configured as a proxy/API gateway and we'd like to obtain the execution time for Kong plugins, more specifically the plugins and code that runs before a request is forwarded upstream as we have been facing some latency issues and would like to diagnose the issues more accurately.

[According to file-log](https://docs.konghq.com/hub/kong-inc/file-log/#json-object-considerations) plugin the `latency.kong` is close to what we need but the latency also includes the time it took to download the bytes from the upstream response which in some cases can take a long time (and also be correct behaviour) which can complicate the diagnosis.

From looking at the [kong source code](https://github.com/Kong/kong/blob/2784bf54d8cbf3dbffe743837c1cbac2338c69f3/kong/pdk/log.lua#L844-L845) it seem like the following should do the trick?

```yaml
  - name: file-log
    config:
      path: "/tmp/logs/file-log.json"
      custom_fields_by_lua: 
        kong-plugin-latency: "return (ngx.ctx.KONG_PROXY_LATENCY or ngx.ctx.KONG_RESPONSE_LATENCY or 0)"
```

Would this be the correct interpretation `KONG_PROXY_LATENCY`?
