### DISCUSSION TITLE
Is there a way to set the Secure flag to the Load Balancer cookie

### DISCUSSION THREAD

**Discussion by john-hu** [Kong/kong#12262] [Help] [answered]
Hi all,

We use the following resource to load balance our Web Socket service:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: cookie-balancer
upstream:
  hash_on_cookie: "sessionAffinity"
  hash_on: "cookie"
  hash_fallback: "none"
  hash_on_cookie_path: "/"
```
It works very well with the sample cookie like this `sessionAffinity=b34a9a65-b303-4ac3-aa67-0dd129803748; Path=/; Same-Site=Lax; HttpOnly`.

Recently, we would like to add the Secure flag to have the cookie look like: `sessionAffinity=b34a9a65-b303-4ac3-aa67-0dd129803748; Path=/; Same-Site=Lax; HttpOnly; Secure`.

I checked the [doc](https://docs.konghq.com/gateway/3.4.x/how-kong-works/load-balancing/#balancing-algorithms) and [KongIngress reference](https://docs.konghq.com/kubernetes-ingress-controller/latest/reference/custom-resources/#kongingressupstream) without any lucks.

May we know if there is a way to set the Secure flag to the cookie generated by the KongIngress load balancer?
