### DISCUSSION TITLE
Prevent Basic Auth prompt many times in sub-domains

### DISCUSSION THREAD

**Discussion by duylddev** [Kong/kong#12335] [Help]
I config Kong ingress basic auth for all public domain and sub-domains like this

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "kong"
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "308"
    konghq.com/plugins: basic-auth
spec:
  ingressClassName: kong
  rules:
    - host: domain.com
      ....
   - host: sub2.domain.com
      .....
   - host: sub3.domain.com
      .....
    - host: sub4.domain.com
      .....
```

The problem is I have to input basic auth prompt many times, or sometimes it keep getting error if sub-domain is called via xhr or ws request.
How Kong support remember user for all domains in ingress config, so when I go to domain.com and input basic auth, other sub-domains will not need to input basic auth again?
