### DISCUSSION TITLE
Prometheus plugin stopped scrapping metrics after creating customize metrics in rate limit plugin, i am using a KongClusterPlugin resource in a Kubernetes environment to configure the Prometheus plugin for Kong

### DISCUSSION THREAD

**Discussion by vanigupta82** [Kong/kong#12386] [Help]
Prometheus plugin:

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-prometheus
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: {{ .Values.plugins.prometheus.global | quote }}
    app.kubernetes.io/name: {{ include "kong.name" . }}
    helm.sh/chart: {{ include "kong.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
plugin: prometheus
```

Rate limit plugin handler file :
````
 local timestamp = require "kong.tools.timestamp"
local exporter = require "kong.plugins.prometheus.exporter"
local prometheus

RateLimitingHandler.VERSION = kong_meta.version
RateLimitingHandler.PRIORITY = 910

function RateLimitingHandler:init_worker()
  -- Register your custom metrics with the Prometheus plugin
  prometheus = exporter.get_prometheus()
  if prometheus then
    prometheus:counter("custom_rate_limit_remaining_quota", "Remaining quota for rate limiting", 0)
  else
    kong.log.err("Prometheus library is not available")
  end
end

local function get_usage(conf, identifier, current_timestamp, limits)
  local usage = {}
  local stop
  local metric_name = "custom_rate_limit_remaining_quota_" .. current_timestamp .. "_" .. identifier
  for period, limit in pairs(limits) do
    local current_usage, err = policies[conf.policy].usage(conf, identifier, period, current_timestamp)
    if err then
      return nil, nil, err
    end

    -- What is the current usage for the configured limit name?
    local remaining = limit - current_usage
    prometheus:counter(metric_name, "Remaining quota for rate limiting", remaining)
    -- Recording usage
    usage[period] = {
      limit = limit,
      remaining = remaining,
    }
   
    if remaining <= 0 then
      stop = period
    end
  end

  return usage, stop
end


local function get_identifier(conf)
 --- some logic to find identifier
end

function RateLimitingHandler:access(conf)
  local current_timestamp = time() * 1000

  -- Consumer is identified by ip address or authenticated_credential id
  local identifier = get_identifier(conf)
  kong.log.info("identifier from the kong request :", identifier)

  local fault_tolerant = conf.fault_tolerant
  
  local limits = get_limits(conf, identifier)
  
  -- apply_rate_limits(conf, identifier, limits, current_timestamp)
  local dotCount = select(2, identifier:gsub("%.", ""))
  
  local usage, stop, err = get_usage(conf, identifier, current_timestamp, limits)
  
end
 
return RateLimitingHandler
``
```
