### DISCUSSION TITLE
Kong Prometheus Plugin: Metrics Not Showing for Specific Services

### DISCUSSION THREAD

**Discussion by AshutoshM10** [Kong/kong#12462] [Help]
I recently set up Grafana with Kong and Prometheus in my staging environment. The goal is to monitor key metrics such as 500 error reports, API response times, identification of slow APIs, and tracking the hottest APIs in terms of hits.

### Configuration Details
- Kong Image: kong/kong-gateway:3.4.0.0
- Prometheus Plugin Configuration:
```
{
  "instance_name": "name",
  "name": "prometheus",
  "consumer": null,
  "enabled": true,
  "config": {
    "per_consumer": true,
    "upstream_health_metrics": true,
    "latency_metrics": true,
    "bandwidth_metrics": true,
    "status_code_metrics": true
  },
  "updated_at": 1706607128,
  "tags": null,
  "service": null,
  "created_at": 1706607128,
  "route": {
    "id": "<ID>",
    "name": "<gatewayname"
  },
  "protocols": [
    "grpc",
    "grpcs",
    "http",
    "https"
  ],
  "ordering": null,
  "consumer_group": null,
  "id": "<ID>"
}
```
- Grafana image: grafana/grafana-enterprise
- Prometheus Data Source Configuration:
![image](https://github.com/Kong/kong/assets/98653336/c2a58ff7-c585-44b1-a98f-47a143f86406)
![image](https://github.com/Kong/kong/assets/98653336/0eb8a538-dd8b-4574-ba5d-315a79d1499b)
- prometheus.yml
```
# my global config
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "kong-services"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["kong admin api url."]
    scheme: https
```
Here my kong admin Api is running on port 8001 in https.
as i have configured this in caprover, it has it's own URL.

## EXPECTATIONS
- metrics for 500 error reports.
- The response time of APIs (in ms).

But Nginx Connection rates, Caching details, these are coming.
I would appreciate any insights, guidance, or troubleshooting tips to address these missing metrics in the Grafana dashboard. Thank you!
And please let me know if my Approach is spot on. I shall forever Grateful. Thank you Again!
