### DISCUSSION TITLE
how set the correct hostname when calling kubernetes external service?

### DISCUSSION THREAD

**Discussion by cybercoder** [Kong/kong#12706] [Help] [answered]
I'm trying to create a transparent web proxy:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    konghq.com/plugins: p
    konghq.com/strip-path: "true"
  name: emma
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: emmagw
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: emma-svc-1
      port: 443
      weight: 100
    - group: ""
      kind: Service
      name: emma-svc-2
      port: 443
      weight: 100
    matches:
    - path:
        type: PathPrefix
        value: /
```
Those multiple backends are kubernetes external services ( it seems there's no UpStream Kind on CRD )
 e.g.
 ```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/plugins: p
    konghq.com/protocol: https
  name: emma-svc-0
spec:
  externalName: yyyy.yyy
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  type: ExternalName
 ```
 It works but does not work properly :)
 It seems it proxies to the ```yyyy.yyy``` with not enough HTTP headers. so the web server at the destination shows the default web server page.
 How i can use request-transformer plugin to set correct host headers?
 
 This is not working:

 ```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: p
plugin: request-transformer
config:
  add:
    headers:
    - "Host: yyyy.yyy" 
 ```
