### DISCUSSION TITLE
Kong lost all consumers

### DISCUSSION THREAD

**Discussion by baznikin** [Kong/kong#12803] [Help]
Hello! We have an issue today and I want to understand why it happened and how to prevent it in future.

Long story short - data in kong's postgresql database was deleted today at 07:30:54
1. we use DigitalOcean managed Kubernetes. In 07:30:09 control plane briefly became unavailable across all the clusters
2. our database running with Zalando postgres-operator dectect K8S API failure, but do not failover since all servers was available to each other and identify it as control plane issue
3. however, kong leader lost leader lock and restarted. Second pod for some reason do nothing. First (ex-leader) restarted and became leader again
4. something happens here and I need help to trace it down. Somehow it make sure configuration is empty and "sync" by deleting thousands of consumers from database.

Leader previous log:
```
E0328 07:30:03.203096       1 leaderelection.go:330] error retrieving resource lock production/kong-ingress-controller-leader-kong: Get "https://10.245.0.1:443/apis/coordination.k8s.io/v1/namespaces/production/leases/kong-ingress-controller-leader-kong": context deadline exceeded
I0328 07:30:03.203286       1 leaderelection.go:283] failed to renew lease production/kong-ingress-controller-leader-kong: timed out waiting for the condition
time="2024-03-28T07:30:03Z" level=info msg="stopping telemetry manager"
Error: leader election lost
time="2024-03-28T07:30:04Z" level=info msg="diagnostics server disabled"
```

after restart:
```
time="2024-03-28T07:30:04Z" level=info msg="starting controller manager" commit=29640a012d95418eb099adcabf3f524de266c2a7 logger=setup release=2.9.4 repo="https://github.com/Kong/kubernetes-ingress-controller.git"
time="2024-03-28T07:30:04Z" level=info msg="the ingress class name has been set" logger=setup value=kong
time="2024-03-28T07:30:04Z" level=info msg="getting enabled options and features" logger=setup
time="2024-03-28T07:30:04Z" level=info msg="getting the kubernetes client configuration" logger=setup
W0328 07:30:04.462450       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2024-03-28T07:30:04Z" level=info msg="starting standalone health check server" logger=setup
time="2024-03-28T07:30:04Z" level=info msg="getting the kong admin api client configuration" logger=setup
time="2024-03-28T07:30:09Z" level=error msg="tag filtering disabled" error="Kong Admin API (https://localhost:8444) does not support tags: HTTP status 500 (message: \"An unexpected error occurred\")" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="configuring and building the controller manager" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="building the manager runtime scheme and loading apis into the scheme" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="Database mode detected, enabling leader election" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="Metrics server is starting to listen" addr=":10255" logger=controller-runtime.metrics
time="2024-03-28T07:30:09Z" level=info msg="Initializing Dataplane Client" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="Starting Admission Server" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="Updated current TLS certificate" logger=controller-runtime.certwatcher
time="2024-03-28T07:30:09Z" level=info msg="Starting certificate watcher" logger=controller-runtime.certwatcher
time="2024-03-28T07:30:09Z" level=info msg="Initializing Dataplane Synchronizer" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="combined routes mode has been enabled" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="Starting Status Updater" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="Initializing Dataplane Address Discovery" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="falling back to a default address finder for UDP" logger=setup reason="no publish status address or publish service were provided"
time="2024-03-28T07:30:09Z" level=info msg="Starting Enabled Controllers" logger=setup
time="2024-03-28T07:30:09Z" level=info msg="Disabling controller for Group=gateway.networking.k8s.io/v1beta1, Resource=referencegrants due to missing CRD" logger=controllers.crdCondition
time="2024-03-28T07:30:09Z" level=info msg="Disabling controller for Group=networking.internal.knative.dev/v1alpha1, Resource=ingresses due to missing CRD" logger=controllers.crdCondition
time="2024-03-28T07:30:09Z" level=info msg="Disabling controller for Group=gateway.networking.k8s.io/v1beta1, Resource=gateways due to missing CRD" logger=controllers.crdCondition
time="2024-03-28T07:30:09Z" level=info msg="Disabling controller for Group=gateway.networking.k8s.io/v1beta1, Resource=httproutes due to missing CRD" logger=controllers.crdCondition
time="2024-03-28T07:30:09Z" level=info msg="Add readiness probe to health server" logger=setup
time="2024-03-28T07:30:13Z" level=error msg="failed setting up anonymous reports" error="failed to get Kong root config data: HTTP status 500 (message: \"An unexpected error occurred\")" logger=setup
time="2024-03-28T07:30:13Z" level=info msg="anonymous reports enabled" logger=setup
time="2024-03-28T07:30:13Z" level=info msg="Starting manager" logger=setup
I0328 07:30:13.572917       1 leaderelection.go:248] attempting to acquire leader lease production/kong-ingress-controller-leader-kong...
time="2024-03-28T07:30:13Z" level=info msg="Starting server" addr="{\"IP\":\"::\",\"Port\":10255,\"Zone\":\"\"}" kind=metrics path=/metrics
I0328 07:30:29.443228       1 leaderelection.go:258] successfully acquired lease production/kong-ingress-controller-leader-kong
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.Ingress.netv1 source="channel source: 0xc0003225a0"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.IngressClass.netv1 source="kind source: *v1.IngressClass"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.Endpoints source="kind source: *v1.Endpoints"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.UDPIngress source="channel source: 0xc000322820"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.UDPIngress source="kind source: *v1.IngressClass"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.UDPIngress source="kind source: *v1beta1.UDPIngress"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.UDPIngress
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.Endpoints
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.IngressClass.netv1
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.Secrets source="kind source: *v1.Secret"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.Secrets
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.Ingress.netv1 source="kind source: *v1.IngressClass"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.Ingress.netv1 source="kind source: *v1.Ingress"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.Ingress.netv1
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.KongIngress source="kind source: *v1.KongIngress"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.KongIngress
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.TCPIngress source="channel source: 0xc0003228c0"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.Service source="kind source: *v1.Service"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.Service
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.KongPlugin source="kind source: *v1.KongPlugin"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.KongPlugin
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.TCPIngress source="kind source: *v1.IngressClass"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.IngressClassParameters source="kind source: *v1alpha1.IngressClassParameters"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.IngressClassParameters
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.TCPIngress source="kind source: *v1beta1.TCPIngress"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.TCPIngress
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.KongClusterPlugin source="kind source: *v1.IngressClass"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.KongClusterPlugin source="kind source: *v1.KongClusterPlugin"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.KongClusterPlugin
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.KongConsumer source="kind source: *v1.IngressClass"
time="2024-03-28T07:30:29Z" level=info msg="Starting EventSource" logger=controllers.KongConsumer source="kind source: *v1.KongConsumer"
time="2024-03-28T07:30:29Z" level=info msg="Starting Controller" logger=controllers.KongConsumer
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.UDPIngress worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.IngressClass.netv1 worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.KongIngress worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.Service worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.Ingress.netv1 worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.KongConsumer worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.KongPlugin worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.Secrets worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.IngressClassParameters worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.TCPIngress worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.KongClusterPlugin worker count=1
time="2024-03-28T07:30:29Z" level=info msg="Starting workers" logger=controllers.Endpoints worker count=1
time="2024-03-28T07:31:07Z" level=warning msg="exceeded Kong API timeout, consider increasing --proxy-timeout-seconds" kong_url="https://localhost:8444"
time="2024-03-28T07:31:07Z" level=error msg="could not update kong admin" error="performing update for https://localhost:8444 failed: 11 errors occurred:\n\tfailed to sync all entities: context deadline exceeded\n\twhile processing event: {Delete} jwt-auth xxxx for consumer 3_xxx@gmail.com failed: making HTTP request: Delete \"https://localhost:8444/consumers/c5db605a-b403-4ac1-b10d-xxxxxxx/jwt/26fadde8-d1ba-4998-xxxxxx\": dial tcp [::1]:8444: i/o timeout\n\twhile processing event: {Delete} jwt-auth yyyyyyy for consumer yyyyy@o2.pl failed: making HTTP request: Delete \"https://localhost:8444/consumers/679c0595-ff33-yyyyyy/jwt/26fc67af-d345-46b4-yyyyyy\" [REDACTED - AND SO ON]\n" subsystem=dataplane-synchronizer
time="2024-03-28T07:32:07Z" level=warning msg="exceeded Kong API timeout, consider increasing --proxy-timeout-seconds" kong_url="https://localhost:8444"
time="2024-03-28T07:32:07Z" level=error msg="could not update kong admin" error="performing update for https://localhost:8444 failed: 11 errors occurred:\n\tfailed to sync all entities: context deadline exceeded\n\twhile processing event: {Delete} jwt-auth [REDACTED - AND SO ON]\n" subsystem=dataplane-synchronizer
time="2024-03-28T07:37:08Z" level=warning msg="exceeded Kong API timeout, consider increasing --proxy-timeout-seconds" kong_url="https://localhost:8444"
```
In same time in proxy logs there were thousands of DELETE requests:
```
127.0.0.1 - - [28/Mar/2024:07:30:57 +0000] "DELETE /consumers/dfedb704-e1ef-4215-aaaaa/jwt/01d734c7-4f74-4249-bbbbb HTTP/2.0" 204 0 "-" "Go-http-client/2.0"
```

PS: At same time 2 replicas of Kong on another cluster failed to operate in other way - one reply as usually and second reply with "503 failure to get a peer from the ring-balancer" on all requests. I triple checked - Ingress points to correct Service and Service have endpoints. So, one replica of Kong lost its configuration (it was leader afair) and second operates OK. Now I have serious doubts in Kong ability to serve in production for me.

**UPDATE:**
Kong installed with Helm chart. Chart version: 2.19.0
values:
```
env:
  database: "postgres"
  pg_host: "${dbname}"
  nginx_http_gzip: "on"
  pg_port: "5432"
  pg_user: "kong_owner_user"
  pg_password:
    valueFrom:
      secretKeyRef:
        name: kong-owner-user.${dbname}.credentials.postgresql.acid.zalan.do
        key: password
  pg_database: "kong"
  pg_ssl: "off"
  log_level: notice
  trusted_ips: 0.0.0.0/0,::/0
  real_ip_header: proxy_protocol
  real_ip_recursive: "on"
  # Default values from https://github.com/Kong/charts/blob/main/charts/kong/values.yaml follows
  router_flavor: "traditional"

# Specify Kong admin API service and listener configuration
admin:
  enabled: true
  http:
    # Enable plaintext HTTP listen for the admin API
    # Disabling this and using a TLS listen only is recommended for most configuration
    enabled: true
    servicePort: 8001
    containerPort: 8001

proxy:
  type: NodePort

  http:
    nodePort: 30080
    parameters:
      - proxy_protocol
  tls:
    nodePort: 30443
    parameters:
    - http2
    - proxy_protocol
  stream:
   # additional_tcp_ports to expose
   %{ for port in additional_tcp_ports }
   - containerPort: ${port}
     servicePort: ${port}
     nodePort: ${port}
     parameters:
       - proxy_protocol
   %{ endfor ~}

# Custom Kong plugins can be loaded into Kong by mounting the plugin code
# into the file-system of Kong container.
plugins:
   configMaps:
   - pluginName: optional-jwt
     name: kong-plugin-optional-jwt
     subdirectories:
     - name: kong-plugin-optional-jwt-migrations
       path: migrations

migrations:
  resources:
   limits:
     memory: 1Gi
   requests:
     memory: 500Mi

ingressController:
  env:
    kong_admin_tls_skip_verify: true
    kong_real_ip_recursive: "on"

replicaCount: 2

podDisruptionBudget:
  enabled: true
  # Uncomment only one of the following when enabled is set to true
  # maxUnavailable: "50%"
  minAvailable: "50%"

serviceMonitor:
  enabled: true

extraObjects:
- apiVersion: configuration.konghq.com/v1
  kind: KongClusterPlugin
  metadata:
    name: prometheus
    annotations:
      kubernetes.io/ingress.class: kong
    labels:
      global: "true"
  config:
    #per_consumer: true
    status_code_metrics: true
    latency_metrics: true
    bandwidth_metrics: true
    upstream_health_metrics: true
  plugin: prometheus
```
