### DISCUSSION TITLE
Support for URLRewrites filter from API gateway definition

### DISCUSSION THREAD

**Discussion by jakoberpf** [Kong/kong#12827] [Help]
Hello, does Kong or will Kong support the URLRewrites filters on the HTTPRoute resource? Currently I receive `Error from server: error when creating "gateway-httproute-backend.yaml": admission webhook "validations.kong.konghq.com" denied the request: HTTPRoute spec did not pass validation: rules[0].filters[0]: filter type URLRewrite is unsupported` on a manifest like 

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: default
spec:
  parentRefs:
    - name: portal
  hostnames:
    - ...
  rules:
    - filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /api/application/
      backendRefs:
        - name: srv-application
          port: 80
```
