### DISCUSSION TITLE
Pathes with same start-pattern don't match properly

### DISCUSSION THREAD

**Discussion by mwaeckerlin** [Kong/kong#12845] [Help]
I have:

```
services:
  - name: trading-events
    url: http://trading-events:4369/trading-events
    routes:
      - name: trading-events
        protocols:
          - http
        paths:
          - /api/v1/trading-events
        hosts:
          - localhost
  - name: trading
    url: http://trading:4001/trading
    routes:
      - name: trading
        protocols:
          - http
        paths:
          - /api/v1/trading
        hosts:
          - localhost
```

Results in translation of `/api/v1/trading-events/...` to `/api/v1/trading/-events/...`…

That's of course not wanted behavior!

How do I specify, that the path segment must be complete, so either `/api/v1/trading` or `/api/v1/trading/...`?

... and where to I find a complete reference for the KONG YAML file syntax, includng detail specification of all parameters, i.e. how `paths` is defined? I'm now searching the web for hours and don't find anything…!

I'm trying this, but it does not work at all, and I cannot find the file syntax documentation any more:
```
  - name: trading
    url: http://trading:4001/trading
    routes:
      - name: trading
        paths:
          - /api/v1/trading/
          - /api/v1/trading$
```

**Comment by mwaeckerlin** [comment]
I found a solution, but with try and error, the documentation didn't help at all, I couldn't find any relevant documentation on the topic.

Solution:
```
  - name: trading-events
    url: http://trading-events:4369/trading-events
    routes:
      - name: trading-events
        protocols:
          - http
        paths:
          - ~/api/v1/trading-events/
          - ~/api/v1/trading-events$
        hosts:
          - localhost
  - name: trading
    url: http://trading:4001/trading
    routes:
      - name: trading
        protocols:
          - http
        paths:
          - ~/api/v1/trading/
          - ~/api/v1/trading$
        hosts:
          - localhost
```

**Comment by chronolaw** [comment]
Do you know that kong has three different flavor? `traditional`, `traditional_compatible` and `expressions`.
If you run kong gateway with the flavor `expressions`, you can define a route more accurately, like:
```
    routes:
      - name: trading
        protocols:
          - http
        expression: http.path == "/api/v1/trading" && http.host == "localhost"
```
See: https://docs.konghq.com/gateway/latest/reference/expressions-language/
