### DISCUSSION TITLE
How to get consumer tags in upstreams?

### DISCUSSION THREAD

**Discussion by 99hops** [Kong/kong#12896] [Help] [answered]
Hello, I am looking for a way to get consumer tags as header values in upstreams. What is the way to do this? I have request-transform plugin but I can't find the right values to put, please advice! :pray: 

Maybe something like this? (:

  ```
- name: request-transformer
    enabled: true
    config:
      add:
        headers:
          - "x-consumer-tag1: ${kong.client.tag1}"
```
