### DISCUSSION TITLE
Connection getting dropped immediately in TCPIngress

### DISCUSSION THREAD

**Discussion by tarunmittal24** [Kong/kong#12975] [Help] [answered]
Hi Guys,

I have setup the TCP Ingress, here are the following config

tcp-ingress.yaml
```
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: redis-tcp-ing
  namespace: redis
spec:
  rules:
  - backend:
      serviceName: redis-svc
      servicePort: 6379
    port: 6379
```

service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
```

I am trying to do the telnet and it is working fine as expected

<img width="918" alt="Screenshot 2024-05-02 at 22 11 39" src="https://github.com/Kong/kong/assets/131644722/7d2369ca-1ccf-4bdd-97ef-b5bbf1f7deda">

**But if my background service is down, it is showing connected and then got dicsonnected error**

[
<img width="952" alt="Screenshot 2024-05-02 at 22 09 06" src="https://github.com/Kong/kong/assets/131644722/e2c6c6bb-fa5f-4725-9329-918955a2390b">
](url)

Does anyone have ever faced it, or i am missing something.
