### DISCUSSION TITLE
KongUpstreamPolicy : How to make session affinity cookie to have samesite=None, secure=true

### DISCUSSION THREAD

**Discussion by shivpatel1** [Kong/kong#13066] [Help]
In our application, we have configured KongUpstreamPolicy to have a cookie based upstream policy. This does not work with google chrome as expected when couple of requests are coming from cross domain and this cookie has already past 2 minutes from its creation time. This is because chrome considers LAX as a default value for sameSite for this cookie as Kong is not explicitly adding sameSite=None.

```yaml
apiVersion: configuration.konghq.com/v1beta1
kind: KongUpstreamPolicy
metadata:
  name: session-affinity
spec:
  hashOn:
   cookie: replica
   cookiePath: "/"
  algorithm: consistent-hashing
```

We have tried looking for many of the Kong documentation pages but could not find any way to configure our needs for this specific cookie. Can someone please help ?
