### DISCUSSION TITLE
Unable to use external postgresql on GKE / Stuck in migrations ( Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: timeout )

### DISCUSSION THREAD

**Discussion by hashaaamm** [Kong/kong#13229] [Help] [answered]
I am using google managed postgrsql with kong on GKE. And my migration pod seems to be stuck and not doing it's job.

I have install kong with helm using the below values.

```yaml
image:
  repository: kong
  tag: "3.5"

env:
  prefix: /kong_prefix/
  database: postgres
  admin_gui_api_url: 
  admin_gui_url: 
  pg_host: 
  pg_user: 
  pg_password: 
  pg_database: 

admin:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001

postgresql:
  enabled: false

ingressController:
  enabled: false

manager:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002
migrations:
  enabled: true
  postUpgrade: true
  preUpgrade: true
```

```bash
NAME                                 READY   STATUS             RESTARTS      AGE
my-kong-kong-69fb74bbdd-wh9tq        0/1     Init:1/2           0             8m2s
my-kong-kong-init-migrations-gmw5q   0/1     CrashLoopBackOff   4 (80s ago)   8m2s
```

```bash
# pod logs
Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: timeout
```

**Comment by jschmid1** [comment]
The error usually indicates that postgres could not be reached. Can you check that you're able to authenticate to postgres? 

You probably redacted the values but just checking. Did you populate these values?

```
  pg_host: 
  pg_user: 
  pg_password: 
  pg_database: 
```
