### DISCUSSION TITLE
Kong

### DISCUSSION THREAD

**Discussion by stiti-bacem** [Kong/kong#13295] [Help] [answered]

**Comment by hanshuebner** [comment]
@stiti-bacem In order to restrict a plugin to specific HTTP methods, you can create a separate route for `POST` requests and add the plugin to it.

```yaml
_format_version: "2.1"

services:
- name: example-service
  url: http://web
  routes:
    - name: post-route
      paths:
        - /
      methods:
        - POST
      plugins:
        - name: response-transformer
          config:
            add:
              json:
                - "hello: world"

    - name: default-route
      paths:
        - /
```
