### DISCUSSION TITLE
Intermittent Failing of the plugin.

### DISCUSSION THREAD

**Discussion by tarunmittal24** [Kong/kong#13422] [Help]
Hi Guys,

I am facing one weird issue in the kong ingress, where one pod in my deployment is failing all the request to a specific route.

So, my request is like  **ops.example.com** is the url and using the request transformer plugin it is going to to add the **index.html** in the end of the url whatever it will be, so in this case final request will become **ops.example.com/index.html** 

When it hits the server, now it is working fine if request is going to all the other pods expect one, which is giving 403, that might be happened because of the request transformer plugin not working inside this pod.

I have also manually go inside the pod and run the curl command, like 

`curl http://<ip-of-pod>:8000 -H "Host: ops.example.com"` 

it is giving me the error, but the same is working inside the other pods.

Not Sure what is the issue in my setup, and this is working fine when i am using the **kong-ingress-controller:2.7**, i recently switched to **2.8** and facing this issue, but if this is the version issue then why this intermittent failing is happening [working in some pods and not working in other.] and having the **kong:3.0** as the image in both the cases.

Really don't find any way to debug this.

**Comment by tarun9715m** [comment]
I got the Issue:-

I basically have the two ingress objects:-

ingress-1.yaml

```apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: request-transformer-plugin
  name: ops-dashboard-ing
spec:
  ingressClassName: internal
  rules:
    - host: ops.beta.abcd.com
      http:
        paths:
          - backend:
              service:
                name: ops-dashboard-svc
                port:
                  number: 80
            path: /
            pathType: Exact
```

and 

ingress-2.yaml

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ops-dashboard-ing-1
  namespace: core
spec:
  ingressClassName: internal
  rules:
    - host: ops.beta.abcd.com
      http:
        paths:
          - backend:
              service:
                name: ops-dashboard-svc
                port:
                  number: 80
            path: /(.*)
            pathType: Prefix
```

Now you can see the path /(.*) and /, now getting 403 is because when the request matching with the **ingress1.yaml** config because annotations of the transformer is there it is working fine and when it matches the **ingress2.yaml** it is failing because no transformer is there.


**Now question is, why there is a randomness:-** (Working in some pods and not working in some)

Because by default if there is no regex priority set and no regular expression is there, then they will be randomness in the behaviour how the routes get routed.

**Read this for more info:-** https://docs.konghq.com/gateway/latest/key-concepts/routes/#how-requests-are-routed


**Solutions:-**

1. Set the regex priority in the ingress1.yaml:- with this  https://docs.konghq.com/kubernetes-ingress-controller/latest/reference/annotations/#konghqcomregex-priority

  As **ingress1.yaml** with get more priority, everything will be fine.

2. In the ingress2.yaml, make it act as a regular expression by adding the **/~** in the path. Final path will become:- 

   **old**:- path: /(.*)
   
   **new**:- path: /~/(.*)
   
3. or you can make the same path (/) in both the files, 

    a. ingress1.yaml with pathType: Exact 
    
    b. ingress2.yaml with pathType: Prefix, 
    
   **as Exact will have more priority then Prefix, it will start working.**
    
   **read this for more info**:- https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches
   
   
commenting from the different ID
