### DISCUSSION TITLE
Kong Connection Issues with EMQX

### DISCUSSION THREAD

**Discussion by rakeshreddyrg09** [Kong/kong#13426] [Help]
Hi team,
I have installed Kong in my EKS cluster.
here is  my proxy configuration
```
proxy:
        streamPorts:
          # MQTT SSL Port
          - protocol: TCP
            containerPort: 1883
            servicePort: 1883
          # MQTT SSL Port
          - protocol: TCP
            containerPort: 8883
            servicePort: 8883
        tls:
          containerPort: 8000
```
TCPIngress

```
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: mqttingress
  namespace: iotcore
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - port: 1883 # MQTT port
      backend:
        serviceName: emqx
        servicePort: 1883
    - port: 8883 # MQTT SSL port
      backend:
        serviceName: emqx
        servicePort: 8883
```

here when I try to run this 
```
mqttx pub \
  --hostname mqtt.iot-test.org.com \
  --port 1883 \
  --topic devices \
  --message "{\"deviceId\":16,\"value\":40.1,\"region\":\"EMEA\",\"timestamp\":1482236627236}" \
  --username 'admin' \
  --password 'public'
```
![image](https://github.com/user-attachments/assets/a6564f8f-313d-47e0-9adb-21cb6aaf4f86)

below is the ticket raised for the same issue with mqttx community
https://github.com/emqx/MQTTX/issues/1726

mqttx is unable to send the message and I don't see any logs in Kong.
Traffic is coming in when I use *curl* with *http* end point, but not for the mqttx with tcp endpoint 
can anyone help me here
