### DISCUSSION TITLE
HTTP header X-Forwarded-Proto not defined correctly on the backend app

### DISCUSSION THREAD

**Discussion by iuriipro** [Kong/kong#13478] [Help] [answered]
Hi, we are using Kong behind AWS NLB, where we have ssl/tls termination, also we are using Gateway API with HTTPRoute, so the client connection looks like this:
AWS NLB -> Kong -> Gateway -> HTTPRoute -> k8s-service - backend-app

The backend app is an Express application and should work with secure cookies, for this purpose it should get X-Forwarded-Port 443 and X-Forwarded-Proto https.

But somewhere on the Kong level, X-Forwarded-Port is set to 80 and X-Forwarded-Proto to http.
We have tried to change these headers with the help of KongClusterPlugin post-function and suggestions from this issue [#5559](https://github.com/Kong/kong/issues/5559)

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: pre-function-x-forwarded-headers
  annotations:
    kubernetes.io/ingress.class: kong-internal
  labels:
    global: "true"
plugin: post-function
config:
  access:
    - |
      ngx.var.upstream_x_forwarded_port=443
      ngx.var.upstream_x_forwarded_proto=https
```

Then X-Forwarded-Port was changed successfully, but X-Forwarded-Proto disappeared at all.
Please suggest what we can do in this case. 

Also additional question: If we're not using Ingress and instead want to use Gateway API resources, do we still need to define an annotation with an ingress class for the creation of the plugin, because without it Kong is not recognize a plugin? Is there an annotation for GatewayClass, or do we still need to use IngressClass for this purpose?

Thanks in advance! 
Waiting for response.
