### DISCUSSION TITLE
Rate limiting plugin is not working / Unexpected behaviour of plugin / How to disable cache

### DISCUSSION THREAD

**Discussion by hashaaamm** [Kong/kong#13711] [Help]
Hi, I have kong OSS deployed:
* Traditional Mode
* GKE autopilot (GCP managed Node)
* GCP managed certificate
* Custom Ingress / Terminating SSL at load balancer

I have set a rate limiting plugin and it is not working all the time but only randomly. I have no other plugin as well.
When I look at header it says `X-Cache HIT`

Can I not use plugin If I have Ingress define? or my helm settings are wrong which is why my plugin is not working properly?

**Note**
* additionally it says cache hit for html response and for other end points it just reset
`X-RateLimit-Remaining-Day`

My ingress file
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: kong-cert
    kubernetes.io/ingress.global-static-ip-name: kong-proxy-ip
spec:
  rules:
  - host: api.kongsensity.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-kong-kong-proxy
            port: 
              number: 80
  - host: admin.kongsensity.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-kong-kong-admin
            port: 
              number: 8001
  - host: manager.kongsensity.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-kong-kong-manager
            port: 
              number: 8002
```

My helm chart

```yaml
# Kong Helm values for GKE Autopilot
image:
  repository: kong
  tag: "3.6"

env:
  prefix: /kong_prefix/
  database: "postgres"
  pg_host: "10.64.0.5"
  pg_user: "postgres"
  pg_password:
    valueFrom:
      secretKeyRef:
        name: kong-postgres-secret
        key: pg-password
  pg_database: "postgres"
  pg_port: "5432"
  log_level: debug
  admin_gui_url: "https://manager.kongsensity.com"
  admin_gui_api_url: "https://admin.kongsensity.com"

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    enabled: false
  ingress:
    enabled: false  # Disable Helm-managed Ingress for admin

manager:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002
  tls:
    enabled: false
  ingress:
    enabled: false  # Disable Helm-managed Ingress for manager

proxy:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
  tls:
    enabled: false
  ingress:
    enabled: false  # Disable Helm-managed Ingress for proxy

# Ingress Controller
ingressController:
  enabled: false

postgresql:
  enabled: false

enterprise:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  behavior: {}
  ## targetCPUUtilizationPercentage only used if the cluster doesn't support autoscaling/v2 or autoscaling/v2beta
#  targetCPUUtilizationPercentage:
  ## Otherwise for clusters that do support autoscaling/v2 or autoscaling/v2beta, use metrics
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

resources:
  limits:
    cpu: 1
    memory: 1G
  requests:
    cpu: 500m
    memory: 1G


# Enable/disable migration jobs, and set annotations for them
migrations:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
```

And I see no cache at my load balancer so I wonder why is it saying cache
![Screenshot 2024-09-25 at 23 34 21](https://github.com/user-attachments/assets/938410d3-7b88-4824-adaf-8e47df22d2ae)
