### DISCUSSION TITLE
Kong Gateway DB-less Route with Authorization Header Regex Works in Docker but Fails in Kubernetes

### DISCUSSION THREAD

**Discussion by twlap** [Kong/kong#13821] [Help]
I'm using Kong Gateway 3.4 in a DB-less configuration to set up a route that requires token-based authentication. This setup works perfectly in Docker but fails when deployed to Kubernetes (K8s). Below are the configuration details and the issue observed.

The configuration file (YAML) for the route setup is as follows:
```
services:
- name: api-with-token
  host: test.demo.com
  port: 443
  protocol: https
  path: /test
  routes:
    - name: api-with-token
      paths:
        - /api/test
      methods:
        - GET
      headers:
        Authorization:
          - ~*Bearer
      strip_path: true
```
The request that works in Docker but fails in K8s:
```
curl --location 'https://demo.com/api/test' \
--header 'Authorization: Bearer eyJj...'
```
When deploying to K8s, the request returns:
```
{
  "message": "no Route matched with those values"
}
```

To troubleshoot, I tried different regex patterns in the Authorization header, but they didn’t resolve the issue:
```
Authorization:
   - ~*Bearer
   - /~/*Bearer
   - \~\*Bearer
   - ~^Bearer
```

Kong Version: 3.4
Environment:
- Working: Docker
- Not Working: Kubernetes (installed via Helm)
- Kong Mode: DB-less
  
Would appreciate any guidance or troubleshooting steps from the community on why this configuration works in Docker but not in Kubernetes. Thank you!
