### DISCUSSION TITLE
dbless declarative configuration in helm no effect

### DISCUSSION THREAD

**Discussion by miniboxhaha** [Kong/kong#13894] [Help] [answered]
#### and here is my value.yaml
```
deployment:
  test:
    enabled: false

controller:
  proxy:
    nameOverride: "{{ .Release.Name }}-gateway-proxy"

  enabled: true

  deployment:
    kong:
      enabled: false

  ingressController:
    enabled: true
    image:
      repository: registry.cluster.local:30443/kong/kubernetes-ingress-controller
      tag: "3.3.1"

    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true

  podAnnotations:
    kuma.io/gateway: enabled
    # This port must match your Kong admin API port. 8444 is the default.
    # If you set gateway.admin.tls.containerPort, change these annotations
    # to use that value.
    traffic.kuma.io/exclude-outbound-ports: "8444"
    traffic.sidecar.istio.io/excludeOutboundPorts: "8444"

gateway:
# already create pulugin configmap
  plugins:
    configMaps:
      - name: my-kong-plugin-header
        pluginName: my-header
  proxy:
    type: NodePort
    http:
      nodePort: 32000
  manager:
    type: NodePort
    http:
      nodePort: 32100
  
  enabled: true
  image:
    repository: registry.cluster.local:30443/kong
    tag: "3.7"
  dblessConfig:
    config: |
    _format_version: "1.1"
    _transform: true
    # 
    services:
    - name: my-first-service
      protocol: http
      port: 3000
      # service name in k8s
      host: test-app-service.ha
      path: /test_header
      routes:
      - name: my-first-route
        plugins:
        - name: my-header
          config: 
              header_value: haha
        paths:
        - /test_app
    - name: my-sceond-service
      protocol: http
      port: 3000
      # service name in k8s
      host: test-app-service.ha
      path: /test_header1
      routes:
      - name: my-second-route
        plugins:
        - name: my-header
          config: 
              header_value: huhu
        paths:
        - /test_app1
  deployment:
    kong:
      enabled: true

  admin:
    enabled: true
    # type: ClusterIP
    # clusterIP: None
    http:
      enabled: true
      nodePort: 32080
      servicePort: 32080
      containerPort: 32080

  ingressController:
    enabled: false

  env:
    role: traditional
    database: "off"

```

after pod running, i can't see any configuration in manage console page. but i can set config use http api /config with @config.yam below.
```
_format_version: "1.1"
_transform: true
# 
services:
- name: my-first-service
  protocol: http
  port: 3000
  # service name in k8s, or maybe it shoud be a upstream name in kong
  host: test-app-service.ha
  path: /test_header
  routes:
  - name: my-first-route
    plugins:
    - name: my-header
      config: 
          header_value: haha
    paths:
    - /test_app
- name: my-sceond-service
  protocol: http
  port: 3000
  # service name in k8s, or maybe it shoud be a upstream name in kong
  host: test-app-service.ha
  path: /test_header1
  routes:
  - name: my-second-route
    plugins:
    - name: my-header
      config: 
          header_value: huhu
    paths:
    - /test_app1
```
#### and my finall goal actually is define httproute in k8s, and set kong via KIC.
but my problem is i want use different congfig args in same plugin.  
as far as i understand the [KIC doc says](https://docs.konghq.com/kubernetes-ingress-controller/3.3.x/plugins/custom/),
i have to define many KongPlugin resource with different config args like:
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-first-custom-plugin
config:
  header_value: "my first plugin"
plugin: myheader

---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-second-custom-plugin
config:
  header_value: "my second plugin"
plugin: myheader
```
and define many HttpRoute resource
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: ha
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/plugins: my-first-custom-plugin
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /test_app
    backendRefs:
    - name: test-app-service
      kind: Service
      port: 3000

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: ha
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/plugins: my-second-custom-plugin
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /test_app1
    backendRefs:
    - name: test-app-service
      kind: Service
      port: 3000

``` 
i don,t think that is the right way to do it.
any one can help? thank so much!!!

#### update:
i saw [since 3.0](https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md#331) 
```
Support ExtensionRef HTTPRoute filter. It is now possibile to set a KongPlugin reference in the HTTPRoutes' ExtensionRef filter field
```
but i am not sure it can set different config args
