### DISCUSSION TITLE
Question about download large file speed

### DISCUSSION THREAD

**Discussion by zxh326** [Kong/kong#13993] [Help]
I have local kubernetes with MetalLB load-balancer

deploy kong 3.7 with kic

```
➜  k get svc -n kong
NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                     AGE
kong-controller-metrics              ClusterIP      10.103.4.175    <none>        10255/TCP,10254/TCP                         23h
kong-controller-validation-webhook   ClusterIP      10.105.180.63   <none>        443/TCP                                     23h
kong-gateway-admin                   ClusterIP      None            <none>        8444/TCP                                    23h
kong-gateway-manager                 NodePort       10.97.158.241   <none>        8002:30687/TCP,8445:31704/TCP               23h
kong-gateway-proxy                   LoadBalancer   10.111.37.44    10.0.0.240    80:31231/TCP,443:31521/TCP,8443:30385/TCP   23h
```

deploy a bandwidth test service with `python -m http.server`, It contains a 2GB test file.

```
➜  k get svc 
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
bw-test         LoadBalancer   10.108.80.88   10.0.0.241    8000:32643/TCP   10m
```

also deploy ingress to expose this bandwidth test server

```
➜  k get ingress -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bw-test
  namespace: default
spec:
  ingressClassName: kong
  rules:
  - host: bw-test.zzde.me
    http:
      paths:
      - backend:
          service:
            name: bw-test
            port:
              number: 8000
        path: /
        pathType: Prefix

```

If we use the  bw-test ingress and EXTERNAL-IP of bw-test service to test bandwidth, we will see a very obvious gap.

- Through the ingress speed

```sh
➜  wget bw-test.zzde.me/root/2gb-file

~200MB/s
```

- Through EXTERNAL-IP of bw-test service

```sh
➜  wget 10.0.0.241:8000/root/2gb-file

~800MB/s
```

We care about why there is such a huge difference in bandwidth?

We have tried adding the following annotations to turn on or off buffering, but have not seen any improvement.

```
    konghq.com/response-buffering: "true"
    konghq.com/request-buffering: "true"
```
