### DISCUSSION TITLE
Port Forwarding to a different Server/Service

### DISCUSSION THREAD

**Discussion by YukiAttano** [Kong/kong#14133] [Help]
Hello, i have some difficulties using Kong but cannot switch to another solution like Nginx.
The whole Website doesn't seem to handle "declarative configuration" kong.yml which i have to use instead of curl commands.

My whole network completly abstracted looks like this:
I have 2 server, "analytics" and "db" and need Kong to pipe its ports to them.

my Kong.yml looks like this:
(borrowed from https://github.com/Kong/kong/issues/5656)
```yml
_format_version: '2.1'
_transform: true

services:
  - name: analytics-stream
    host: analytics
    port: 4000
    protocol: tcp
    routes:
      - name: analytics-redirect
        protocols:
          - tcp
        destinations:
          - port: 4000

  - name: db-stream
    host: db
    port: 6543
    protocol: tcp
    routes:
      - name: db-redirect
        protocols:
          - tcp
        destinations:
          - port: 6543
```

my Kong is configured through environment variables.
```conf
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      #KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_STREAM_LISTEN: 0.0.0.0:4000, 0.0.0.0:6543
```

because i am using docker to set all of them up, the names "analytics", "db" and "kong" are resolved to their service ip correctly.

I am quite sure something is wrong with my config, as i don't get through my services.
The documentation is not of any help as everything is only defined for curl commands.
