### DISCUSSION TITLE
Kong Ingress Controller in DBless mode intermittently loses service configurations after ~24 hours

### DISCUSSION THREAD

**Discussion by ParagPatil96** [Kong/kong#14334] [Help]
# Kong Ingress Controller in DBless mode intermittently loses service configurations after ~24 hours

## Environment
- Kong Gateway with Ingress Controller in DBless mode
- Kubernetes Gateway API implementation
- 2+ replicas of both controller and gateway pods
- Kong Gateway API reconciliation seems to be failing periodically
- We are using GCP and Preemptible Nodes

## Issue Description
Our Kong setup is experiencing an intermittent issue where the gateway stops routing traffic to backend services properly. When this happens, querying the Admin API shows empty services:

```bash
curl -s http://localhost:8001/services | jq
{
  "next": null,
  "data": []
}
```

The issue appears to happen:
- Approximately every 24 hours
- Seemingly randomly at times 

**Temporary workaround:** Restarting the controller pods immediately fixes the issue, but this is not a sustainable solution.

## Controller Logs
When the system is working correctly after a restart, I see:
```
Successfully synced configuration to Kong {"url": "https://10.9.0.5:8444", "update_strategy": "InMemory", "v": 0, "duration": "568ms"}
```

During normal operation when gateway pods restart:
```
controllers.KongAdminAPIService Reconciling Admin API EndpointSlice {"v": 0, "namespace": "kong", "name": "kong-gateway-admin-n8nnw"}
HTTPRoute has been configured on the data-plane {"GatewayV1HTTPRoute": {"name":"kong-lang-gang-http-route-backend-app","namespace":"kong"}, "v": 0, "namespace": "kong", "name": "kong-lang-gang-http-route-backend-app"}
```

When the issue occurs, I see:
```
Could not send configuration to gateways {"error": "no ready gateway clients"}
```

## Configuration

Helm values configuration for Kong/Ingress charts:

```yaml
controller:
  enabled: true
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  ingressController:
    enabled: true
    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true
      retryDelay: 3
      maxRetries: 20

gateway:
  enabled: true
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  admin:
    enabled: true
    type: ClusterIP
    http:
      enabled: true
      servicePort: 8001
  env:
    role: traditional
    database: "off"
    admin_api_keepalive_timeout: "60s"
    admin_api_request_timeout: "60s"
```

GatewayClass, Gateway, HttpRoutes
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
 name: kong
 annotations:
   konghq.com/gatewayclass-unmanaged: 'true'
spec:
 controllerName: konghq.com/kic-gateway-controller
 
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
 name: kong
 namespace: kong
spec:
gatewayClassName: kong
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: kong-tls-cert
      mode: Terminate
      
 ---
 apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kong-lang-gang-http-route-marketing-app
  namespace: kong
spec:
  hostnames:
  - <host1>
  - <host2>
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: kong-lang-gang-gateway
    namespace: kong
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: marketing-service
      namespace: marketing
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```

## Questions
1. Why would the controller periodically lose connection to gateway pods despite having proper gateway discovery configuration?
2. Is there a known issue with the Kong Ingress Controller's ability to maintain connections to gateway pods over time?
3. Are there any configuration parameters I should adjust to make reconnection more reliable?
4. Are there any best practices for setting up health checks or liveness probes to better handle this scenario?
