### DISCUSSION TITLE
Kong proxy expose ldap port 389/636

### DISCUSSION THREAD

**Discussion by rchekhina** [Kong/kong#14476] [Help] [answered]
HI,

In my cluster k8s on DigitalOcean I have a openldap service that works with port-forward on both ports 389/636. Now I want to expose it to the public network but I cant get it working. I have applied the following configuration:

deployment:

```
kubectl patch deploy -n kong-ingress kong-ingress-kong --patch '{
   "spec": {
     "template": {
       "spec": {
         "containers": [
           {
             "name": "proxy",
             "env": [
               {
                 "name": "KONG_STREAM_LISTEN",
                 "value": "0.0.0.0:389, 0.0.0.0:636 ssl"
               }
             ],
             "ports": [
               {
                 "containerPort": 389,
                 "name": "stream389",
                 "protocol": "TCP"
               },
               {
                 "containerPort": 636,
                 "name": "stream636",
                 "protocol": "TCP"
               }
             ]
           }
         ]
       }
     }
   }
 }'
```

service:

```
kubectl patch service -n kong-ingress kong-ingress-kong-proxy --patch '{
  "spec": {
    "ports": [
      {
        "name": "stream389",
        "port": 389,
        "protocol": "TCP",
        "targetPort": 389
      },
      {
        "name": "stream636",
        "port": 636,
        "protocol": "TCP",
        "targetPort": 636
      }
    ]
  }
}'
```
tcpingress:

```
echo "apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: openldap
  namespace: sa-openldap
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - port: 389
    backend:
      serviceName: openldap
      servicePort: 389
  - port: 636
    backend:
      serviceName: openldap
      servicePort: 636
" | kubectl apply -f -
```

can you help me please ?

**Comment by Oyami-Srk** [comment]
Is there any error log for Kong? Could you please check if the port was open on the dataplane nodes?

**Comment by rchekhina** [comment, marked as answer]
HI,

I have resolved it. the issue was that the port < 1024 has permission denied on the kong pod so to resolve it I have added root permission on the pod:

```
# securityContext for containers. 
containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    add: [NET_BIND_SERVICE]
    drop: []
```
