### DISCUSSION TITLE
How can use the internal nginx for caching?

### DISCUSSION THREAD

**Discussion by cybercoder** [Kong/kong#14480] [Ideas and feature requests]
I'm looking for something like nginx-fabric gateway snippet filter:

```

apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: static-content-cache
  namespace: default
spec:
  snippets:
    - context: http
      value: proxy_cache_path /cachestore levels=1:2 keys_zone=cache_store:10m max_size=1g inactive=60m use_temp_path=off;
    - context: http.server.location
      value: |
        proxy_cache cache_store;
        proxy_cache_valid 200 302 10m;
        proxy_cache_valid 404 1m;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_key "$scheme$request_method$host$request_uri";
        proxy_cache_lock on;
        proxy_cache_lock_timeout 5s;
        add_header X-Cache-Status $upstream_cache_status;
```

And use in httproute.
Is there any eq for kong-ingress?

**Comment by Oyami-Srk** [comment]
@randmonkey Could you please take a look at this?

**Comment by Oyami-Srk** [comment]
I think [Proxy Cache](https://docs.konghq.com/hub/kong-inc/proxy-cache/) plugin and its [corresponding doc](https://docs.konghq.com/gateway/latest/get-started/proxy-caching/) might be useful to cache.

**Comment by randmonkey** [comment]
Kong supports proxy cache by the [proxy cache](https://docs.konghq.com/hub/kong-inc/proxy-cache/3.4.x/) plugin. For using the plugin in k8s, you can create a `KongPlugin` resource like:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  namespace: default
  name: proxy-cache
name: proxy-cache
config:
  response_code:
  - 200
  - 301
  request_method:
  - GET
  ttl: 300 # 300 seconds = 5 min
```
Then attach it to `HTTPRoute` or `Ingress` by annotation `konghq.com/plugins` like:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: default
  name: httproute-using-proxy-cache
  annotations:
    konghq.com/plugins: proxy-cache
spec:
...
```
The function of this plugin may not be exactly the same as the nginx proxy cache.
