### DISCUSSION TITLE
How to strip part of the path in routes, but not all.

### DISCUSSION THREAD

**Discussion by liemei** [Kong/kong#7186] [Help]
How to strip part of the path in routes, but not all.
E.g:
route paths: ["/api/user/info","/api/user/all"] 
The actual project path is ["/user/info","user/all"]
How to remove the "api" in the routing?

**Comment by kikito** [comment]
Hello, the answer depends on how you want to make match (by path? by header?) and why you want to remove the api from the routing in the first place.

One option is making the Service have `/api` as part of its path. In declarative configuration it would look like this:

```
_format_version: "2.1"
_transform: true
services:
- name: example
  url: http://myapi.dev/api
  routes:
    - paths: ['/user/info']
    - paths: ['/user/all']
```

As you can see, `/api` is part of the Service, not the routes.
