### DISCUSSION TITLE
[rate-limiting plugin] How can we add multiple `limit_by` conditions for the same entity?

### DISCUSSION THREAD

**Discussion by TVenuMadhav** [Kong/kong#7241] [Help] [answered]
The rate limit plugin [documentation](https://docs.konghq.com/hub/kong-inc/rate-limiting/) isn't very clear in suggesting if it is possible to have multiple `limit_by` conditions configured for the rate limiting plugin.

Example:

Let's say that I want to rate limit incoming requests to service with  `x / min (by ip)` and `y/ min (by header)`. To do this, should we configure two separate rate limiting plugins for each different conditions for the service like for example: 

```
 - name: rate-limiting
    config:
      day: null
      fault_tolerant: true
      hide_client_headers: false
      hour: null
      limit_by: header
      header_name: X-Consumer-Account-ID
      second: null
      minute: 30
      month: null
      policy: local
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_timeout: 2000
      year: null
    enabled: true
    protocols:
    - grpc
    - grpcs
    - http
    - https
- name: rate-limiting
    config:
      day: null
      fault_tolerant: true
      hide_client_headers: false
      hour: null
      limit_by: ip
      second: null
      minute: 80
      month: null
      policy: local
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_timeout: 2000
      year: null
    enabled: true
    protocols:
    - grpc
    - grpcs
    - http
    - https

```

I know that this gives `entity exists error` while  performing `deck validate` . How can we get the intended functionality?

**Comment by kikito** [comment, marked as answer]
There is only one `config` value admitted per plugin, and each of the fields of the `rate-limiting` plugin admit only one value (`second` must be an integer, `minute` must be an integer, and so on).

The message `Multiple limits can be configured` means that it is possible to simultaneously use (for example) the `minute` and the `second` field. In your case, given that you wanted it to happen every 30 and 80 minutes, you could do this:

```
- name: rate-limiting
    config:
      day: null
      fault_tolerant: true
      hide_client_headers: false
      hour: null
      limit_by: ip
      second: 1800
      minute: 80
      month: null
      policy: local
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_timeout: 2000
      year: null
    enabled: true
    protocols:
    - grpc
    - grpcs
    - http
    - https
```
