### DISCUSSION TITLE
Improvement: add /readiness endpoint for Kubernetes hosting

### DISCUSSION THREAD

**Discussion by JorritSalverda** [Kong/kong#7252] [Ideas and feature requests]
### Summary

To run Kong in Kubernetes a /readiness endpoint will tell Kubernetes whether a node is ready to receive traffic and make it part of a service by returning 200 OK. Failing to return 200 OK will - temporarily - remove the node from the service.

Combined with the /liveness endpoint - see https://github.com/Mashape/kong/issues/1677 - this makes running Kong in Kubernetes much more effective.

**Comment by pamiel** [comment]
+1
For sure would be very usefull for the integration of Kong into Kubernetes, for a production grade level.

**Comment by erikgrinaker** [comment]
@JorritSalverda Kong already comes with a `kong health` command to check its health, this can be used as a readiness/liveness probe:

```
        readinessProbe:
          exec:
            command:
            - kong
            - health
          initialDelaySeconds: 3
```
