### DISCUSSION TITLE
Ignore fields starting with 'x-' in yml declarative config

### DISCUSSION THREAD

**Discussion by zmeyc** [Kong/kong#7323] [Ideas and feature requests]
### Summary

It would be nice to be able to define parts of configuration at top level of .yml file and reuse them, for example:

```
x-config:
- &cors-plugin-config-defaults
  origins: ...
  max_age: 5

services:
- name: my_service1
  plugins:
  - name: cors
    config:
      <<: *cors-plugin-config-defaults
      ...other fields...
- name: my_service2
  plugins:
  - name: cors
    config:
      <<: *cors-plugin-config-defaults
      ...other fields...
```

Currently this doesn't work:
```
Error: Failed parsing:
in 'x-config': unknown field
```

I worked this around by declaring a non-existent plugin and putting reusable sets of fields into it's config:
```
plugins:
- name: common_settings
  enabled: false
  config:
  - &cors-plugin-config-defaults
    origins: ...
    max_age: 5

...rest of the config is the same...
```

I propose allowing fields starting with `x-` at top level of yml document to contain any data to allow using them for YML anchors, similar to docker-compose Extension Fields: https://docs.docker.com/compose/compose-file/#extension-fields
