### DISCUSSION TITLE
Custom authorization in Kong

### DISCUSSION THREAD

**Discussion by reetik-raj** [Kong/kong#7524] [Help] [answered]
We wanted to move our company's custom authorisation to Kong. Currently we have an internal table which maps URLs to scopes and using the request URL and consumer details we are able to authorise the request. We want to move all this to Kong.
 
We need to maintain a table on Kong level which has the different scopes associated with the different URLs. Calling another service to get the scope is also one solution for this. Any suggestions or recommended methods for this?

**Comment by kikito** [comment]
Good morning, you should be able to accomplish what you need by creating a _Custom Plugin_.

The Custom Plugin Development Guide is here:

https://docs.konghq.com/gateway-oss/2.4.x/plugin-development/

Plugins can have migrations (on db mode) and custom entities (both on db and db-less modes) which could be used to map your scopes and how they map to each consumer.

Since you are doing an auth plugin, it will probably be a good idea to give a look at the [Basic Auth Plugin](https://github.com/Kong/kong/tree/master/kong/plugins/basic-auth) source code, or even use it as a base for your own plugin.

**Comment by reetik-raj** [comment]
Hey, @kikito, thanks for your reply. I went through the plugin development guide and read all about custom plugins and how they work. I have a few more doubts - 
I need to map scopes required with URLs. So I will need to regex match the request URLs in my custom plugin and then compare that regex with the mapping values stored in the plugin custom entity. Then I will call my authorization service with scope, consumer details to authorize. 
Is it a good practice to do this in Kong, or should we develop a service ourselves which we call from Kong passing the URL and the service, in turn, does the whole regex matching, scope determination as well as authorization returning with just one detail - whether the request is authorized or not. What do you recommend?
Also, if we do this in Kong, I am not very clear on how to populate the custom entity table with all the mapping data of URLs and scopes. 
I look forward to your answer.

**Comment by kikito** [comment, marked as answer]
It is difficult for me to understand what you are trying to accomplish, exactly, because "Scope" can mean a lot of different things; since this is an authorization-related discussion, I assume they mean some sort of "permission group", like "Payroll" or "Sales".

> I need to map scopes required with URLs

It sounds like you are trying to do something like this:

```
services:
- name: my-service
  routes:
  - paths: ["/foo"]
  - paths: ["/bar"]
  - paths: ["/baz"]
  plugins:
  - name: my-custom-auth-plugin 
```

So you have one instance of your plugin associated to one Service, and then inside your custom plugin you are trying to do something like this, only with more regexes involved:

```
local path = kong.request.get_path()
if path == "/foo" then
  scope = "sales"
elseif path == "/bar" then
  scope = "payroll"
...
```

Kong already has a way to "map" request urls to regexes on its router (the `paths` attribute admits regexes). So instead of a single plugin associated with the Service, have several plugins, one per Route, and put the as a config variable. Then let the Router pass the appropriate scope to the plugin when it matches a route:

```
services:
- name: my-service
  routes:
  - paths: ["/foo"]
    plugins:
    - name: my-custom-auth-plugin
      config:
        scope: "sales"
  - paths: ["/bar"]
    plugins:
    - name: my-custom-auth-plugin
      config:
        scope: "payroll"
  - paths: ["/baz"]
    plugins:
    - name: my-custom-auth-plugin
     config:
        scope: "admins"
```

And then inside your plugin you will only need to do:

```
config.scope
```

To get the scope.

It's possible that I have misunderstood your needs, please provide more context if that's the case.
