### DISCUSSION TITLE
Custom Plugin - Not getting deployed/enabled

### DISCUSSION THREAD

**Discussion by saravanan-periyasamy03** [Kong/kong#7634] [Help] [answered]
Team, We are trying to deploy the https://github.com/nokia/consumer-rate-limiting custom plugin to our k8's based open-source kong gateway integrated with Postgres DB. Step1, created ConfigMap and updated the plugin configuration in the Kong CR file. Since this plugin has a migrations job (new table creation), added the subdirectory in the plugin configuration in the CR file as below.

```
plugins:
  configMaps:
  - pluginName: consumer-rate-limiting
    name: kong-plugin-consumer-rate-limiting
    subdirectories:
    - name: kong-plugin-consumer-rate-limiting-migrations
      path: migrations
```

Also added the init.lua file in the migrations folder in the custom plugin. While applying the Kong kind(CR), pods are not coming up and throwing below error,

```
waiting for db
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /kong_prefix/nginx.conf:6
nginx: [error] init_by_lua error: attempt to compare string with number
stack traceback:
  [C]: in function 'sort'
  /usr/local/share/lua/5.1/kong/db/errors.lua:21: in function 'sorted_keys'
  /usr/local/share/lua/5.1/kong/db/errors.lua:222: in function 'schema_violation'
  /usr/local/share/lua/5.1/kong/db/migrations/state.lua:117: in function 'load_subsystems'
  /usr/local/share/lua/5.1/kong/db/migrations/state.lua:187: in function 'load'
  /usr/local/share/lua/5.1/kong/db/init.lua:432: in function 'schema_state'
  /usr/local/share/lua/5.1/kong/init.lua:474: in function 'init'
  init_by_lua:3: in main chunk
lua:3: in main chunk
```

Even though pre and post-migrations jobs are successful, new tables are not getting created.
