### DISCUSSION TITLE
Kong Ingress: failed to fetch publish-service

### DISCUSSION THREAD

**Discussion by raman-nbg** [Kong/kong#7709] [Help] [answered]
I'm trying to install Kong Hybrid and got stuck while installing the Control Plane. I'm getting this error from the Kong Deployment (Ingress Container): `failed to fetch publish-service: services "kong-control-plane-kong-proxy" not found`.

What is the publish-service? Where does the kong-proxy come from?

I have the following resources in my kubernetes cluster after deploying Kong using Helm.
```
kubectl get all -n kong
NAME                                                READY   STATUS             RESTARTS   AGE
pod/kong-control-plane-kong-54d6bdd886-6dxgv        1/2     CrashLoopBackOff   6          6m22s
pod/kong-control-plane-kong-init-migrations-9skzm   0/1     Completed          0          18h

NAME                                      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
service/kong-control-plane-kong-cluster   ClusterIP   10.2.10.24   <none>        8005/TCP   18h

NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kong-control-plane-kong   0/1     1            0           18h

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/kong-control-plane-kong-54d6bdd886   1         1         0       18h

NAME                                                COMPLETIONS   DURATION   AGE
job.batch/kong-control-plane-kong-init-migrations   1/1           4s         18h
```

I'm using the following values.yaml for the helm chart:
```yaml
secretVolumes:
- kong-cluster-cert

env:
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  database: "postgres"
  pg_user: kong
  pg_password: kong
  pg_host: "10.3.0.3"

cluster:
  enabled: true
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005

proxy:
  enabled: false
```

**Comment by liyangau** [comment, marked as answer]
This error means control plane is unable to find data plane.

It is mentioned [here](https://github.com/Kong/charts/tree/main/charts/kong#control-plane-node-configuration). 

> If using the ingress controller, you must also specify the DP proxy service as its publish target to keep Ingress status information up to date.

**Reply by raman-nbg** [reply]
How can I specify the DP if it runs on a different kubernetes cluster? In my case CP and DP run on different clusters. The docs that you referenced only describe the case with a different namespace (as far as I understand).

**Reply by liyangau** [reply]
Ingress controller does not work across clusters. You probably need to disable ingress controller on CP and use Admin API to create your Kong objects instead if you don't use CP/DP on the same cluster.

**Reply by raman-nbg** [reply]
Hmm, as you can see in my configuration I did not enable the Ingress Controller on CP.

This is my CP config (using the Kong helm chart):
```yaml
image:
  repository: kong/kong-gateway

secretVolumes:
- kong-cluster-cert

env:
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  admin_api_uri: https://admin.dev.kong.example.com
  admin_gui_url: https://manager.dev.kong.example.com
  database: "postgres"
  pg_user: kong
  pg_password: kong
  pg_host: "10.3.0.3"
  password:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password

cluster:
  enabled: true
  type: ClusterIP
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005

proxy:
  enabled: true
  type: ClusterIP

enterprise:
  enabled: true
  type: ClusterIP
  rbac:
    enabled: true

manager:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8002
  tls:
    enabled: true
    servicePort: 8445

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001
  tls:
    enabled: true
    servicePort: 8444

# only available with enterprise license
clustertelemetry:
  enabled: true
  tls:
    enabled: true
    servicePort: 8006
    containerPort: 8006
```

Now I have the proxy enabled - otherwise the CP does not start. But as far as I understand the proxy should be disabled on the CP.

I don't want to use the Ingress Controller. I want to setup the DP on a different k8s cluster.
