### DISCUSSION TITLE
Can not setup Data Plane - Get "https://localhost:8444": connection refused

### DISCUSSION THREAD

**Discussion by raman-nbg** [Kong/kong#7730] [Help] [answered]
I want to setup Kong (Enterprise with trial license) in Hybrid Mode. The CP is up and running. While the DP tries to start I get the following error:

```
retry 1 to fetch metadata from kong: making HTTP request: Get "https://localhost:8444/": dial tcp 127.0.0.1:8444: connect: connection refused
```

The installation is done using Helm with the following configuration:
```yaml
image:
  repository: kong/kong-gateway

secretVolumes:
- kong-cluster-cert

env:
  role: data_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  admin_api_uri: https://admin.dev.kong.example.com
  admin_gui_url: https://manager.dev.kong.example.com
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_server_name: cluster.dev.kong.example.com
  cluster_control_plane: cluster.dev.kong.example.com:443
  admin_listen: cluster.dev.kong.example.com:443
  database: "off"

admin:
  enabled: false
```

As you can see I want to configure the DP to connect to the CP using a Domain. The CP runs in a different Kubernetes Cluster. The CP exposes the cluster endpoint on `cluster.dev.kong.example.com` and. the admin API on `admin.dev.kong.example.com`.

Why is Kong DP still trying to fetch anything from localhost?

I added the `admin_listen` parameter just for testing. As far as I understand this is only needed on the CP.
