### DISCUSSION TITLE
How to configure an allowed exception for the bot-detection plugin?

### DISCUSSION THREAD

**Discussion by dpraul** [Kong/kong#7745] [Help] [answered]
Hello! We're using the bot-detection plugin for our service, but I'm having difficulties adding an exception to allow the `Microsoft-BotFramework` bot. The bot has the following User-Agent:
```
Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)
```

And we've got the following configuration for out bot-detection plugin:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: api-bot-detection
plugin: bot-detection
config:
  allow:
    - '(Microsoft-SkypeBotApi \(Microsoft-BotFramework\/\d\.\d\))'
```

But requests are still getting a 403 Forbidden from Kong. Is there some trick to how the regex has to be formatted? Or did I miss something?
