### DISCUSSION TITLE
CORS with grpc-web using the kong plugins on GKE

### DISCUSSION THREAD

**Discussion by samelie** [Kong/kong#7890] [Help] [answered]
I've installed kong with helm on gke. 

The grpc-js node application is in 'insecure' mode (not sure this matters?).

This is what I'm seeing:  I'm trying to access a service running on a different subdomain.

<img width="793" alt="Screen Shot 2021-09-25 at 10 54 52 AM" src="https://user-images.githubusercontent.com/942192/134789449-b6c1f8f0-8825-49ed-86ba-6c7e1e4ab050.png">

I  _am_ able however to use `grpcurl` to 'ping' through the ingress to the application.

What I've tried.

` k apply -f plugins.yaml`

> plugins.yaml

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-cors-plugin
config:
  origins:
  - "https://frontend.domain.com"
  - "https://grpc.domain.com"
  methods:
  - GET
  - POST
  headers:
  - Accept
  - Accept-Version
  - Content-Length
  - Access-Control-Allow-Origin
  - origin
  - keep-alive
  - user-agent
  - cache-control
  - content-type
  - content-transfer-encoding
  - custom-header-1
  - x-accept-content-transfer-encoding
  - x-accept-response-streaming
  - x-user-agent
  - x-grpc-web
  - grpc-timeout
  - access-control-request-method
  - access-control-expose-headers
  - Access-Control-Allow-Credentials
  - Content-MD5
  - Authorization
  - Content-Type
  - Date
  - grpc-status
  - grpc-message
  - X-Auth-Token
  exposed_headers:
  - Content-Type
  - X-Auth-Token
  - Access-Control-Allow-Origin
  - grpc-status
  - grpc-message
  credentials: true
  max_age: 3600
  preflight_continue: false
plugin: cors
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-grpc-web-plugin
plugin: grpc-web
```
Then in annotations on ingress: `'konghq.com/plugins': 'my-grpc-web-plugin,my-cors-plugin'` and patch the service `k patch svc grpc-service-prod -p '{"metadata":{"annotations":{"konghq.com/plugins":"my-grpc-web-plugin,my-cors-plugin"}}}'`

Made sure the domains and headers are in the cors plugin.

Any help would so appreciated; feels really close, but I'm missing something. Kong is really nice to work with. 

#### Edit

The first question should be _**does the kong installation need to be in same namespace as KongPlugins, Ingress and other resources?**_ Having a feeling these plugins are not being picked up. Reason being, I added this plugin to the ingress, but observed that `demo: injected-by-kong-for-kubernetes` was _not_ on the `grpcurl` response 

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: add-response-header
  annotations:
    kubernetes.io/ingress.class: kong
config:
  add:
    headers:
    - "demo: injected-by-kong-for-kubernetes"
plugin: response-transformer
```

## Update

Was able to solve this particular issue. The problem was on the ingress annotations, in addition to the plugins, i `"konghq.com/protocol":"grpcs,grpc"` My understanding this is needed when working with server-side grpc, not grpc web.

Facing a new problem now with `Error: Response closed without grpc-status (Headers only)` . Will open another discussion
