### DISCUSSION TITLE
[ProxyCache] X-Cache-Status always Bypass if cache_control is enabled

### DISCUSSION THREAD

**Discussion by wlzch** [Kong/kong#7966] [Help]
I am enabling proxy cache on kong 2.5 using declarative config:
```
  - name: proxy-cache
    config: 
      response_code:
      - 200
      request_method:
      - GET
      - HEAD
      content_type:
      - application/json
      cache_ttl: 300
      strategy: memory
      cache_control: true
```

Then I tried to request using postman and got this response:
<img width="1014" alt="Screen Shot 2021-10-18 at 13 23 39" src="https://user-images.githubusercontent.com/977245/137679714-99857387-3905-44f9-baa1-d59a22fcfffe.png">

The cache-control header should be correct already, but I'm not sure why X-Cache-Status is always Bypass.

I have tried removing `cache_control: true` setting and it successfully returns `X-Cache-Status: Hit`, but I want to be able to configure the cache control from upstream.
