### DISCUSSION TITLE
Allow plugin servers to communicate over network protocols

### DISCUSSION THREAD

**Discussion by esatterwhite** [Kong/kong#7991] [Ideas and feature requests]
The ability to build plugins in languages other than lua is great. However, in the current implementation, the plugin server external to kong is restricted to communicate over a local unix domain socket. In the old Virtual Machine world, this may make a fair amount of sense. In the containerized micro-service drivel Kubernetes world, this poses several challenges. 

Mainly, The plugin server process runs in the same container as kong. Even if one were to mount the unix socket over a volume, it still has to run on the same host as one of the kong instances.

This is a problem on several fronts. 

But primarily is an anti-pattern of containers. Its best practice to have a single process / application running in a single container. In this case, it would be kong and its NGINX workers. As a result, observability of the application (plugin server and/or plugins) is virtually lost. If CPU or memory is running high, I can really only understand that the kong container / pod is running hot. This creates quite a black box problem in terms of system resource utilization problems.

As a result the rules around scaling become rather coarse. I can't really understand if kong needs to be scaled, or if the plugin servers need to be scaled - the run in the same container. The only course of action is to scale everything kong even if the core of kong isn't the thing that needs scaling.

By default, prometheus will use `Deployment` level annotations to discover endpoints for scraping metrics.

```yaml
    kind: Deployment
    metadata:
      name: my-plugin-server
      labels:
        app: my-plugin-server
    spec:
      selector:
        matchLabels:
          app: my-plugin-server
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "8090"
```
If one needs to scrape multiple containers within the same deployment / pod - things get rather tricky rather quickly. If one needs to scrape metrics from multiple processes in a single container; I think you may just be out of luck. Kong would either need to support reporting of arbitrary metrics from plugins, or end users will be required to deploy an additional [metrics proxy](https://github.com/prometheus/pushgateway) just to facilitate the specific problem introduced by kong.

* UNIX Doman Socket
  *  `unix:///path/to/local/domain.sock`
  *  `ipc:///path/to/local/domain.sock`
* TCP Socket
  * `tcp://a-hostname.com`
  * `tcp://a-k8s-service:5050`
  * `tcp://a-k8s-service.default.svc.cluster.local:5050`
* HTTP Connection - `http://a-k8s-service:5050` (maybe not necessary...)
* GRPC Connection - `grpc://a-k8s-server:5050`

This one shift in communication gives implementers of proprietary plugins the ability to deploy, scale and observe the plug applications how they want. And the default behavior of a local socket on the same machine / in the same container as kong still works. So the promise of being able to run kong in VMs, plain containers or kubernetes still holds true. And in the case of kubernetes, engineers can build + deploy them as services in the same fashion they deploy everything else in their production stack.

Thinking out loud, socket library abstractions like [ZeroMQ ](http://wiki.zeromq.org/docs:features#toc6) or [NanoMsg](https://nng.nanomsg.org) / [nng](https://github.com/nanomsg/nng) make this sort of thing much less complicated to implement and give support for a number of network protocols as well as IPC support
