### DISCUSSION TITLE
Opensource Kong API Gateway can route by header?

### DISCUSSION THREAD

**Discussion by storehubdeploy** [Kong/kong#8020] [Help] [answered]
we need a new request that one domain can route to different back service by header diffrent key. is any plugins or just need wirte by myself. Is anyone has the example?
Thanks

**Comment by liyangau** [comment, marked as answer]
Kong route object supports it by default.

Consider below as an example

```yaml
services:
- name: first-svc
  url: https://httpbin.org/anything
  routes:
  - name: first-route
    hosts: ["example.com"]
    headers:
      test-header:
      - first
    paths:
    - /demo
- name: second-svc
  url: https://mockbin.org/request
  routes:
  - name: second-route
    hosts: ["example.com"]
    headers:
      test-header:
      - second
    paths:
    - /demo
```

Request -> `http://example.com/demo -H "test-header:first"` -> httpbin
Request -> `http://example.com/demo -H "test-header:second"` -> mockbin
