### DISCUSSION TITLE
Kong let’s encrypt http challenge conflicts with permanent HTTPS redirect via https_redirect_status_code

### DISCUSSION THREAD

**Discussion by eurodomenii** [Kong/kong#8288] [Help] [answered]
With https_redirect_status_code set to 301 or 302, it’s possible to automatically redirect to HTTPS. This property was introduced in Kong 1.2.  https://github.com/Kong/kong/pull/4424/files 
 
However, this redirect seems to be unconditionally. So, it’s incompatible with let’s encrypt http challenge  https://docs.konghq.com/hub/kong-inc/acme/  

The only solution I’ve come with was based on https://github.com/Kong/kong/issues/1946#issuecomment-485830359, using pre-function plugin.

It’s essential to run curl from the current directory of the .lua file

`root@kg1:/usr/local/share/lua/5.1/kong# curl -i -X POST http://localhost:8001/services/blx/plugins  -F "name=pre-function"  -F "config.access[1]=@http-acme-2-https.lua"
`
```
root@kg1:/usr/local/share/lua/5.1/kong# cat http-acme-2-https.lua
local scheme = kong.request.get_scheme()
local query = kong.request.get_path_with_query()
local pattern = "/%.well%-known/acme%-challenge/.*$"
local match = string.find(query, pattern)
if scheme == "http" and match == nil then  
  local host = kong.request.get_host()
  local url = "https://" .. host ..query
  kong.response.set_header("Location",url)
  return kong.response.exit(301,url)
end

```

Thx!

**Comment by hbagdi** [comment, marked as answer]
Could you create a route in kong that has a path set to `/.well-known/acme-challenge/` which does not have the https_redirect_status_code set to 30X? The more specific route wins that will work around this issue.

**Comment by eurodomenii** [comment]
Thanks for the tip. It works! 

I was stuck on the idea to use a global dummy route, from the example https://docs.konghq.com/hub/kong-inc/acme/#configure-plugin 

```
services:
  - name: acme-dummy
    url: http://127.0.0.1:65535
    routes:
      - name: acme-dummy
        protocols:
          - http
        paths:
          - /.well-known/acme-challenge 

```

But it’s cleaner to add another route ( the code is generated with deck) 

```
services:
- connect_timeout: 60000
  host: BackendIP
  name: myservice
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - hosts:
    - mydomain.eu
    https_redirect_status_code: 301
    id: cabf6d2f-9d4a-474e-ac4c-c50ee53735f9
    path_handling: v0
    preserve_host: true
    protocols:
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - hosts:
    - mydomain.eu
    https_redirect_status_code: 426
    id: cabf6d2f-9d4a-474e-ac4c-c50ee83735f9
    path_handling: v0
    paths:
    - /.well-known/acme-challenge
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  write_timeout: 60000

```
