### DISCUSSION TITLE
Kong not picking up env variables from deployment yaml on kubernetes.

### DISCUSSION THREAD

**Discussion by arbazsiddiqui** [Kong/kong#8418] [Help] [answered]
I am trying to run kong with database backend on kubernetes. I dont want to use the ingress controller, instead will be using a service to expose proxy routes. The problem is that kong is not picking up ENV variables for kong.conf from the deployment.yaml.

deployment.yaml:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kong
  namespace: turnip
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: 'kong:latest'
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: postgres-stage.c0cu0shiozn2.ap-south-1.rds.amazonaws.com
            - name: KONG_PG_USER
              value: postgres
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
```

These env are getting correctly sent to pod, after bashing into a pod and doing `echo $KONG_DATABASE` I get `postgres`.

But inside the pod at `/etc/kong/` the `kong.conf.default` the database section is commented out:

```
#database = postgres             # Determines which of PostgreSQL or Cassandra
                                 # this node will use as its datastore.
                                 # Accepted values are `postgres`,
                                 # `cassandra`, and `off`.

#pg_host = 127.0.0.1             # Host of the Postgres server.
#pg_port = 5432                  # Port of the Postgres server.
#pg_timeout = 5000               # Defines the timeout (in ms), for connecting,
                                 # reading and writing. 
```

Do I need to build a custom image with the conf I want or is there any way to do this using latest image and env variables.
