### DISCUSSION TITLE
Kong service load balancer(svclb) pod pulls image from docker hub

### DISCUSSION THREAD

**Discussion by shusriva** [Kong/kong#8433] [Help]
Hi Team,

kong service load balancer pod pulls rancher/klipper image from docker hub. As per requirement, I want to pull this image from my own repository but there is no configuration defined in proxy section of values.yaml to pull this proxy image(svclb) from custom repository rather than docker hub. 
Can you please help me out to resolve this issue

**Comment by kikito** [comment]
I am not exactly sure of what the "kong service load balancer pod" means in your question. Can you please clarify? What commands are typing to use it?

> I want to pull this image from my own repository but there is no configuration defined in proxy section of values.yaml to pull this proxy image(svclb) from custom repository rather than docker hub.

Usually those infrastructure changes are defined in the infrastructure files: docker image files, or kubernetes configurations. Your question seems to indicate that you need to fork an existing one and create your own, with modifications. I would need more information about what exactly you are attempting.

**Comment by shusriva** [comment]
Hi kikito,
Thank you for your response !

I'll explain the issue in more detail way.

I am deploying kong gateway through helm chart. I have provided some custom values in values.yaml file.
These are the values

```
ingressController:
  installCRDs: false
  image:
    repository: ${registry_container_image:NA}/${repo_image_kubernetes_ingress_controller:NA}
    tag: ${tag_image_kubernets_ingress_controller:="2.0"}
    pullSecrets:
    - shubham-secret  

env:
  plugins: "bundled,oidc"
  database: "postgres"
  pg_host:
    valueFrom:
      secretKeyRef:
        name: kong-admin-postgres-cluster-pguser-kong-admin-user
        key: host
  pg_port: 
    valueFrom:
      secretKeyRef:
        name: kong-admin-postgres-cluster-pguser-kong-admin-user
        key: port
  pg_user: 
    valueFrom:
      secretKeyRef:
        name: kong-admin-postgres-cluster-pguser-kong-admin-user
        key: user
  pg_password:
    valueFrom:
      secretKeyRef:
        name: kong-admin-postgres-cluster-pguser-kong-admin-user
        key: password
  pg_database:
    valueFrom:
      secretKeyRef:
        name: kong-admin-postgres-cluster-pguser-kong-admin-user
        key: dbname

admin:
  enabled: true   
  http:
    enabled: true   
image:
  repository: ${registry_container_image:NA}${repo_image_kong:NA}
  tag: ${tag_image_kong:NA}
  pullPolicy: IfNotPresent
  pullSecrets:
    - shubham-secret

#this proxy is working, if you want to use load balancer than use
proxy:
  http:
   servicePort: 9090
  tls:
    servicePort: 9443   

#Making kong HA
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3


#autoscalling will depend on below config
resources:
  limits:
    # cpu: 400m
    memory: 1Gi
  requests:
    # cpu: 5m
    memory: 500Mi

```
once the kong is deployed, following pods are coming up(screenshot attached)
![image](https://user-images.githubusercontent.com/35764437/155263684-0da2d631-880e-4688-a0c9-c88935e43d29.png)

admin-kong-kong pods containers pulls the image from my local registry which is absolutely fine.
**service load balancer pod**
```
svclb-admin-kong-kong-proxy-79wqj 
svclb-admin-kong-kong-proxy-gnmgq
svclb-admin-kong-kong-proxy-p8wcp
```
this service load balancer pod pulls the image(rancher/klipper) from docker hub directly.
![image](https://user-images.githubusercontent.com/35764437/155263954-e57d55e2-aac0-460a-baaf-984b19f92e30.png)

As per my requirement I want to pull this rancher/klipper image from ly local registry instead of docker hub 

Can you please let me know in which section of values.yaml(kong helm chart) shall I modify so that these pods  ( svclb-admin-kong-kong-proxy-79wqj , svclb-admin-kong-kong-proxy-gnmgq ,svclb-admin-kong-kong-proxy-p8wcp ) should pull the image from my custom repository instead of docker hub. As i am able to do in case of ingressController
