### DISCUSSION TITLE
Can IP restriction plugin be used to block traffic to certain IPs on service type load balancer in AKS?

### DISCUSSION THREAD

**Discussion by max77p** [Kong/kong#8532] [Help] [answered]
I have the following:

This is deployed into an AKS cluster. 

**Problem:** When I simply go to the ip of my load balancer, i get a message "no matching routes found" which means I am able to hit my load balancer ip.

**What I am expecting:** "Your IP address is not allowed"

**Question:** Am I expecting this to do something it is not designed to do or do I have this configured incorrectly?

kongplugin:

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-id
disabled: false
config:
  allow: ["<ip-i-own>"]
  deny: ["<another-ip-i-own"]
plugin: ip-restriction
```

service:

```
apiVersion: v1
kind: Service
metadata:
  name: ce-infra-kong-proxy
  namespace: kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-2.6.3
    app.kubernetes.io/instance: "ce-infra"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "2.6"
    enable-metrics: "true"
  annotations:
    konghq.com/plugins: request-id
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: kong-proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-tls
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: "ce-infra"
