### DISCUSSION TITLE
Kong Portal CLI - Support additional headers

### DISCUSSION THREAD

**Discussion by meesvandongen** [Kong/kong#8536] [Ideas and feature requests]
DecK allows adding additional headers to requests to the admin API, which is useful for those that want to add an additional layer of security to the API (e.g. API key). It would be useful is this were supported in the Portal CLI as well.

Edit: it seems this IS supported, but the documentation is a bit lacking. Will try to see if I can get it to work, and then close this / maybe make a merge request.

**Comment by meesvandongen** [comment]
This seems to work:
```yaml
# Kong Admin URL
# @required
kong_admin_url: https://my-admin-url/with-api-key

# Kong Admin Token
# @optional
kong_admin_token: "my-admin-token"

# The new part: list of key / value pairs per header.
headers:
  "apikey": "my-api-key"
```

Options are currently documented in the code: https://github.com/Kong/kong-portal-cli/blob/master/src/core/WorkspaceConfig.ts

Not sure where on the website it would best fit to put this info more structurally, so I will refrain from making any suggestions.
