### DISCUSSION TITLE
configFrom in kongClusterPlugin, is this the correct format? Not documented anywhere

### DISCUSSION THREAD

**Discussion by max77p** [Kong/kong#8538] [Help] [answered]
The secret:
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kongsecret
  namespace: kong
stringData:
  config.yaml: |
    allow: "ip1"
    deny: "ip2"
    message: "denied"
```
KongClusterPlugin
```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-ip-restriction
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
configFrom:
    secretKeyRef:
       name: kongsecret
       key: deny
       namespace: kong
plugin: ip-restriction
```

In my Kubernetes cluster I am seeing the following:
<img width="1228" alt="Screen Shot 2022-03-11 at 11 51 17 AM" src="https://user-images.githubusercontent.com/12217034/157911574-a5fdb014-41cd-4982-bf20-b1aed23b194f.png">
