### DISCUSSION TITLE
Kong - Host Header Problem

### DISCUSSION THREAD

**Discussion by stephanbartkowiak-hotmart** [Kong/kong#8551] [Help] [answered]
I'm having an issue using Kong Gateway. When I call my route with the `fedoraStaging` service It is not changing the host to the same of the origin proxy and the requests respond to me with `404` because the `host` from kong are using the wrong header host.

# Kong Configuration:
```
_format_version: "1.1"
plugins:
  - config:
      anonymous: null
      hide_credentials: false
      key_in_body: false
      key_in_header: true
      key_in_query: true
      key_names:
        - apikey
      run_on_preflight: true
    enabled: true
    name: key-auth
    protocols:
      - grpc
      - grpcs
      - http
      - https
services:
  - connect_timeout: 60000
    host: echoserver.test.test.com
    name: fedoraStaging
    path: /kong_api
    port: 443
    protocol: https
    read_timeout: 60000
    write_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        methods:
          - GET
        name: TestKong
        path_handling: v0
        paths:
          - /echoworld$
        preserve_host: false
        protocols:
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: false
```

# Problem:

## Request:
```
curl --location --request GET 'http://kong.test.test.com/echoworld' \
--header 'apikey: 3fdn2pRU32t70U9ztRTHz56p30KxdseN'
```

## Expected:
```
{
    "hello": "world"
}
```

## Response:
```
Status 404
```

# Working:

## Request
```
curl --location --request GET 'http://kong.test.test.com/echoworld' \
--header 'apikey: 3fdn2pRU32t70U9ztRTHz56p30KxdseN'
--header 'Host: kong.test.test.com'
```

## Response:
```
{
    "hello": "world"
}
```
