### DISCUSSION TITLE
Add delay in API response

### DISCUSSION THREAD

**Discussion by anup-krai** [Kong/kong#8980] [Help] [answered]
We are using Kong with KIC deployed in K8s cluster with Postgres DB.
Kong - 2.7.1
KIC - 2.2.1
We have Kong deployed in multiple datacenter and Postgres running with master and replica setup.
Postgres master is running in one datacenter and replicas are running in other datacenter. Write calls are routed to Postgres master node and read calls are routed to Postgres replicas. We are using oauth2 plugin for the API routes.

We see when token is generated a write call is made to master Postgres node and the same is getting synced to other replicas. So when actual API call comes then token will be read from read replicas and then API call is allowed.

In some cases we see before the tokens are synced to the replicas the API call is made and it’s getting rejected with HTTP 401.

Is there a way we can avoid this issue?

We tried to add some (ms) delay to the oauth calls using a custom plugin with below code -
```
function ResponseDelayHandler:header_filter(conf)
    local http_status = kong.response.get_status()
    local sleep_time = conf.sleep_time
    if http_status == 200 then
        socket.sleep(sleep_time)
    end
end
```
This plugin is added only to oauth token route but this is decreasing the throughput for other routes also.

**Before adding a delay** -
Both oauth and API calls are handling more than 1K TPS.

**After adding a delay** -
TPS is reduced to 1/3. OAuth call throughput reduction is expected because of delay but why other API calls throughput is also reduced? This API has only local rate limiting plugin added.

**Comment by hanshuebner** [comment]
Hello @anup-krai,

thank you for your report.  We think that when running a Kong node against a read-only Postgres replica, you're bound to see consistency problems like these.  We'd thus suggest that you run your Kong nodes against a writeable PostgreSQL endpoint that is globally consistent instead.

Delaying all requests in order to wait for any replica writes to have happened is bound to cause failures during high-load situations, and as you have observed, it reduces the overall throughput, too.

Kind regards,
Hans

**Reply by anup-krai** [reply]
If we point all the calls to only Postgres master then it may create other issues like high latency as Kong running is other datacenters need to connect to Postgres master which is in different datacenter. Also it may create issues during high load as only one Postgres node is taking both read and write traffic.

We just wanted to know if delay plugin is added only for oauth route then why throughput is reduced for other routes as well where this delay plugin is not added or is there any other way for adding delays?

**Reply by hanshuebner** [reply]
Can you supply us with an isolated test case that demonstrates how your plugin, when added to a particular route, slows down other routes?  As you expect, if a plugin is added to a route, it should affect only that route, but we'll need more detailed information in order to reproduce your problem.

**Reply by anup-krai** [reply]
[Here](https://github.com/anup-krai/kong-plugin-response-delay/tree/master/kong/plugins/response-delay) is the plugin code which I am using.
Below is the plugin configuration -
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oauth-response-delay
plugin: response-delay
config:
  sleep_time: 0.03
```
This plugin is added to `/oauth2/token` route.

When the perf test is done **without** adding this plugin -
Oauth route - 300 TPS
Read calls - 800 TPS

When perf test is done **after adding** the plugin to oauth route -
Oauth route - 80 TPS
Read calls - 400 TPS

**Reply by hanshuebner** [reply]
Can you provide a [decK](https://docs.konghq.com/deck/latest/) dump of the complete configuration you use for testing?

**Reply by anup-krai** [reply]
Below are the configurations which are applied -
**OAuth Route** -
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: oauth2, oauth-response-delay
    konghq.com/protocol: https
    kubernetes.io/ingress.class: kong
  name: oauth
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: oauth-svc
                port:
                  number: 443
            path: /oauth2/token
            pathType: Exact
```
**Service** -
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/protocol: https
  name: oauth-svc
spec:
  externalName: example.com
  ports:
    - name: http
      port: 443
      protocol: TCP
  type: ExternalName
```
**Response delay Plugin** -
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oauth-response-delay
plugin: response-delay
config:
  sleep_time: 0.03
```
**OAuth Plugin** -
```
apiVersion: configuration.konghq.com/v1
config:
  enable_client_credentials: true
  global_credentials: true
  hide_credentials: true
  provision_key: 'true'
  token_expiration: 3600
kind: KongPlugin
metadata:
  name: oauth2
plugin: oauth2
```
**Second API (Without OAuth)** -
**Ingress**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: 'loopback-v1-request-termination,loopback-rate-limiting'
    konghq.com/protocol: https
    kubernetes.io/ingress.class: kong
  name: loopback-v1
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: loopback-v1-svc
                port:
                  number: 443
            path: /v1/loopback/status
            pathType: Exact
```
**Service** -
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/protocol: https
  name: loopback-v1-svc
spec:
  externalName: example.com
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 443
  type: ExternalName
```
**Plugin** -
```
apiVersion: configuration.konghq.com/v1
config:
  message: UP
  status_code: 200
kind: KongPlugin
metadata:
  name: loopback-v1-request-termination
plugin: request-termination
```
```
apiVersion: configuration.konghq.com/v1
config:
  fault_tolerant: true
  hide_client_headers: false
  limit_by: consumer
  policy: local
  second: 2000
kind: KongPlugin
metadata:
  name: loopback-rate-limiting
plugin: rate-limiting
```
