### DISCUSSION TITLE
use of require or ngx in request-transformer?

### DISCUSSION THREAD

**Discussion by mdaniel** [Kong/kong#9003] [Help]
- Kong: 2.7.2
- KIC: 2.2

I am trying to do string surgery upon a header value, but it blows up with "failed to render the template" and [looking at `pl.temlate`](https://github.com/lunarmodules/Penlight/blob/1.12.0/lua/pl/template.lua) didn't help me to know what helper functions were available; I did see the [`shared` in the sandbox env](https://github.com/Kong/kong/blob/2.7.2/kong/plugins/request-transformer/access.lua#L87) but it wasn't obvious what was exposed upon it

Attempting to use `require` or to use the `ngx` family of modules causes errors

```yaml
plugin: request-transformer
config:
  add:
    headers:
    - |
      x-sample:$((function()
        local b64d = ngx.base64_decode -- kaboom
        local cjson = require "cjson" -- kaboom
        shared.log.debug("hello") -- kaboom
      end)())
```

How can one find out what lua-isms are legal inside that `function` block?
