### DISCUSSION TITLE
Kong is not loading my static CSS files

### DISCUSSION THREAD

**Discussion by Semproms** [Kong/kong#9025] [Help] [answered]
Hi! I am new using Kong and I am building a reverse proxy with NGINX that controls the access to a three docker containers which contain a little App I've developed. This proxy can only be accessed by an apy-key authorized by Kong with the [key-auth plugin](https://docs.konghq.com/hub/kong-inc/key-auth/). The scheme is something like this:

![imagen](https://user-images.githubusercontent.com/9299890/176179023-a7f81aed-b712-44bc-94c2-145a596b0ad5.png)

If the clients don't have the api-key the request is denied. It seems to be working, but I have a problem with the static css files. From the browser I can access the application, but the CSS and JS does not load because they don't send the api-key in the request. For this reason I get a 401 HTTP unauthorized response when the browser tries to load the styles:

```
GET http://localhost:8000/myapp/r2/docs/stylesheets/library.css[HTTP/1.1 401 Unauthorized 1ms]
message "No API key found in request"
```

So my app is loading in the browser without styles. These are my style headers in the app:

`  <link href="myapp/r2/docs/stylesheets/library.css" rel="stylesheet" type="text/css">`

How can I send my api-key to load the styles and js too?

**Comment by flrgh** [comment, marked as answer]
Hi @Semproms :wave: 

In general this is something you'll need to account for in your frontend (html/css/js) code. Alternatively, if you want to simply allow static files without requiring auth, you could add a separate route for them that is unprotected by the key-auth plugin (e.g. `/myapp/` requires an API key, but `/myapp/r2/docs/stylesheets/` does not).

Another option to consider would be to use the basic-auth plugin instead. Most browsers will automatically attach the `Authorization` header to subsequent requests for the same domain after you have authenticated for the first time, so this would largely do away with the need to attach an API key to each static asset request.

**Comment by Semproms** [comment]
Hi @flrgh

Thank you very much for your reply.

I can't use basic-auth because I need api-key authentication method and basic-auth I think it uses user and password. Anyway I've tried the solution of creating two routes, one route for `/myapp/r2/docs/stylesheets/` and another one for `/myapp/r2/docs/` but it is not working. This is my `kong.yaml`, according to the docs I think everything seems to be ok. If anyone sees something wrong it would be very helpful.

```
_format_version: '2.1'
_transform: true

services:
- name: myapp-service
  host: myapp  
  url: http://192.168.1.95:3505/myapp/r2/docs/
  tags:
  - team-svc1
  routes:
  - name: r1
    paths:
    - /myapp/r2/docs/
  - name: r2
    paths:
    - /myapp/r2/docs/stylesheets/

plugins:
- name: key-auth
  route: r1
  config: 
    key_names:
    - apikey
    key_in_body: false
    key_in_header: true
    key_in_query: true
    hide_credentials: false
    run_on_preflight: true

consumers:
- username: my-user
  keyauth_credentials:
  - key: ausbasudAS5589AS8W8yQe

keyauth_credentials:
- consumer: my-user
```
The key-auth is only activated in r1. If I run this the error is 404 instead of the 401 I had before.

**Reply by flrgh** [reply]
Most likely Kong is sending `/stylesheets/library.css` to the backend because of Kong's [path stripping strategy](https://docs.konghq.com/gateway/latest/admin-api/#path-handling-algorithms). I usually find it easier to leave the service path empty and set `strip_path = false` on any attached routes. Try this:

```yaml
services:
- name: myapp-service
  url: http://192.168.1.95:3505
  tags:
  - team-svc1
  routes:
  - name: r1
    paths:
    - /myapp/r2/docs/
    strip_path: false
  - name: r2
    paths:
    - /myapp/r2/docs/stylesheets/
    strip_path: false
```

**Reply by Semproms** [reply]
I am still having 404 error for these files with the strip_path:
```
http://localhost:8000/myapp/r2/docs/stylesheets/library.css
http://localhost:8000/myapp/r2/docs/stylesheets/ipc.css
http://localhost:8000/myapp/r2/docs/stylesheets/style.scss
```
The current yaml:
```
_format_version: '2.1'
_transform: true

services:
- name: myapp-service
  url: http://192.168.1.95:3505
  tags:
  - team-svc1
  routes:
  - name: r1
    paths:
    - /myapp/r2/docs/
    strip_path: false
  - name: r2
    paths:
    - /myapp/r2/docs/stylesheets/
    strip_path: false

plugins:
- name: key-auth
  route: r1
  config: 
    key_names:
    - apikey
    key_in_body: false
    key_in_header: true
    key_in_query: true
    hide_credentials: false
    run_on_preflight: true
- name: session
  config: 
    secret: opensesame

consumers:
- username: my-user
  keyauth_credentials:
  - key: ausbasudAS5589AS8W8yQe

keyauth_credentials:
- consumer: my-user
```
In case it could be helpful, the links in the ejs file:

```
  <link href="/myapp/r2/docs/stylesheets/library.css" rel="stylesheet" type="text/css">
  <link href="/myapp/r2/docs/stylesheets/ipc.css" rel="stylesheet" type="text/css">
  <link href="/myapp/r2/docs/stylesheets/style.scss" rel='stylesheet' type="text/css"/>
```
One of the kong's error messages in docker-compose:
```
172.21.0.1 - - [29/Jun/2022:07:42:33 +0000] "GET /myapp/r2/docs/stylesheets/ipc.css?apikey=ausbasudAS5589AS8W8yQe HTTP/1.1" 404 189 "http://localhost:8000/myapp/r2/docs/7778?apikey=ausbasudAS5589AS8W8yQe" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
```
Thank you very much for your help. Hopefully we can fix it soon.

**Reply by flrgh** [reply]
@Semproms what does the upstream/origin server (`http://192.168.1.95:3505`) report in its logs for these 404 messages? Ideally you should be able to see the URI it received from Kong and compare it to what is expected in order to find the issue.

**Reply by Semproms** [reply]
Thanks, @flrgh 

Finally I was able to find the problem. The href route in the static file and the route in the kong.yaml for the stylesheets were wrong.

`<link href="/myapp/r2/docs/stylesheets/library.css" rel="stylesheet" type="text/css"> (Wrong)`
`<link href="/stylesheets/library.css" rel="stylesheet" type="text/css">`(Correct)

And the yaml:

```
  - name: r2
    paths:
    - /myapp/stylesheets/
    strip_path: false
```

Now is working. Thanks for your answers!
