### DISCUSSION TITLE
Exposing Kong status listener port

### DISCUSSION THREAD

**Discussion by sanjimoh** [Kong/kong#9152] [Help]
I have a setup with KIC (Kong Ingress Controller on Kubernetes) which is provisioned through Kong helm chart.
```
$ helm repo add kong https://charts.konghq.com
$ helm repo update

$ helm install kong/kong --generate-name
```
Post the installation, I noticed that Kong services created doesn’t expose the status listener port 8100; only 80 & 443 ports are currently being exposed.
```
(⎈ |arn:aws:eks:us-west-2:xxxx:cluster/data-plane:apigw)k get svc -o wide | grep kong
kong-kong-proxy          LoadBalancer   x.x.x.x     80:32442/TCP, 443:31590/TCP   32h
   app.kubernetes.io/component=app,app.kubernetes.io/instance=kong,app.kubernetes.io/name=kong
```

Digging a bit onto the helm values of the Kong chart, I noticed the below comment which indicates that the status listener port 8100 is not supposed to be exposed through a service. Is there a reason for this?
```
# Specify Kong status listener configuration
# This listen is internal-only. It cannot be exposed through a service or ingress.
status:
  enabled: true
  http:
    # Enable plaintext HTTP listen for the status listen
    enabled: true
    containerPort: 8100
    parameters: []
```

I am trying to use Kong [prometheus-plugin](https://docs.konghq.com/hub/kong-inc/prometheus/#accessing-the-metrics) which mentions in it’s doc that once the status API is enabled, the metrics can be accessed through /metrics endpoint via port 8100.

If I explicitly edit the Kong service and add 8100 port explicitly then I am able to access the metrics endpoint over 8100 port without an issue.

Need help to understand why is 8100 port not exposed through Kong service when the prometheus Kong plugin doc is relying on this port for the metrics. Any help here in clarifying the above query is highly appreciated.
