### DISCUSSION TITLE
Kong Manager authentication in Enterprise free mode

### DISCUSSION THREAD

**Discussion by vrlorad** [Kong/kong#9239] [Help]
I manage to run Kong Manager in Enterprise free mode and I can see default workspace with all services, routes and consumers I created by using Admin API. Also, it is possible to add new consumers, create services and routes and assign plugins etc. 
As I understood, since I do not have license I am limited only to default workspace and there is no possibility do add new users and roles since for RBAC I need license for this as well.
But what about Kong Manager authentication? I have enabled basic-auth for kong_admin_gui_auth and my expectation was that I would be able to get login form and use super admin user to log in but I get "Authentication is not enabled" when go to:

`https://kong-manager.my-domain.com/login` 

Is it possible to enable authentication in Kong Manager Enterprise Free mode or I need to obtain licensed version for this?

Also, this is part of my values.yaml from Helm chart where I enabled the basic-auth:

```
enterprise:
  enabled: true
  # CHANGEME: https://github.com/Kong/charts/blob/main/charts/kong/README.md#kong-enterprise-license
  license_secret: 
  vitals:
    enabled: true
  portal:
    enabled: false
  rbac:
    enabled: true
    admin_gui_auth: basic-auth
    session_conf_secret: kong-session-config
  smtp:
    enabled: false
```
Thanks in advance for any help!
