### DISCUSSION TITLE
kong sends SNI only from target upstream | does not read certificate

### DISCUSSION THREAD

**Discussion by dimitryvoronov** [Kong/kong#9247] [Help]
Hello kong team,
I would like to understand how SNI works on kong level, so far I did not manage to get it working in way when it's reading certificate.

Test env setup:
API gateway: kong, version 2.8.1
service: haproxy with self-generated certificate
service backend: nginx

kong configuration:
- certificate uploaded from haproxy service
- upstream which looks on haproxy:443
- service with https protocol and 443 port
- route with /haproxy-service path for the service configured above with client certificate of haproxy id

deck example conf-on:
```
_format_version: "1.1"
_info:
  select_tags:
  - custom-conf
upstreams:
- slots: 10000
  name: haproxy_test
  targets:
  - target: 172.20.68.154:443
services:
- name: haproxy-test-service
  url: http://haproxy_test:443
  retries: 5
  protocol: https
  routes:
  - name: haproxy-test-service-route
    strip_path: false
    paths:
    - "/haproxy-service"
    path_handling: v0
    https_redirect_status_code: 426
```

When we send a request to https://api-gateway/haproxy-service I do see that sni sends within a value from upstream:target

### question one:
**Is it possible to send a different SNI value, from certificate when it's defined on service level?**
I run a numerous test and  kong only sends a value from upstream target and that's it.

### question two:
**Why kong does not read certificate sni value when it's used on upstream level?**

If I define a certificate on upstream level.
example:
```
_format_version: "1.1"
_info:
  select_tags:
  - custom-conf

upstreams:
- slots: 10000
  client_certificate:
    id: 1d558c54-c37d-458a-8034-b0eac6a91773
  name: haproxy_test
  targets:
  - target: 172.20.68.154:443
```

When I try to request https://api-gateway/haproxy-service I was expecting that a value defined on certificate (SNI value) will be used, but it not. kong does not read certificate at all and on traffic dump I do not see anything related sni.

Thanks.
