### DISCUSSION TITLE
How to URL encode query strings using request transformer

### DISCUSSION THREAD

**Discussion by rhargreaves** [Kong/kong#9613] [Help]
We're using the `request-transformer` plugin as so:

```
- name: some-route
  url: http://some-url
  routes:
    - name: some-route
      paths:
        - /some-url/?$
      methods:
        - GET
  plugins:
    - name: request-transformer
      config:
        replace:
          uri: /foo/$(query_params.foo)/bar/$(query_params.bar)/
 ```

However, there doesn't seem to be a way to properly URL encode the `query_params.foo` or `query_params.bar` variables. This means it cannot be used with any query string which might contain Unicode characters. We've tried using `untrusted_lua` but it doesn't seem to allow us to access any global variables (such as `require` or `ngx`)

As such, we've had to make a custom plugin to solve this particular issue, but its not a generic solution.

We're using version 2.5.0.
