### ISSUE TITLE
Route with Host and Path not working in Kong 3.1.1

### ISSUE THREAD

**Issue by ArneRiemann4711** [Kong/kong#10024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1

### Current Behavior

With Kong 2.8.

```
 - name: start-ui
    url: https://start-ui.local:8443
    connect_timeout: 1000
    write_timeout: 10000
    read_timeout: 10000
    routes:
      - name: start-ui
        hosts:
          - start.domain.de
  - name: start-service
    url: https://start-service.local:8443
    connect_timeout: 1000
    write_timeout: 10000
    read_timeout: 10000
    routes:
      - name: start-service
        hosts:
          - start.domain.de
        paths:
          - /start-service
```

Works fine, requests to `start.domain.de` will routed to the frontend and `start.domain.de/start-service` to the backend.
With Kong 3.1.1. the route to the backend is not found.

### Expected Behavior

Routing works like in 2.8.x
