### ISSUE TITLE
Kong Ingress strip-path is not working

### ISSUE THREAD

**Issue by sridhar1495** [Kong/kong#10064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.4.0

### Current Behavior

I have configured my kong-ingress as follows for my Kubernetes environment
```
ingress:
  name: kong-ingress
  annotations:
    konghq.com/strip-path: "true"
  rules:
  - http:
      paths:
      - path: /apipath
        pathType: ImplementationSpecific
        backend:
          service:
            name: mt-amp-api-gateway
            port:
              number: 8080
```
mt-amp-api-gateway - is my Kubernetes service name 
I am trying the access the resource that is having the path as '/api/service/endpoint'.
To access the service endpoint with the above configuration my access url must be 'http://{ip}:{port}/apipath/api/service/endpoint'.  
'http://{ip}:{port}/api/service/endpoint' is not working.

To remove '/apipath' from the URL I have given the 'konghq.com/strip-path: "true"' as well. But still, it is not working.

### Expected Behavior

The resource must be accessed with 'http://{ip}:{port}/api/service/endpoint'. 
How to configure this behaviour. If this is the bug is there any alternatives available for now?
