### ISSUE TITLE
Regex priority not working as expected in Kong v3.1.1

### ISSUE THREAD

**Issue by r1ckr** [Kong/kong#10151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1

### Current Behavior

In Kong v < 3 we were able to have these routes:
```
  - name: service-a
    url: http://serviceA:3000
    routes:
      - name: account-get
        strip_path: false
        tags: [ account ]
        paths:
          - /account
        methods:
          - GET

  - name: service-b
    url: http://serviceB:3000
    routes:
      - name: account-some-get
        strip_path: false
        tags: [ account ]
        paths:
          - /account/some/.+/else
        methods:
          - GET
```
So the service-a was going to get all urls starting with `/account`, and only a url like `/account/some/anywordhere/else` would match the service-b route.

The reason this worked is because Kong in versions <3 was prioritizing regexes over non-regexes.

### Expected Behavior

We are upgrading to Kong 3.1.1 and we are changing all our regexes to start with ~ like so:
```
  - name: service-a
    url: http://serviceA:3000
    routes:
      - name: account-get
        strip_path: false
        tags: [ account ]
        paths:
          - /account
        methods:
          - GET

  - name: service-b
    url: http://serviceB:3000
    routes:
      - name: account-some-get
        strip_path: false
        tags: [ account ]
        paths:
          - ~/account/some/.+/else
        methods:
          - GET
```
And we were seeing requests going to `/account/some/..../else` ending up un the service-a service rather than the service-b.

Then we decided to change the route in service-a to a regex `~/account$`. After that change we started to see the requests to `/account/some/..../else` ending on service-b, which is the expected behaviour.

If we update service-a to a route like `~/account` it won't work again, which is wrong since longer regexes should have higher priority.

Here is the documentation explaining the priority:
https://docs.konghq.com/gateway/latest/key-concepts/routes/#regular-expressions-and-prefix-paths

### Steps To Reproduce

```markdown
1. Create a service with a non-regex route like `/account`
2. Create another service with a regex route on a subpath of the previous like `~/account/.+/some`
3. Try calling to `/account/anystring/some`. You would expect hitting the second service, but in reality hits the first.

4. Update the first service to be regex now like: ~/account$

5. Call to `/account/anystring/some`. Now the request ends up in the second service as it should.

6. Update the first service to be regex now like: ~/account

7. Call to `/account/anystring/some`. The request ends up in the first service, this should not be like that, since according to the documentation longer regexes have higher priority.
```

**Comment by hanshuebner** [comment]
> If we update service-a to a route like ~/account it won't work again, which is wrong since longer regexes should have higher priority.

Regular expressions are never compared by their length.  This is done only for prefix paths, and that is also what's described in the documentation.  We're open to improving the wording in the documentation since apparently, it is not clear enough.  Can you make a suggestion?

Thank you,
Hans

**Comment by r1ckr** [comment]
We could help on that, I think we need to see what is the right behaviour before we jump into improving the docs.

Would non-regexes be evaluated before or after regex paths?
Non-regex paths will be prioritized by length?

We could order the following list to explain how the routes are evaluated, the same it's done with the plugins:

Evaluation order:
- Complex regex
- Less complex regex
- Longer non-regex
- Shorter non-regex

We would also need to update the migration instructions to v3. The migration only mentions that we need to prefix our regex paths with ~, but that is not enough.

**Comment by hanshuebner** [comment]
Please read the section in the manual that you have pointed to in your original posting.  It completely describes the evaluation order and the prioritization.  It also describes that the length of the regular expression plays no role.  Kong terminates the search for a route on the first match, and the length of a regular expression does not at all reflect how specific it is.  If Kong tried all routes and then used the best one, it would be possible to use the longest match, but that is not how Kong works.

You may want to review the documentation starting here: https://docs.konghq.com/gateway/latest/key-concepts/routes/#how-requests-are-routed

Again, I'm not saying that the documentation is perfect and the documentation on how Kong routes requests in `traditional_compat` mode is new, because many users were confused like you seem to be.  However, the points that you bring up are all already clarified in the documentation, so it might be worthwhile checking it out.

**Comment by r1ckr** [comment]
Hey folks we finally discovered the issue here, after a lot of back and forth with our definition we saw this:


## Defintion A (Doesn't work as expected)
```
_format_version: "3.0"
_transform: true

services:
  - url: https://mockbin.org/bin/74dfa5d5-3c6b-4d30-bb7d-a1dad8f32e1b
    name: example_service_a
    port: 80
    protocol: http
    routes:
      - name: example_route_a
        tags: [ account ]
        paths:
          - /account
          - ~/account/.+/another
        strip_path: false
  - url: https://mockbin.org/bin/9b4226a9-fa80-4f31-be50-0f1aafb57bd7
    name: example_service_b
    port: 80
    protocol: http
    routes:
      - name: example_route_b
        tags: [ account ]
        paths:
          - ~/account/.+/test
        strip_path: false
```

## Defintion B (Works as expected)
```
_format_version: "3.0"
_transform: true

services:
  - url: https://mockbin.org/bin/74dfa5d5-3c6b-4d30-bb7d-a1dad8f32e1b
    name: example_service_a
    port: 80
    protocol: http
    routes:
      - name: example_route_a
        tags: [ account ]
        paths:
          - /account
        strip_path: false
      - name: example_route_a_a
        tags: [ account ]
        paths:
          - ~/account/.+/another
        strip_path: false
  - url: https://mockbin.org/bin/9b4226a9-fa80-4f31-be50-0f1aafb57bd7
    name: example_service_b
    port: 80
    protocol: http
    routes:
      - name: example_route_b
        tags: [ account ]
        paths:
          - ~/account/.+/test
        strip_path: false
```


In the definition A, we have 2 paths on the route defined, one has a regex and the other one doesn't, then doing that the definition doesn't work as expected.


This is how Kong is routing with that definition:
```
GET /account -> Service A
GET /account/abc/another -> Service A
GET /account/abc/test -> Service A (This one should be going to Service B)
```

If instead we split Service A into 2 routes, one with the regex and one without it, all works as expected:
```
GET /account -> Service A
GET /account/abc/another -> Service A
GET /account/abc/test -> Service B
```

Do you think would be good to add validation on the routes? and if someone is trying to create a route with regex and non-regex paths, to block it. That way people won't end up creating deinfitions that in reality don't work.

The other option might be to make routes with regex and non-regex paths work, that way we won't need the validation.
