### ISSUE TITLE
Problems with keys greater than 511 in declarative configuration

### ISSUE THREAD

**Issue by copipasteTest** [Kong/kong#10218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version 3.1.1

kong 3.1.1

### Current Behavior

we are upgrading Kong from 2.x to Kong 3.x, and we are facing a blocking bug :cry:
We use Kong Databaseless, and with the new LMDB mechanisms from Kong 3.x, our configurations are not loading.

In the tests in declarative config file the length of a consumer's API Key is causing it (but other places may also have the same problem)

When the value has more than 511 characters Kong starts the process, but with empty configurations, also Kong reports:
2023/02/02 14:21:35 [crit] 1129#0: *8 [lua] init.lua:697: init_worker(): worker initialization error: failed to load declarative config file: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size; this node must be restarted, context: init_worker_by_lua*

### Expected Behavior

kong in version 3.1.1 can load declarative configuration without errors

### Steps To Reproduce

1. Using the image kong:3.1.1
2. Load this configuration file bellow: (following the steps in the image [readme](https://hub.docker.com/_/kong))
```yaml
---
_format_version: "1.1"

consumers:
  - username: consumer-with-credential-bigger-than-512-chars
    keyauth_credentials:
      - key: 6y8fivuu6jj822b77hcuxp6z33pxgie3t5ypx8mwuxne59gp3yvgt62m2vazuu8b3ahyjhzdmri8bk768qpdp745ijt362f3z5nnwgn785iakpwia5pegwpxki4k8xjzrac2nbg2ff3adrbbgmw7ihj8mj4itwmjaxkkrany5qnb7za46imhc9vwqmg4vpqf5vkza5dfgkr8fphpfrk6bcgz2mxuqgvcvadjb974jpjuctfjptw4j5izb68pywg9a7h85wfdddxh7j7j9yd2cxtvyk7n4cggibec9qtjhci8rdhuwcf2ixtfk4vm6hzj5j6ece9xwuxicdtrizwgm6mrx99av4ukw4c9qp7yr23ij9tutph8gek698765ydjrmgkm88pyzuq7jabpeqe7ae9j8qiew2d9rjdmmd27nmtkdgajrg78347dmrbgvxzjw3f4ewakckxnia3izv7itqa9bufnjn7rd9mwkvzfmuba4hrwk49f2ktzw9npw94

services:
  - name: httpbin
    url: https://httpbin.org/anything

routes:
  - name: httpbin
    service: httpbin
    paths:
      - /
    plugins:
      - name: key-auth
        config:
          key_names:
            - X-API-Key
```
3. see in the log the following error in loading the configuration:
```
2023/02/02 16:40:15 [error] 1127#0: *889 [kong] config.lua:124 failed loading declarative config into cache: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size, client: 172.17.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8001"

```
