### ISSUE TITLE
Zipkin seems to be generating incorrect b3 traceIds

### ISSUE THREAD

**Issue by prashantkalkar** [Kong/kong#10270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 3.1.1

### Current Behavior

I have configured the Zipkin plugin with following configuration:

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
  name: zipkin
config:
  header_type: b3
  http_response_header_for_traceid: traceid
  include_credential: true
  sample_ratio: 1
plugin: zipkin
```

When I send a request without an B3 Trace Id header `X-B3-TraceId` in the request, kong generates a traceId. As per the Zipkin plugin configuration an HTTP response header is also added as traceId: <generate_traceId_value>. But it seems that generated traceId is incorrect. The b3 trace ids should consist of hex characters but the generated traceId is not hex character but just random bytes. 

Here is a traceId generated by Kong Zipkin plugin: `0y%16é>ý%00¨%04U?d%1CN`

### Expected Behavior

The generated traceId should consist of only lower case hex characters as per the b3 standard. 

### Anything else?

I think the issue seems to be in the Zipkin plugin code. The trace Id is generated as follows:

```
if trace_id == nil then
   trace_id = rand_bytes(conf.traceid_byte_count)
end
```
https://github.com/Kong/kong/blob/eedadc26dcba3d494ebf73f3d9ab7b3b7afa87e1/kong/plugins/zipkin/handler.lua#L135

Which just generate random bytes. The Plugin test code however is using following code to generate the traceIds which seems correct: 

```
local function gen_trace_id(traceid_byte_count)
  return to_hex(utils.get_rand_bytes(traceid_byte_count))
end
```
https://github.com/Kong/kong/blob/master/spec/03-plugins/34-zipkin/zipkin_no_endpoint_spec.lua#L9
