### ISSUE TITLE
Plugin configuration of type map doesn't work with declarative file

### ISSUE THREAD

**Issue by Jimm119** [Kong/kong#10357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1.3

### Current Behavior

When I configure a plugin (like OpenTelemetry) with a configuration property of type map, I get the following error when starting my container :

```
2023/02/23 15:14:28 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:697: error parsing declarative config file /usr/src/app/config/kong.yml:
in 'plugins':
  - in entry 1 of 'plugins':
    in 'config':
      in 'headers': expected a string
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:697: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:697: error parsing declarative config file /usr/src/app/config/kong.yml:
in 'plugins':
  - in entry 1 of 'plugins':
    in 'config':
      in 'headers': expected a string
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:697: in function 'init'
        init_by_lua:3: in main chunk
```

### Expected Behavior

I'm expecting type map to be supported and working in declarative file as it does with Admin API.

### Steps To Reproduce

Here is the plugins section of my declarative config file
```
plugins:
- name: opentelemetry
  config: 
    endpoint: http://opentelemetry.collector:4318/v1/traces
    headers:
    - X-Auth-Token:secret-token
```

Here is the services section of my docker-compose.yml
```
services:
  local-gateway:
    container_name: local-gateway
    image: kong/kong-gateway:3.1.1.3
    restart: always
    networks:
      local-gateway-network:
        ipv4_address: 10.99.1.40
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_DECLARATIVE_CONFIG: "/usr/src/app/config/kong.yml"
      KONG_PLUGINS: "bundled,opentelemetry"
      KONG_LOG_LEVEL: "debug"
```

### Anything else?

1. The plugin section is identical to the one shown on the OpenTelemetry official documentation.
![image](https://user-images.githubusercontent.com/43527332/220952941-b1ebb73c-d069-4261-9a93-c799e1972669.png)

2. The OpenTelemetry plugin doesn't seem to have any compatibility problem according to official documentation.
![image](https://user-images.githubusercontent.com/43527332/220952703-f9967a9a-2710-4b22-8297-cc1193bd43e5.png)

3. I tried to configure the same plugin with the Admin API (with a database) and the following command was working fine :
`curl -X POST http://localhost:8001/plugins/ --data "name=opentelemetry"  --data "config.endpoint=http://opentelemetry.collector:4318/v1/traces" --data "config.headers.X-Auth-Token=secret-token"`

4. I tried to make my own plugin with a map as config type and I get the same error. Actually, my real need is to make it work for my custom plugin, but as I was not able to, I tried to configure the Open Telemetry plugin with the official documentation just to end with the same error.

**Comment by hbagdi** [comment]
Try 
```yaml
plugins:
- name: opentelemetry
  config: 
    endpoint: http://opentelemetry.collector:4318/v1/traces
    headers:
      X-Auth-Token:secret-token
```

config.headers is a map and not an array of maps. The documentation seems to be wrong as well.
A PR to fix the docs would be welcome.

**Comment by hbagdi** [comment]
I made a mistake. Try this (space between `:`):

```yaml
plugins:
- name: opentelemetry
  config: 
    endpoint: http://opentelemetry.collector:4318/v1/traces
    headers:
      X-Auth-Token: secret-token
```
