### ISSUE TITLE
OpenTelemetry plugin does not send out any span while 'tracing_sampling_rate' is lower than 1.0

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#10402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.1.1

### Current Behavior

In my local development environment, I have a running container with image `jaegertracing/all-in-one:1.41` in order to verify OpenTelemetry plugins interacts with Jaeger.

With below environment configuration, everything works well:
```
KONG_OPENTELEMETRY_TRACING=all
KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE=1.0
```

After I change `KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE` to `0.9`, Kong does not send out any span to my Jaeger.  

### Expected Behavior

When I set `KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE` between 0 to 1, it should send out span regarding to the sampling rate.

### Steps To Reproduce

1. Set up a `jaegertracing/all-in-one:1.41` locally
```yaml
jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      SPAN_STORAGE_TYPE: "memory"
```
2. Setup Kong with 3.1.1 with following settings.
```
KONG_OPENTELEMETRY_TRACING=all
KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE=0.9
```
3. Enable `OpenTelemetry` Plugin
```yaml
plugins:
  - name: opentelemetry
    enabled: true
    config:
      endpoint: http://docker.for.mac.host.internal:4318/v1/traces
```

4. Verify by visiting any route, and browser `http://localhost:16686/` to see the OpenTelemetry spans, you will see nothing if `KONG_OPENTELEMETRY_TRACING_SAMPLING_RATE` is 0.9, and after setting it to 1.0, it works and show spans.

### Anything else?
After a roughly tracing, the value of `sampled` is always false while set tracing sampling rate to 0.9
I guess this equation is incorrect and always fail since `tracer.sampler(trace_id)` is a `True` or `False` result, so it always not equals to `FLAG_SAMPLED_AND_RECORDING`
```
tracer.sampler(trace_id) == FLAG_SAMPLED_AND_RECORDING
```
Ref: https://github.com/Kong/kong/blob/3.1.1/kong/pdk/tracing.lua#L160

_No response_
