### ISSUE TITLE
Add or Append on request-transformer plugin

### ISSUE THREAD

**Issue by jviloria111** [Kong/kong#10584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6.1 and 3.2.2

### Current Behavior

When transformed to add a field to the body, but the body is a large JSON it only sends the added field.

![image](https://user-images.githubusercontent.com/33170504/228774178-8024dac8-7138-4e37-8629-c4386dbb6ddc.png)

![image](https://user-images.githubusercontent.com/33170504/228773896-4872c7d3-f805-4806-ace1-577cd45c2df0.png)

![image](https://user-images.githubusercontent.com/33170504/228774281-c25a3e39-521a-4d70-811c-eff3cbb6647c.png)

### Expected Behavior

The expected result is the body with the new field (token).
![image](https://user-images.githubusercontent.com/33170504/228774500-4399d663-558d-4eb4-b4c6-ec7d0577d9c3.png)

### Steps To Reproduce

Add a new service and start the transformation by adding a field. In the call to service the body must be large.

**Comment by sabertobihwy** [comment]
Is anyone verifying? If not, you can assign it to me.

**Comment by sabertobihwy** [comment]
I tested on the master branch and did not reproduce it.

here is my `kong.yaml`

```yaml
_format_version: "3"

services:
- name: my-service
  url:  http://mockbin.org/request
routes:
- name: my-route
  service: my-service
  methods:
  - POST
  paths:
    - /request
plugins:
- name: request-transformer
  route: my-route
  config:
    add:
      body:
      - Hello:rzqtvtprmbsihpbzfjamjyduxaqemirdigyoucx...(10240 characters)

```

sent request to hit this route:

```shell
curl --request POST \
  --url http://192.168.8.241:8000/request \
  --header 'Content-Type: application/json' \
  --data '{
	"foo": "bar"
}'
```

the following is the upstream response after hitting this route.

```shell
{
	"postData": {
		"mimeType": "application/json",
		"text": "{\"foo\":\"bar\",\"Hello\":\"rzqtvtprmbsihpbzfjamjyduxaqemirdigyoucx...(10240 characters)"}",
		"params": []
	},
	"bodySize": 10264
}
```

It can be seen that both the original body field and the body field added by the `request-transformer` plugin (more than 10240 characters) exist in the requests that proxy by Kong.
