### ISSUE TITLE
Kong Rate Limiting Plugin not working as expected when limit by path

### ISSUE THREAD

**Issue by cunkz** [Kong/kong#10672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5

### Current Behavior

When I add Rate Limiting plugin, I do this following step :
1. set config.limit_by with path
2. set config.path with /abc
3. hit other path like /zxc

Kong also do rate limit in /zxc path

### Expected Behavior

I assume Kong didn't rate limit it.
Then I check this line : 
[https://github.com/Kong/kong/blob/009ee44a11b1d6d3fd5426a0b79f4892152f48ad/kong/plugins/rate-limiting/handler.lua#L73](https://github.com/Kong/kong/blob/009ee44a11b1d6d3fd5426a0b79f4892152f48ad/kong/plugins/rate-limiting/handler.lua#L73)

And
[https://github.com/Kong/kong/blob/009ee44a11b1d6d3fd5426a0b79f4892152f48ad/kong/plugins/rate-limiting/handler.lua#L79](https://github.com/Kong/kong/blob/009ee44a11b1d6d3fd5426a0b79f4892152f48ad/kong/plugins/rate-limiting/handler.lua#L79)

When request_path didn't same with config.path why Kong didnt bypass it ? But, he change identifier to forwarded ip ?

### Steps To Reproduce

1. set config.limit_by with path
2. set config.path with /abc
3. hit other path like /zxc

**Comment by Clint-Chester** [comment]
We are seeing this issue as well with the Advanced Rate Limiting Plugin. It doesn't seem like matching by path is actually matching any paths specified, and is applied to the lot.

**Comment by hanshuebner** [comment]
@Clint-Chester The Rate Limiting Advanced plugin is an enterprise feature - Please reach out to your support contact for assistance.  Thank you!

**Comment by Clint-Chester** [comment]
> @Clint-Chester The Rate Limiting Advanced plugin is an enterprise feature - Please reach out to your support contact for assistance. Thank you!

Thanks @hanshuebner, tried the standard Rate Limiting Plugin and got the same behaviour unfortunately.

**Comment by hanshuebner** [comment]
@Clint-Chester I'm going to re-open this ticket.  You may get expedited responses through the enterprise support channel, though.

**Comment by Clint-Chester** [comment]
Current configuration is the following.
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: website-login-rate-limiting
plugin: rate-limiting
config:
  limit_by: path
  path: /api/login
  minute: 70
  sync_rate: -1
  hide_client_headers: true
  error_message: "Login Rate Limit Exceeded"
```
With the following as my Ingress Controller Configuration.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    konghq.com/plugins: website-login-rate-limiting
spec:
  ingressClassName: kong
  rules:
  - host: "website.com"
    http:
      paths:
      - pathType: Exact
        path: "/api/login"
        backend:
          service:
            name: web-api-backend
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web-frontend
```
Is the behaviour that it's going to try and match all paths?

Thanks for re-opening @hanshuebner, appreciate it! We've got Enterprise Support Open as well but was very interested in seeing if others had experienced this in the past.

**Comment by StarlightIbuki** [comment]
@Clint-Chester By the name ("login") I guess we are configuring it to have smaller limitations than general requests?
`limit-by` uses a fallback mechanism to determine its limit scope, that is if the request path does not match the configured path, it will use IP to limit the request. So the behavior is kind of expected.
I also feel this behavior makes little sense. I'm looking for more information and opinions about this.

**Comment by mheap** [comment]
I can't comment on the rate limiting defaults, but to achieve what you're looking for with `Ingress` you can define two `Ingress` resources:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-ingress
  annotations:
    konghq.com/plugins: website-login-rate-limiting
spec:
  ingressClassName: kong
  rules:
  - host: "website.com"
    http:
      paths:
      - pathType: Exact
        path: "/api/login"
        backend:
          service:
            name: web-api-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
spec:
  ingressClassName: kong
  rules:
  - host: "website.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web-frontend
```

The `konghq.com/plugins` annotation applies to all routes in an `Ingress` definition, which means they should be split if you only want the plugin to apply to specific routes
