### ISSUE TITLE
Incorrect or Unexpected Outputs from grpc-gateway plugin

### ISSUE THREAD

**Issue by JKTChua** [Kong/kong#10745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.2.2

### Current Behavior

**Problem 1**
The underlying gRPC service outputs a field with an empty array value.

![image](https://user-images.githubusercontent.com/2293824/234399342-8d4b3eef-d5c7-4c6f-a5dd-66609b5ae663.png)

Using the `grpc-gateway` plugin and a proto config, the output from Kong is a 200 OK Status and an empty string body.

![image](https://user-images.githubusercontent.com/2293824/234399942-0c4b6c79-1a98-4f90-83a1-4569a38d00ee.png)
![image](https://user-images.githubusercontent.com/2293824/234400219-e7b8cb08-31c4-427e-9230-59ceba0cce83.png)

**Problem 2**
In my attempts to work around this issue, I modified the underlying gRPC service to output an additional field that would not even need to be parsed by the `grpc-gateway` plugin.

![image](https://user-images.githubusercontent.com/2293824/234400808-9be17d5b-0ab2-4b32-ae13-2d97ed98756e.png)

The output from Kong is closer to what my expectation. However, the array field is exposed as an object rather than array.

![image](https://user-images.githubusercontent.com/2293824/234400887-f402bd74-7dbe-4da5-8f28-c02105c4ea4a.png)

### Expected Behavior

I would expect the first scenario to output valid JSON at the very least (e.g. empty object `{}`), but at the most I would want it to output the same result as the response in my first screenshot: valid JSON with an empty array in the single field (e.g. `{"decisions": []}`).

The second scenario should output the field's value as an empty array (e.g. `{"decisions": []}`) rather than an empty object.

### Steps To Reproduce

1. With this kong.yml
```
_format_version: "3.0"

_transform: true

services:
 - host: host.docker.internal
   name: cyber-lifecycle
   port: 9090
   protocol: grpc
   routes:
   - protocols:
     - http
     name: decision
     paths:
     - ~/v1/Packages/[\-0-9a-zA-Z]+/Decisions$
     plugins:
     - name: grpc-gateway
       config:
        proto: /protos/decision.proto
```
2. With this proto file
```
syntax = "proto3";

package decision;
option go_package = "/lifecycle/decision";

import "google/api/annotations.proto";

service DecisionService {
  rpc GetPackageDecisions(GetPackageDecisionsRequest) returns (GetPackageDecisionsResponse) {
    option (google.api.http) = {
      get: "/v1/Packages/{uuid}/Decisions",
    };
  }
}

message GetPackageDecisionsRequest {
  string uuid = 1;
}

message GetPackageDecisionsResponse {
  repeated Decision decisions = 1;
}

message Decision {
  string uuid = 1;
}
```
3. Run Kong and also standup a gRPC service with the same protobuf interface that outputs an empty array for the `decisions` field.
4. Make an HTTP request via Kong which should route the request to the gRPC service.
5. Observe the response from Kong.
