### ISSUE TITLE
Exposing MySQL

### ISSUE THREAD

**Issue by arezvani** [Kong/kong#10772]
How can I expose mysql with TCPIngress?
I use this yaml:
```yaml
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: mysql
  namespace: default
spec:
  rules:
  - backend:
      serviceName: my-mysql
      servicePort: 3306
    host: tls9443.kong.example
    port: 9443
  tls:
  - hosts:
    - tls9443.kong.example
    secretName: tls9443.kong.example
```

I can't connect to my mysql.
