### ISSUE TITLE
At some point, connection between ingress controller with proxy sidecar disappeared and  the reconcile of httproute fails forever.

### ISSUE THREAD

**Issue by parkjeongryul** [Kong/kong#10923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.2 and kong ingress controller v2.9.2

### Current Behavior

We Installed KIC using helm chart with values like below.
```yaml
          image:
            repository: reg.navercorp.com/clous-public/kong-ubuntu
            tag: "3.2.2"
          ingressController:
            image:
              repository: reg.navercorp.com/clous-public/kong-ingress-controller
              tag: "v2.9.2"
            env:
              ingress_class: clous-api
              gateway_api_controller_name: konghq.com/clous-api-gateway-controller
            ingressClass: clous-api
          proxy:
            nameOverride: test-gateway
          replicaCount: 30
          podAnnotations:
          # TODO: Attach linkerd after investigation 
            # linkerd.io/inject: ingress
            # config.linkerd.io/proxy-memory-limit: 2Gi
            # To add the x-forwared-* header, skip the service mesh for inbound traffic.
            # config.linkerd.io/skip-inbound-ports: 8000,8443
          serviceMonitor:
            enabled: true
```

And We use gateway API and HTTPRoute.

We have an issue where it works fine at first, but after a certain time (about 1~3 days after the KIC pod is created?), the httproute reconcile fails forever.

Routing for exisiting HTTPRoute works well. but newly created httproute cannot be routed with this response.
```
// After that point, only newly created httproutes
{
message: "no Route matched with those values"
}
```

***

So we investigated.

1. First, Connection with kong admin(maybe it listen 8443 port) was disappeared.
```
// netstat in kong ingress controller pod.
tcp        0      0 localhost:8444          localhost:53612         ESTABLISHED 
tcp        0      0 localhost:53612         localhost:8444          ESTABLISHED 
```
Normal ingress pod has this connection with netstat.
But when ingress controller was broken (which cannot reconcile), we cannot find the connection in this pod.

2. This is logs for proxy container and ingress-controller container.
- GET /status HTTP/2.0 logs stoped.
```
// proxy container
127.0.0.1 - - [22/May/2023:11:39:48 +0900] "GET /status HTTP/2.0" 200 1226 "-" "Go-http-client/2.0"
127.0.0.1 - - [22/May/2023:11:39:51 +0900] "GET /status HTTP/2.0" 200 1226 "-" "Go-http-client/2.0"
127.0.0.1 - - [22/May/2023:11:39:54 +0900] "GET /status HTTP/2.0" 200 1226 "-" "Go-http-client/2.0"
127.0.0.1 - - [22/May/2023:11:39:57 +0900] "GET /status HTTP/2.0" 200 1226 "-" "Go-http-client/2.0"
127.0.0.1 - - [22/May/2023:11:40:00 +0900] "GET /status HTTP/2.0" 200 1226 "-" "Go-http-client/2.0"
2023/05/22 11:40:03 [notice] 1198#0: *92268 [lua] init.lua:240: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1&flatten_errors=1 HTTP/2.0", host: "localhost:8444"
2023/05/22 11:40:03 [notice] 1198#0: *92268 [lua] init.lua:240: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1&flatten_errors=1 HTTP/2.0", host: "localhost:8444"
127.0.0.1 - - [22/May/2023:11:40:03 +0900] "POST /config?check_hash=1&flatten_errors=1 HTTP/2.0" 201 94728 "-" "Go-http-client/2.0"
2023/05/22 11:40:03 [notice] 1199#0: *8 [lua] init.lua:240: purge(): [DB cache] purging (local) cache, context: ngx.timer
2023/05/22 11:40:03 [notice] 1199#0: *8 [lua] init.lua:240: purge(): [DB cache] purging (local) cache, context: ngx.timer
2023/05/22 11:40:03 [notice] 1198#0: *4 [lua] init.lua:240: purge(): [DB cache] purging (local) cache, context: ngx.timer
2023/05/22 11:40:03 [notice] 1198#0: *4 [lua] init.lua:240: purge(): [DB cache] purging (local) cache, context: ngx.timer
```

```
// ingress controller
time="2023-05-22T11:40:01+09:00" level=info msg="successfully synced configuration to kong" kong_url="https://localhost:8444"
time="2023-05-22T11:40:01+09:00" level=error msg="Reconciler error" error="Operation cannot be fulfilled on httproutes.gateway.networking.k8s.io \"clous-api\": the object has been modified; please apply your changes to the latest version and try again" logger=controllers.HTTPRoute reconcileID="\"4f7db20a-3163-4c26-aac3-1a5c66cecc1e\""
time="2023-05-22T11:40:01+09:00" level=info msg="httproute has been configured on the data-plane" GatewayV1Beta1HTTPRoute="{\"Namespace\":\"clous-ngs-mem-00001404\",\"Name\":\"clous-api\"}" logger=controllers.HTTPRoute name=clous-api namespace=clous-ngs-mem-00001404
time="2023-05-22T11:40:03+09:00" level=error msg="Reconciler error" error="Operation cannot be fulfilled on httproutes.gateway.networking.k8s.io \"clous-api\": the object has been modified; please apply your changes to the latest version and try again" logger=controllers.HTTPRoute reconcileID="\"d904ce6e-26c4-4610-92db-cb2cae6b5463\""
time="2023-05-22T11:40:04+09:00" level=warning msg="no active endpoints" service_name=ras service_namespace=clous-jykim-2305111602 service_port="&ServicePort{Name:ras,Protocol:TCP,Port:80,TargetPort:{1 0 http},NodePort:0,AppProtocol:nil,}"
time="2023-05-22T11:40:04+09:00" level=info msg="no targets could be found for kubernetes service clous-jykim-2305111602/ras" service_name=httproute.clous-jykim-2305111602.clous-api-ras.0
time="2023-05-22T11:40:04+09:00" level=info msg="no targets found to create upstream" service_name=httproute.clous-jykim-2305111602.clous-api-ras.0
time="2023-05-22T11:40:04+09:00" level=warning msg="no active endpoints" service_name=ginad service_namespace=clous-ngs-storage-00001404 service_port="&ServicePort{Name:ginad,Protocol:TCP,Port:80,TargetPort:{1 0 http},NodePort:31837,AppProtocol:nil,}"
time="2023-05-22T11:40:04+09:00" level=info msg="no targets could be found for kubernetes service clous-ngs-storage-00001404/ginad" service_name=httproute.clous-ngs-storage-00001404.clous-api.0
time="2023-05-22T11:40:04+09:00" level=info msg="no targets found to create upstream" service_name=httproute.clous-ngs-storage-00001404.clous-api.0
time="2023-05-22T11:40:04+09:00" level=info msg="successfully synced configuration to kong" kong_url="https://localhost:8444"
time="2023-05-22T11:40:04+09:00" level=info msg="httproute has been configured on the data-plane" GatewayV1Beta1HTTPRoute="{\"Namespace\":\"clous-ngs-storage-00001404\",\"Name\":\"clous-api\"}" logger=controllers.HTTPRoute name=clous-api namespace=clous-ngs-storage-00001404
time="2023-05-22T11:40:05+09:00" level=info msg="httproute has been configured on the data-plane" GatewayV1Beta1HTTPRoute="{\"Namespace\":\"clous-ngs-storage-00001404\",\"Name\":\"clous-api\"}" logger=controllers.HTTPRoute name=clous-api namespace=clous-ngs-storage-00001404
time="2023-05-22T11:40:06+09:00" level=error msg="Reconciler error" error="Operation cannot be fulfilled on httproutes.gateway.networking.k8s.io \"clous-api\": the object has been modified; please apply your changes to the latest version and try again" logger=controllers.HTTPRoute reconcileID="\"7236d421-e56b-49a0-bad4-f782dc7c9efd\""
time="2023-05-22T11:40:08+09:00" level=error msg="Reconciler error" error="Operation cannot be fulfilled on httproutes.gateway.networking.k8s.io \"clous-api\": the object has been modified; please apply your changes to the latest version and try again" logger=controllers.HTTPRoute reconcileID="\"a8c7d6cc-61d9-43c8-b777-483a49314a6e\""
```

### Expected Behavior

Ingress controller reconcile httproute consistently.

### Steps To Reproduce

1. Install Kong ingress controller with helm.
2. Create gatewayclass and gateway
3. Create Httproutes and it works.
4. After 1 ~ 3 days (Suddenly), Httproutes couldn't be reconciled.

### Anything else?

And we can fix it by restarting ingress controller pods.
But this behavior was reproduced again.
