### ISSUE TITLE
Go custom plugin does not work with versions of Kong Gateway's Docker image > 3.0.x

### ISSUE THREAD

**Issue by cakctrst** [Kong/kong#11084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.2.2.0 (> 3.0.x)

### Current Behavior

When I use a version of the Docker image [kong/kong-gateway](https://hub.docker.com/r/kong/kong-gateway/tags) (I have also tried with [kong](https://hub.docker.com/_/kong/tags)) higher than 3.0.x like 3.2.2.0, I can see in the container logs (via Docker Desktop) that the plugin named go-login-manager-kong-plugin starts up fine, but the .socket file (go-login-manager-kong-plugin.socket in my case) cannot be found in the filesystem.

![image](https://github.com/Kong/kong/assets/137088700/1b0234c0-e43f-4f48-af25-3e59f74f4eff)

And when I check the existence of the .socket file, I see that it's there, as you can see in the following image:

![image](https://github.com/Kong/kong/assets/137088700/5300dc7a-0135-4bd5-8a49-760135834095)

We can also see in the first image that the container is trying to access the .socket file before the Go plugin has started...

### Expected Behavior

The expected behaviour must be the same as in version 3.0.2.0 or lower:

![image](https://github.com/Kong/kong/assets/137088700/fbaf62fb-653f-4c74-ba07-849909948e41)

We can see that the last message after the container setup is the one for starting the plugin, and there are no errors relating to the .socket file.

### Steps To Reproduce

I'm using the following dockerfile and docker-compose for it:

*dockerfile*
```yml
# Build Go plugin
FROM amd64/golang:1.20.4-alpine as build

RUN mkdir /go-plugins
WORKDIR /go-plugins
COPY go-login-manager-kong-plugin-module/* ./
RUN go mod download && go build -o /go-plugins/go-login-manager-kong-plugin

# Build Kong
FROM kong/kong-gateway:3.2.2.0-alpine
USER root
COPY --from=build /go-plugins/go-login-manager-kong-plugin /usr/local/bin/go-login-manager-kong-plugin

USER kong
ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 8000 8443 8001 8444 8002 8445 8003 8446 8004 8447
STOPSIGNAL SIGQUIT
HEALTHCHECK --interval=10s --timeout=10s --retries=10 CMD kong health
CMD ["kong", "docker-start"]
```

*docker-compose.yml*
```yml
version: '3.9'

services: 
  kong-gateway:
    build: .
    container_name: kong-gateway
    volumes:
      - ./kong.yml:/opt/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/opt/kong.yml
      - KONG_PLUGINSERVER_NAMES=go-login-manager-kong-plugin
      - KONG_PLUGINS=go-login-manager-kong-plugin
      - KONG_PLUGINSERVER_GO_LOGIN_MANAGER_KONG_PLUGIN_QUERY_CMD=/usr/local/bin/go-login-manager-kong-plugin -dump
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_HEADERS=off
    # command: "kong start -c /etc/kong/kong.conf"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks:
      - kong-gateway

networks:
  kong-gateway:
    external: true
```

**Comment by hanshuebner** [comment]
@cakctrst Can you please share your kong.yml file as well?

**Comment by cakctrst** [comment]
@hanshuebner yes, here is the kong.yml file (I have renamed some values) :
```yml
_format_version: "1.1"
services:
  - name: sample-service
    url: http://service_host:8080
    routes:
      - name: sample-route
        paths:
          - "/api/example"
        strip_path: false

  - name: login-manager-service
    url: http://example.mycompany.com
    routes:
      - name: login-manager-route
        paths:
          - "/services/getEmailByLoginId"
        strip_path: false
    plugins:
      - name: go-login-manager-kong-plugin
        config:
          optin_service_host: http://service_host:8080
```
