### ISSUE TITLE
request-transformer `rename` is not preserving renamed header casing

### ISSUE THREAD

**Issue by l8nite** [Kong/kong#11579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4.0

### Current Behavior

Consider request-transformer configuration:

```
plugins:
- name: request-transformer
  service: foo
  config:
    rename:
      headers:
      - X-FOO-QixQux:X-BAR-QixQux
```

When renaming the header, the new value sent upstream is `X-Bar-Qixqux`

### Expected Behavior

The expected header sent upstream is `X-BAR-QixQux` (case sensitive).

Now, according to HTTP RFC, the plugin behavior is OK; however, we have run into some implementation of upstream services that _require_ strict http header casing, and it would be better if Kong preserved the renamed header casing.

This is similar to Issue #4504 

### Steps To Reproduce

Set up request-transformer plugin with the above config, execute request with inbound header that is renamed, observe the casing of the header sent to upstream.
