### ISSUE TITLE
Kong's log system does not allow you to set fields with dots

### ISSUE THREAD

**Issue by john-wd** [Kong/kong#11582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.2.2.2

### Current Behavior

When I set a custom field to the `file-log` plugin containing dots, it automatically unpacks the name into nested fields. For example, when I try to set [Google's magic trace field](https://cloud.google.com/appengine/docs/standard/writing-application-logs?tab=python) `logging.googleapis.com/trace`, it unpacks as:

```
{
  logging:
    googleapis:
      com/trace: "my-trace"
}
```

which does not integrate with google cloud at all.

### Expected Behavior

When I set field with dots, I expect it to keep dots

```
{
  logging.googleapis.com/trace: "my-trace"
}
```

### Steps To Reproduce

1. Configure `file-log` setting a custom field containing dots
```
plugins:
- name: file-log
  config:
    path: "/tmp/file.log"
    custom_fields_by_lua:
      "logging.googleapis.com/trace": "return kong.request.get_header('x-cloud-trace-context')"
```
2. Hit any exposed endpoint
3. See in /tmp/file.log that this field was broken into a nested document

### Anything else?

This seems to be the default behavior judging by [these lines](https://github.com/Kong/kong/blob/d1fac2e62da64039790cded0db9ab0d5dc16ad65/kong/pdk/log.lua#L654-L666), but I'd expect to be able to integrate with my cloud provider.

Additional info:
- Deployed with public helm chart
- Tag: 3.2.2.2-ubuntu
