### ISSUE TITLE
Preventing selective forwarding of X-Forwarded-* headers to upstream

### ISSUE THREAD

**Issue by shawnchapla-8451** [Kong/kong#11752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Enterprise 3.3.1.0

### Current Behavior

Trying to follow [this example](https://support.konghq.com/support/s/article/How-to-disable-the-x-forwarded-x-headers-from-a-single-route) to prevent Kong from passing the X-Forwarded-Proto header to the upstream for a specific API. However, even with adding that post-function plugin, the header is still being sent. 

### Expected Behavior

Expect that adding the plugin would prevent the header being sent.

### Steps To Reproduce

1. Create a simple service and route (with the post-function plugin on the latter) using the attached decK file.
2. Use curl to call the API (http://localhost:8000/myapi)
3. The response from mockbin.com shows that Kong still sent the X-Forwarded-Proto header to the upstream:
```
% curl http://localhost:8000/myapi
{
  "startedDateTime": "2023-10-12T15:04:56.595Z",
  "clientIPAddress": "192.168.65.1",
  "method": "GET",
  "url": "https://localhost/request/myapi",
  "httpVersion": "HTTP/1.1",
  "cookies": {},
  "headers": {
    "host": "mockbin.com",
    "connection": "close",
    "accept-encoding": "gzip, br",
    "x-forwarded-for": "<redacted>",
    "cf-ray": "81503cf99f3f3b29-IAD",
    "x-forwarded-proto": "http",
    "cf-visitor": "{\"scheme\":\"https\"}",
    "x-forwarded-host": "localhost",
    "x-forwarded-port": "80",
    "x-forwarded-path": "/myapi",
    "x-forwarded-prefix": "/myapi",
    "user-agent": "curl/8.1.2",
    "accept": "*/*",
    "cdn-loop": "cloudflare",
    "cf-connecting-ip": "139.180.244.123",
    "x-request-id": "40c1e8bc-56fa-4e31-9369-29c051e9c631",
    "via": "1.1 vegur",
    "connect-time": "0",
    "x-request-start": "1697123096592",
    "total-route-time": "0"
  },
  "queryString": {},
  "postData": {
    "mimeType": "application/octet-stream",
    "text": "",
    "params": []
  },
  "headersSize": 598,
  "bodySize": 0
}
```

[example.yaml.txt](https://github.com/Kong/kong/files/12884042/example.yaml.txt)

### Anything else?

As a test, I tried to clear all the X-Forwarded-* headers with this as the post-function code:
```
    plugins:
    - enabled: true
      name: post-function
      protocols:
      - grpc
      - grpcs
      - http
      - https
      config:
        access: 
        - ngx.var.upstream_x_forwarded_proto=nil;ngx.var.upstream_x_forwarded_host=nil;ngx.var.upstream_x_forwarded_port=nil;ngx.var.upstream_x_forwarded_path=nil;ngx.var.upstream_x_forwarded_prefix=nil;ngx.var.upstream_x_forwarded_for=nil
        body_filter: []
        certificate: []
        header_filter: []
        log: []
        rewrite: []
```
This shows that *some* of the headers are removed, but not all; appears the -Proto, -Port and -For headers are still sent while the others are not:
```
% curl http://localhost:8000/myapi
{
  "startedDateTime": "2023-10-12T15:12:45.737Z",
  "clientIPAddress": "139.180.244.123",
  "method": "GET",
  "url": "https://mockbin.com/request/myapi",
  "httpVersion": "HTTP/1.1",
  "cookies": {},
  "headers": {
    "host": "mockbin.com",
    "connection": "close",
    "accept-encoding": "gzip, br",
    "x-forwarded-for": "<redacted>",
    "cf-ray": "8150486dce753879-IAD",
    "x-forwarded-proto": "http",
    "cf-visitor": "{\"scheme\":\"https\"}",
    "user-agent": "curl/8.1.2",
    "accept": "*/*",
    "cdn-loop": "cloudflare",
    "cf-connecting-ip": "139.180.244.123",
    "x-request-id": "f140d771-76a4-45af-8d84-abf7427277e8",
    "x-forwarded-port": "80",
    "via": "1.1 vegur",
    "connect-time": "0",
    "x-request-start": "1697123565735",
    "total-route-time": "0"
  },
  "queryString": {},
  "postData": {
    "mimeType": "application/octet-stream",
    "text": "",
    "params": []
  },
  "headersSize": 502,
  "bodySize": 0
}
```
So this method works for some of the headers, but not all.

**Comment by nowNick** [comment]
Hi @shawnchapla-8451 

Giving it a quick look it seems like it should work. We're not sure why you don't see those headers removed. We need to dive deeper into this.

**Comment by shawnchapla-8451** [comment]
@nowNick I noticed that using mockbin.com as the upstream wasn't showing the all the values I expected; for instance, while I was running Kong in Docker listening on port 8000, mockbin was indicating that the port was 80. So I tried another free mocking site (Beeceptor) and I'm still seeing similar behavior as far as trying to prevent the headers from being forwarded to the upstream:

```
{
  "user-agent": "curl/8.1.2",
  "accept": "*/*",
  "x-forwarded-for": "<redacted>",
  "x-forwarded-host": "<redacted>",
  "x-forwarded-proto": "https",
  "accept-encoding": "gzip"
}
```

I even tried "separating" the Lua code in the post-function plugin to see if that made any difference; it didn't:

```
    plugins:
    - enabled: true
      name: post-function
      protocols:
      - grpc
      - grpcs
      - http
      - https
      config:
        access: 
        - ngx.var.upstream_x_forwarded_proto=nil
        - ngx.var.upstream_x_forwarded_host=nil
        - ngx.var.upstream_x_forwarded_port=nil
        - ngx.var.upstream_x_forwarded_path=nil
        - ngx.var.upstream_x_forwarded_prefix=nil
        - ngx.var.upstream_x_forwarded_for=nil
        body_filter: []
        certificate: []
        header_filter: []
        log: []
        rewrite: []
```

Even with all of those set to nil, X-Forwarded-For, -Host and -Proto were still sent.
