### ISSUE TITLE
Undefined behavior when multiple JWTs are provided using different methods

### ISSUE THREAD

**Issue by mikeholler** [Kong/kong#11796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4.2

### Current Behavior

The behavior of supplying two JWTs in one request is completely undefined in documentation.

### Expected Behavior

There should be well-defined and deterministic behavior around requests that include more than one JWT.

### Steps To Reproduce

The [Kong JWT plugin](https://docs.konghq.com/hub/kong-inc/jwt/) describes three ways to provide JWTs: a cookie, a query string parameter, or a header. Unfortunately, it doesn't describe what happens when multiple are provided.

Take the following config:

```yaml
config:
  uri_param_names:
    - token1
    - token2
  header_names:
    - token3
    - token4
  cookie_names:
    - token5
    - token6
```

What happens when all locations are populated by a valid (but different) token? What is the priority on the order they are resolved and tested? What if an invalid token is found? Does it go through invalid tokens until it finds one invalid token (or runs out) or does it fail fast on the first invalid token?

We'd like to include this documentation in our product, but as it isn't documented in Kong, this is challenging, and the contract may change at any point in time as it is not documented.
