### ISSUE TITLE
http-log plugin throws bad argument #4 to 'fmt' (number expected, got nil), context: ngx.timer

### ISSUE THREAD

**Issue by philippsteinberg** [Kong/kong#11931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4

### Current Behavior

Hi I try to send logs with the http-log plugin to an http endpoint via a post request.  
To test the functionality I configured it liked described on the plugin docu page https://docs.konghq.com/hub/kong-inc/http-log/how-to/basic-example/ under Enable globally 

```
plugins:
- name: http-log
  config:
    content_type: application/json
    http_endpoint: https://xxx
    method: POST
    flush_timeout: 2
    retry_count: 15
    timeout: 1000
    keepalive: 1000
```

When I start Kong with the config I see the following error in the logs:
[error] 2317#0: *13 [lua] job.lua:284: execute(): [timer-ng] failed to run timer queue 0dc6f45b-8f8d-40d2-a504-473544ee190b.https://xxx:POST:application/json:3000:60000:nil: ./http-log/handler.lua:135: bad argument #4 to 'fmt' (number expected, got nil), context: ngx.timer

After that I see no more logs from the plugin in the logs and no data is received at the endpoint

### Expected Behavior

Plugin should work and send the request and response logs to the http endpoint

### Steps To Reproduce

Configure the http-log plugin like described in the plugin page
https://docs.konghq.com/hub/kong-inc/http-log/how-to/basic-example/ under Enable globally
