### ISSUE TITLE
file-log plugin fails to log to `/dev/stdout` with `Permission Denied` error

### ISSUE THREAD

**Issue by gsadhani** [Kong/kong#12129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4

### Current Behavior

file-log plugin fails to log to /dev/stdout with Permission Denied error when running in a container.

```
kong-gateway-6d98fccc96-pzzvv proxy 2023/11/29 12:17:09 [error] 1263#0: *1315 [kong] handler.lua:56 [file-log] 
failed to open the file: Permission denied while logging request, client: xxx.18.82.100, server: kong,
request: "GET /v1/xxxxx/xxx HTTP/2.0", upstream: "http://100.64.92.168:9002/v1/xxxxx/xxx", host: "dev14.xxxxxxx.io"
```

I have tried the following:
1. Changing permissions of /dev/stdout to 777
2. Creating a link from `/var/log/kong/kong.log` to `/dev/stdout` and log to `/var/log/kong/kong.log`
```
ln -sf /dev/stdout /var/log/kong/kong.log
```
But the issue persists.

### Expected Behavior

The file-log plugin should be able to log to `/dev/stdout` as indicated in the [documentation](https://docs.konghq.com/hub/kong-inc/file-log/).

### Steps To Reproduce

1. Configure file-log plugin as below: 
```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: file-log
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  path: "/dev/stdout"
plugin: file-log
```

2. Make API calls routed through the gateway
