### ISSUE TITLE
Kong with http2 and coalescing

### ISSUE THREAD

**Issue by dweber019** [Kong/kong#12179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5.x

### Current Behavior

Currently we have the following setup.
Kong deployed in version 3.5.x with KIC.
We have two Kong clusters in one Kubernetes cluster. It's like a non prod Kubernetes cluster with a TEST and INT environment for Kong.
We used the gateway spec for our setup like this (example for TEST but similar config for INT):
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    konghq.com/publish-service: ch-kong-test/ch-kong-test-kong-data-proxy
  name: ch-kong-test
spec:
  gatewayClassName: ch-kong-test
  listeners:
    - hostname: api-ch-test.example.com
      name: api-ch-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - ...
        mode: Terminate
    - hostname: '*.api-ch-test.example.com'
      name: wildcard-api-ch-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - ...
        mode: Terminate
```

Now if we use some host based routes, we get issues with the http2 spec, as there is only one load balancer IP for the Kubernetes cluster. We have this issue for browsers like Chrome but not for other clients like Insomnia or CURL.

It seams like Chrome is caching/reusing connections for http2 like described in https://stackoverflow.com/questions/48701719/http2-different-domain-but-same-ip-multiple-connection-or-one-connection and https://daniel.haxx.se/blog/2016/08/18/http2-connection-coalescing/.

The result of this caching behavior, is that a request for a route for the INT cluster is routed to the TEST cluster, if there is all ready a connection cached for the IP.

By downgrading to http1, the issue is gone, done with
```
proxy:
  tls:
    parameters: []
```

### Expected Behavior

I would expect that the mention setup works.

I think downgrading to http1 is not the solution.

A solution could be to return `421` as suggested by the http2 spec, when the hostname is missing in the `apiVersion: gateway.networking.k8s.io/v1 / kind: Gateway` definition.
Reasoning: I define a list of listeners and all have a hostname, then the Kong gateway should not feel responsible for hostnames, which aren't matched at least once. If there is no hostname match the gateway should return 421.
As it's valid to leave the hostname empty, the issue could happen again.

Do you have any other solutions?
