### ISSUE TITLE
Kong KIC fails when rate-limiting plugin  config.policy is set to cluster 

### ISSUE THREAD

**Issue by meezaan** [Kong/kong#12260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4, KIC 2.12

### Current Behavior

When I change config.policy on an instance of the rate-limiting plugin to cluster, I see the following in KIC logs:

```
level=error msg="could not update kong admin" error="performing update for https://localhost:8444 failed: failed posting new config to /config: got status code 400"
```

and Kong no longer proxies any requests to the service.

### Expected Behavior

I'd expect things to work just as they do with `local` and `redis`, both of which work fine.

### Steps To Reproduce

Apply a rate limit plugin, such as:

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  namespace: some-space
  name: some-ratelimit
config:
  second: 5
  minute: 300
  policy: local
plugin: rate-limiting
```
Watch the KIC logs.
