### ISSUE TITLE
OTEL plugin sends incoming W3C tracestate and Instana tracing HTTP headers out as received

### ISSUE THREAD

**Issue by sriemer** [Kong/kong#12494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.5.0

### Current Behavior

Receiving Instana + W3C tracing headers like
```
X-INSTANA-L: 1
X-INSTANA-T: 2696d845a4b364f5
X-INSTANA-S: ecbea6329e46a665
traceparent: 00-00000000000000002696d845a4b364f5-ecbea6329e46a665-01
tracestate: in=2696d845a4b364f5;ecbea6329e46a665
```
Sending out tracing headers like
```
X-INSTANA-L: 1
X-INSTANA-T: 2696d845a4b364f5
X-INSTANA-S: ecbea6329e46a665
traceparent: 00-00000000000000002696d845a4b364f5-d666cccb26e1ba7e-01
tracestate: in=2696d845a4b364f5;ecbea6329e46a665
```
Next Instana tracer in the chain picks up span ID from `X-INSTANA-S`, fallback: `tracestate` `in` member, only then `traceparent`. So on the Instana UI it appears as if spans are directly sent from client app to server app without Kong.

### Expected Behavior

Would be nice to be able to add support for Instana headers or at least filtering out Instana headers and the `tracestate` header.

Is that possible with custom LUA code?

Does "customize OTel spans as a developer" (https://docs.konghq.com/hub/kong-inc/opentelemetry/#customize-opentelemetry-spans-as-a-developer) work for this?

So expecting to see just header `traceparent` here with the new span ID:
```
traceparent: 00-00000000000000002696d845a4b364f5-d666cccb26e1ba7e-01
```

### Steps To Reproduce

1. clone our demo repo `kong-tracing` -> it is private for now
2. get access to Instana UI with an own agent key and configure file `.env`
3. run `docker-compose build && docker-compose up`
4. get the gateway network interface used by docker-compose via
`ip -s a | grep $(docker inspect $(docker ps | grep kong-tracing_kong | cut -d' ' -f1) | grep "Gateway.*[0-9\.]\+" | grep -o "[0-9\.]\+")`
5. take a `tcpdump` via `tcpdump -s 0 -i $BRIDGE_INTERFACE -w kong-tracing-demo.pcap`
6. analyze the headers with `wireshark`

OTel plugin config:
```yaml
plugins:
- name: opentelemetry
  config:
    endpoint: "http://instana-agent:4318/v1/traces"
    resource_attributes:
      service.name: "kong-otel-demo"
```

### Anything else?

OS: Linux x86_64

**Comment by sriemer** [comment]
Okay, found a workaround for this issue. :tada: :tada: :tada: :smiley: 

First working custom LUA code:
```lua
-- Modify the root span
local root_span = kong.tracing.active_span()
-- Kong PDK request API has no set_header(). So use NGINX request API instead.
h = ngx.req.get_headers()
local span_id_in = h["x-instana-s"]
local tracestate_in = h["tracestate"]
if span_id_in then
  root_span:set_attribute("headers.x-instana-s", span_id_in)
  root_span:set_attribute("headers.dropping-x-instana-s", "true")
  ngx.req.set_header("x-instana-s", "")
else
  root_span:set_attribute("headers.no-x-instana-s", "true")
end
if tracestate_in then
  root_span:set_attribute("headers.tracestate", tracestate_in)
  root_span:set_attribute("headers.dropping-tracestate", "true")
  ngx.req.set_header("tracestate", "")
else
  root_span:set_attribute("headers.no-tracestate", "true")
end
```

My demo uses the declarative YAML config and Kong without database. So I have to put the code into `kong.yml`.
Unfortunately, the Kong `post-function` method `access` does not allow reading a LUA file in there, expects an equals sign '=' and an array in a single line. So I have to inject that code into a single line by:
* dropping comment lines
* escaping double-quotes `"`
* replacing newlines with `; `
* injecting all this via `envsubst` and an `${OTEL_LUA_CODE}` variable

`kong.yml.in` part:
```yml
plugins:
- name: opentelemetry
  config:
    endpoint: "http://instana-agent:4318/v1/traces"
    resource_attributes:
      service.name: "kong-otel-demo"
- name: post-function
  config:
    access: ["${OTEL_LUA_CODE}"]
```
