### ISSUE TITLE
Reading issues with array elements in configuration files in DB less mode

### ISSUE THREAD

**Issue by lubw7** [Kong/kong#12601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4

### Current Behavior

I am using the plugin developed by our team.

plugins config example:
```
plugins:
    - name: our-plugin
      config:
        allowed_iss: [https://test.com/dev, https://test1.com/pro] 
```

In kong 2.8, this example is right, but in kong 3.4, it will be error, error info:
`failed parsing declarative configuration: 25:22: found unexpected ':'`

If adding single quotes to elements within array, for example :
`allowed_iss: ['https://test.com/dev', 'https://test1.com/pro'] `
It will be ok.

### Expected Behavior

What is the reason for this difference? I have checked Kong's upgrade announcement and cannot find any relevant information.

In general, in the configuration file of Kong3.4, if the value of the key value pair is an array and wrapped in square brackets, and if the array element contains a colon and is not wrapped in single quotation marks, an error will occur.

### Steps To Reproduce

In Kong 3.4
```
services:
- name: local-sso
  url: https://localhost
  routes:
  - name: sso-native
    paths: [/:login, /api/frm/sso, /actuator/health]
```
/:login is a invalid url, just for show case

error logs:
```
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:652: error parsing declarative config file /tmp/home/kong/kong.yml:
failed parsing declarative configuration: 9:12: found unexpected ':'
```

But in kong 2.8, Kong can start normally without any errors.
