### ISSUE TITLE
Bug in proxy-cache plugin returning compressed cached content to clients not supporting compression

### ISSUE THREAD

**Issue by tobiasehlert** [Kong/kong#12796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Enterprise 3.6.1.1

### Current Behavior

I've got reports from users from my API that they get compressed output when the response was cached from another user.

Lets say for instance a `/api/healthz` page is called from one client with gzip compression enabled and then another client makes straight away another call to the same endpoint, then the second client is served the compressed cached content but in a not readable format.

### Expected Behavior

I expected that the proxy-cache plugin does take the compression part in consideration and returns a non-compressed content to the second client.

Or maybe something some possibility to convert compressed cached content to non-compressed content? I don't know exactly.

### Steps To Reproduce

1. add proxy-cache plugin to a route
2. run curl command with compression enabled
   ```console
   curl --compressed https://example.com/api/healthz -v --output -
   ```
4. run curl command without compression right afterwards
   ```console
   curl https://example.com/api/healthz -v --output -
   ```

### Anything else?

This is my Kubernetes resource:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-cache-1min
  namespace: my-api-v4
config:
  cache_ttl: 60
  content_type:
    - text/plain
    - application/json
    - application/json; charset=utf-8
  request_method:
    - GET
    - HEAD
  response_code:
    - 200
  ignore_uri_case: true
  strategy: memory
plugin: proxy-cache
```
