### ISSUE TITLE
AI Prompt Guard plugin: Unexpected error due to malformed `messages` array in request body

### ISSUE THREAD

**Issue by dascole** [Kong/kong#12892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.6.1

### Current Behavior

When sending a request where the request body field `messages` is not an array it will result in an HTTP 500 "An unexpected error occurred".

```
2024/04/19 20:42:38 [error] 1320#0: *18338 [kong] init.lua:405 [ai-prompt-guard] ...l/share/lua/5.1/kong/plugins/ai-prompt-guard/handler.lua:28: bad argument #1 to 'ipairs' (table expected, got string), client: 172.27.0.1, server: kong, request: "POST /echo HTTP/1.1", host: "localhost:8000", request_id: "a647243bbf35935eaab50241dbb69206"
```

The result of trying to iterate over a non-table value:

for _, v in ipairs(request.messages) do
...

### Expected Behavior

The Prompt Guard plugin should be able to handle this more gracefully returning an HTTP 400 Bad Request.

### Steps To Reproduce

1. Spin up the Kong instance

```yaml
version: "3.7"

volumes:
    kong_data_ce: {}

services:
  kong-postgres-ce:
    image: postgres:9.6
    restart: always
    container_name: kong-postgres-ce
    networks:
      - kong-ce
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: kong
    ports:
      - "7432:5432/tcp"

  kong-migrations-ce:
    image: kong/kong:3.6.1
    container_name: kong-migrations-ce
    command: kong migrations bootstrap
    depends_on:
      - kong-postgres-ce
    environment:
      KONG_DATABASE: postgres
      KONG_PASSWORD: admin
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: kong-postgres-ce
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
    networks:
      - kong-ce
    restart: on-failure

  kong-ce:
    image: kong/kong:3.6.1
    container_name: kong-ce
    networks:
      - kong-ce
    depends_on:
      - kong-postgres-ce
      - kong-migrations-ce
    restart: on-failure
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8002:8002/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
      - "8445:8445/tcp"
    environment:
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_ADMIN_GUI_LISTEN:  0.0.0.0:8002, 0.0.0.0:8445 ssl http2
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl http2
      KONG_LOG_LEVEL: debug
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-postgres-ce
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}

networks:
  kong-ce:
    name: kong-ce
    driver: bridge
```

2. Sync the deck config: deck gateway sync --kong-addr http://localhost:8001/ kong.yaml

```yaml
_format_version: "3.0"
plugins:
- config:
    allow_all_conversation_history: false
    allow_patterns: []
    deny_patterns:
    - gruber
  enabled: true
  name: ai-prompt-guard
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: httpbin.org
  name: httpbin
  path: /anything
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: httpbin-route
    path_handling: v0
    paths:
    - /echo
    plugins:
    - config:
        auth: null
        logging:
          log_payloads: false
          log_statistics: true
        model:
          name: llama2
          options:
            anthropic_version: null
            azure_api_version: "2023-05-15"
            azure_deployment_id: null
            azure_instance: null
            llama2_format: ollama
            max_tokens: 256
            mistral_format: null
            temperature: 1
            top_k: 0
            top_p: 1
            upstream_url: https://localhost:443/v1
          provider: llama2
        route_type: llm/v1/chat
      enabled: true
      name: ai-proxy
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
```

3. Send a request with `messages` as a string

```shell
curl --request POST http://localhost:8000/echo \
  --header 'Content-Type: application/json' \
  --data '{
	"messages": "invalid"
}' -i
```

Response:
```shell
HTTP/1.1 500 Internal Server Error
Date: Fri, 19 Apr 2024 20:54:53 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Kong-Response-Latency: 1
Server: kong/3.6.1
X-Kong-Request-Id: ba8ed760842c1058ff296e73c427bb78

{
  "message":"An unexpected error occurred",
  "request_id":"ba8ed760842c1058ff296e73c427bb78"
}
```

4. Review the logs

```shell
2024/04/19 20:54:53 [error] 1320#0: *23480 [kong] init.lua:405 [ai-prompt-guard] ...l/share/lua/5.1/kong/plugins/ai-prompt-guard/handler.lua:28: bad argument #1 to 'ipairs' (table expected, got string), client: 172.27.0.1, server: kong, request: "POST /echo HTTP/1.1", host: "localhost:8000", request_id: "ba8ed760842c1058ff296e73c427bb78"
```

### Anything else?

I'm happy to submit the PR for this if we agree on the approach. The below has been working in my tests.

https://github.com/Kong/kong/blob/master/kong/plugins/ai-prompt-guard/handler.lua#L25
https://github.com/Kong/kong/blob/master/kong/plugins/ai-prompt-guard/handler.lua#L36

```
  if request.messages and not conf.allow_all_conversation_history then
    if type(request.messages) ~= "table" then
      return nil, "invalid 'messages' field"
    end

...

  elseif request.messages then
    --just take the trailing 'user' prompt
    if type(request.messages) ~= "table" then
      return nil, "invalid 'messages' field"
    end
