### ISSUE TITLE
OTEL plugin: the header_type parameter is deprecated, please update your configuration to use propagation.extract and propagation.inject instead

### ISSUE THREAD

**Issue by garciasdos** [Kong/kong#13202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.7.0

### Current Behavior

When any service call reaches this plugin, I get a warning message:
```
kong-1  | 2024/06/13 11:39:50 [warn] 5363#0: *6481 [kong] init.lua:86 [opentelemetry] the header_type parameter is deprecated, please update your configuration to use propagation.extract and propagation.inject instead, client: 192.168.65.1
```
Here's my opentelemetry plugin configuration: 
```yaml
  - name: opentelemetry
    id: 9e7fdd24-d119-40b7-8e7c-75e8042fd59d
    protocols:
      - grpc
      - grpcs
    tags:
      - global-plugin
    enabled: true
    config:
      endpoint: $ENDPOINT
      resource_attributes:
        ...
      headers:
        api-key: $KEY
```

but `header_type` is not being modified elsewhere

### Expected Behavior

When any service call reaches this plugin, I should not get a warning message if no custom configuration was made

### Steps To Reproduce

1. Launch a kong `3.7` project
2. Add the `opentelemetry` OSS plugin
3. Do not modify the `header_type` attribute
