### ISSUE TITLE
Upstream response time mismatch.

### ISSUE THREAD

**Issue by ksgnextuple** [Kong/kong#13302]
### Discussed in https://github.com/Kong/kong/discussions/13300

<div type='discussions-op-text'>

<sup>Originally posted by **ksgnextuple** June 25, 2024</sup>
Hi Team

We are running few performance tests on of our apis and we see that the kong_upstream_response time reported on Prometheus is having a large difference as compared to the actual upstream latency.

Kong : 3.6
KIC: 3.1

The same test was run using Kong 2.8 and KIC 2.5 we saw that this difference was minimal which is expected behavior.

Has anyone faced such an issue?</div>

**Comment by chobits** [comment]
> Prometheus is having a large difference as compared to the actual upstream latency.
Could you give us some examples? 

For `the actual upstream latency`, could you show us how you monitored this **actual** latency value?

**Comment by ksgnextuple** [comment]
We have instrumented the application using newrelic java agent, and also monitoring it using prometheus micrometer metrics. We saw that on both the places the latency were matching and much lower than the upstream reported by the prometheus plugin of kong. This was not the case with Kong 2.8, where the upstream latency reported by kong prom plugin was pretty close to latency observed on the above places.

The difference we see with kong 3.6 is around 100ms (sometimes more) whereas it was not more than 10ms with kong 2.8.

**Comment by hanshuebner** [comment]
It is not impossible that there is a bug in how the Prometheus plugin response upstream latency that was introduced between 2.8 and 3.6.  To dig deeper, we'd need a way to reproduce.  Can you share details on what your custom plugin does, i.e. what functions it implements and what is done in them?

**Comment by ksgnextuple** [comment]
So the plugin intercepts every request made to kong and then makes a HTTP POST request to a custom auth service which has authorization logic. Can share the lua scripts here if required.  The script itself is based on this custom plugin -> https://github.com/pantsel/kong-middleman-plugin/tree/master

We have modified the above a bit and can share those scripts if required.

**Comment by hanshuebner** [comment]
It would be useful to have a way to reproduce the problem, so if you can supply your plugin as well as a minimal configuration for reproduction, it'd help.

**Comment by ksgnextuple** [comment]
[middleman-plugin-cm.zip](https://github.com/user-attachments/files/16017833/middleman-plugin-cm.zip)

Attached the configMap as a zip

Below is the sample plugin yaml

``` 
apiVersion: configuration.konghq.com/v1
config:
  response: table
  timeout: 2
  url: http://<endpoint>/<some-api>
kind: KongPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: <className>
  name: middleman-plugin
plugin: middleman
```

**Comment by hanshuebner** [comment]
@ksgnextuple Please provide the plugin in a ZIP containing the individual files, not as a YAML file.  Also, provide instructions to reproduce the problem.

**Comment by hanshuebner** [comment]
@ksgnextuple Don't bother with the plugin files.  I was able to extract them from the YAML file and to set up a test environment.  I could not reproduce the issue, however.  With the `kong:latest` image, your plugin and the Prometheus plugin installed and the middleman http server responding after a 200ms delay, I see these metrics (elided):

```
# HELP kong_request_latency_ms Total latency incurred during requests for each service/route in Kong
# TYPE kong_request_latency_ms histogram
kong_request_latency_ms_bucket{service="example-service",route="example-route",workspace="default",le="250"} 24
# HELP kong_upstream_latency_ms Latency added by upstream response for each service/route in Kong
# TYPE kong_upstream_latency_ms histogram
kong_upstream_latency_ms_bucket{service="example-service",route="example-route",workspace="default",le="25"} 24
```

As you can see, the request latency for all 24 requests is below 250ms, and the upstream latency is below 25ms.  Hence, the upstream response time metrics don't include the time that the middleman server takes to respond.

From our perspective, it does not look like there is a problem in Kong Gateway here.  If you think different, please provide a self-contained way to reproduce the problem.

**Comment by hanshuebner** [comment]
Here is my test environment in case you want to experiment with it yourself: [middleman.zip](https://github.com/user-attachments/files/16025328/middleman.zip)

**Comment by ksgnextuple** [comment]
@hanshuebner Thanks for the inputs, will try this setup on our end and get back.

**Comment by ksgnextuple** [comment]
@hanshuebner  I setup the test environment, but I set it up on a k8s cluster as that's where we run our tests. First I ran a 15 min test and used the below Prometheus queries to record the response times (p95)

histogram_quantile(0.95, sum by(le) (rate(kong_kong_latency_ms_bucket{kubernetes_namespace="kong", service="default.echo-service.80"}[$__interval])))

histogram_quantile(0.95, sum by(le) (rate(kong_request_latency_ms_bucket{kubernetes_namespace="kong", service="default.echo-service.80"}[$__interval])))

histogram_quantile(0.95, sum by(le) (rate(kong_upstream_latency_ms_bucket{kubernetes_namespace="kong", service="default.echo-service.80"}[$__interval])))

These were the results:

Without Middleman

P95 Kong - 4.29ms
P95 Request - 17.9ms
P95 Upstream - 17.8ms

Then I ran a another test with Middleman Enabled, below are the results:

P95 Kong - 364ms
P95 Request - 485ms
P95 Upstream - 325ms

Pasting the k8s yamls for reproduction if required.

``` 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: test-middleman
          # command: [ "/bin/bash", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 100Mi
          ports:
            - name: http-port
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: echo-server
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: middleman-plugin
  name: echo-service
spec:
  rules:
    - host: "poc.example.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo-service
                port:
                  number: 80
```
Do let me know if the plugin yaml is required for the setup on k8s cluster.
