### ISSUE TITLE
Kong to backend FastAPI service: 405 Method Not Allowed

### ISSUE THREAD

**Issue by surajvm1** [Kong/kong#13512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.x (kong:latest)

### Current Behavior

I have a backend FastAPI service which (say) is defined like this: 
```
GET/POST API service:

@app.get("/api/getWeather/{location}", response_model=WeatherResponse)
async def get_weather(location: str, db: Session = Depends(get_db)):
    # location is my query params which can keep changing based on request from frontend service
    weather = fetch_weather_from_postgres(db, location)
    if weather:
        response_data = {
        # some data 
        }
        return response_data

@app.post("/api/sendWeather")
async def send_weather(weather: WeatherData, db: Session = Depends(get_db)):
    '''
    Sample data expected: 
    {
      "user": "user",
      "location": "someLocation",
      "temperature": 25
    }
    '''
    add_weather_to_postgres(db, weather),
    # some data
    return response_data
```

Dockerfile of app:
```
FROM python:3.9-slim
ENV APP_HOME /internalWeatherServiceB
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY . /$APP_HOME
RUN pip install -r requirements.txt
EXPOSE 8900
ENTRYPOINT ["sh", "-c"]
CMD ["uvicorn app.main:app --host 0.0.0.0 --port 8900 --reload"]
```

Sample Docker compose file: 
```
version: '3'
networks:
  service_network:
    name: service_compose_network
services:
  internal_weather_service_b:
    build:
      context: ./internalWeatherServiceB
      dockerfile: Dockerfile
    container_name: internal_weather_service_b
    ports:
      - "8900:8900"
    env_file:
      - ./internalWeatherServiceB/.env
    networks:
      - service_network
    depends_on:
      - postgres_service
     
  kong_gateway_1:
    image: kong:latest
    container_name: kong_gateway_1
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - .././kongApiGateway/kong.yml:/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - service_network
```

Now, if I hit just the backend service with a POST request: 

```
curl -X POST http://localhost:8900/api/sendWeather -H "Content-Type: application/json" -d '{"user": "usertest", "location": "someLocation", "temperature": 25}'
# I get success message 
```

But when I hit the API routed via Kong's service, I get error. Kong yml file:
```
_format_version: "3.0"
services:
  - name: internal-weather-service
    url: http://internal_weather_service_b:8900  
    routes:
      - name: internal-weather-route-GET
        paths:
          - /api/getWeather/*
        methods:
          - GET
      - name: internal-weather-route-POST
        paths:
          - /api/sendWeather
upstreams:
  - name: weather-upstream
    targets:
      - target: internal_weather_service_b:8900
        weight: 100
    healthchecks:
      active:
        http_path: "/" 
        healthy:
          interval: 180
          http_statuses: [200, 302]
          successes: 1
        unhealthy:
          interval: 120
          http_statuses: [429, 500, 503]
          tcp_failures: 3
          timeouts: 1
          http_failures: 3
```

When I hit cURL command: 
```
curl -X POST http://localhost:8000/api/sendWeather -H "Content-Type: application/json" -d '{"user": "testuser", "location": "someLocation", "temperature": 25}'
Output: {"detail":"Method Not Allowed"}                                  
```

Error in Kong/FastAPI service logs: `"POST / HTTP/1.1" 405 Method Not Allowed` 

As part of debugging, I commented all routes except POST route and ran: 
```
GET: http://localhost:8001/routes
        {
            "regex_priority": 0,
            "snis": null,
            "tags": null,
            "protocols": [
                "http",
                "https"
            ],
            "paths": [
                "/api/sendWeather"
            ],
            "request_buffering": true,
            "response_buffering": true,
            "path_handling": "v0",
            "created_at": 1724007558,
            "updated_at": 1724007558,
            "https_redirect_status_code": 426,
            "id": "cd397c5b-437f-5d40-8ecf-8aaa8285d9f3",
            "hosts": null,
            "preserve_host": false,
            "name": "internal-weather-route-POST",
            "strip_path": true,
            "sources": null,
            "destinations": null,
            "headers": null,
            "methods": [
                "POST"
            ],
            "service": {
                "id": "35bfcec6-69c9-5f7b-8539-5e4a33befffd"
            }
        },
```

```
GET: http://localhost:8001/services
{
            "name": "internal-weather-service",
            "tags": null,
            "ca_certificates": null,
            "protocol": "http",
            "connect_timeout": 60000,
            "read_timeout": 60000,
            "tls_verify": null,
            "created_at": 1724007558,
            "host": "internal_weather_service_b",
            "id": "35bfcec6-69c9-5f7b-8539-5e4a33befffd",
            "write_timeout": 60000,
            "port": 8900,
            "path": null,
            "retries": 5,
            "client_certificate": null,
            "updated_at": 1724007558,
            "tls_verify_depth": null,
            "enabled": true
        }
```

Kong test error: 
<img width="744" alt="Screenshot 2024-08-19 at 1 05 45 AM" src="https://github.com/user-attachments/assets/53333fc0-60ee-4f70-8a24-937bca5ab6b9">

Normal POST directly to backend works: 
<img width="744" alt="Screenshot 2024-08-19 at 1 05 25 AM" src="https://github.com/user-attachments/assets/89523730-af05-40fd-864a-54cf15bf49fb">

The error persists. 

### Expected Behavior

It should POST data to API and return say ~ `{"message":"Weather data added successfully"}`.
