### ISSUE TITLE
Kong 3.7.1 Exponential memory growth over time.

### ISSUE THREAD

**Issue by muh-kamran** [Kong/kong#13553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7.1

### Current Behavior

We recently upgraded from 3.3 to 3.71. In last 8 days the memory of proxy grew from **550MB** to **1.03GB** and eventually got OOM killed. we didn't saw this issue on 3.3.

<img width="1462" alt="Screenshot 2024-08-22 at 3 44 22 PM" src="https://github.com/user-attachments/assets/1c0bbe12-d18b-4095-8a52-cfb3037abcbd">

Nothing changed from our end.. just version upgrade.
Please inform me if you need more details. Additionally, I would appreciate any recommendations for debugging steps, areas to investigate, or configuration changes that have successfully addressed similar issues for you.

### Expected Behavior

kong 3.3 its much stable:
<img width="1447" alt="Screenshot 2024-08-22 at 4 00 43 PM" src="https://github.com/user-attachments/assets/96929beb-24a6-4e71-9456-6abe1be0b6bc">

### Anything else?

only error message in logs i see is:
`[error] 1437#0: *582289 [lua] http.lua:962: request_uri(): closed, context: ngx.timer`

**Comment by nowNick** [comment]
Hi @muh-kamran !
That looks concerning! We should definitely investigate further. Could you please share a little bit more info about your configuration?
- What is your deployment topology? Traditional / declarative / hybrid mode? 
- How many services / routes / consumers / other entities are defined?
- What plugins are enabled? How many plugin instances?

Sharing this data will allow us to create a similar environment to yours and potentially replicate this issue.

**Comment by muh-kamran** [comment]
we are using kong as ingress as well as gateway. In gateway we push declarative configuration through admin api.The issue is on both but very aggressive on kong ingress. let share the detail of ingress.

Helm chart: https://github.com/Kong/charts/tree/main/charts/kong
version: 2.38.0
Max current rps is : 200
values file:
`---
deployment:
  ## Specify the service account to create and to be assigned to the deployment / daemonset and for the migrations
  serviceAccount:
    # Automount the service account token. By default, this is disabled, and the token is only mounted on the controller
    # container. Some sidecars require enabling this. Note that enabling this exposes Kubernetes credentials to Kong
    # Lua code, increasing potential attack surface.
    automountServiceAccountToken: true

readinessProbe:
  httpGet:
    path: /status/ready
    port: status
    scheme: HTTP

livenessProbe:
  httpGet:
    path: /status/ready
    port: status
    scheme: HTTP

customEnv:
  MEM_CACHE_SIZE: 256m
  LUA_SOCKET_POOL_SIZE: 200
  nginx_main_worker_rlimit_nofile: 8192
  nginx_events_worker_connections: 16384
  LMDB_MAP_SIZE: 500m
env:
  PROXY_LISTEN: 0.0.0.0:8000 reuseport, 0.0.0.0:8443 reuseport ssl
  TRUSTED_IPS: 0.0.0.0/0,::/0
  REAL_IP_RECURSIVE: "on"
  REAL_IP_HEADER: "X-Forwarded-For"
  nginx_worker_processes: 2
  plugins: "bundled"
  MEM_CACHE_SIZE: 256m
  LUA_SOCKET_POOL_SIZE: 200
  nginx_main_worker_rlimit_nofile: 8192
  nginx_events_worker_connections: 16384
  LMDB_MAP_SIZE: 500m
  
# Use NodePort instead of the default LoadBalancer type
proxy:
  type: ClusterIP

namespace: "kong-ingress"
image:
  repository: docker-mirror.control.sre.red/library/kong
  tag: "3.7.1"
  effectiveSemver:
  pullPolicy: IfNotPresent  
autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5

resources:
    requests:
      cpu: 3
      memory: 5Gi
    limits:
      cpu: 3
      memory: 5Gi
ingressController:
    # ingress controller container resources
  resources:
      requests:
        cpu: 100m
        memory: 256Mi
podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '8100'

# Setting required for this chart to work with Helm 3
ingressController:
  image:
    repository: docker-mirror.control.sre.red/kong/kubernetes-ingress-controller
    tag: "3.1"
    effectiveSemver:
  installCRDs: false
  env:
    enable_reverse_sync: false
    update_status: false
    PROXY_SYNC_SECONDS: 600

podDisruptionBudget:
  enabled: true

podSecurityPolicy:
  enabled: false
  spec:
    privileged: false
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: RunAsAny
    runAsGroup:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
      - 'configMap'
      - 'secret'
      - 'emptyDir'
      - 'projected'
      - 'downwardAPI'
      - 'persistentVolumeClaim'
    allowPrivilegeEscalation: false
    hostNetwork: false
    hostIPC: false
    hostPID: false
    # Make the root filesystem read-only. This is not compatible with Kong Enterprise <1.5.
    # If you use Kong Enterprise <1.5, this must be set to false.
    readOnlyRootFilesystem: true
    # Required for linkerd sidecar proxy
    allowedCapabilities:
      - NET_ADMIN
      - NET_RAW
`
**_One thing to note_** this configuration have impact on memory:

ingressController:
  image:
    repository: docker-mirror.control.sre.red/kong/kubernetes-ingress-controller
    tag: "3.1"
    effectiveSemver:
  installCRDs: false
  env:
    enable_reverse_sync: false
    update_status: false
    PROXY_SYNC_SECONDS: 600`
when **enable_reverse_sync: true** and **PROXY_SYNC_SECONDS: 30** .. the proxy got OOM killed immediately in few hours.  setting it to **enable_reverse_sync: false** and **PROXY_SYNC_SECONDS: 600** or so .. The memory grow slowly and proxy got OOM in days.  **Could be memory leak on configuration push to admin api**.

**Plugins enabled:**
- request-termination
- prometheus

**services:** 70
**routes:** 119

**Comment by chobits** [comment]
hi @muh-kamran We need some detailed information to help us identify where the memory consumption is happening.
You could run the following commands to get the stats .

1. whether the memory is consumed in kong's lua land.

```
$ curl localhost:8001/status
```

2. show us the heap map of kong(nginx worker process) 

```
$ cat /proc/<nginx-worker-process-id>/maps
```

3. show the open fd of kong (nginx worker process) to see whether there are some leaked connection

```
lsof -p <nginx-worker-process-id>

or 

netstat -np|grep nginx
```

or any information which you think is helpful for troubleshooting

**Comment by bungle** [comment]
The growth here doesn't look exponential to me, but quite linear. Also at the end it seems to drop. Am I correct?

**Comment by muh-kamran** [comment]
Yes, it's experiencing OOM. We increased the memory to 5GB, but it still hits the OOM state in about 2 hours. This time, the issue is more severe because we changed these two flags on the controller to:
```
    enable_reverse_sync: true
    proxy_sync_seconds: 2
```


<img width="1480" alt="Screenshot 2024-08-27 at 8 17 15 PM" src="https://github.com/user-attachments/assets/710877b2-ff9b-4a7e-b914-00a1db49631e">

**Comment by muh-kamran** [comment]
I'll provide the requested details. However, before doing so, I was testing it on a local kind cluster and observed the same pattern with a single ingress object. Here are the steps:
- kind create cluster --name kong-debug
- helm repo add stable https://charts.helm.sh/stable
- helm repo add kong https://charts.konghq.com
- helm repo update
- kubectl create namespace monitoring
- helm install kind-prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --set prometheus.service.nodePort=30000 --set prometheus.service.type=NodePort --set grafana.service.nodePort=31000 --set grafana.service.type=NodePort --set alertmanager.service.nodePort=32000 --set alertmanager.service.type=NodePort --set prometheus-node-exporter.service.nodePort=32001 --set prometheus-node-exporter.service.type=NodePort
- values.yaml
```
deployment:
  prefixDir:
    sizeLimit: 1Gi
  serviceAccount:
    automountServiceAccountToken: true
image:
  repository: docker-mirror.control.sre.red/library/kong
  tag: "3.7.1"
  effectiveSemver:
  pullPolicy: IfNotPresent
readinessProbe:
  httpGet:
    path: /status/ready
    port: status
    scheme: HTTP
livenessProbe:
  httpGet:
    path: /status/ready
    port: status
    scheme: HTTP
env:
  PROXY_LISTEN: 0.0.0.0:8000 reuseport, 0.0.0.0:8443 reuseport ssl
  TRUSTED_IPS: 0.0.0.0/0,::/0
  REAL_IP_RECURSIVE: "on"
  REAL_IP_HEADER: X-Forwarded-For
  nginx_worker_processes: 2
  MEM_CACHE_SIZE: 256m
  LUA_SOCKET_POOL_SIZE: 200
  nginx_main_worker_rlimit_nofile: 8192
  nginx_events_worker_connections: 16384
  LMDB_MAP_SIZE: 500m
  proxy_access_log: 'off'
customenv:
  MEM_CACHE_SIZE: 256m
  LUA_SOCKET_POOL_SIZE: 200
  nginx_main_worker_rlimit_nofile: 8192
  nginx_events_worker_connections: 16384
  LMDB_MAP_SIZE: 500m
proxy:
  type: ClusterIP
namespace: "kong-ingress"
autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
resources:
    requests:
      cpu: 0.5
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '8100,10255'
lifecycle:
  preStop:
    exec:
      command:
        - kong
        - quit
        - '--wait=60'
        - '--timeout=15'
terminationGracePeriodSeconds: 90
ingressController:
  image:
    repository: docker-mirror.control.sre.red/kong/kubernetes-ingress-controller
    tag: "3.1"
    effectiveSemver:
  installCRDs: false
  env:
    enable_reverse_sync: true
    proxy_sync_seconds: 2
    update_status: false
    log_level: debug
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
podDisruptionBudget:
  enabled: true
podSecurityPolicy:
  enabled: false
  spec:
    privileged: false
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: RunAsAny
    runAsGroup:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
      - 'configMap'
      - 'secret'
      - 'emptyDir'
      - 'projected'
      - 'downwardAPI'
      - 'persistentVolumeClaim'
    allowPrivilegeEscalation: false
    hostNetwork: false
    hostIPC: false
    hostPID: false
    readOnlyRootFilesystem: true
    allowedCapabilities:
      - NET_ADMIN
      - NET_RAW
```
- helm install --values values.yaml kong/kong --generate-name
- helm repo add ealenn https://ealenn.github.io/charts
- helm repo update
- helm install --set ingress.enable=true --name echoserver ealenn/echo-server
- ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo1
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    configuration.konghq.com: echo1
    konghq.com/request-buffering: 'false'
    konghq.com/response-buffering: 'false'
    kubernetes.io/ingress.class: kong
    meta.helm.sh/release-name: echo1
    meta.helm.sh/release-namespace: echo1
    plugins.konghq.com: echo1-request-transformer,echo1-response-transformer
spec:
  rules:
    - host: echo1.dev.test.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: echoserver-echo-server
                port:
                  number: 80
    - host: echo1.alfa.dev.test.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: echoserver-echo-server
                port:
                  number: 80

```

- Next i port forward to grafana and run `sum(container_memory_working_set_bytes{container=~"proxy", container!="", image!=""}) by (pod,container)`
<img width="1470" alt="Screenshot 2024-08-27 at 8 29 02 PM" src="https://github.com/user-attachments/assets/5be0e67a-06bc-4e77-9173-e0283e6702c8">
