### ISSUE TITLE
Excessive logs when using a redirect filter

### ISSUE THREAD

**Issue by lynkz-matt-psaltis** [Kong/kong#13724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.7 (KIC 3.3)

### Current Behavior

When using a requestRedirect filter, the following info is logged every 3 seconds. It makes log review and debugging difficult.

`2024-09-30T11:02:38Z	info	No targets found to create upstream	{"v": 0, "service_name": "httproute.website.website-redirect.0"}`

```
HTTPRoute:

  rules:
    - filters:
        - requestRedirect:
            hostname: <alternative host>
            port: 443
            scheme: https
            statusCode: 301
          type: RequestRedirect
      matches:
        - path:
            type: PathPrefix
            value: /
```

### Expected Behavior

Our log retention costs go down by not logging this error. There's no backend configured for this redirect rule.
