### ISSUE TITLE
The plugin response-transformer doesn't work with gzipped responses

### ISSUE THREAD

**Issue by kelvingl** [Kong/kong#13741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.8, 2.8 and 2.1.4

### Current Behavior

When the upstream response has gzip encode, the response-transformer with json transformations doesnt work

### Expected Behavior

The defined body modifications were made. On test case, the key "addedkey" would be added and the key "debug" removed.

### Steps To Reproduce

I used the following docker-compose to simulate on 2.1.4, 2 (lts) and 3 (latest)

```yaml
services:
  service:
    image: golang:1.23-alpine
    environment:
      MAIN_GO: |
        package main

        import (
            "fmt"
            "net/http"
            "bytes"
            "compress/gzip"
        )

        func dataAsGzip(a string) []byte {
            var buf bytes.Buffer
            gz := gzip.NewWriter(&buf)
            if _, err := gz.Write([]byte(a)); err != nil {
                panic(err)
            }
            if err := gz.Close(); err != nil {
                panic(err)
            }
            return buf.Bytes()
        }

        func handler(w http.ResponseWriter, r *http.Request) {
            data := "{\"key\":\"value\",\"debug\":\"this should be removed\"}"
            dataGzip := string(dataAsGzip(data))
            lenData := len(data)
            lenGzip := len(dataGzip)
            fmt.Printf("data: %d, gzip: %d\n", lenData, lenGzip)

            w.Header().Set("Content-Encoding", "gzip")

            w.Header().Set("Content-Type", "application/json")

            w.Header().Set("Content-Length", fmt.Sprintf("%d", lenGzip))

            w.WriteHeader(http.StatusOK)

            fmt.Fprintf(w, dataGzip)
        }

        func main() {
            http.HandleFunc("/", handler)
            http.ListenAndServe(":8080", nil)
        }
    command: [ "sh", "-c", 'echo "$$MAIN_GO" > /tmp/main.go && go run /tmp/main.go' ]

  kong:
    image: kong:3
    environment:
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
      KONG_DATABASE: "off"
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    healthcheck:
      test: "kong health"
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "8000:8000"

  kong-config-loader:
    image: alpine/httpie
    depends_on: { kong: { condition: service_healthy } }
    environment:
      YAML: |
        _format_version: '2.1'
        _transform: true
        services:
          - name: my-service
            protocol: http
            host: service
            port: 8080
            routes:
              - name: my-route
                service: my-service
                paths: [ / ]
                plugins: [ { name: response-transformer, config: { add: { json: ["addedkey:true"] }, remove: { json: [ "debug" ] } } } ]
    entrypoint: [ "sh", "-c", "echo \"$$YAML\" | http -I kong:8001/config check_hash==1 config=@/dev/stdin" ]
```

and tested with httpie:

```
http localhost:8000
```

### Anything else?

On kong 2.1.4, no changes are made on response payload and no logs are generated.

On kong 2.8 (lts), the connection is abruptly closed with this error at log:

```
172.20.0.1 - - [10/Oct/2024:18:45:58 +0000] "GET / HTTP/1.1" 200 0 "-" "HTTPie/3.2.2"
2024/10/10 18:45:58 [error] 1110#0: *80 failed to run body_filter_by_lua*: /usr/local/share/lua/5.1/kong/init.lua:326: body must be a string
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/pdk/response.lua:614: in function </usr/local/share/lua/5.1/kong/pdk/response.lua:610>
	/usr/local/share/lua/5.1/kong/init.lua:326: in function 'execute_collected_plugins_iterator'
	/usr/local/share/lua/5.1/kong/init.lua:1270: in function 'body_filter'
	body_filter_by_lua:2: in main chunk while sending to client, client: 172.20.0.1, server: kong, request: "GET / HTTP/1.1", upstream: "http://172.20.0.2:8080/", host: "localhost:8000"
```

On kong 3 (latest), we had a warning on logs:

```
172.21.0.1 - - [10/Oct/2024:18:47:14 +0000] "GET / HTTP/1.1" 200 83 "-" "HTTPie/3.2.2" kong_request_id: "3fb9ba3510123c664384446fd648a27c"
2024/10/10 18:47:14 [warn] 1405#0: *1293 [kong] handler.lua:38 [response-transformer] body transform failed: failed parsing json body while sending to client, client: 172.21.0.1, server: kong, request: "GET / HTTP/1.1", upstream: "http://172.21.0.2:8080/", host: "localhost:8000", request_id: "3fb9ba3510123c664384446fd648a27c"
```

The responses on all cases (except 2.8) is:

```
{
    "debug": "this should be removed",
    "key": "value"
}
```
