### ISSUE TITLE
ERROR The plain HTTP request was sent to HTTPS port

### ISSUE THREAD

**Issue by didlawowo** [Kong/kong#13880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3,7

### Current Behavior

I 'm trying to install kong gateway and get ingress controller for manager
when i'm trying to join the dns, it respond with and http request have been send to https service. i think it's maybe not a bug, but i have tried to understand the configuration and i don't found the correct way

error: 
400 Bad Request
The plain HTTP request was sent to HTTPS port

### Expected Behavior

see the web page for manager

### Steps To Reproduce

deploy kong using helm value 

### Anything else?

running on traefik with rke2

value file from argo

```
        podAnnotations:
          ad.datadoghq.com/ingress-controller.logs: '[{"source":"kong" }]'

        certificates:
          enabled: true
          clusterIssuer: letsencrypt-cloudflare
          proxy:
            commonName: kong.dc-tech.work
          portal:
            commonName: kong-portal.dc-tech.work
          admin:
            commonName: kong.dc-tech.work
          cluster:
            enabled: false
        autoscaling:
          enabled: true

        portal:
          type: ClusterIP
          enabled: true
          ingress:
            enabled: true
            ingressClassName: kong
            hostname: kong-portal.dc-tech.work

            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-cloudflare
            tls: kong-portal-tls

        manager:
          http:
            enabled: false
          type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: kong
            hostname: kong-manager.dc-tech.work
            annotations:
              konghq.com/protocols: https
              cert-manager.io/cluster-issuer: letsencrypt-cloudflare

        env:
          # admin_gui_url: https://kong-manager.dc-tech.work
          admin_api_url: https://kong-api.dc-tech.work/

        admin:
          enabled: true
          http:
            enabled: true
          tls:
            enabled: false
          type: ClusterIP

          ingress:
            enabled: true
            ingressClassName: kong
            hostname: kong-api.dc-tech.work

            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-cloudflare
            tls: kong-api-tls

        postgresql:
          enabled: true
```
