### ISSUE TITLE
Kong Cors Plugin - unable to add multiple url in the origins config

### ISSUE THREAD

**Issue by carmine-ianniello-deltatre** [Kong/kong#13919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

KIC 3.1

### Current Behavior

Hello, 

I'm using Kong ingress controller 3.1 version with the Cors plugin configured as below.
When I use it with a single origin in the config field, everything works as expected, as shown in the image below.
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-cors-custom
config:
  origins:
  - first-url.com
  - second-url.com
  credentials: true
  max_age: 3600
  preflight_continue: false
plugin: cors

```
![image](https://github.com/user-attachments/assets/deda6133-5288-4b9d-acdf-53178a2bbf64)

But when I try to add another origin, the Allow-Control-Allow-Origins header disappears, not allowing neither the first URL.

From my understanding the plugin should be able to add multiple origins URLs, is that right? 

 
![image](https://github.com/user-attachments/assets/3015a9e1-fa9b-43d8-8fc8-0d7bd848d76f)

### Expected Behavior

I'm expecting to be able to allow multiple URL with cors plugin

### Steps To Reproduce

- Create the cors plugin in yaml format
- add 2 or more hostname in the origins config
- check the header in the Response headers
