### ISSUE TITLE
GatewAPI address field overriden with publish service

### ISSUE THREAD

**Issue by hassanbsee2071** [Kong/kong#14140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 3.8

### Current Behavior

I applied below manifest files.

```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong-class-multi
  annotations:
    konghq.com/gatewayclass-unmanaged: 'true'
    # konghq.com/gatewayclass-unmanaged: 'false'
spec:
  controllerName: konghq.com/kic-gateway-controller-multi
```

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong-gateway-hotels
  namespace: public-gateway-http
  # annotations:
  #   konghq.com/publish-service: kong-multi/kong-multi-hotels-gateway-proxy
spec:
  gatewayClassName: kong-class-multi
  listeners:
  - name: http-hotels
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: "hotels"
  addresses:
    - type: Hostname
      value: kong-multi-hotel-gateway-86435522.eu-west-1.elb.amazonaws.com

```

Even though I have specifically mention the addresses in the gateway but it is not reflecting. Load balancer address of publish service is taking over this address.

```
kubectl get gateway -n public-gateway-http
NAME                        CLASS              ADDRESS                                                                         PROGRAMMED   AGE
kong-gateway-common-teams   kong-class-multi   k8s-kongmult-kongmult-72545a7b88-75418e3312e5914b.elb.eu-west-1.amazonaws.com    True         36h
kong-gateway-flights        kong-class-multi  k8s-kongmult-kongmult-72545a7b88-75418e3312e5914b.elb.eu-west-1.amazonaws.com    True         36h
kong-gateway-hotels         kong-class-multi   k8s-kongmult-kongmult-72545a7b88-75418e3312e5914b.elb.eu-west-1.amazonaws.com   True         54m
```

I want to create 4 gateways and all 4 gateways have their own load balancers address to listen on.  But as you can see above all the gateways have same address. This address is the load balancer of publish service. 

### Expected Behavior

Each gateway should reflect its own address, instead of same address.
