### ISSUE TITLE
K8S Gateway API - TLSRoute with wildcard hostname, ROUTER_FLAVOR=expressions

### ISSUE THREAD

**Issue by piotrgasior** [Kong/kong#14252]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.9

### Current Behavior

Gateway is configured in DB-less mode together with KIC 3.4.1.
The Gateway is deployed by helm chart with env: `router_flavor: expressions`

Gateway config cannot be updated with TLSRoute, which contains wildcard in the hostname definition, the error is:
```
invalid expression: length must be at least 1
```

### Expected Behavior

Gateway should accept following config.

### Steps To Reproduce

Kong deployment via Helm charts with FeatureGate and Router Flvaor env:
```
feature_gates: GatewayAlpha=true
router_flavor: expressions  
```

Gateway:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: somename
  namespace: somenamespace
spec:
  gatewayClassName: gatewayclassname
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.example.net'
    name: tls
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough

```
TLSRoute:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: somename
  namespace: somenamespace
spec:
  hostnames:
  - '*.example.net'
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gatewayname
    sectionName: tls
  rules:
  - backendRefs:
    - kind: Service
      name: gateway-proxy
      port: 9443
```
