### ISSUE TITLE
Kong behind CDN

### ISSUE THREAD

**Issue by omegion** [Kong/kong#14269]
Hi,

I am running Kong in my Kubernetes cluster behind a service and a CDN. I have an HTTPRoute with a hostname:

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: service-a
spec:
  parentRefs:
    - name: internal
      namespace: gateway-api
  hostnames:
    - service-a.private-domain
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: deployment
          port: 80
```

The problem is that I accept traffic to `service-a.example.com` public domain, but my internal hostname is `service-a.private-domain`, but Kong gets the `Host` header as `service-a.example.com` and does not match any route.

How can I ignore the Host header of my CDN?
