### ISSUE TITLE
Validating route headers against Konnect results in "proto: syntax error (line 1:20): unexpected token ["

### ISSUE THREAD

**Issue by dimimari-flutterint** [Kong/kong#14299]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Konnect (Data plane nodes 3.8.0.0)

### Current Behavior

When validating a route with `headers` present, the local `deck file validate` passes while the `deck gateway validate` throws an error. This behavior is present against Kong Konnect, validating against an on prem Kong control plane does not have the error. When configuring the header from the UI it is accepted and saved, when dumping the config the same syntax is being used. Both deck and postman/curl requests for the same example service and route (see Steps To Reproduce) return the error.

### Expected Behavior

The validate should pass.

### Steps To Reproduce

Test service

```yaml
_format_version: "3.0"
services:
- connect_timeout: 60000
  enabled: true
  host: www.example.com
  name: MockService
  path: /path
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - hosts:
    - testhost.com
    headers:
      Test:
        - ~*.+
    https_redirect_status_code: 426
    methods:
    - GET
    name: test_route
    path_handling: v0
    paths:
    - /path1
    - ~/path1/status$
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - test
  tags:
  - TestService
  write_timeout: 60000
```

Run deck file validate

```shell
deck file validate mockservice.yaml
```

Run deck gateway validate

```shell
deck gateway validate mockservice.yaml --konnect-addr https://us.api.konghq.com --konnect-token <token> --konnect-control-plane-name <cplane>
Error: validate entity 'routes (test_route)': HTTP status 400 (message: "proto: syntax error (line 1:20): unexpected token [")
```

### Anything else?

Running the same on Kong Enterprise 3.4.3.10 does not produce the error.

```shell
deck gateway validate mockservice.yaml --kong-addr https://api.kongenterprise.site --headers "kong-admin-token:token" -w <workspace>
```
