### ISSUE TITLE
Kong status API is invoked every 3 seconds

### ISSUE THREAD

**Issue by bharanitharanm** [Kong/kong#14332]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

3.4.2

### Current Behavior

In Kong logs, I can see the below logs are logged every 3 seconds

```
127.0.0.1 - - [28/Feb/2025:11:17:47 +0000] "GET /status HTTP/1.1" 200 1317 "-" "Go-http-client/1.1"
127.0.0.1 - - [28/Feb/2025:11:17:50 +0000] "GET /status HTTP/1.1" 200 1317 "-" "Go-http-client/1.1"
127.0.0.1 - - [28/Feb/2025:11:17:53 +0000] "GET /status HTTP/1.1" 200 1317 "-" "Go-http-client/1.1"
```

How to increase the frequency to 60 seconds ? OR How to disable altogather

**Comment by DMaxter** [comment]
Can it be that it is some kind of liveness probe? If you are running in a Kubernetes environment that might be it, but the timeframe is 5s and usually the user agent is `kube-probe`...

Might also be from Kong gateway operator?

**Comment by bharanitharanm** [comment]
I'm deploying in Kubernetes environement, liveness probe and readiness probe frequency is 60 seconds and 30 seconds respectively for both Kong (Proxy) and ingress controller.

I'm not using Kong gateway operator

**Comment by DMaxter** [comment]
Can it be some kind of load balancer you are using? After that I'm out of ideas

**Comment by bharanitharanm** [comment]
I'm deploying in a K3S environment which has a default load balancer ServiceLB

**Comment by bharanitharanm** [comment]
To reproduce this issue,

Create Chart.yaml
```
apiVersion: v2
name: kong
version: "1.0.0"
dependencies:
  - name: kong
    version: 2.32.0
    repository: https://charts.konghq.com
```

Create values.yaml
```
kong:
  # DB-less mode
  env:
    database: "off"

  # Prepare for k8s Ingress manifests
  ingressController:
    enabled: true
    ingressClass: kong

  # There's an HTTP2 bug in Kong which creates
  # an excess of noise in the proxy logs.
  # The fix will be in Kong 2.8.2
  # https://github.com/Kong/kong/pull/8690
  admin:
    tls:
      parameters: []
```

Update the dependencies
```
helm dep up .
```

Install the helm chart
```
helm install kong .
```

Check the logs
```
kubectl logs deploy/kong-kong -c proxy
```


```
# status API log is logged every 3 seconds
127.0.0.1 - - [15/Apr/2025:10:47:18 +0000] "GET /status HTTP/1.1" 200 1179 "-" "Go-http-client/1.1"
127.0.0.1 - - [15/Apr/2025:10:47:21 +0000] "GET /status HTTP/1.1" 200 1179 "-" "Go-http-client/1.1"
127.0.0.1 - - [15/Apr/2025:10:47:24 +0000] "GET /status HTTP/1.1" 200 1179 "-" "Go-http-client/1.1"
127.0.0.1 - - [15/Apr/2025:10:47:27 +0000] "GET /status HTTP/1.1" 200 1179 "-" "Go-http-client/1.1"
127.0.0.1 - - [15/Apr/2025:10:47:30 +0000] "GET /status HTTP/1.1" 200 1179 "-" "Go-http-client/1.1"
127.0.0.1 - - [15/Apr/2025:10:47:33 +0000] "GET /status HTTP/1.1" 200 1179 "-" "Go-http-client/1.1"
127.0.0.1 - - [15/Apr/2025:10:47:36 +0000] "GET /status HTTP/1.1" 200 1179 "-" "Go-http-client/1.1"
```
