### ISSUE TITLE
Gateway API Traffic Splitting Not Working

### ISSUE THREAD

**Issue by ricfeatherstone-sky** [Kong/kong#14350]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

3.8.0

### Current Behavior

When I create the following deployments, exposed with an HTTP Route

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-blue
  name: simple-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-blue
  template:
    metadata:
      labels:
        app: simple-blue
    spec:
      containers:
        - image: docker.io/ricfeatherstone/blue-green
          name: simple-blue
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-blue
  name: simple-blue
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: simple-blue
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-green
  name: simple-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-green
  template:
    metadata:
      labels:
        app: simple-green
    spec:
      containers:
        - image: docker.io/ricfeatherstone/blue-green
          name: simple-green
          env:
            - name: RESP
              value: green
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-green
  name: simple-green
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: simple-green
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: simple-weighted
  namespace: default
spec:
  hostnames:
    - simple-weighted.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kong
      namespace: kong-external
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: simple-blue
          namespace: default
          port: 8080
          weight: 80
      matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - group: ""
          kind: Service
          name: simple-green
          namespace: default
          port: 8080
          weight: 20
      matches:
        - path:
            type: PathPrefix
            value: /
```

### Expected Behavior

I expect roughly 80% of requests to return blue and roughly 20% to return green.
What am I seeing is roughly a 50/50 split
