### ISSUE TITLE
hashOn.header with X-Session (hyphenated header name) does not work as expected

### ISSUE THREAD

**Issue by WatakOps** [Kong/kong#14447]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

3.9.0

### Current Behavior

We are using Kong with the following KongUpstreamPolicy:
```
apiVersion: configuration.konghq.com/v1beta1
kind: KongUpstreamPolicy
metadata:
  name: sticky-session-on-x-session-header
spec:
  algorithm: consistent-hashing
  hashOn:
    header: X-Session
```
Despite sending different values for the X-Session header (e.g., randomly generated UUIDs), Kong consistently routes traffic to the same upstream target, as if the hash was always the same.

### Expected Behavior

The consistent-hashing algorithm should correctly hash on any valid HTTP header name, including standard hyphenated ones such as X-Session and the traffic should be loadbalanced to all endpoints.

According to RFC 7230 section 3.2, header names like X-Session are completely valid.
This might indicate a parsing or normalization bug inside Kong’s upstream routing logic.

### Steps To Reproduce

1. Follow Kong Guide customizing-load-balancing to deploy Kong and demo pods:
https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/requests/customizing-load-balancing/
2. Use ingress instead of GatewayAPI
3. Create KongUpstreamPolicy
4. Get Ingress if needed
```
 export PROXY_IP=$(kubectl get svc --namespace kong kong-gateway-proxy -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
 echo $PROXY_IP
```
5. Test with hyphenated name
```
for i in {1..100}; do
        session_id=$(uuidgen)
  echo "X-Session: $session_id"
  curl -s -H "X-Session: $session_id" $PROXY_IP &
  echo
done
```
All traffic will be routed to the same pods

6. Remove "-" from header
```
spec:
  algorithm: consistent-hashing
  hashOn:
    header: XSession
```

7. Retry the curl without (-)
```
for i in {1..100}; do
        session_id=$(uuidgen)
  echo "XSession: $session_id"
  curl -s -H "XSession: $session_id" $PROXY_IP &
  echo
done
```
The traffic will be loadbalanced across endpoints as normally

### Anything else?

I have also open a bug in [Kong/kubernetes-ingress-controller](https://github.com/Kong/kubernetes-ingress-controller/issues/7393), sorry if it's not the right place
