### ISSUE TITLE
Kong deck fails with Error ```find any PEM data in certificate input```

### ISSUE THREAD

**Issue by ChiragR7** [Kong/kong#14496]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

3.8.0

### Current Behavior

I was going through documentation 

https://docs.konghq.com/deck/gateway/configuration/

First of all as specified in documentation 

`deck gateway ping --tls-client-cert-file /path/to/tls.crt --tls-client-cert-key /path/to/tls.key`

deck command does not have a argument called `--tls-client-cert-key` it should be `--tls-client-key-file`.

Fails in 

```
deck gateway ping  \
  --kong-addr https://127.0.0.1:8444 \
  --tls-client-cert-file $(pwd)/tls.crt \
  --tls-client-key-file $(pwd)/tls.key \
  --ca-cert-file $(pwd)/ca.crt
```

### Expected Behavior

It seems to be working with 

curl  --cacert ca.crt --cert tls.crt --key tls.key https://127.0.0.1:8444

### Steps To Reproduce

Run kong in hybrid mode 

Kong CP values.yaml

```
ingressController:
  enabled: false

postgresql:
  enabled: false

replicaCount: 2

image:
  repository: kong/kong-gateway
  tag: "3.8.0.0"

secretVolumes:
  - kong-clustering-tls

env:
  role: control_plane
  
  cluster_cert: /etc/secrets/kong-clustering-tls/tls.crt
  cluster_cert_key: /etc/secrets/kong-clustering-tls/tls.key
  cluster_ca_cert: /etc/secrets/kong-clustering-tls/ca.crt
  admin_ssl_cert: /etc/secrets/kong-clustering-tls/tls.crt
  admin_ssl_cert_key: /etc/secrets/kong-clustering-tls/tls.key
 
  database: postgres
  pg_database: kong
  pg_host: kong-cp-postgresql-postgresql-ha-pgpool.infra.svc.cluster.local
  pg_user: kong
  pg_ssl: "on"
  pg_password:
    valueFrom:
      secretKeyRef:
        name: kong-postgres-password
        key: password


  password: kong_admin_password


admin:
  enabled: true
  http:
    enabled: true
  type: ClusterIP
  tls:
    client:
      secretName: kong-clustering-tls


cluster:
  type: ClusterIP
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  type: ClusterIP

# These roles will be served by different Helm releases
proxy:
  enabled: false
```
Kong DP values.yaml

```
ingressController:
  enabled: false

postgresql:
  enabled: false


replicaCount: 2

image:
  repository: kong/kong-gateway
  tag: "3.8.0.0"

secretVolumes:
  - kong-clustering-tls


env:
  role: data_plane
  database: "off"

  cluster_control_plane: kong-cp-kong-cluster.infra.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry.infra.svc.cluster.local:8006

 
  lua_ssl_trusted_certificate: /etc/secrets/kong-clustering-tls/ca.crt
  cluster_cert: /etc/secrets/kong-clustering-tls/tls.crt
  cluster_cert_key: /etc/secrets/kong-clustering-tls/tls.key

enterprise:
  enabled: false
  license_secret: kong-enterprise-license

# The data plane handles proxy traffic only
proxy:
  enabled: true
  type: ClusterIP
  ingress:
    # Enable/disable exposure using ingress.
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    path: /
    tls: kong-clustering-cert
  tls:
    enabled: false
  http:
    enabled: true

admin:
  enabled: false

manager:
  enabled: false

cluster:
  telemetry:
    enabled: false
```

Install deck on mac 
```
brew tap kong/deck
brew install deck
```
