### ISSUE TITLE
Schema violation: config.include_consumer_groups: unknown field

### ISSUE THREAD

**Issue by mr-pascal** [Kong/kong#14531]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

3.9

### Current Behavior

When I try to apply our `acl` `KongPlugin`, it gets rejected by the admission webhook.

```yaml
# Example, taken from https://docs.konghq.com/hub/kong-inc/acl/3.6.x/how-to/consumer-groups/
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: acl-example
plugin: acl
config:
  include_consumer_groups: true
  allow:
  - admin
```

```sh
# kubectl apply -f tmp/dev/demo.yaml
Error from server: error when creating "tmp/dev/demo.yaml": admission webhook "validations.kong.konghq.com" denied the request: plugin failed schema validation: schema violation (config.include_consumer_groups: unknown field)
```

According to the [Changelog](https://docs.konghq.com/hub/kong-inc/acl/changelog/) the `config.include_consumer_groups` was introduced with the gateway 3.6.x.

> Kong Gateway 3.6.x
This plugin now includes the configuration parameter include_consumer_groups, which lets you specify whether Kong consumer groups can be added to allow and deny lists.

We are using the [Kong Helm chart](https://artifacthub.io/packages/helm/kong/kong) in version `2.4.7` which appears to use the Kong gateway version 3.9.

![Image](https://github.com/user-attachments/assets/26735edf-77cf-46db-a187-5734a25e7bda)
We don't understand why it's rejected since 3.9 is used and the feature was introduced in 3.6.

### Expected Behavior

When I apply the above YAML file, it should be created on the K8s cluster instead of being rejected by the admission webhook.

### Steps To Reproduce

1. Use the  [Kong Helm chart](https://artifacthub.io/packages/helm/kong/kong) in version `2.4.7`
2. Try to apply above YAML
3. Notice the rejection of the admission webhook.

### Anything else?

It doesn't seem to be only the admission webhook. Even when I disable it, it seems like the plugin can't be properly initialized:

```yaml
Events:
  Type     Reason                        Age                 From         Message
  ----     ------                        ----                ----         -------
  Warning  KongConfigurationApplyFailed  58s (x25 over 94s)  kong-client  invalid config.include_consumer_groups: unknown field

```
