### ISSUE TITLE
AI Proxy: no completion tokens stats when streaming enabled

### ISSUE THREAD

**Issue by peacand** [Kong/kong#14535]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.10

### Current Behavior

With the AI Proxy, if I'm making a chat/completions request to my service with streaming=True, the stats generated in the logs have the completion_tokens to 0 and no response logging. While I've actually got some tokens in response : 

Test request : 
`curl -N -X POST -H 'Content-Type: application/json' -v http://KONG_GW:8000/llm/chat/completions --data '{"model": "meta-llama/llama-4-maverick:free", "messages": [{"role": "user", "content": "what time is it?"}], "stream":true}'`
Response:
```
[....]
data: {"id":"gen-1747407129-yl70dmWsVlkp0fOxVO8A","provider":"Chutes","model":"meta-llama/llama-4-maverick:free","object":"chat.completion.chunk","created":1747407129,"choices":[{"index":0,"delta":{"role":"assistant","content":"."},"finish_reason":null,"native_finish_reason":null,"logprobs":null}]}

data: {"id":"gen-1747407129-yl70dmWsVlkp0fOxVO8A","provider":"Chutes","model":"meta-llama/llama-4-maverick:free","object":"chat.completion.chunk","created":1747407129,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":"stop","native_finish_reason":"stop","logprobs":null}]}

data: {"id":"gen-1747407129-yl70dmWsVlkp0fOxVO8A","provider":"Chutes","model":"meta-llama/llama-4-maverick:free","object":"chat.completion.chunk","created":1747407129,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null,"native_finish_reason":null,"logprobs":null}],"usage":{"prompt_tokens":15,"completion_tokens":169,"total_tokens":184,"prompt_tokens_details":null}}

data: [DONE]
```

Generated log : 

```
{
  "proxy": {
    "usage": {
      "total_tokens": 7,
      "time_per_token": 0,
      "prompt_tokens": 7,
      "completion_tokens": 0,
      "cost": 0
    },
    "meta": {
      "response_model": "meta-llama/llama-4-maverick:free",
      "plugin_id": "3e969f4d-a28e-4141-8809-999a48f0e89c",
      "request_model": "meta-llama/llama-4-maverick:free",
      "provider_name": "openai",
      "llm_latency": 75
    },
    "payload": {
      "request": "{\"model\": \"meta-llama/llama-4-maverick:free\", \"messages\": [{\"role\": \"user\", \"content\": \"what time is it?\"}], \"stream\":true}"
    }
  }
}

```

So the prompt_tokens is at 0 and the response payload is not logged.

If I'm doing the exact same test with streaming: false, I get the correct logs :

```
{
  "proxy": {
    "usage": {
      "total_tokens": 167,
      "time_per_token": 19.927631578947,
      "prompt_tokens": 15,
      "completion_tokens": 152,
      "cost": 0
    },
    "meta": {
      "response_model": "meta-llama/llama-4-maverick:free",
      "plugin_id": "3e969f4d-a28e-4141-8809-999a48f0e89c",
      "request_model": "meta-llama/llama-4-maverick:free",
      "provider_name": "openai",
      "llm_latency": 3029
    },
    "payload": {
      "request": "{\"model\": \"meta-llama/llama-4-maverick:free\", \"messages\": [{\"role\": \"user\", \"content\": \"what time is it?\"}], \"stream\":false}",
      "response": "\n         \n\n         \n\n         \n\n         \n\n         \n\n         \n{\"id\":\"gen-1747407226-2uDLhSjlCzrTp6AT8cr4\",\"provider\":\"Chutes\",\"model\":\"meta-llama/llama-4-maverick:free\",\"object\":\"chat.completion\",\"created\":1747407226,\"choices\":[{\"logprobs\":null,\"finish_reason\":\"stop\",\"native_finish_reason\":\"stop\",\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"I'm not capable of providing the current time as I don't have access to real-time information. However, I can suggest a few ways for you to find out the current time:\\n\\n1. **Check your device**: You can check the clock on your phone, computer, or watch.\\n2. **Ask a voice assistant**: If you have a smart speaker or a virtual assistant like Siri, Google Assistant, or Alexa, you can ask them for the current time.\\n3. **Look online**: You can search for \\\"current time\\\" or \\\"time now\\\" on a search engine like Google, and it will show you the current time in your location or UTC (Coordinated Universal Time).\\n\\nLet me know if there's anything else I can help you with!\",\"refusal\":null,\"reasoning\":null}}],\"usage\":{\"prompt_tokens\":15,\"completion_tokens\":152,\"total_tokens\":167,\"prompt_tokens_details\":null}}"
    }
  }
}

```

### Expected Behavior

The completion_tokens and response payload should be logged in case of streamed response

### Steps To Reproduce

Kong GW 3.10
Simple service with AI Proxy to OpenAI - streaming Allow 
Test chat/completions request with streaming:true

**Comment by chronolaw** [comment]
@oowl could you take a look? thanks.

**Comment by oowl** [comment]
@peacand Thank you very much for your feedback. We tried to reproduce your problem locally using Llamas but found that it could not be reproduced. Can you tell us about your method of reproducing?

**Comment by peacand** [comment]
Hi @oowl 

I'm using OpenRouter as backend LLM provider at the end. Here is the configuration 

**Service**
```
{
  "connect_timeout": 60000,
  "enabled": true,
  "host": "localhost",
  "id": "10b938f3-d672-4e3c-b49c-effc87011b64",
  "name": "dummy-service",
  "port": 32000,
  "protocol": "http",
  "read_timeout": 60000,
  "retries": 5,
  "write_timeout": 60000
}
```
**Route**
```
https_redirect_status_code: 426
id: 148953a2-80d4-477f-83dd-6bf8464afbc7
methods:
  - POST
name: llm-chat-completions
path_handling: v0
paths:
  - /llm/chat/completions
preserve_host: false
protocols:
  - http
  - https
regex_priority: 0
request_buffering: true
response_buffering: true
service:
  id: 10b938f3-d672-4e3c-b49c-effc87011b64
strip_path: true
```
**AI Proxy Plugin**
```
config:
  auth:
    allow_override: false
    aws_access_key_id: null
    aws_secret_access_key: null
    azure_client_id: null
    azure_client_secret: null
    azure_tenant_id: null
    azure_use_managed_identity: false
    gcp_service_account_json: null
    gcp_use_service_account: false
    header_name: Authorization
    header_value: >-
      Bearer
      <openrouter_api_key>
    param_location: null
    param_name: null
    param_value: null
  llm_format: openai
  logging:
    log_payloads: true
    log_statistics: true
  max_request_body_size: 8192000
  model:
    name: meta-llama/llama-4-maverick:free
    options:
      anthropic_version: null
      azure_api_version: '2023-05-15'
      azure_deployment_id: null
      azure_instance: null
      bedrock: null
      gemini: null
      huggingface: null
      input_cost: 300000
      llama2_format: null
      max_tokens: null
      mistral_format: null
      output_cost: 150000000
      temperature: 0.6
      top_k: null
      top_p: null
      upstream_path: /api/v1/chat/completions
      upstream_url: https://openrouter.ai/api/v1/chat/completions
    provider: openai
  model_name_header: true
  response_streaming: allow
  route_type: preserve
enabled: true
id: 3e969f4d-a28e-4141-8809-999a48f0e89c
name: ai-proxy
protocols:
  - grpc
  - grpcs
  - http
  - https
route:
  id: 148953a2-80d4-477f-83dd-6bf8464afbc7
service:
  id: 10b938f3-d672-4e3c-b49c-effc87011b64
```
**Plugin File Log**
```
config:
  custom_fields_by_lua: {}
  path: /tmp/ai.log
  reopen: false
enabled: true
id: 47833f4c-ce78-4dab-988a-3e1766e68d0c
name: file-log
protocols:
  - grpc
  - grpcs
  - http
  - https
route:
  id: 148953a2-80d4-477f-83dd-6bf8464afbc7
```

With that configuration, this curl command : 
`curl -N -X POST -H 'Content-Type: application/json' -v http://KONG_GW:8000/llm/chat/completions --data '{"model": "meta-llama/llama-4-maverick:free", "messages": [{"role": "user", "content": "what time is it?"}], "stream":true}'`
Generates a good response :
```
[...]
data: {"id":"gen-1747902518-zl1n4AaSWM1YhHRzdcom","provider":"Chutes","model":"meta-llama/llama-4-maverick:free","object":"chat.completion.chunk","created":1747902518,"choices":[{"index":0,"delta":{"role":"assistant","content":"-time"},"finish_reason":null,"native_finish_reason":null,"logprobs":null}]}

data: {"id":"gen-1747902518-zl1n4AaSWM1YhHRzdcom","provider":"Chutes","model":"meta-llama/llama-4-maverick:free","object":"chat.completion.chunk","created":1747902518,"choices":[{"index":0,"delta":{"role":"assistant","content":" information"},"finish_reason":null,"native_finish_reason":null,"logprobs":null}]}

data: {"id":"gen-1747902518-zl1n4AaSWM1YhHRzdcom","provider":"Chutes","model":"meta-llama/llama-4-maverick:free","object":"chat.completion.chunk","created":1747902518,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":"stop","native_finish_reason":"stop","logprobs":null}]}

data: {"id":"gen-1747902518-zl1n4AaSWM1YhHRzdcom","provider":"Chutes","model":"meta-llama/llama-4-maverick:free","object":"chat.completion.chunk","created":1747902518,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null,"native_finish_reason":null,"logprobs":null}],"usage":{"prompt_tokens":15,"completion_tokens":18,"total_tokens":33,"prompt_tokens_details":null}}

data: [DONE]
```

But the log generated in log file has an empty "completion_tokens" and "time per token" :
tail /tmp/ai.log | jq '.'
```
  "ai": {
    "proxy": {
      "usage": {
        "total_tokens": 7,
        "time_per_token": 0,
        "prompt_tokens": 7,
        "completion_tokens": 0,
        "cost": 0
      },
      "meta": {
        "response_model": "meta-llama/llama-4-maverick:free",
        "plugin_id": "3e969f4d-a28e-4141-8809-999a48f0e89c",
        "request_model": "meta-llama/llama-4-maverick:free",
        "provider_name": "openai",
        "llm_latency": 1247
      },
     
```

If I'm doing the same request but with streaming:false, the completion tokens works as expected : 
`curl -N -X POST -H 'Content-Type: application/json' -v http://KONG_GW:8000/llm/chat/completions --data '{"model": "meta-llama/llama-4-maverick:free", "messages": [{"role": "user", "content": "what time is it?"}], "stream":false}'`
tail /tmp/ai.log | jq '.'
```
  "ai": {
    "proxy": {
      "usage": {
        "total_tokens": 32,
        "time_per_token": 88.588235294118,
        "prompt_tokens": 15,
        "completion_tokens": 17,
        "cost": 0
      },
      "meta": {
        "response_model": "meta-llama/llama-4-maverick:free",
        "plugin_id": "3e969f4d-a28e-4141-8809-999a48f0e89c",
        "request_model": "meta-llama/llama-4-maverick:free",
        "provider_name": "openai",
        "llm_latency": 1506
      },
```

You should be able to reproduce the problem
