### ISSUE TITLE
Race condition(?) when running clustered in Kubernetes

### ISSUE THREAD

**Issue by DonMartin76** [Kong/kong#2125]
### Summary

At times, when running several (3+) Kong instances at once in a clustered environment inside Kubernetes, and I (for some reason or the other, like draining nodes) kill all associated containers/pods, it sometimes happens that I get into a "split brain" kind of cluster state: One Kong instance thinks it's alone in a cluster, while the other two think they make up a cluster of two (when checking inside the containers using the `kong` CLI).

It's not always reproducible, but once in a while this happens, and the effect is obviously that some changes done on the admin API do not propagate to the other "side", and that calls to the configured APIs are met with a 503 ("No API defined for...") instead of the real response.

The workaround for this is to not let Kubernetes start more than one Kong instance at once; if I scale up "slowly" (like every 5 seconds or so), this problem does not occur.

If I don't "restart" the entire Kong cluster at once, this does not occur, it seems to be some kind of race condition if two Kong instances both claim to be the "first" instance in the cluster. In cases this does not happen, everything works perfectly.

Is there something I might be doing wrong, something I can check, and/or do to make this not happen?

### Additional Details & Logs

- Kong 0.9.9
- Operating System: Official Docker image

**Comment by shashiranjan84** [comment]
@DonMartin76 Can you check what `cluster_listening_address` saved in the DB, you may have to log into the backing DB pod and query `nodes` table.

Also please try explicitly setting `KONG_CLUSTER_LISTEN` with <pod_ip:serf_port> like following template 

```
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-ssl
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: kong

---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: kong

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong-rc
        app: kong
    spec:
      containers:
      - name: kong
        image: mashape/kong:0.10.0rc3
        env:
          - name: KONG_PG_PASSWORD
            value: kong
          - name: KONG_PG_HOST
            value: postgres.default.svc.cluster.local
          - name: KONG_DNS_RESOLVER
            value: 10.100.0.10
          - name: KONG_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        command: [ "/bin/sh", "-c", "KONG_CLUSTER_ADVERTISE=$(KONG_HOST_IP):7946 KONG_NGINX_DAEMON='off' kong start && env" ]
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP
```
