### ISSUE TITLE
Allow JWT header `kid` to identify the credentials in use

### ISSUE THREAD

**Issue by Floby** [Kong/kong#2858]
### Summary

Currently, the JWT plugin looks at a configured claim (`iss` by default). I would like to have the key being used to sign the token to be specified as the [`kid`](https://tools.ietf.org/html/rfc7516#section-4.1.6) header. This seems like a incomplete implementation since this header is specifically designed for this use-case. If this is a feature that has a go, I'm happy to write a PR.

### Steps To Reproduce

1. Create an API
2. Enable the JWT plugin
3. Make a request to this API with a signed JWT with a kid header.

### Additional Details & Logs

- Kong version (`0.11`)
- Kong configuration (registered APIs/Plugins & configuration file)

```yaml
host: 'localhost:8001'
headers: []
apis:
  - name: Admin
    plugins:
      - name: jwt
        attributes:
          enabled: true
          config:
            claims_to_verify: {}
            key_claim_name: kid
            anonymous: ''
            secret_is_base64: false
            uri_param_names: {}
    attributes:
      uris:
        - /admin
      strip_uri: true
      preserve_host: false
      upstream_url: 'http://nginx-lb:8001'
      retries: 5
      upstream_connect_timeout: 60000
      upstream_read_timeout: 60000
      upstream_send_timeout: 60000
      https_only: false
      http_if_terminated: false
consumers:
  - username: Floby's app
    custom_id: floby
    acls: []
    credentials:
      - name: jwt
        attributes:
          algorithm: HS256
          key: floby-sym
          secret: salut
plugins: []
```
