### ISSUE TITLE
Kong on Docker does not pickup port information in upstream url while creating an api

### ISSUE THREAD

**Issue by feelgoodman** [Kong/kong#3046]
### Summary

Kong does not pickup port information in upstream url while creating an api. Defaults it to 80.

### Steps To Reproduce

1. Create Kong Docker image from official Kong:0.11.1
2. Create a new api with upstream url as "http://abc.com:8080".
3. Try opening the same on Kong and it will redirect you to "http://abc.com" and trim the port information or return error if port 80 is not accessible

### Additional Details & Logs

- Kong version: 0.11.1
- Kong error logs:
2017/11/22 15:54:31 [error] 60#0: *23789 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: kong, request: "GET /my-webapp HTTP/1.1", upstream: "http://172.18.0.2:80/", host: "localhost:39000"
- Kong configuration:
In docker-compose, the Kong container is called 'kong-gateway', and the upstream container is 'my-webapp-dist'
Python script to add API:
```
import requests

payload = {'name':'my-webapp','uris':'/my-webapp','methods':'GET,HEAD,POST','upstream_url':'http://my-webapp-dist:8080}'}
response = requests.post('http://kong-gateway:8001/apis/',data=payload)
assert response.status_code == 201
```
Relevant output from /apis:
`{"created_at":1511361399672,"strip_uri":true,"id":"6ad7a130-5094-486b-8a97-3f15c4d1e14a","name":"my-webapp","methods":["GET","HEAD","POST"],"http_if_terminated":false,"https_only":false,"upstream_url":"http:\/\/my-webapp-dist:8080}","uris":["\/my-webapp"],"preserve_host":false,"upstream_connect_timeout":60000,"upstream_read_timeout":60000,"upstream_send_timeout":60000,"retries":5}`
NOTE: If I exec into the kong-gateway container and run curl `http://172.18.0.2:8080`. The correct response is received from the upstream API
- Operating System: Linux

**Comment by feelgoodman** [comment]
This is the output from DIG, doesn't seem to mention ports:

```
dig my-webapp-dist

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7 <<>> my-webapp-dist
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55911
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;my-webapp-dist.	IN	A

;; ANSWER SECTION:
my-webapp-dist. 600	IN	A	172.18.0.2

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Thu Nov 23 09:57:07 UTC 2017
;; MSG SIZE  rcvd: 82
```
I was only running the upstream services in the same docker-compose file for easy local testing. The production upstream services will be outside of docker. I'll therefore set it up this way to avoid this issue

**Comment by feelgoodman** [comment]
so, I removed my-webapp from docker, and instead ran my webapp outside of docker, on my local machine, i.e. 172.0.18.1:38091. and updated Kong config:

`{"created_at":1511435237966,"strip_uri":true,"id":"8591ec6a-c47d-4a29-9b31-67444d678fc1","name":"cb-webapp","methods":["GET","HEAD","POST"],"http_if_terminated":false,"https_only":false,"upstream_url":"http:\/\/172.18.0.1:38091}","uris":["\/cb-webapp"],"preserve_host":false,"upstream_connect_timeout":60000,"upstream_read_timeout":60000,"upstream_send_timeout":60000,"retries":5}`

Still, it is proxing to port 80:

`2017/11/23 11:12:54 [error] 61#0: *1762 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: kong, request: "GET /cb-webapp HTTP/1.1", upstream: "http://172.18.0.1:80/", host: "localhost:39000"`

What is it that I need to configure in Docker to enable me to proxy to port 39081, instead of 80?

**Comment by kikito** [comment]
Hi,
When you run docker directly, there's an [option called `-p`](https://docs.docker.com/engine/reference/run/#expose-incoming-ports) which allows you to map ports between the docker image and the host. In our case it would look similar to:

```
docker run -d -p 123456:123456
```

That should map port 123456 of the docker image to port 123456 in the host.

If using docker-compose, there is a [section called `ports`](https://docs.docker.com/compose/compose-file/#ports) for it:

```
services:
  your-endpoint:
    image: xxx 
    ports:
      - "123456:123456"
    expose:
      - 
```

It is considered a good practice to inform about the ports that are docker container is listening to by using the [EXPOSE option](https://docs.docker.com/engine/reference/builder/#expose) (`expose` section in docker-compose)

**Comment by feelgoodman** [comment]
@kikito The API that I want Kong to proxy to is running on the host machine: 172.18.0.1:38091, which is what I have specified in the Kong config. But Kong errors because it tries to send the request to 172.18.0.1:80

I don't see how the exposed Docker ports re relevant to this, but this is my docker-compose for info:

```
version: '2.1'

services:

  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:latest
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  kong-gateway:
    image: my-company/my-company-kong
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
    ports:
      - 39000:8000
      - 39001:8001
      - 39443:8443
      - 39444:8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10

  configure-kong:
    build: configure-gateway/
    depends_on:
      kong-gateway:
        condition: service_healthy
```

Dockerfile for my-company/my-company-kong

```
FROM kong:0.11.1

EXPOSE 8000 8443 8001 7946

COPY wait-for-migrations.sh /wait-for-migrations.sh
RUN ["chmod", "+rx", "/wait-for-migrations.sh"]

CMD ./wait-for-migrations.sh kong-migration kong start
```
