### ISSUE TITLE
First request to Kong microservice shows higher latency

### ISSUE THREAD

**Issue by svenmueller** [Kong/kong#3367]
Hi,

We are seeing higher response times when issuing a request for the first time in a while to a registered microservice. The header value `X-Kong-Proxy-Latency` is much higher for the first request. I've see the documentation about the latency token header (https://getkong.org/docs/0.10.x/proxy/#5-response) but it's not clear to me what exactly happends here.

- why does the first request show a higher latency for `X-Kong-Proxy-Latency`? What exactly is done during this timespan?
- after what time does this happen again (some kind of cache invalidation maybe?)?
- how can we avoid this higher latency?

1st request:
```
$ curl -sv https://www.domain.com/endpoint 2>&1 | grep X-Kong
< X-Kong-Upstream-Latency: 4
< X-Kong-Proxy-Latency: 1798
```

subsequet requests:
```
$ curl -sv https://www.domain.com/endpoint 2>&1 | grep X-Kong
< X-Kong-Upstream-Latency: 2
< X-Kong-Proxy-Latency: 102
```

### Additional Details & Logs

- Kong version: 0.12.1
- Kong configuration (registered APIs/Plugins & configuration file)
```
    Environment:
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_NGINX_DAEMON: off
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: postgres
      KONG_PG_HOST: yyy.com
      KONG_PG_PASSWORD: XXX
      KONG_PG_PORT: 5432
      KONG_PG_SSL: true
      KONG_PG_SSL_VERIFY: false
      KONG_PG_USER: YYY
      KONG_SSL: on
      KONG_SSL_CERT: /ssl/cert.pem
      KONG_SSL_CERT_KEY: /ssl/cert.key
```
```
{"total":1,"data":[{"created_at":1518917520000,"config":{"methods":["GET","POST","PUT","DELETE"],"exposed_headers":["X-Auth-Token"],"max_age":3600,"origins":["*"],"headers":["Accept","Accept-Version","Content-Length","Content-MD5","Content-Type","Date","X-Auth-Token","Authorization"],"credentials":true,"preflight_continue":false},"id":"a1734dbf-f78c-4e24-96d9-2978f32528d2","enabled":true,"name":"cors"}]}
```

- Operating System: GKE/k8s, stable Helm chart (https://github.com/kubernetes/charts/tree/master/stable/kong)
