### ISSUE TITLE
Kong Helm Chart with TLS disabled does not work

### ISSUE THREAD

**Issue by StianOvrevage** [Kong/kong#3537]
### Summary

I'm deploying Kong to Kubernetes using the stable/kong Helm chart.

kong-dashboard refuses to communicate with Kong over HTTPS because of the self-signed TLS certificate.

For now, I want to deploy Kong with admin API on HTTP, not HTTPS.

### Steps To Reproduce

Works:
  1. `helm install --name kongssl stable/kong`
  2. Change Service Type to LoadBalancer using `kubectl patch`

Can access API on https://publicip:8444

Logs on pod say:
```
10.244.0.1 - - [14/Jun/2018:21:11:18 +0000] "GET / HTTP/1.1" 200 4859 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36"
10.244.0.1 - - [14/Jun/2018:21:11:19 +0000] "GET /status HTTP/1.1" 200 222 "-" "kube-probe/1.9"
```

Does not work:

  1. `helm install --name kong stable/kong --set admin.useTLS=false --set admin.servicePort=8001 --set admin.containerPort=8001`
  2. Change Service Type to LoadBalancer using `kubectl patch`

Can NOT access API on http://publicip:8001.

Logs on pod say:
```
10.244.0.1 - - [14/Jun/2018:21:11:38 +0000] "\x16\x03\x01\x00\x9B\x01\x00\x00\x97\x03\x03\xDD\xF3" 400 179 "-" "-"
10.244.0.1 - - [14/Jun/2018:21:11:47 +0000] "\x16\x03\x01\x00\x9B\x01\x00\x00\x97\x03\x031\x87\x13\x8B*l\xF3\x8B\x9E9\x97\x14\x8D\x0B*" 400 179 "-" "-"
```
(I cannot for sure say that (some of) these requests are generated by me or if they are just the periodic calls by kube-probe).

I CAN access port 8001 on the pod(container) when using `kubectl port-forward` directly to the container. In which case the logs look normal again:

```
127.0.0.1 - - [14/Jun/2018:21:15:13 +0000] "GET / HTTP/1.1" 200 4710 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36"
```

Extra info:
Patch command: `kubectl patch service kong-kong-admin --patch "$(cat ingress-lb-type-patch.yaml)"`
Contents of `ingress-lb-type-patch.yaml`:

```
spec:
  type: LoadBalancer
```

### Additional Details & Logs

- Kong version: 0.13
- Operating System: Kubernetes (Kong Docker image)

**Comment by tin4g** [comment]
- __check this comment__: `Line-16: # HTTPS traffic on the admin port\n# if set to false also set readinessProbe and livenessProbe httpGet scheme's to 'HTTP'`

- __patched values.yaml__:
```
# Specify Kong admin and proxy services configurations
admin:
  # If you want to specify annotations for the admin service, uncomment the following
  # line, add additional or adjust as needed, and remove the curly braces after 'annotations:'.
  annotations: {}
  #  service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

  # HTTPS traffic on the admin port
  # if set to false also set readinessProbe and livenessProbe httpGet scheme's to 'HTTP'
  useTLS: false
  servicePort: 8001
  containerPort: 8001
  # Kong admin service type
  type: ClusterIP
  # Set a nodePort which is available
  # nodePort: 32444

proxy:
  # If you want to specify annotations for the proxy service, uncomment the following
  # line, add additional or adjust as needed, and remove the curly braces after 'annotations:'.
  annotations: {}
  #  service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

  # HTTPS traffic on the proxy port
  useTLS: false
  servicePort: 8000
  containerPort: 8000
  type: ClusterIP
  # Set a nodePort which is available
  # nodePort: 32443

...

# readinessProbe for Kong pods
readinessProbe:
  httpGet:
    path: "/status"
    port: admin
    scheme: HTTP  # HTTPS
  initialDelaySeconds: 120
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5

# livenessProbe for Kong pods
livenessProbe:
  httpGet:
    path: "/status"
    port: admin
    scheme: HTTP  # HTTPS
  initialDelaySeconds: 180
  timeoutSeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 5
```
