### ISSUE TITLE
kong 0.13 with RDS  temporary failure in name resolution 

### ISSUE THREAD

**Issue by DevOpsRoot** [Kong/kong#3563]
Hello,

I use this kubernetes config file to deploy kong : 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong-rc
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:0.13
        env:
          - name : KONG_DATABASE
            value : postgres
          - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
          - name: KONG_PG_PASSWORD
            value: "*********"
          - name: KONG_PG_HOST
            value: "kongdbprod.**********.eu-west-3.rds.amazonaws.com"
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"
        ports:
        - name: admin
          containerPort: 8001
          hostPort: 8001
        - name: proxy
          containerPort: 8000
          hostPort: 8000
        - name: proxy-ssl
          containerPort: 8443
          hostPort: 8443
        - name: admin-ssl
          containerPort: 8444
          hostPort: 8444
      nodeSelector:
        zone-type: front
```
The kong database is an RDS PostgreSQL 9.5.2.

When i start the service like this : 
```
kubectl create -f kong.yml
```
i've got this error : 
```
prefix directory /usr/local/kong not found, trying to create it

2018/06/20 08:58:38 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:169: [postgres error] could not retrieve server_version: temporary failure in name resolution

stack traceback:

	[C]: in function 'error'

	/usr/local/share/lua/5.1/kong/init.lua:169: in function 'init'

	init_by_lua:3: in main chunk

nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:169: [postgres error] could not retrieve server_version: temporary failure in name resolution

stack traceback:

	[C]: in function 'error'

	/usr/local/share/lua/5.1/kong/init.lua:169: in function 'init'

	init_by_lua:3: in main chunk
```

Do you know where the error came from ? kong accept RDS database ?
