### ISSUE TITLE
Execute Admin API that require write to cassandra return 500

### ISSUE THREAD

**Issue by Dauto98** [Kong/kong#3709]
### Summary
When I deploy kong and cassandra into docker swarm using docker stack, all requests that require write to cassandra are returned 500 code, sometime 400 with the same error message `could not execute insertion query: [Write timeout] Operation timed out - received only 0 responses.`

### Steps To Reproduce
1. Create `docker-compose.yml`
```
version: "3.7"
services:
  cassandra:
    image: cassandra:3
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "9042:9042"
    networks:
      - kongNet
    volumes:
      - type: volume
        source: cassandra-kong-swarm
        target: /var/lib/cassandra
        volume:
          nocopy: true

  redis:
    image: redis
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "6379:6379"
    networks:
      - kongNet
    volumes:
      - type: volume
        source: redis-kong-swarm
        target: /data
        volume:
          nocopy: true

  kong-migration:
    image: kong
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    command: ["kong", "migrations", "up", "--v"]
    networks:
      - kongNet
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"

  kong:
    image: kong
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    healthcheck:
      test: "kong health"
      interval: 10s
      timeout: 5s
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    networks:
      - kongNet
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"

networks:
  kongNet:
    name: kong-swarm

volumes:
  cassandra-kong-swarm:
  redis-kong-swarm:
```
redis is used for my custom plugin
2. deploy using Docker stack
3. Execute any admin api that require write to cassandra
E.g: `curl -i -X POST --url http://localhost:8001/services/ --data 'name=test-writing' --data 'url=https://google.com'`
Response
```
HTTP/1.1 500 Internal Server Error
Date: Thu, 16 Aug 2018 10:12:04 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.0
Content-Length: 43

{"message":"An unexpected error occurred"}
```
Error log in `/user/local/kong/logs/error.log` file
```
2018/08/16 10:12:04 [error] 60#0: *181 [lua] responses.lua:121: handler(): [nil] could not execute insertion query: [Write timeout] Operation timed out - received only 0 responses., client: 10.255.0.2, server: kong_admin, request: "POST /services/ HTTP/1.1", host: "localhost:8001"
```

### Additional Details & Logs
- When I emit request to admin API and get 500, cassandra log this out
```
INFO  [Native-Transport-Requests-2] 2018-08-16 10:12:02,728 OutboundTcpConnection.java:108 - OutboundTcpConnection using coalescing strategy DISABLED
```
- Kong version: 0.14.0
- Kong configuration
```
{
   "plugins":{
      "enabled_in_cluster":[

      ],
      "available_on_server":{
         "response-transformer":true,
         "oauth2":true,
         "acl":true,
         "correlation-id":true,
         "pre-function":true,
         "jwt":true,
         "cors":true,
         "ip-restriction":true,
         "basic-auth":true,
         "key-auth":true,
         "rate-limiting":true,
         "request-transformer":true,
         "http-log":true,
         "file-log":true,
         "hmac-auth":true,
         "ldap-auth":true,
         "datadog":true,
         "tcp-log":true,
         "zipkin":true,
         "post-function":true,
         "request-size-limiting":true,
         "bot-detection":true,
         "syslog":true,
         "loggly":true,
         "azure-functions":true,
         "udp-log":true,
         "response-ratelimiting":true,
         "aws-lambda":true,
         "statsd":true,
         "prometheus":true,
         "request-termination":true
      }
   },
   "tagline":"Welcome to kong",
   "configuration":{
      "plugins":[
         "bundled"
      ],
      "admin_ssl_enabled":true,
      "lua_ssl_verify_depth":1,
      "trusted_ips":{

      },
      "prefix":"\/usr\/local\/kong",
      "loaded_plugins":{
         "response-transformer":true,
         "request-termination":true,
         "prometheus":true,
         "ip-restriction":true,
         "pre-function":true,
         "jwt":true,
         "cors":true,
         "statsd":true,
         "basic-auth":true,
         "key-auth":true,
         "ldap-auth":true,
         "aws-lambda":true,
         "http-log":true,
         "response-ratelimiting":true,
         "hmac-auth":true,
         "request-size-limiting":true,
         "datadog":true,
         "tcp-log":true,
         "zipkin":true,
         "post-function":true,
         "bot-detection":true,
         "acl":true,
         "loggly":true,
         "syslog":true,
         "azure-functions":true,
         "udp-log":true,
         "file-log":true,
         "request-transformer":true,
         "correlation-id":true,
         "rate-limiting":true,
         "oauth2":true
      },
      "cassandra_username":"kong",
      "admin_ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.csr",
      "ssl_cert_key":"\/usr\/local\/kong\/ssl\/kong-default.key",
      "admin_ssl_cert_key":"\/usr\/local\/kong\/ssl\/admin-kong-default.key",
      "dns_resolver":{

      },
      "pg_user":"kong",
      "mem_cache_size":"128m",
      "cassandra_data_centers":[
         "dc1:2",
         "dc2:3"
      ],
      "nginx_admin_directives":{

      },
      "custom_plugins":{

      },
      "pg_host":"127.0.0.1",
      "nginx_acc_logs":"\/usr\/local\/kong\/logs\/access.log",
      "proxy_listen":[
         "0.0.0.0:8000",
         "0.0.0.0:8443 ssl"
      ],
      "client_ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt",
      "ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key",
      "dns_no_sync":false,
      "db_update_propagation":0,
      "nginx_err_logs":"\/usr\/local\/kong\/logs\/error.log",
      "cassandra_port":9042,
      "dns_order":[
         "LAST",
         "SRV",
         "A",
         "CNAME"
      ],
      "dns_error_ttl":1,
      "headers":[
         "server_tokens",
         "latency_tokens"
      ],
      "dns_stale_ttl":4,
      "nginx_optimizations":true,
      "database":"cassandra",
      "pg_database":"kong",
      "nginx_worker_processes":"auto",
      "lua_package_cpath":"",
      "admin_acc_logs":"\/usr\/local\/kong\/logs\/admin_access.log",
      "lua_package_path":".\/?.lua;.\/?\/init.lua;",
      "nginx_pid":"\/usr\/local\/kong\/pids\/nginx.pid",
      "upstream_keepalive":60,
      "cassandra_contact_points":[
         "cassandra"
      ],
      "client_ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr",
      "proxy_listeners":[
         {
            "ssl":false,
            "ip":"0.0.0.0",
            "proxy_protocol":false,
            "port":8000,
            "http2":false,
            "listener":"0.0.0.0:8000"
         },
         {
            "ssl":true,
            "ip":"0.0.0.0",
            "proxy_protocol":false,
            "port":8443,
            "http2":false,
            "listener":"0.0.0.0:8443 ssl"
         }
      ],
      "proxy_ssl_enabled":true,
      "admin_access_log":"logs\/admin_access.log",
      "ssl_ciphers":"ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
      "enabled_headers":{
         "latency_tokens":true,
         "X-Kong-Proxy-Latency":true,
         "Via":true,
         "server_tokens":true,
         "Server":true,
         "X-Kong-Upstream-Latency":true,
         "X-Kong-Upstream-Status":false
      },
      "cassandra_ssl":false,
      "ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr",
      "db_resurrect_ttl":30,
      "client_max_body_size":"0",
      "cassandra_consistency":"ONE",
      "db_cache_ttl":0,
      "admin_error_log":"logs\/error.log",
      "pg_ssl_verify":false,
      "dns_not_found_ttl":30,
      "pg_ssl":false,
      "client_ssl":false,
      "db_update_frequency":5,
      "cassandra_repl_strategy":"SimpleStrategy",
      "nginx_kong_conf":"\/usr\/local\/kong\/nginx-kong.conf",
      "cassandra_repl_factor":1,
      "nginx_http_directives":[
         {
            "value":"prometheus_metrics 5m",
            "name":"lua_shared_dict"
         }
      ],
      "error_default_type":"text\/plain",
      "kong_env":"\/usr\/local\/kong\/.kong_env",
      "real_ip_header":"X-Real-IP",
      "dns_hostsfile":"\/etc\/hosts",
      "admin_listeners":[
         {
            "ssl":false,
            "ip":"0.0.0.0",
            "proxy_protocol":false,
            "port":8001,
            "http2":false,
            "listener":"0.0.0.0:8001"
         },
         {
            "ssl":true,
            "ip":"0.0.0.0",
            "proxy_protocol":false,
            "port":8444,
            "http2":false,
            "listener":"0.0.0.0:8444 ssl"
         }
      ],
      "admin_ssl_cert":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt",
      "ssl_cert":"\/usr\/local\/kong\/ssl\/kong-default.crt",
      "proxy_access_log":"logs\/access.log",
      "admin_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.key",
      "cassandra_ssl_verify":false,
      "cassandra_lb_policy":"RoundRobin",
      "ssl_cipher_suite":"modern",
      "real_ip_recursive":"off",
      "proxy_error_log":"logs\/error.log",
      "client_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key",
      "nginx_daemon":"off",
      "anonymous_reports":true,
      "cassandra_timeout":5000,
      "nginx_proxy_directives":{

      },
      "pg_port":5432,
      "log_level":"notice",
      "client_body_buffer_size":"8k",
      "cassandra_schema_consensus_timeout":10000,
      "lua_socket_pool_size":30,
      "admin_ssl_cert_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt",
      "cassandra_keyspace":"kong",
      "ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt",
      "nginx_conf":"\/usr\/local\/kong\/nginx.conf",
      "admin_listen":[
         "0.0.0.0:8001",
         "0.0.0.0:8444 ssl"
      ]
   },
   "version":"0.14.0",
   "node_id":"f2158119-935d-4632-a4d9-c71e777dbe8d",
   "lua_version":"LuaJIT 2.1.0-beta3",
   "prng_seeds":{
      "pid: 57":224168416925,
      "pid: 58":122157135228,
      "pid: 60":741091350145,
      "pid: 59":453772253251
   },
   "timers":{
      "pending":4,
      "running":0
   },
   "hostname":"d3f48f199f1e"
}
```
- Operating system: Ubuntu 16.04
