### ISSUE TITLE
Custom plugin schema value changes seem to not invalidate and properly apply across worker processes Kong 1.0

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#4161]
### Summary

Take this plugin for instance:
https://github.com/Optum/kong-response-size-limiting 

I am installing it just from Github source at the moment(haven't undated it on luarocks yet) like so:
```
RUN git clone https://github.com/Optum/kong-response-size-limiting.git /usr/local/share/lua/5.1/kong/plugins/kong-response-size-limiting &&\
    find /usr/local/share/lua/5.1/kong/plugins/kong-response-size-limiting -type f -maxdepth 1 -delete &&\
    cd /usr/local/share/lua/5.1/kong/plugins/kong-response-size-limiting &&\
    mv src/* . &&\
    rm -r src
```

I am then launching Kong with the schema value set to say a 100 mb limit. Running a few tx calls, plugin seems great right? Working fine. 

Then I go ahead and patch the plugin to say 0 or something for mb size against back-ends that return a content length to force the error situation. Run more requests, change it back and forth occasionally every 10-15 minutes

I am noticing some worker processes apply the conf change while others miss it. I made the change almost 8 minutes ago now and most workers did not pick up the change:

I send requests and see some responses like this(Backend response not rejected):
```
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Server: BaseHTTP/0.3 Python/2.7.5
Date: Mon, 07 Jan 2019 07:59:31 GMT
optum-cid-ext: 46a1aebb-de7d-48fb-bf5e-4c111d8bce07#24514 (coorelation-id worker process uuid # count)
X-Upstream-Latency: 6
X-Proxy-Latency: 0
Set-Cookie: 9b2731b6f344dac3aa25878b9b1193ea=a62016330b85f2308f810753eb2d790b; path=/; HttpOnly; Secure

None
```

Others throwing the rejection(Backend response rejected):
```
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Server: BaseHTTP/0.3 Python/2.7.5
Date: Mon, 07 Jan 2019 08:00:49 GMT
optum-cid-ext: f5ef5d19-c5f1-475e-a0c7-4a0b023a9dd0#24503(coorelation-id worker process uuid # count)
X-Upstream-Latency: 6
X-Proxy-Latency: 1
Set-Cookie: 9b2731b6f344dac3aa25878b9b1193ea=a62016330b85f2308f810753eb2d790b; path=/; HttpOnly; Secure

{"message": "Response size limit exceeded"}
```

Kinda arbitrary which workers picked up the change vs didn't, I run 6 workers and seems like 1 of the 6 picked up the change, and the rest still have not(maybe the worker that recieved the admin api call patch does invalidate, while others don't pickup an event around it?), going on 10 minutes of running(I waited like 20 and still didn't fix themselves so I gave up waiting to see if it would occur). I am not even actively load testing either, just clicking submit manually trying to see if it ever corrects itself, so far the workers have not.

### Steps To Reproduce

1. Enable plugin I mentioned above globally, set schema to 100mb

2. Send a few requests , toggle the schema value to 0 or 100 back and forth while doing requests occasionally to hit various worker processes in between your changes, if your environment behaves like mine its behavior is very obvious of them not picking up the change at all.

I will note when Kong comes up initially all worker processes and the plugin details are imported properly, it executes with the values stored and pulled from the db. Problem only starts occurring after changes are made while the node is live so that points to invalidation logic/worker event notification problems me thinks. 

### Additional Details & Logs

- Kong version 1.0
- Kong env:
```
 - env:
        - name: KONG_LOG_LEVEL
          value: notice
        - name: KONG_PROXY_ACCESS_LOG
          value: 'off'
        - name: KONG_ADMIN_ACCESS_LOG
          value: 'off'
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ANONYMOUS_REPORTS
          value: 'off'
        - name: KONG_PROXY_LISTEN
          value: '0.0.0.0:8000, 0.0.0.0:8443 ssl http2'
        - name: KONG_ADMIN_LISTEN
          value: '0.0.0.0:8001'
        - name: KONG_MEM_CACHE_SIZE
          value: 1m
        - name: KONG_SSL_CERT
          value: /usr/local/kong/ssl/kongcert.crt
        - name: KONG_SSL_CERT_DER
          value: /usr/local/kong/ssl/kongcertder.der
        - name: KONG_SSL_CERT_KEY
          value: /usr/local/kong/ssl/kongprivatekey.key
        - name: KONG_CLIENT_SSL
          value: 'off'
        - name: KONG_UPSTREAM_KEEPALIVE
          value: '0'
        - name: KONG_HEADERS
          value: latency_tokens
        - name: KONG_REAL_IP_HEADER
          value: X-Real-IP
        - name: KONG_REAL_IP_RECURSIVE
          value: 'off'
        - name: KONG_CLIENT_MAX_BODY_SIZE
          value: 1000m
        - name: KONG_CLIENT_BODY_BUFFER_SIZE
          value: 20m
        - name: KONG_ERROR_DEFAULT_TYPE
          value: text/plain
        - name: KONG_DATABASE
          value: cassandra
        - name: KONG_PG_SSL
          value: 'off'
        - name: KONG_CASSANDRA_PORT
          value: '9042'
        - name: KONG_CASSANDRA_KEYSPACE
          value: kong_dev
        - name: KONG_CASSANDRA_TIMEOUT
          value: '5000'
        - name: KONG_CASSANDRA_SSL
          value: 'on'
        - name: KONG_CASSANDRA_SSL_VERIFY
          value: 'on'
        - name: KONG_CASSANDRA_USERNAME
          value: *****
        - name: KONG_CASSANDRA_PASSWORD
          value: *****
        - name: KONG_CASSANDRA_CONSISTENCY
          value: LOCAL_QUORUM
        - name: KONG_CASSANDRA_LB_POLICY
          value: RequestDCAwareRoundRobin
        - name: KONG_CASSANDRA_LOCAL_DATACENTER
          value: DC2
        - name: KONG_DB_UPDATE_FREQUENCY
          value: '5'
        - name: KONG_DB_UPDATE_PROPAGATION
          value: '5'
        - name: KONG_DB_CACHE_TTL
          value: '0'
        - name: KONG_DNS_HOSTSFILE
          value: /etc/hosts
        - name: KONG_DNS_STALE_TTL
          value: '4'
        - name: KONG_DNS_NOT_FOUND_TTL
          value: '30'
        - name: KONG_DNS_ERROR_TTL
          value: '1'
        - name: KONG_DNS_NO_SYNC
          value: 'off'
        - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
          value: /usr/local/kong/ssl/kongcert.pem
        - name: KONG_LUA_SSL_VERIFY_DEPTH
          value: '3'
        - name: KONG_LUA_SOCKET_POOL_SIZE
          value: '30'
        - name: SPLUNK_HOST
          value: gateway-dev-core-dc2.company.com
        - name: KONG_CASSANDRA_CONTACT_POINTS
          value: 'server00466,server00467,server00468,server00469,server00470,server00471'
        - name: KONG_DNS_ORDER
          value: 'LAST,SRV,A,CNAME'
        - name: KONG_PLUGINS
          value: >-
            zipkin,kong-error-log,kong-oidc-implicit-token,kong-response-size-limiting,request-transformer,kong-service-virtualization,kong-cluster-drain,kong-upstream-jwt,kong-splunk-log,kong-spec-expose,kong-path-based-routing,kong-oidc-multi-idp,correlation-id,oauth2,statsd,jwt,rate-limiting,acl,request-size-limiting,request-termination,cors
```
- Docker-Kong Alpine 3.6
