### ISSUE TITLE
Kong 1.0.0 docker can't proxy to port 80

### ISSUE THREAD

**Issue by timpamungkas** [Kong/kong#4173]
### Summary

I can't  bind kong proxy listen to port 80 using docker-compose.
Got this message on kong logs   
`nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)`

### Steps To Reproduce
Create kong container using docker-compose

```
  kong:
    container_name: kong
    image: kong:latest
    restart: always
    networks:
      - kong-net
    environment:
      KONG_PG_HOST: kong-database
      KONG_PROXY_LISTEN: 0.0.0.0:80
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 30s
      timeout: 3s
      retries: 10
    ports:
      - "8001:8001"
      - "8444:8444"
      - "80:80"
      - "443:443"
```

### Additional Details & Logs
Port 80 is free
