### ISSUE TITLE
kong:1.0.1-centos can not start

### ISSUE THREAD

**Issue by nnsay** [Kong/kong#4223]
### Summary
the docker image(kong:1.0.1-centos) of kong can not start or make test

### Steps To Reproduce

1. edit the docker-compose.yaml
2. docker-compose up
3. docker exec -i -t kong bash
4. make test

### Additional Details & Logs

- Kong version (`$ kong version`): 1.0.1
- Kong debug-level startup logs (`$ kong start --vv`): 
[root@c94d56e3649c plugins]# kong start --vv
/usr/local/openresty/nginx/sbin/nginx: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
- Operating system: 
I use the kong:1.0.1-centos docker image and docker-compose for testing
dockerfile:
```
FROM kong:1.0.1-centos
RUN rpm -ivh https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm \
  && yum -y install epel-release \
  && yum -y install gcc unzip nodejs npm \
  && npm install -g nodemon --registry=https://registry.npm.taobao.org \
  && luarocks install busted 2.0.rc12-1 \
  && luarocks install luacov 0.12.0-1

# Set resty path for tests shell  
ENV PATH="/usr/local/openresty/bin:${PATH}"

CMD nodemon -L --watch /plugins --watch /etc/kong --ext lua,rockspec,yml --exec 'cd /plugins && luarocks make --local'
```
docker-compose.yaml:
```
services:
  # Kong Database
  kong-database:
    image: postgres:9.6
    ports:
      - 5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  # Redis for tests
  redis:
    image: redis:3.2
    ports:
      - 6379

  # Kong
  kong:
    build: kong/ ## see the dockerfile
    restart: always
    links:
      - kong-database:kong-database
      - redis:redis
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 7946:7946
      - 7946:7946/udp
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - TZ=Asia/Shanghai
    depends_on:
      - kong-database
      - redis
    volumes:
      - ./config:/etc/kong/
      - ./plugins:/plugins
```
