### ISSUE TITLE
Kong get stuck on response

### ISSUE THREAD

**Issue by Gaspechak** [Kong/kong#4322]
### Summary
After setting up Kong with DigitalOcean managed database, apparently everything is working well, the connection with database is working and i already executed kong migrations bootstrap.
The stack is up and running, all the necessary ports are open and the service logs shows that kong is running but when i send a request to him, the response never comes, only when i remove the stack.

### Steps To Reproduce
1. docker stack deploy -c docker-compose.yml
```yml
version: "3.5" 
services:
  kong:
      image: kong:1.0.3-alpine
      command: kong start --run-migrations --vv
      volumes:
        - /root/apps/secrets:/root/apps/secrets
      environment:
        - KONG_PG_USER=kong
        - KONG_PG_DATABASE=kong
        - KONG_PG_PASSWORD=password123
        - KONG_DATABASE=postgres
        - KONG_PG_HOST=dohost
        - KONG_PG_PORT=25060
        - KONG_PG_SSL=true
        - KONG_PG_SSL_VERIFY=true
        - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/root/apps/secrets/ca-certificate.pem
      networks:
        - kong
      ports:
        - "8000:8000"
        - "8001:8001"
        - "8443:8443"
        - "8444:8444"
networks:   
 kong:     
  driver: overlay     
  attachable: true
```
This is a bug with kong?
Maybe with DO managed database? 
or i'm missing something?

The kong logs show's nothing:
```
[debug] searching for OpenResty 'nginx' executable
[debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.2'
[debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
```

**Comment by Gaspechak** [comment]
Ok, after digging a lot, turns out that kong fails trying to read the ca-certificate because its on /root folder of the container.

Then i changed that:
```yml
volumes:
        - /root/apps/secrets:/root/apps/secrets
 environment:
        - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/root/apps/secrets/ca-certificate.pem
```

to that:
```yml
volumes:
        - /root/apps/secrets:/usr/local/kong/secrets
 environment:
        - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/usr/local/kong/secrets/ca-certificate.pem
```
then everything is working fine, its not a bug.
