### ISSUE TITLE
database dns error

### ISSUE THREAD

**Issue by sunnoy** [Kong/kong#4536]
### Summary

database dns error

### Steps To Reproduce

1. install kong ingress  in kubernets use `kubectl apply -f https://bit.ly/kong-ingress`
2. look the kong proxy logs 

```bash
2019/04/24 04:10:57 [warn] 35#0: *11217 [lua] connector.lua:288: unable to clean expired rows from postgres database ([toip() name lookup failed]: dns server error: 3 name error), context: ngx.timer
```

3. the containers logs 

```bash
[root@kong-6d46d587c5-9rr87 /]# nslookup postgres.kong
Server:		10.68.0.2
Address:	10.68.0.2#53

Name:	postgres.kong.svc.cluster.local
Address: 10.68.152.48
```

### Additional Details & Logs

- Kong version (`1.1`)
- Kong error logs
```bash
2019/04/24 04:10:57 [warn] 35#0: *11217 [lua] connector.lua:288: unable to clean expired rows from postgres database ([toip() name lookup failed]: dns server error: 3 name error), context: ngx.timer
```
- Kong configuration

```yaml
# Deployment kong file
        - name: KONG_PG_HOST
          value: postgres.kong
        - name: KONG_PG_PASSWORD
          value: kong
```

**Comment by sunnoy** [comment]
if the env `KONG_PG_HOST ` is postgres service ip ,all thins is ok !

**Comment by hbagdi** [comment]
This might happen initially as the service is being installed and there are not endpoints for the `postgres.kong` service but this error should resolve itself (with kong-proxy pod restarting) once the postgres pod is up and running.

Do you see the problem being resolved after a couple of pod restarts?

**Comment by sunnoy** [comment]
its not ,the https://bit.ly/kong-ingress has include postgres installed.

and i have give KONG_PG_HOST the postgres service ip,and to test kong 

when the upstream is the www domain such as www.google.com ,it can proxy.

when the upstream is the service in kubernetes,such as service-apollo-portal-server.sre, it wall get error

the proxy service give 

```bash
{
    "message": "name resolution failed"
}
```

log 

```bash
2019/04/24 07:20:02 [error] 36#0: *16648 [lua] balancer.lua:822: execute(): [dns] dns server error: 3 name error. Tried: ["(short)service-apollo-portal-server.sre:(na) - cache-miss",

"service-apollo-portal-server.sre.default.svc.cluster.local.:33 - cache-miss/scheduled/querying/dns server error: 3 name error",

"service-apollo-portal-server.sre.svc.cluster.local.:33 - cache-miss/scheduled/querying/1:service-apollo-portal-server.sre.svc.cluster.local removed/33:service-apollo-portal-server.sre.svc.cluster.local removed/dns client error: 101 empty record received",

"service-apollo-portal-server.sre.cluster.local.:33 - cache-miss/scheduled/querying/dns server error: 3 name error",

"service-apollo-portal-server.sre:33 - cache-miss/scheduled/querying/dns server error: 3 name error",

"service-apollo-portal-server.sre.default.svc.cluster.local.:1 - cache-miss/scheduled/querying/dns server error: 3 name error",

"service-apollo-portal-server.sre.svc.cluster.local.:1 - cache-miss/scheduled/querying/1:service-apollo-portal-server.sre.svc.cluster.local removed/dns client error: 101 empty record received",

"service-apollo-portal-server.sre.cluster.local.:1 - cache-miss/scheduled/querying/dns server error: 3 name error",

"service-apollo-portal-server.sre:1 - cache-miss/scheduled/querying/dns server error: 3 name error",

"service-apollo-portal-server.sre.default.svc.cluster.local.:5 - cache-miss/scheduled/querying/dns server error: 3 name error",

"service-apollo-portal-server.sre.svc.cluster.local.:5 - cache-miss/scheduled/querying/dns client error: 101 empty record received",

"service-apollo-portal-server.sre.cluster.local.:5 - cache-miss/scheduled/querying/dns server error: 3 name error",

"service-apollo-portal-server.sre:5 - cache-miss/scheduled/querying/dns server error: 3 name error"], client: 172.77.0.0, server: kong, request: "GET / HTTP/1.1", host: "apollo.com"
```

and the coredns log . the coredns container ip is 172.77.1.161 

```bash
2019-04-24T08:26:28.639Z [ERROR] plugin/errors: 2 service-apollo-portal-server.sre. SRV: read udp 172.77.1.161:52284->183.60.82.98:53: i/o timeout
2019-04-24T08:26:30.640Z [ERROR] plugin/errors: 2 service-apollo-portal-server.sre. SRV: read udp 172.77.1.161:38606->183.60.83.19:53: i/o timeout
2019-04-24T08:31:36.213Z [ERROR] plugin/errors: 2 service-apollo-portal-server.sre. A: read udp 172.77.1.161:49224->183.60.82.98:53: i/o timeout
2019-04-24T08:31:40.219Z [ERROR] plugin/errors: 2 service-apollo-portal-server.sre. CNAME: read udp 172.77.1.161:36468->183.60.83.19:53: i/o timeout
```


i have no idea

**Comment by sunnoy** [comment]
the kuberntes svc

```bash
kk-kong-proxy                        NodePort    10.68.210.112   <none>        80:25730/TCP,443:29140/TCP   158m
kk-postgresql                        ClusterIP   10.68.55.2      <none>        5432/TCP                     158m
kk-postgresql-headless               ClusterIP   None            <none>        5432/TCP                     158m
```
the deployment config

```yaml
        - name: KONG_PG_HOST
          value: kk-postgresql
```

kong log

```bash
172.77.2.1 - - [24/Apr/2019:08:53:18 +0000] "GET /status HTTP/1.1" 200 206 "-" "kube-probe/1.13"
2019/04/24 08:53:28 [error] 36#0: *888 [lua] kong.lua:111: fn(): failed to connect to PostgreSQL during /status endpoint check: [PostgreSQL error] [toip() name lookup failed]: dns server error: 3 name error, client: 172.77.2.1, server: kong_admin, request: "GET /status HTTP/1.1", host: "172.77.2.119:8444"
172.77.2.1 - - [24/Apr/2019:08:53:28 +0000] "GET /status HTTP/1.1" 200 206 "-" "kube-probe/1.13"
^[2019/04/24 08:53:38 [error] 36#0: *1009 [lua] kong.lua:111: fn(): failed to connect to PostgreSQL during /status endpoint check: [PostgreSQL error] [toip() name lookup failed]: dns server error: 3 name error, client: 172.77.2.1, server: kong_admin, request: "GET /status HTTP/1.1", host: "172.77.2.119:8444"
```

nslookup database

```bash
nslookup kk-postgresql
nslookup: can't resolve '(null)': Name does not resolve

Name:      kk-postgresql
Address 1: 10.68.55.2 kk-postgresql.default.svc.cluster.local
```

**Comment by sunnoy** [comment]
i use chart install kong

```bash
NAME       	CHART VERSION	APP VERSION	DESCRIPTION
stable/kong	0.9.9        	1.1        	The Cloud-Native Ingress and Service Mesh for APIs and Mi...
```

**Comment by sunnoy** [comment]
and it can work ok in docker-compose install 

```yaml
version: "3"

networks:
 kong-net:
  driver: bridge

services:
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:latest
    command: [ "/bin/sh", "-c", "kong migrations bootstrap" ]
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
    links:
      - kong-database
    depends_on:
      - kong-database

  kong:
    image: kong:latest
    restart: always
    networks:
      - kong-net
    environment:
      KONG_PG_HOST: kong-database
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"
```
i misunderstand why it can give error in kubernetes
