### ISSUE TITLE
Deploying using a PG Dump file

### ISSUE THREAD

**Issue by anthonyliriano** [Kong/kong#4584]
### Summary

What are the best practices for disaster recovery when using postgres? For example, if I'm creating postgres dump files periodically, how can I quickly spin up a Kong instance referencing one these backup files ?

### Additional Details & Logs

- Kong version 1.1

**Comment by hbagdi** [comment]
You could restore the pg_dump file into a different Postgresql server and then simply point Kong to the new database.

Have you considered using Kong's declarative configuration `kong config db_import` to load a declarative configuration file into a new database?

I'll also add a shameless plug for [decK](https://github.com/hbagdi/deck), which lets you export, import and sync configuration to Kong.

**Comment by cilindrox** [comment]
@hbagdi problem with the current implementation of `db_import` is that it requires a running kong instance, so it's not suitable for initcontainers or scenarios where you'd like to boot kong into a working state. This makes the built-in tools kinda useless on config-as-code scenarios vs approaches like decK.

**Comment by hbagdi** [comment]
> @hbagdi problem with the current implementation of db_import is that it requires a running kong instance, so it's not suitable for initcontainers or scenarios where you'd like to boot kong into a working state.

That doesn't sound correct. You can run `db_import` even if there is no Kong running. All it needs is that the DB is up and running and database migrations are up to date.

**Comment by cilindrox** [comment]
Here's a quick way to repro:

```yaml
# docker-compose.yml
version: '3.7'

services:
  postgres:
    image: postgres:11.3-alpine
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  bootstrap:
    image: kong:1.1.2-alpine@sha256:550eaa94080dec3dd0c369d124a1e5d1e8cc70b10584d230d377eaeddc91d048
    environment:
    - KONG_PROXY_LISTEN=off
    - KONG_ADMIN_LISTEN=off
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=postgres
    depends_on:
    - postgres
    volumes:
    - ./config:/etc/kong/:ro
    command: ['kong', 'migrations', 'bootstrap']

  db-import:
    image: kong:1.1.2-alpine@sha256:550eaa94080dec3dd0c369d124a1e5d1e8cc70b10584d230d377eaeddc91d048
    environment:
    - KONG_PROXY_LISTEN=off
    - KONG_ADMIN_LISTEN=off
    - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=postgres
    depends_on:
    - postgres
    - bootstrap
    volumes:
    - ./config:/etc/kong/:ro
    command: ['kong', 'config', 'db_import', '/etc/kong/kong.yml']

  admin:
    image: kong:1.1.2-alpine@sha256:550eaa94080dec3dd0c369d124a1e5d1e8cc70b10584d230d377eaeddc91d048
    restart: unless-stopped
    ports:
    - "8001:8001"
    environment:
    - KONG_PROXY_LISTEN=off
    - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=postgres
    depends_on:
    - postgres
    - bootstrap
    volumes:
    - ./config:/etc/kong/:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/status"]
      interval: 60s
      timeout: 1s
      retries: 3
      start_period: 60s
```

```bash
docker-compose up
```
and you'll get a `Error: Kong is not running at /usr/local/kong` from the `db-import` container
