### ISSUE TITLE
kong cannot get client ip 

### ISSUE THREAD

**Issue by dotbalo** [Kong/kong#4712]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

I deployed kong on kubernetes, used NodePort to expose ports 80 and 443, and then configured the domain name on kong, which was able to access normally, but could not get the real IP of the client.

In front of kong is F5 for the reverse.

### Steps To Reproduce

1. Deploy kong on kubernetes
````
kind: DaemonSet
apiVersion: extensions/v1beta1 
metadata:
  namespace: kong 
  name: kong-proxy
  labels:
    app: kong-proxy
    env: prod
spec:
  updateStrategy:    
    rollingUpdate:      
      maxUnavailable: 1    
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kong-proxy
    spec:
      nodeSelector: 
        kong: "true"
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      securityContext:
        sysctls:
        - name: net.ipv4.tcp_timestamps
          value: "0"
        - name: net.core.somaxconn
          value: "65535"
        - name: net.ipv4.tcp_max_syn_backlog
          value: "65535"
      containers:
      - image: kong0.14:v2
        imagePullPolicy: IfNotPresent
        env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: KONG_ADMIN_LISTEN
              value: "127.0.0.1:8001"
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:80,0.0.0.0:443 ssl"
            - name: KONG_DATABASE
              value: "cassandra"
            - name: KONG_CASSANDRA_CONTACT_POINTS
              value: "xxxxx"
            - name: KONG_CASSANDRA_KEYSPACE
              value: "xxxxx"
            - name: KONG_CASSANDRA_USERNAME
              value: "xxxxx"
            - name: KONG_CASSANDRA_PASSWORD
              value: "xxxxx"
            - name: KONG_DB_UPDATE_FREQUENCY
              value: "5"
            - name: KONG_DB_UPDATE_PROPAGATION
              value: "5"
            - name: KONG_PLUGINS
              value: "bundled,cube-auth,lenovo-auth"
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: requests.memory
                  divisor: 1Mi
        ports:
            - containerPort: 80
              name: proxy
            - containerPort: 443
              name: proxyssl
            - containerPort: 8001
              name: admin
            - containerPort: 8002
              name: admin2
        livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: proxy
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: proxy
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
        name: kong-proxy
````
2. expose the kong Port by NodePort of kubernetes service
````
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kong-proxy 
  name: kong-proxy
  namespace: kong
spec:
  type: NodePort
  ports:
    - port: 443
      name: proxyssl
      targetPort: 443
      nodePort: 443
    - port: 80
      name: proxy 
      targetPort: 80
      nodePort: 80
    - port: 8002
      name: admin2
      targetPort: 8002
      nodePort: 8002 
  selector:
   app: kong-proxy
````
3. Then I configured the following environment variables:
````
KONG_TRUSTED_IPS: 0.0.0.0/0,::0
KONG_REAL_IP_RECURSIVE: on
KONG_REAL_IP_HEADER: X-Forwarded-For
````
Also tried:
````
KONG_TRUSTED_IPS: 0.0.0.0/0,::0
KONG_REAL_IP_RECURSIVE: on
KONG_REAL_IP_HEADER: X-Real-IP

KONG_TRUSTED_IPS: 10.0.0.0/8,20.0.0.0/8
KONG_REAL_IP_RECURSIVE: on
KONG_REAL_IP_HEADER: X-Real-IP

and many more，but not。
````

4. Finally, I accessed the configured domain name, but the kong log did not get the IP of my computer. 
````
20.251.14.192 - - [11/Jun/2019:18:38:12 +0800] "GET /ip.ashx HTTP/1.1" 200 1340 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
20.251.14.192 - - [11/Jun/2019:18:38:12 +0800] "GET /ip.ashx HTTP/1.1" 200 1340 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
20.251.14.192 - - [11/Jun/2019:18:38:13 +0800] "GET /ip.ashx HTTP/1.1" 200 1340 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
````
### Additional Details & Logs

- Kong version (`$ kong version`)
````
[root@kong-proxy-4qrw5 /]# kong version
0.14.1
````
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
````
charset UTF-8;

error_log syslog:server=kong-hf.mashape.com:61828 error;

error_log logs/error.log notice;


client_max_body_size 0;
proxy_ssl_server_name on;
underscores_in_headers on;

lua_package_path './?.lua;./?/init.lua;;;';
lua_package_cpath ';;';
lua_socket_pool_size 30;
lua_max_running_timers 4096;
lua_max_pending_timers 16384;
lua_shared_dict kong                5m;
lua_shared_dict kong_db_cache       128m;
lua_shared_dict kong_db_cache_miss 12m;
lua_shared_dict kong_locks          8m;
lua_shared_dict kong_process_events 5m;
lua_shared_dict kong_cluster_events 5m;
lua_shared_dict kong_healthchecks   5m;
lua_shared_dict kong_rate_limiting_counters 12m;
lua_shared_dict kong_cassandra      5m;
lua_socket_log_errors off;

# injected nginx_http_* directives
lua_shared_dict prometheus_metrics 5m;

init_by_lua_block {
    Kong = require 'kong'
    Kong.init()
}

init_worker_by_lua_block {
    Kong.init_worker()
}


upstream kong_upstream {
    server 0.0.0.1;
    balancer_by_lua_block {
        Kong.balancer()
    }
    keepalive 60;
}

server {
    server_name kong;
    listen 0.0.0.0:80;
    listen 0.0.0.0:443 ssl;
    error_page 400 404 408 411 412 413 414 417 494 /kong_error_handler;
    error_page 500 502 503 504 /kong_error_handler;

    access_log logs/access.log;
    error_log logs/error.log notice;

    client_body_buffer_size 8k;

    ssl_certificate /usr/local/kong/ssl/kong-default.crt;
    ssl_certificate_key /usr/local/kong/ssl/kong-default.key;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_certificate_by_lua_block {
        Kong.ssl_certificate()
    }

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;


    real_ip_header     X-Forwarded-For;
    real_ip_recursive  on;
    set_real_ip_from   0.0.0.0/0;
    set_real_ip_from   ::0;

    # injected nginx_proxy_* directives

    location / {
        default_type                     '';

        set $ctx_ref                     '';
        set $upstream_host               '';
        set $upstream_upgrade            '';
        set $upstream_connection         '';
        set $upstream_scheme             '';
        set $upstream_uri                '';
        set $upstream_x_forwarded_for    '';
        set $upstream_x_forwarded_proto  '';
        set $upstream_x_forwarded_host   '';
        set $upstream_x_forwarded_port   '';

        rewrite_by_lua_block {
            Kong.rewrite()
        }

        access_by_lua_block {
            Kong.access()
        }

        proxy_http_version 1.1;
#        proxy_set_header   Host              $upstream_host;
        proxy_set_header   Host              $host;
        proxy_set_header   Upgrade           $upstream_upgrade;
        proxy_set_header   Connection        $upstream_connection;
        proxy_set_header   X-Forwarded-For   $upstream_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $upstream_x_forwarded_proto;
        proxy_set_header   X-Forwarded-Host  $upstream_x_forwarded_host;
        proxy_set_header   X-Forwarded-Port  $upstream_x_forwarded_port;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_pass_header  Server;
        proxy_pass_header  Date;
        proxy_ssl_name     $upstream_host;
        proxy_pass         $upstream_scheme://kong_upstream$upstream_uri;

        header_filter_by_lua_block {
            Kong.header_filter()
        }

        body_filter_by_lua_block {
            Kong.body_filter()
        }

        log_by_lua_block {
            Kong.log()
        }
    }

    location = /kong_error_handler {
        internal;
        uninitialized_variable_warn off;

        content_by_lua_block {
            Kong.handle_error()
        }

        header_filter_by_lua_block {
            Kong.header_filter()
        }

        body_filter_by_lua_block {
            Kong.body_filter()
        }

        log_by_lua_block {
            Kong.log()
        }
    }
}

server {
    server_name kong_admin;
    listen 127.0.0.1:8001;

    access_log logs/admin_access.log;
    error_log logs/error.log notice;

    client_max_body_size 10m;
    client_body_buffer_size 10m;


    # injected nginx_admin_* directives

    location / {
        default_type application/json;
        content_by_lua_block {
            Kong.serve_admin_api()
        }
    }

    location /nginx_status {
        internal;
        access_log off;
        stub_status;
    }

    location /robots.txt {
        return 200 'User-agent: *\nDisallow: /';
    }
}
````
- Operating system
````
CentOS 7.6 
Kubernetes 1.13.5
````
