### ISSUE TITLE
Seeming bug with accessing local urls with file databasef

### ISSUE THREAD

**Issue by George3d6** [Kong/kong#4952]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. Use the following yml file as the kong database:

```
_format_version: "1.1"

# Each Kong entity (core entity or custom entity introduced by a plugin)
# can be listed in the top-level as an array of objects:

services:

- name: mindsdb-ec2-controller

#  url: 'http://127.0.0.1:7777'
  protocol: http
  host: 0.0.0.0
  port: 7777
  path: /

  plugins:

  - name: key-auth

  routes:

  - name: test_route

    paths:

    - /



consumers:

- username: admin

  keyauth_credentials:

  - key: 'wahtever'
```

2. run python3 -m http.server 7777

3. got to http://your_machine_ips:8000/test_route/?apikey=wahtever

You'll get the error: `The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`

Also tried with localhost, 0.0.0.0 and even the machine's public IP instead of 127.0.0.1
### Additional Details & Logs

Only thing I see in the logs when I make a request is:

```
==> /usr/local/kong/logs/access.log <==
98.151.119.105 - - [22/Aug/2019:06:37:27 +0000] "GET /test_route/?apikey=<hidden> HTTP/1.1" 404 232 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
```
