### ISSUE TITLE
rate limiting plugin failed with runtime error: attempt to index local 'policy' (a nil value)

### ISSUE THREAD

**Issue by zyjiaobj** [Kong/kong#4965]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Rate limiting plugin failed with runtime error: `attempt to index local 'policy' (a nil value)`

### Steps To Reproduce

1. save a `kong.yml` file
```
_format_version: "1.1"
services:
- name: my-cf
  url: http://api.bosh-lite.com/v2/info
  routes:
  - name: my-route
    hosts:
    - example.com
plugins:
- name: rate-limiting
  config:
    minute: 5
```
2. save a `kong.conf` file
```
 database = off
 declarative_config =  /home/abc/kong.yml
```
3. start kong using the above configure files:
```
$ kong start -c ./kong.conf
```
4. test my service route:
```
$ curl http://localhost:8000 -H 'host: example.com'
{"message":"An unexpected error occurred"}
```

### Additional Details & Logs

- Kong version (`$ kong version`) 
```
1.3.0
```
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
```
2019/08/26 08:44:40 [error] 4138#0: *23308 lua coroutine: runtime error: ...are/lua/5.1/kong/plugins/rate-limiting/policies/init.lua:112: attempt to index local 'policy' (a nil value)
stack traceback:
coroutine 0:
	...are/lua/5.1/kong/plugins/rate-limiting/policies/init.lua: in function 'usage'
	...cal/share/lua/5.1/kong/plugins/rate-limiting/handler.lua:47: in function 'get_usage'
	...cal/share/lua/5.1/kong/plugins/rate-limiting/handler.lua:96: in function <...cal/share/lua/5.1/kong/plugins/rate-limiting/handler.lua:79>
coroutine 1:
	[C]: in function 'resume'
	coroutine.wrap:21: in function <coroutine.wrap:21>
	/usr/local/share/lua/5.1/kong/init.lua:727: in function 'access'
	access_by_lua(nginx-kong.conf:91):2: in main chunk, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "example.com"
2019/08/26 08:44:40 [error] 4138#0: *23308 [kong] init.lua:733 ...are/lua/5.1/kong/plugins/rate-limiting/policies/init.lua:112: attempt to index local 'policy' (a nil value), client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "example.com"
```
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
```
 database = off
 declarative_config =  /home/abc/kong.yml
```
- Operating system
```
Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-45-generic x86_64)
```

**Comment by zyjiaobj** [comment]
fixed by updating the kong.yml with: 
```
_format_version: "1.1"

services:
- name: my-cf
  url: http://api.bosh-lite.com/v2/info
  routes:
  - name: my-route
    hosts:
    - example.com
- name: my-cf2
  url: http://api.bosh-lite.com/
  routes:
  - name: my-cf2-route
    hosts:
    - example2.com

plugins:
- name: rate-limiting
  config:
    policy: local
    minute: 5
```

missing `policy: local` in the docs: https://docs.konghq.com/hub/kong-inc/rate-limiting/
```
Without a database

Configure this plugin on a Service by adding this section do your declarative configuration file:

plugins:
- name: rate-limiting
  service: {service}
  config: 
    second: 5
    hour: 10000
```
