### ISSUE TITLE
Questionable use of kong and Prometheus in combination

### ISSUE THREAD

**Issue by xichengliudui** [Kong/kong#4970]
Usage of Prometheus along with kong was problematic，
I used Prometheus to monitor port 8000 and 8001 of kong. I found that port 8001 failed all the time. The error was `server returned HTTP status 403 Forbidden`.
Below is my command to run kong and configuration of Prometheus.

```
 $ docker run -d --name kong \
     --network=kong-net \
     -e "KONG_DATABASE=postgres" \
     -e "KONG_PG_HOST=kong-database" \
     -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
     -p 8000:8000 \
     -p 8443:8443 \
     -p 8001:8001 \
     -p 8444:8444 \
     kong:latest
```
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['10.20.14.122:9090']
 
  - job_name: 'konghttp'
    static_configs:
    - targets: ['10.20.14.122:8000']
      labels:
        group: "konghttp"

  - job_name: 'kongapi'
    static_configs:
    - targets: ['10.20.14.122:8001']
      labels:
        group: "kongapi"
```

**What I want to know is whether kong 8000 port is allowed to be monitored or what special configuration is needed for Prometheus?**

**Thanks to every contributor of kong!**

### Additional Details & Logs

- Kong version (`$ kong version`) , 1.3.0
