### ISSUE TITLE
Kong access.log doesn't have any information

### ISSUE THREAD

**Issue by xichengliudui** [Kong/kong#5004]
### Summary

SUMMARY_GOES_HERE

I use the container to run kong, its log in /usr/local/kong/logs/access.log The log but it doesn't have any information

### Steps To Reproduce

execute: `docker-compose up -d`

```
  kong:
    container_name: "kong"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      - TZ=Asia/Shanghai
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    depends_on:
      - "postgres"
      - "briefkong"
    restart: always
    image: kong:1.3rc1-centos
```

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
