### ISSUE TITLE
kong1.3.0 dbless mode fail start: by using basic-auth plugin to set basicauth_credentials

### ISSUE THREAD

**Issue by crazytravel** [Kong/kong#5005]
### Summary

basic-auth plugin on kong 1.3.0 declarative dbless mode start failed. 
Rollback to kong 1.2.0 it works.

nginx: [error] init_by_lua error: ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:423: attempt to index local 'parent_fk' (a nil value)

```yml
basicauth_credentials:
  - consumer: eq-survey
    username: admin
    password: ***********************
```

### Additional Details & Logs

- Kong version (`1.3.0`)
- Kong debug-level startup logs (
```
nginx: [error] init_by_lua error: ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:423: attempt to index local 'parent_fk' (a nil value)
stack traceback:
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:423: in function 'get_key_for_uuid_gen'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:457: in function 'generate_ids'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:480: in function 'flatten'
        /usr/local/share/lua/5.1/kong/db/declarative/init.lua:153: in function 'parse_file'
        /usr/local/share/lua/5.1/kong/init.lua:252: in function 'parse_declarative_config'
        /usr/local/share/lua/5.1/kong/init.lua:430: in function 'init'
        init_by_lua:3: in main chunk
```
)
- Docker: kong:1.3.0-alpine

**Comment by andiexer** [comment]
same problem here. try to use jwt plugin. error raises when adding 'key' field

```yaml
jwt_secrets:
 - consumer: test
   algorithm : HS256
   secret: any-secret
   key: any-key
```
