### ISSUE TITLE
Support yaml references in declarative config

### ISSUE THREAD

**Issue by ArtemDerevnjuk** [Kong/kong#5107]
yaml might be useful to manage complex config files. For example, yaml supports references.

https://camel.readthedocs.io/en/latest/yamlref.html?_ga=2.105617600.217112987.1570526132-738201176.1567149463

We can use the YAML references to combine declarations to DRY config.

```yml
_format_version: '1.1'

services:
  identity: &identity
    host: identity.api
    connect_timeout: 60000
    protocol: http
    port: 8000
    retries: 5
   
  feed: 
    <<: *identity
    connect_timeout: 30000
    host: feed.api
```

**Comment by ArtemDerevnjuk** [comment]
@ArtemDerevnjuk dfsdfs #5107

**Comment by kikito** [comment]
Hi, Kong supports YAML "references" (anchors).

However, Kong is strict about the syntax used. In particular, the `services` entry needs to be a *list*, not a *hash*.

Here's how your declaration would look, using anchors with the expected list syntax:

```
_format_version: '1.1'

services:
  - &identity
    name: identity
    host: identity.api
    connect_timeout: 60000
    protocol: http
    port: 8000
    retries: 5

  - <<: *identity
    name: feed
    host: feed.api
    connect_timeout: 30000
```

I have tried it locally with `KONG_DATABASE=off KONG_DECLARATIVE_CONFIG=kong.yml bin/kong start` and the two services appeared in `:8001/services`.
