### ISSUE TITLE
acls   Without a database

### ISSUE THREAD

**Issue by duzhenxun** [Kong/kong#5144]
Without a database

You can create ACL objects via the acls: entry in the declarative configuration file:

acls:
- consumer: { consumer }
  group: group1
consumer: The id or username property of the Consumer entity to associate the credentials to.
group: The arbitrary group name to associate to the consumer.

```
_format_version: "1.1"

services:
- name: tms.ping
  url: http://utms.x.com/ping
  routes:
  - name: tms.ping
    paths:
    - /tms/ping

consumers:
- username: ado
  keyauth_credentials:
  - key: ado


- username: ado2
  keyauth_credentials:
  - key: ado2


plugins:
- name: key-auth
- name: acl
  config: 
    whitelist:
    - ado
    - group2

acls:
- consumer: ado
  group: ado
```

> 
[root@13bcd82242c7 kong]# kong config parse /data/kong/kong.yaml --vv
2019/10/21 20:32:37 [verbose] Kong: 1.3.0
2019/10/21 20:32:37 [debug] ngx_lua: 10015
2019/10/21 20:32:37 [debug] nginx: 1015008
2019/10/21 20:32:37 [debug] Lua: LuaJIT 2.1.0-beta3
2019/10/21 20:32:37 [debug] admin_access_log = "logs/admin_access.log"
2019/10/21 20:32:37 [debug] admin_error_log = "logs/error.log"
2019/10/21 20:32:37 [debug] upstream_keepalive = 60
2019/10/21 20:32:37 [verbose] prefix in use: /usr/local/kong
Error: 
...are/lua/5.1/kong/db/schema/others/declarative_config.lua:423: attempt to index local 'parent_fk' (a nil value)
stack traceback:
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:423: in function 'get_key_for_uuid_gen'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:457: in function 'generate_ids'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:480: in function 'flatten'
        /usr/local/share/lua/5.1/kong/db/declarative/init.lua:153: in function 'parse_file'
        /usr/local/share/lua/5.1/kong/cmd/config.lua:109: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:49: in function <init_worker_by_lua:47>
        [C]: in function 'xpcall'
        init_worker_by_lua:56: in function <init_worker_by_lua:54>

>
