### ISSUE TITLE
Global Plugins - Support "exclude" of services/routes

### ISSUE THREAD

**Issue by liorsamuni** [Kong/kong#5233]
Currently, Kong has the option of enabling a plugin per service/consumer, enabling it globally etc.

**What is missing is the ability to enable a plugin globally, but to exclude it from certain services/paths.**

E.g. when working with declarative configuration, i can see kong support the following:
```yaml
_format_version: "1.1"
services:
- name: my-service
  url: https://example.com
  plugins:
  - name: key-auth
  excluded-plugins:
  - syslog

plugins:
   - name: syslog
```

(other valid option is to have a new attribute added to the global plugin definition, with excluded services/routes capability)
