### ISSUE TITLE
Longest path routing breaks when a route with different host and same path is added

### ISSUE THREAD

**Issue by atikhono** [Kong/kong#5418]
### Summary

After #5371 is fixed, longest path routing still breaks when I add another route with the same paths and different host to my declarative configuration piece. Wrong service is getting matched. The issue persists since 1.3.0.

### Steps To Reproduce

1. Start kong in db-less mode with the following kong.conf and kong.yaml:
```
docker run -p 8000:8000 -p 8001:8001 -v `pwd`/kong.yaml:/config/kong.yaml -v `pwd`/kong.conf:/config/kong.conf kong:1.3.0 kong start -c /config/kong.conf
```
kong.conf:
```
database = off
declarative_config = /config/kong.yaml
proxy_access_log = /dev/stdout
admin_listen = 0.0.0.0:8001
admin_access_log = /dev/stdout
```
kong.yaml:
```
_format_version: "1.1"

services:
  - name: devportal-public
    host: localhost
    port: 8001
    path: /routes
    routes:
      - name: public-apiv1
        hosts:
          - api.local
        paths:
          - /rest/devportal/api/v1
          - /rest/devportal

  - name: devportal-aux
    host: localhost
    port: 8001
    path: /services
    routes:
      - name: aux
        hosts:
          - api.local
        paths:
          - /rest/devportal/aux

  - name: devportal-aux-host
    host: localhost
    port: 8001
    path: /plugins
    routes:
      - name: aux-host
        hosts:
          - test-api.local
        paths:
          - /rest/devportal/aux
```
Added devportal-aux-host service and route compared to kong.yaml in #5371.
2. Call kong as follows:
```
curl -H 'Host:api.local' localhost:8000/rest/devportal/aux
```
With Kong 1.3.0+ public-apiv1 is getting matched.
With Kong 1.2.2 aux route is getting matched.

### Additional Details & Logs

kong 1.3.0
kong 1.4.2
kong-nightly/master 2020-01-08 (includes fix for #5371)
