### ISSUE TITLE
Longest path routing with multiple hosts and the same path is broken

### ISSUE THREAD

**Issue by atikhono** [Kong/kong#5438]
### Summary

After #5418 is fixed, longest path routing still breaks when I add more than one route with the same path and different host to my declarative configuration piece. Wrong service is getting matched.

### Steps To Reproduce

1. Start kong in db-less mode with the following kong.conf and kong.yaml:
```
docker run -p 8000:8000 -p 8001:8001 -v `pwd`/kong.yaml:/config/kong.yaml -v `pwd`/kong.conf:/config/kong.conf kong:1.3.0 kong start -c /config/kong.conf
```

kong.conf:
```
database = off
declarative_config = /config/kong.yaml
proxy_access_log = /dev/stdout
admin_listen = 0.0.0.0:8001
admin_access_log = /dev/stdout
```

kong.yaml:
```
_format_version: "1.1"

services:
  - name: devportal-public
    host: localhost
    port: 8001
    path: /routes
    routes:
      - name: public-apiv1
        hosts:
          - api.local
        paths:
          - /rest/devportal/api/v1
          - /rest/devportal

  - name: devportal-aux
    host: localhost
    port: 8001
    path: /services
    routes:
      - name: aux
        hosts:
          - api.local
        paths:
          - /rest/devportal/aux

  - name: devportal-aux-host
    host: localhost
    port: 8001
    path: /plugins
    routes:
      - name: aux-host
        hosts:
          - test-api.local
        paths:
          - /rest/devportal/aux

  - name: devportal-aux-host2
    host: localhost
    port: 8001
    path: /endpoints
    routes:
      - name: aux-host2
        hosts:
          - atest-api.local
        paths:
          - /rest/devportal/aux
```
Added devportal-aux-host2 service and route compared to kong.yaml in #5418.

2. Call kong as follows:
```
curl -H 'Host:test-api.local' localhost:8000/rest/devportal/aux
## Edit: curl -H 'Host:api.local' localhost:8000/rest/devportal/aux
```
With kong-nightly/master/2020-01-11 public-apiv1 is getting matched. I expect aux route match.

### Additional Details & Logs

kong-nightly/master 2020-01-11 (includes fix for #5418)
