### ISSUE TITLE
Support for GRPC-Web

### ISSUE THREAD

**Issue by saltxwater** [Kong/kong#5456]
### Summary
Is it possible to configure kong to proxy GRPC web requests? If not, this feature would help simplify our setup.

We are using GRPC web to connect front-end web apps (Angular) to our backend services (C#). Currently the request goes through Kong to a sidecar Envoy service which then forwards it on to the C# service. We have found that we need this sidecar to manage the HTTP/1.1 request connecting to the backend. The setup works with the kong route protocol set to https but setting it to grpcs and trying to go direct to the service (or even to the sidecar!) then this fails:

`172.17.0.1 - - [16/Jan/2020:10:14:31 +0000] "POST /Proto.BackendService/GetConfig HTTP/1.1" 426 39 "https://frontend.company.com/page" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"`

I believe the 426 is related to upgrading this connection from http/1.1 to http 2?

We would ideally like to remove this sidecar completely so we have no proxying dependencies other than Kong.

Grpc Web: https://github.com/grpc/grpc-web

If it helps, the Envoy sidecar config which is working for us is:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 1338 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 443 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout"
          codec_type: auto
          stat_prefix: ingress_http
          stream_idle_timeout: 0s
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              response_headers_to_add:
                - header:
                    key: "X-Accel-Buffering"
                    value: "no"
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: main_service
                  max_grpc_timeout: 0s
              cors:
                allow_origin:
                - "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,Authorization
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
                enabled: true
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router
      tls_context:
        common_tls_context:
          alpn_protocols: ["h2"]
          tls_certificates:
            certificate_chain: { "filename": "/certs/local.cer" }
            private_key: { "filename": "/certs/local.key" }
  clusters:
  - name: main_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: ${SERVICE_ADDRESS}, port_value: ${SERVICE_PORT} }}]
    upstream_connection_options:
      tcp_keepalive:
        keepalive_probes: 1
        keepalive_time: 30
        keepalive_interval: 30
    tls_context:
      common_tls_context:
        tls_certificates:
          certificate_chain: { "filename": "/certs/local.cer" }
          private_key: { "filename": "/certs/local.key" }
        alpn_protocols: ["h2"]
        validation_context:
          trusted_ca: { "filename": "/certs/ca.cer" }
```
