### ISSUE TITLE
Kong 1.4 + 2.0 Active healthchecks for Upstream not automatically setting status back to healthy, after its gone unhealthy. (when healthchecks.active.https_verify_certificate=false)

### ISSUE THREAD

**Issue by joedugdale** [Kong/kong#5531]
### Summary
After creating an active healthcheck for a kong upstream, all appears fine at first, but if the target goes to an Unhealthy state, Kong doesn't seem to set the status to healthy again automatically.

After trying this out I've found a workaround: If you update upstream (with the same details), it seems to kick it in the butt and sets it back to healthy. Restarting kong also seems to do this.

### Steps To Reproduce

1. create an upstream with active healthchecks enabled (ignoring passive checks).
2. When running with a healthy status, simulate a failure scenario on the upstream, eg kill the endpoint.
3. Check that kong shows target as unhealthy. Up to this point everything is working as expected.
4. Resolve the failure scenario, kong stays unhealthy. Checks do continue to run but health status doesn't change back to healthy as expected. Hitting the target through kong results in 503 failure to get a peer from the ring-balancer".
5. restart kong or "update upstream". Correct health is obtained. 503s change to 200s.

### Additional Details & Logs

- Kong version (2.0.0) - also tried this on 1.4 with same behaviour
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

2020/02/04 21:59:16 [warn] 34#0: *4376 [lua] balancer.lua:242: callback(): [healthchecks] balancer test-upstream reported health status changed to UNHEALTHY, context: ngx.timer

172.30.8.1 - - [04/Feb/2020:22:46:20 +0000] "GET /health HTTP/1.1" 503 58 "-" "curl/7.29.0"
-- restart kong or post update
172.30.8.1 - - [04/Feb/2020:22:49:14 +0000] "GET /health HTTP/1.1" 200 25 "-" "curl/7.29.0"

- Kong configuration (the output of a GET request to Kong's Admin port - see

upstream details

```
{
  "created_at": 1580851690,
  "hash_on": "none",
  "id": "b4a3a9f1-fdb4-41cc-b253-d90a0f9e83ac",
  "algorithm": "round-robin",
  "name": "test-upstream",
  "tags": null,
  "hash_fallback_header": null,
  "hash_fallback": "none",
  "hash_on_cookie": null,
  "host_header": null,
  "hash_on_cookie_path": "/",
  "healthchecks": {
    "threshold": 0,
    "active": {
      "unhealthy": {
        "http_statuses": [
          429,
          404,
          500,
          501,
          502,
          503,
          504,
          505,
          499
        ],
        "tcp_failures": 1,
        "timeouts": 1,
        "http_failures": 1,
        "interval": 10
      },
      "type": "https",
      "http_path": "/health",
      "timeout": 4,
      "healthy": {
        "successes": 1,
        "interval": 10,
        "http_statuses": [
          200,
          302
        ]
      },
      "https_sni": null,
      "https_verify_certificate": false,
      "concurrency": 10
    },
    "passive": {
      "unhealthy": {
        "http_failures": 0,
        "http_statuses": [
          429,
          500,
          503
        ],
        "tcp_failures": 0,
        "timeouts": 0
      },
      "healthy": {
        "http_statuses": [
          200,
          201,
          202,
          203,
          204,
          205,
          206,
          207,
          208,
          226,
          300,
          301,
          302,
          303,
          304,
          305,
          306,
          307,
          308
        ],
        "successes": 0
      },
      "type": "https"
    }
  },
  "hash_on_header": null,
  "slots": 10000
}
```

-  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)

- Operating system: Docker/Openshift same behaviour on both

**Comment by joedugdale** [comment]
Similar issues raised..
https://github.com/Kong/kong/issues/5151
https://github.com/Kong/kong/issues/5195

**Comment by hishamhm** [comment]
@joedugdale Hi there, thanks for reporting!

I am failing to reproduce this locally. We do have test cases for automatic recovery in our test suite, but I also tried to reproduce your scenario manually. This is what I am attempting:

I ran the following setup, with Kong 2.0.0, on both Postgres and Cassandra:

nginx server at `127.0.0.1:2112` as the test service:

```
# demo/rush/conf/nginx.conf

worker_processes auto;

pid pids/nginx.pid;
error_log /dev/stdout debug;

worker_rlimit_nofile 1024;

events {
    worker_connections 1024;
    multi_accept on;
}

http {
    server {
        listen 2112;
        listen [::]:2112;
        location = /status {
            return 200;
        }
        location = / {
            return 200;
        }
    }
}
```

httpie commands for the test scenario, starting from an empty database: 

```
# create upstream
http :8001/upstreams name=rush 

# add a target
http :8001/upstreams/rush/targets target=127.0.0.1:2112

# create a service
http :8001/services name=rush-service url=http://rush

# set active healthchecks
http patch :8001/upstreams/rush healthchecks.active.unhealthy.tcp_failures=1 \
  healthchecks.active.unhealthy.timeouts=1 \
  healthchecks.active.unhealthy.http_failures=1 \
  healthchecks.active.unhealthy.interval=2 \
  healthchecks.active.http_path=/status \
  healthchecks.active.healthy.successes=1 \
  healthchecks.active.healthy.interval=2 -f

# create a route
http :8001/routes name=rush-route paths=/ service.name=rush-service -f

# proxy, runs fine (HTTP 200)
http :8000/

# health appears HEALTHY
http :8001/upstreams/rush/health

# killed the nginx server running at 127.0.0.1:2112, wait 2 seconds
kill $(cat demo/rush/pids/nginx.pid)

# health appears UNHEALTHY
http :8001/upstreams/rush/health

# proxy, fails (HTTP 503)
http :8000/

# restart nginx at 127.0.0.1:2112, wait 2 seconds
nginx -p demo/rush

# health appears HEALTHY
http :8001/upstreams/rush/health

# proxy, works (HTTP 200)
http :8000/
```

I also attempted the same thing running Kong in DB-less mode, using the following declarative config file:

```
# kong.yml
_format_version: '1.1'
services:
- host: rush
  created_at: 1580892715
  connect_timeout: 60000
  id: e5056e68-960b-4591-ba8e-b1260738ff69
  protocol: http
  name: rush-service
  read_timeout: 60000
  port: 80
  updated_at: 1580892715
  retries: 5
  write_timeout: 60000
routes:
- id: b4b567e3-c2e5-4c98-8eaa-7476d8cd7f6f
  path_handling: v0
  paths:
  - /
  protocols:
  - http
  - https
  service: e5056e68-960b-4591-ba8e-b1260738ff69
  name: rush-route
  strip_path: true
  preserve_host: false
  regex_priority: 0
  updated_at: 1580892725
  https_redirect_status_code: 426
  created_at: 1580892725
upstreams:
- created_at: 1580892706
  hash_on: none
  id: 314a4050-b4e3-4325-a0b4-454cca29e775
  algorithm: round-robin
  name: rush
  hash_fallback: none
  hash_on_cookie_path: /
  healthchecks:
    threshold: 0
    active:
      unhealthy:
        http_statuses:
        - 429
        - 404
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        tcp_failures: 1
        timeouts: 1
        http_failures: 1
        interval: 2
      type: http
      http_path: /status
      timeout: 1
      healthy:
        successes: 1
        interval: 2
        http_statuses:
        - 200
        - 302
      https_verify_certificate: true
      concurrency: 10
    passive:
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 500
        - 503
        tcp_failures: 0
        timeouts: 0
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        successes: 0
      type: http
  slots: 10000
targets:
- created_at: 1580892710.093
  upstream: 314a4050-b4e3-4325-a0b4-454cca29e775
  id: fedb09a9-87a9-4b2e-ab9f-e58cb4b108bc
  target: 127.0.0.1:2112
  weight: 100
```

(this `kong.yml` is actually the result of running `kong config db_export` after running the experiment on Postgres :) )

In all three attempts (with Postgres, Cassandra and DB-less) the above scenario worked as intended.

I also re-ran the tests using two targets as described in #5151 (starting another nginx on 127.0.0.1:2113 and adding it to the upstream as well) but it also worked as intended (it returns 200 from the proxy port as long as at least one of the targets is up; switches to 503 if both are down; then returns to 200 when one of them is restarted).

@joedugdale do you spot anything in the above test scenario that does not match how you are testing it in your environment? Did you get anything with `[error]` severity in your `error.log`?
