### ISSUE TITLE
JWT plugin doesn't work correctly

### ISSUE THREAD

**Issue by vietwow** [Kong/kong#5544]
Hi all,

I'm using kong 2.0 on kubernetes with db-less mode (declarative), using following config :

```
_format_version: "1.1"

services:
- name: vendor_service
  url: https://my-url/batches
  plugins:
  - name: jwt
  routes:
  - name: batches
    paths:
    - /batches

consumers:
- username: my-user

jwt_secrets:
- consumer: "my-user"
  key: "abcxyz"
  algorithm: "RS256"
  rsa_public_key: |-
    -----BEGIN PUBLIC KEY-----
    ...
    -----END PUBLIC KEY-----
```

Then I craft a jwt token (using https://jwt.io/) with a wrong public key (and wrong iss) info, but It is still working using this token. My expectation is that it's not working, it's only working when we provide a valid token which is created from the correct public key and iss

So anything I missed in configuration ? Hope anyone could help me. Thank you so much.

Best regards,
VietNC
