### ISSUE TITLE
plugin was built with a different version of package github.com/Kong/go-pdk/bridge

### ISSUE THREAD

**Issue by AndyCornelius** [Kong/kong#5546]
Kong throws this error on startup, when I try to include a simple Go plugin:

```
kong             | 2020/02/06 15:10:12 failed to open plugin test-go: plugin.Open("/home/kong/plugins/test-go"): plugin was built with a different version of package github.com/Kong/go-pdk/bridge
kong             | 2020/02/06 15:10:12 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:455: bad argument Kong/go-pdk#1 to 'ipairs' (table expected, got nil)
kong             | stack traceback:
kong             | 	[C]: in function 'ipairs'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:455: in function 'get_plugin'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:481: in function 'load_plugin'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:151: in function 'load_plugin_handler'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
kong             | 	/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
kong             | 	init_by_lua:3: in main chunk
kong             | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:455: bad argument Kong/go-pdk#1 to 'ipairs' (table expected, got nil)
kong             | stack traceback:
kong             | 	[C]: in function 'ipairs'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:455: in function 'get_plugin'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:481: in function 'load_plugin'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:151: in function 'load_plugin_handler'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
kong             | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
kong             | 	/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
kong             | 	init_by_lua:3: in main chunk
```

I'm running Kong in docker using docker-compose with the `kong:2.0.1-alpine` image.

```
  kong:
    image: kong:2.0.1-alpine
    container_name: kong
    depends_on:
      - kong-database
      - node-service
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_GO_PLUGINS_DIR=/home/kong/plugins
      - KONG_PLUGINS=bundled,test-go
    volumes:
      - "./:/home/kong/plugins"
    networks:
      - kong
```

My go.mod file is requiring `github.com/Kong/go-pdk v0.3.0` which matches the go-pdk repository.

I'm compiling in docker using the `golang:1.13.4` image, with this env:

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/plugin/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build002596274=/tmp/go-build -gno-record-gcc-switches"
```

Anyone have any idea why this error occurs?
