### ISSUE TITLE
Configurable X-Forwarded-* headers on services and routes

### ISSUE THREAD

**Issue by trollr** [Kong/kong#5559]
### Summary

Kong automatically assign X-Forwarded-* headers based on some magic (in my case definitely wrong logic). So it would be great if I could overwrite those headers based on routes and services like I would do in nginx location directives. 

### Solution

Add optional properties for x-forwarded-* header to services and routes. If those fields are empty use the magic to define x-forwarded headers, otherwise take the values

**Comment by trollr** [comment]
Example impl: #5561

**Comment by bungle** [comment]
@trollr, 

What do you think is the magic there?

First it checks if there is existing headers, and if they came from trusted ip (by default Kong does not trust any).

For trust / realip, check:
https://docs.konghq.com/2.0.x/configuration/#trusted_ips
https://docs.konghq.com/2.0.x/configuration/#real_ip_header
https://docs.konghq.com/2.0.x/configuration/#real_ip_recursive

Now, I think your issue is L4 port mapping / load balancing. These don't play nice with `Forwarded` headers. I know that you are trying to add support for this case. E.g. make it forcefully to inject some values to these headers. 

You can btw. write custom plugin to set:
```
var.upstream_x_forwarded_for = "<your value>"
var.upstream_x_forwarded_proto = "<your value>"
var.upstream_x_forwarded_host  = "<your value>"
var.upstream_x_forwarded_port  = <your value>
```

But this would only solve the case where there was no existing `x-forwarded` headers from a trusted source. Last remaining thing is to solve if there was `x-forwarded-*` headers from trusted source, you should not just override them. That's why they are called `forwarded` as they are basically forwarded when trusted, though `X-Forwarded-For` is also modified.

**Comment by trollr** [comment]
My setup: 

I use a gke k8s cluster with kong as my Ingress controller. Public accessible via port 80/443. Kong internal port is 8000/8443. The gke loadbalancer not setting any king of x-forwarded-* header.

Kong set the x-forwarded-port header to it's container internal port: 8000/8443. The proxied service visited on xxx.xxx.com:443 verify x-forwarded header for csrf protection (see https://github.com/FusionAuth/fusionauth-issues/issues/470). 

Tried to overwrite the x-forwarded-header with request transformer plugin but nothing happend

**Comment by trollr** [comment]
For everyone with the same issue: 

Post function

```
http :8001/plugins name=post-function config.functions="\
ngx.var.upstream_x_forwarded_host='test.host';\
ngx.var.upstream_x_forwarded_port=1234;\
ngx.var.upstream_x_forwarded_proto='http'" -f
```

Solution for kong ingress controller
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: post-function
  namespace: fusionauth
config:
  functions:
    - "ngx.var.upstream_x_forwarded_port=443; -f"
plugin: serverless-functions
```

Thanks @bungle for your support :)

**Comment by bungle** [comment]
Note here too:

```
 - "ngx.var.upstream_x_forwarded_port=443; -f"
```
Shoud be:
```
 - ngx.var.upstream_x_forwarded_port=443
```

**Comment by trollr** [comment]
fixed typo

**Comment by bungle** [comment]
And if you want to set more than one, it is quite easy as well:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: post-function
  namespace: fusionauth
config:
  functions:
    - ngx.var.upstream_x_forwarded_host=myhost.test
    - ngx.var.upstream_x_forwarded_port=443
    - ngx.var.upstream_x_forwarded_proto=https
plugin: serverless-functions
```
