### ISSUE TITLE
stream routing does not work in DB-less and hybrid mode

### ISSUE THREAD

**Issue by hbagdi** [Kong/kong#5656]
### Summary

Stream routes are not propagated in DB-less mode and Kong always closes the TCP connections with an error log entry of no routes found. This works in DB-mode.

### Steps To Reproduce

Populate Kong with following configuration:
```
_format_version: "1.1"
services:
- connect_timeout: 60000
  host: httpbin.org
  name: httpbin.httpbin.80
  port: 80
  protocol: tcp
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: httpbin.example-app1.0
    protocols:
    - tcp
    destinations:
    - port: 9000
```

`telnet localhost 9000` will not work.

Run the same setup with postgres and that works.

### Additional Details & Logs

- Kong version (`$ kong version`) 2.0.2
- Operating system: Docker
