### ISSUE TITLE
kong parse dbless config error 

### ISSUE THREAD

**Issue by debu99** [Kong/kong#5694]
```
services:
- name: service_name
  url: http://hostname.com:80
  plugins:
  - name: custom-plugin-1
    config:
      account_id: "xxxxxx"
  - name: custom-plugin-2
    config:
      allow_guest: true
  - name: cors
    config:
      origins: https://anotherhost.com
  routes:
  - name: route_name
....
```

When we parse the config above, kong shows error, if we comment the plugins cors part, there will no error during parse test

```2020/03/18 05:44:00 [verbose] Kong: 2.0.1
2020/03/18 05:44:00 [verbose] prefix in use: /usr/local/kong
Error: 
/usr/local/share/lua/5.1/kong/cmd/config.lua:110: Failed parsing:
in 'services':
  - in entry 1 of 'services':
    in 'plugins':
      - in entry 3 of 'plugins':
        in 'config':
          in 'origins': expected an array
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/config.lua:110: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>
```

**Comment by hishamhm** [comment]
>        in 'config':
>          in 'origins': expected an array

The error message is correct, there's a mistake in your config. It needs to be an array, like this:

```yaml
  - name: cors
    config:
      origins:
      - https://anotherhost.com
```

Yes, YAML can be annoying...
