### ISSUE TITLE
Bug: configuration parsing throws wrong errors on missing foreign key relations

### ISSUE THREAD

**Issue by hbagdi** [Kong/kong#5750]
### Summary

When a foreign relation is missing, the configuration parser throws misleading errors.

### Steps To Reproduce

Run Kong 2.0.2 with DB-less mode

```bash
$ cat kong.json
{
  "_format_version": "1.1",
  "consumers": [
    {
      "username": "consumer-test",
      "basicauth_credentials": [
        {
          "username": "some_user",
          "password": "some_password"
        }
      ]
    }
  ],
  "plugins": [
    {
      "name": "request-transformer",
      "config": {
        "add": {
          "body": [],
          "headers": [],
          "querystring": []
        },
        "append": {
          "body": [],
          "headers": [
            "X-Another-Header:foo"
          ],
          "querystring": []
        },
        "remove": {
          "body": [],
          "headers": [
            "X-Another-Header"
          ],
          "querystring": []
        },
        "rename": {
          "body": [],
          "headers": [],
          "querystring": []
        },
        "replace": {
          "body": [],
          "headers": [],
          "querystring": [],
          "uri": null
        }
      },
      "route": "does-not-exist",
      "enabled": true,
      "protocols": [
        "http",
        "https"
      ]
    }
  ]
}
$ http :8001/config < kong.json
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 362
Content-Type: application/json; charset=utf-8
Date: Fri, 03 Apr 2020 00:03:11 GMT
Server: kong/2.0.1
X-Kong-Admin-Latency: 275

{
    "code": 14,
    "fields": {
        "consumers": [
            {
                "basicauth_credentials": [
                    {
                        "@entity": [
                            "all or none of these fields must be set: 'password', 'consumer.id'"
                        ]
                    }
                ]
            }
        ]
    },
    "message": "declarative config is invalid: {consumers={{basicauth_credentials={{[\"@entity\"]={\"all or none of these fields must be set: 'password', 'consumer.id'\"}}}}}}",
    "name": "invalid declarative configuration"
}
```

If you remove the broken route relation on the above plugin, then the configuration is correctly parsed.

### Additional Details & Logs

- Kong version (`$ kong version`) 2.0.2

**Comment by nvx** [comment]
I think I ran into the same issue with this simpler example:

```
_format_version: "1.1"

consumers:
- username: test
  basicauth_credentials:
  - username: test-user
    password: test-pass
- username: test2
  plugins:
  - name: acl
    config:
      blacklist: [dummy]
```

Results in this error:

```
$ kong config parse test-kong.yaml
Error: Failed parsing:
in 'consumers':
  - in entry 1 of 'consumers':
    in 'basicauth_credentials':
      - in entry 1 of 'basicauth_credentials':
        in '@entity':
          - in entry 1 of '@entity': all or none of these fields must be set: 'password', 'consumer.id'

  Run with --v (verbose) or --vv (debug) for more details
```

**Comment by nvx** [comment]
I've just run into this again. In my previous example it's invalid to define the acl plugin against a consumer (although without basicauth_credentials specified anywhere the config parser does not throw an error which it probably should).

This time however I think the config should be valid, the config parse doesn't throw an error without basicauth_credentials specified, but I'm not entirely sure if it's just a bug with the basicauth_credentials or if it's a bug with the route/plugin object.

This errors:

```
_format_version: "1.1"

services:
- name: test-service
  routes:
  - paths:
    - /test/path
    plugins:
    - name: key-auth
  url: https://example.com

consumers:
- username: test-user
  basicauth_credentials:
  - username: test-username
    password: test-password
```

While this works fine:

```
_format_version: "1.1"

services:
- name: test-service
  routes:
  - name: test-route
    paths:
    - /test/path
    plugins:
    - name: key-auth
  url: https://example.com

consumers:
- username: test-user
  basicauth_credentials:
  - username: test-username
    password: test-password
```

Note the only difference is the route object having a name in the second example. It also works if you explicitly specify an id for the route instead of a name. Should specifying name or id mandatory in such cases? To me it seems like it shouldn't, and indeed if basicauth_credentials aren't provided no error occurs, but in other instances of this bug it's been due to invalid configuration so maybe not? Of note if the key-auth plugin is removed from the route definition the error also doesn't occur.

Happy to raise this as a separate issue if there is a bug in the interactions between the route and plugin objects as well, but would like confirmation that is the case first.

Running Kong 2.0.4
