### ISSUE TITLE
How many routes can be supported in db-less mode？

### ISSUE THREAD

**Issue by WALL-E** [Kong/kong#5785]
### Summary

More than 50000 routes in my configuration, there will be some 5xx error on the data plane when updating the configuration via http://127.0.0.1:8001/config.

### Steps To Reproduce

1. start go-httpbin
    ```
    go-httpbin -host 127.0.0.1 -port 8080 2>/dev/null
    ```

2. start kong

    ```
    kong start
    ```
    kong and go-httpbin run on the same host

3. the  config `/root/kong-config-benchmark/apis.yaml` has more than 50000 routes, like this 

    ```
    _format_version: "1.1"

    targets:
    - upstream: upstream-httpbin
      target: 127.0.0.1:8080

    upstreams:
    - name: upstream-httpbin
    algorithm: round-robin

    services:
    - name: service-httpbin
      host: upstream-httpbin
      protocol: http
      port: 80

    routes:
    - name: route-httpbin-1
       paths:
       - /httpbin1/
       strip_path: true
       service: service-httpbin
    - name: route-httpbin-2
       paths:
       - /httpbin2/
       strip_path: true
       service: service-httpbin
    - name: route-httpbin-3
       paths:
       - /httpbin3/
       strip_path: true
       service: service-httpbin
 
    ......
    ```

4. upload config via `http://127.0.0.1:8001/config`  every minute

    ```
    curl -F "config=@/root/kong-config-benchmark/apis.yaml" http://127.0.0.1:8001/config
    ```

5. use wrk to simulate user requests

    ```
    wrk -c 100 -t 4 -d 7200 -s t.lua http://127.0.0.1:8000/httpbin103/ip
    ```

    file: t.lua
    ```
    response = function(status, headers, body)
        if status ~= 200 then
           print(body)
       end
    end
    ```
6. after about a few minutes of operation, the following error message appears

    ```
    {"message":"no Route matched with those values"}
    {"message":"name resolution failed"} 
    {"message":"no Route matched with those values"}
    {"message":"no Route matched with those values"}
    {"message":"name resolution failed"}
    {"message":"no Route matched with those values"}
    {"message":"no Route matched with those values"}
    {"message":"name resolution failed"}
    {"message":"no Route matched with those values"}
    ....
    ```

### Additional Details & Logs

* cloud host
  * 8 vCPU 8 GiB
* OS
  * CentOS Linux release 7.6.1810 (Core)
* Kong
  * version 2.0.3
  * database = off
  * mem_cache_size = 256m
