### ISSUE TITLE
Replacement worker processes do not get config

### ISSUE THREAD

**Issue by agaffney** [Kong/kong#5799]
### Summary

When a worker process gets killed (such as by the OOM killer) and automatically replaced, it is not automatically synced with the current Kong config, causing it to throw 404 errors for every request that it handles.

### Steps To Reproduce

1. Deploy kong helm chart with default values
2. Apply the following simple config via the ingress controller:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: kong-ingress-test
    kubernetes.io/ingress.class: kong
    plugins.konghq.com: kong-ingress-test-0, kong-ingress-test-1
  name: kong-ingress-test
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - backend:
          serviceName: kong-ingress-test
          servicePort: 80
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: kong-ingress-test
spec:
  externalName: google.com
  type: ExternalName
---
apiVersion: configuration.konghq.com/v1
config:
  status_code: 403
  message: So long and thanks for all the fish!
kind: KongPlugin
metadata:
  name: kong-ingress-test-0
plugin: request-termination
```

3. Test that the config works

```bash
$ kubectl exec deploy/kong-kong -c proxy -- curl -s -H "Host: foo.example.com" localhost:8000; echo
{"message":"So long and thanks for all the fish!"}
```

4. Kill a worker like the OOM killer would

```bash
$ kubectl logs deploy/kong-kong -c proxy | grep 'worker process'
2020/04/19 17:36:28 [notice] 1#0: start worker processes
2020/04/19 17:36:28 [notice] 1#0: start worker process 23
$ kubectl exec deploy/kong-kong -c proxy -- kill -9 23
$ kubectl logs deploy/kong-kong -c proxy | grep 'worker process'
2020/04/19 17:36:28 [notice] 1#0: start worker processes
2020/04/19 17:36:28 [notice] 1#0: start worker process 23
2020/04/19 17:41:47 [alert] 1#0: worker process 23 exited on signal 9
2020/04/19 17:41:47 [notice] 1#0: start worker process 90
```

5. Try the request again, and see that Kong now has no idea what you're talking about

```bash
$ kubectl exec deploy/kong-kong -c proxy -- curl -s -H "Host: foo.example.com" localhost:8000; echo
{"message":"no Route matched with those values"}
```

### Additional Details & Logs

- Kong version (`2.0.3`)
