### ISSUE TITLE
500 Internal Server Error {"message":"An unexpected error occurred"}

### ISSUE THREAD

**Issue by elkh510** [Kong/kong#5813]
**Kong Ingress controller version**
kong-ingress-controller:0.8.1

**Kong or Kong Enterprise version**
kong-enterprise-edition:1.5.0.0-alpine

### Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"2640ac46d96791a135961425127d9c2f7e184924", GitTreeState:"clean", BuildDate:"2019-11-14T04:58:54Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
### Environment

- **Cloud provider or hardware configuration**:
Azure Kubernetes Service (AKS) | Microsoft Azure

### What happened
setup ingress:
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: test-ns-1
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  tls:
    - hosts:
        - test-ns-1.example.com
      secretName: wildcard-certificate-for-example-com
  rules:
    - host: test-ns-1.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: test-ns-1
              servicePort: 80
```
strange errors in kong log:
```
E0423 15:26:19.412983       1 controller.go:127] unexpected failure updating Kong configuration: 
1 errors occurred:
	while processing event: {Update} failed: 400 Bad Request <html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
</body>
</html>

W0423 15:26:19.413034       1 queue.go:112] requeuing test-ns/sh.helm.release.v1.test-ns.v2, err 1 errors occurred:
	while processing event: {Update} failed: 400 Bad Request <html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
</body>
</html>
```
```
E0423 15:24:30.859969       1 controller.go:127] unexpected failure updating Kong configuration: 
loading configuration from kong: routes: 500 Internal Server Error {"message":"An unexpected error occurred"}
W0423 15:24:30.859996       1 queue.go:112] requeuing test-ns/platform-backup, err loading configuration from kong: routes: 500 Internal Server Error {"message":"An unexpected error occurred"}
```

### Steps To Reproduce

these errors occur randomly
how it can be debug or fix ?
