### ISSUE TITLE
Regex route match not working

### ISSUE THREAD

**Issue by David-Lor** [Kong/kong#5905]
### Summary

Given the following kong.yml declarative configuration:

```yml
_format_version: "1.1"

services:
  - name: sample_api
    url: http://sample_api:80/items
    routes:
      - name: sample_api-getone
        paths: ['/items/\d+']
        methods: ['GET']
      - name: sample_api-post
        paths: ['/items']
        methods: ['POST']
```

When requesting `https://localhost/items/1234`, it returns 404 `no Route matched with those values` - but should route through the first route. The upstream API has an endpoint `/items/<itemId>`. 

Defining a path without the regex would work, but I need two routes, one with regex and one without regex, to apply different plugin configurations. On that case, the route without regex is always used.

### Additional Details & Logs

- Kong version: 2.0.3 (Docker)

**Comment by bungle** [comment]
I am not sure about yaml, but should that be:
```yaml
_format_version: "1.1"

services:
  - name: sample_api
    url: http://sample_api:80/items
    routes:
      - name: sample_api-getone
        paths:
          - /items/\d+
        strip_path: true
        methods:
          - GET
      - name: sample_api-post
        paths:
          - /items
        methods:
          - POST
```

**Comment by David-Lor** [comment]
Arrays can be specified both ways, as on my code and as on your code.

**Comment by David-Lor** [comment]
Updated removing `strip_path: true` from the failing route, which I think should not be there, although the problem remains.

**Comment by David-Lor** [comment]
I found what the issue was. The PCRE regex `\d+` only matches numbers, while I was using alphanumeric strings. Changing it to `.+` make it work, so the YML should be as this:

```yml
_format_version: "1.1"

services:
  - name: sample_api
    url: http://sample_api:80/items
    routes:
      - name: sample_api-getone
        paths: ['/items/.+']
        strip_path: true
        methods: ['GET']
      - name: sample_api-post
        paths: ['/items']
        methods: ['POST']
```

Now the problem is another one: the upstream request is not set to the requested path, although strip_path is true. But that is another different issue.
