### ISSUE TITLE
Declarative config basic auth credentials on a consumer errors when key auth is defined on a route without a name or id

### ISSUE THREAD

**Issue by nvx** [Kong/kong#5920]
### Summary and steps to reproduce

This declarative config errors:

```
_format_version: "1.1"

services:
- name: test-service
  routes:
  - paths:
    - /test/path
    plugins:
    - name: key-auth
  url: https://example.com

consumers:
- username: test-user
  basicauth_credentials:
  - username: test-username
    password: test-password
```

```
$ kong config parse test-kong.yaml
Error: Failed parsing:
in 'consumers':
  - in entry 1 of 'consumers':
    in 'basicauth_credentials':
      - in entry 1 of 'basicauth_credentials':
        in '@entity':
          - in entry 1 of '@entity': all or none of these fields must be set: 'password', 'consumer.id'

  Run with --v (verbose) or --vv (debug) for more details
```

Doing one of the following make the error not occur:
* Remove the key-auth plugin on the route
* Remove the basicauth_credentials from the consumer
* Add a name to the route
* Add an ID to the route

For example this config works fine:

```
_format_version: "1.1"

services:
- name: test-service
  routes:
  - name: test-route
    paths:
    - /test/path
    plugins:
    - name: key-auth
  url: https://example.com

consumers:
- username: test-user
  basicauth_credentials:
  - username: test-username
    password: test-password
```

### Additional Details & Logs

- Kong version: 2.0.4 (installed via RPM)
- Operating system: RHEL 7 x64

Logs and config as per above.

The error message seems buggy and related to #5750, but there seems to be an unrelated issue in that I believe this config should be valid in the first place.
