### ISSUE TITLE
strip_path default value seems to be always true

### ISSUE THREAD

**Issue by David-Lor** [Kong/kong#5928]
### Summary

I have the following declarative configuration file, working as intended:

```yml
_format_version: "1.1"

services:
  - name: sample_api
    url: http://sample_api:80
    routes:
      - name: sample_api-items-getone
        paths: ['/items/.+']
        strip_path: false
      - name: sample_api-items-list
        paths: ['/items']
        strip_path: false
      - name: sample_api-me
        paths: ['/me']
        strip_path: false
```

- Accessing http://kong/items/foo123 I want to reach upstream http://sample_api/items/foo123
- Accessing http://kong/me I want to reach upstream http://sample_api/me

But when the strip_path is set to true, OR removed (from all routes), it redirects to upstream http://sample_api/ (the root of it, as declared on the `url` of the service).

This means I had to specify `strip_path: false` on the routes so this can work. On the [documentation about strip_path](https://docs.konghq.com/2.0.x/proxy/#the-strip_path-property) it says about setting it to true, so I was thinking that not defining it should set to a default value of False, but seems it's not the case.

Is that an intended behaviour, or is just that strip_path is True by default?
