### ISSUE TITLE
kong:ubuntu and kong:2.1-ubuntu multiarch docker images are not working in aarch64 / arm VM

### ISSUE THREAD

**Issue by SrinivasanSelvam** [Kong/kong#6095]
**ISSUE DESCRIPTION**

I have created the **kubernetes pod** using **kong multiarch docker image** using the tags **kong:ubuntu and kong:2.1-ubuntu** and it is exposed as a k8s service.  But the created pod is getting **crashed only on arm / (aarch64) VM** and the **pod is working on x86 /(amd).**

**ENVIRONMENT**
I am using aarch64 ubuntu VM

**STEPS TO REPRODUCE :**

I have given the kubernetes yaml file which I have used.

**kong-k8s.yaml**
```
# kong deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apigw-kong
  name: apigw-kong
  namespace: mep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigw-kong
  template:
    metadata:
      labels:
        app: apigw-kong
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:9.6
          command: ['sh', '-c', 'until pg_isready -h postgres-db -p 5432;
                   do echo waiting for database; sleep 2; done;']
      containers:
        - name: kong-proxy
          image: kong:2.1-ubuntu
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_NGINX_WORKER_PROCESSES
              value: "1"
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 127.0.0.1:8444 ssl
            - name: KONG_PROXY_LISTEN
              value: 0.0.0.0:8000, 0.0.0.0:8443 ssl http2
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_PG_DATABASE
              value: kong
            - name: KONG_PG_HOST
              value: postgres-db
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
          ports:
            - containerPort: 8000
              name: proxy
              protocol: TCP
            - containerPort: 8443
              name: proxy-ssl
              protocol: TCP
            - containerPort: 8001
              name: admin-api
              protocol: TCP
            - containerPort: 8444
              name: admin-api-ssl
              protocol: TCP
          volumeMounts:
            - name: kongssl
              mountPath: "/run/kongssl"
              readOnly: true
      volumes:
        - name: kongssl
          secret:
            secretName: kongssl-secret


# kong service
---
apiVersion: v1
kind: Service
metadata:
  name: kong-service
  namespace: mep
spec:
  selector:
    app: apigw-kong
  type: NodePort
  ports:
    - port: 8000
      name: proxy
    - port: 8443
      name: proxy-ssl
    - port: 8001
      name: admin-api
    - port: 8444
      name: admin-api-ssl
````
**Run the yaml using**

`kubectl create -f kong-k8s.yaml`

**ERROR**
We are getting **error Backoff restarting failed container**. 

![image](https://user-images.githubusercontent.com/20473413/86952025-ff7af400-c16f-11ea-9fc0-a192fbe0c8dd.png)

**EXPECTED BEHAVIOUR:**
kubernetes pod (container) has to be started without any error

**Please someone help me to fix the issue related to kong docker images (kong:ubuntu and kong:2.1-ubuntu) on aarch64 / arm architecture.  Also, Please suggest us to find the working kong docker image (with multiarch support) for aarch64**
