### ISSUE TITLE
Kong:2.1-alpine -- cant connect to Postgres 9.6 (Docker)

### ISSUE THREAD

**Issue by jbiss** [Kong/kong#6100]
Running Docker v19.03.8 for Windows (WSL2) on Win 10 pro. Have fired up a container with Docker postgres:9.6 image. I have successfully run an empherical container to initialize the Kong database. I can connect to the postgres instance from Adminer (with the same credentials used in the Kong container) and verify the kong db has in fact been created and properly initialized (as the logs from the container also verify). When I attempt to start my Kong container it fails with the error below. All containers are running on the same network in docker.
I have confirmed the DB is up and running correctly (from container and Adminer)
DNS is resolving to the container properly (used service name in Adminer to connect to container)
User and Password are OK (connected in psql in the container and verified again through Adminer connection)
Kong 2.1 Alpine image does connect to DB in the kong-migration container

excerpts from docker-compose file
```
kong-db:
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes: 
      - kong_db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

......
kong-migration:
    image: kong:2.1-alpine
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    depends_on:
      - kong-db
...
 kong:
    image: kong:2.1-alpine
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://kong:8001"]
    #   interval: 5s
    #   timeout: 2s
    #   retries: 15
    volumes:
      - kong_logs:/usr/local/kong
      - "./kong/certs:/app/certs:ro"    
    depends_on: 
      - kong-db
    ports:
      - "8443:8443"
      - "8444:8444"

volumes:
  portainer_data:
  db_data:
  db_logs:
  elastic_data:
  kong_logs:
  kong_data:
  kong_db_data:
  rabbit_data:
  vault_data:
  vault_logs:
....
networks: 
  default:
    external:
      name: xxxxx.com
```
Kong.conf
```
prefix = /etc/nginx/ssl          
log_level = debug
proxy_access_log = logs/access.log       
proxy_error_log = logs/error.log         
admin_access_log = logs/admin_access.log 
admin_error_log = logs/error.log         
ssl_cert = /app/certs/cert.pem  
ssl_cert_key = /app/certs/privkey.pem  
admin_ssl_cert = /app/certs/cert.pem
admin_ssl_cert_key = /app/certs/privkey.pem 
proxy_listen = 0.0.0.0:8443 ssl
admin_listen = 0.0.0.0:8444 ssl    
database = postgres
pg_host = kong-db
pg_database = kong
pg_port = 5432
pg_user = kong     
pg_password = kong    
# database = off
# declarative_config = /etc/kong/kong.yml
mem_cache_size = 512m
# prefix_folder=/usr/local/kong                         

```
logfile
```
2020/07/09 16:49:31 [warn] 1#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:56
nginx: [warn] load balancing method redefined in /usr/local/kong/nginx-kong.conf:56
2020/07/09 16:49:31 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:419: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: connection refused

stack traceback:

	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:419: in function 'init'
	init_by_lua:3: in main chunk


nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:419: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: connection refused

stack traceback:

	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:419: in function 'init'
	init_by_lua:3: in main chunk
```
SUMMARY_GOES_HERE
### Steps To Reproduce

1. Start containers with the above docker-compose
2.
3.
4.
