### ISSUE TITLE
Content-length header removed

### ISSUE THREAD

**Issue by FelixRodriguezJara** [Kong/kong#6109]
### Summary

When accessing a service via Kong, the Content-lenght header is not present. However, when doing a direct connection to the service, the header shows up.

This is response header for another service using the same Kong configuration, where the content-lenght header is visible in the response from it through Kong:

```
X-Firefox-Spdy	h2
content-length	46
content-type	application/json; charset=UTF-8
date	Tue, 14 Jul 2020 15:08:32 GMT
ratelimit-limit	5
ratelimit-remaining	4
ratelimit-reset	1
server	openresty/1.15.8.1
strict-transport-security	max-age=15724800; includeSubDomains
via	kong/2.0.4
x-kong-proxy-latency	37
x-kong-upstream-latency	17
x-ratelimit-limit-hour	10000
x-ratelimit-limit-second	5
x-ratelimit-remaining-hour	9999
x-ratelimit-remaining-second	4

```
This is the response for the service that is experiencing this behaviour, where we can see how the header "Content-lenght" has disappeared and "Content-encoding: gzip" is showing. As well, "vary" header is being set. Within the service itself, headers are not set explicitly. 

```
X-Firefox-Spdy	h2
content-encoding	gzip
content-type	application/json; charset=UTF-8
date	Tue, 14 Jul 2020 15:09:50 GMT
ratelimit-limit	5
ratelimit-remaining	4
ratelimit-reset	1
server	openresty/1.15.8.1
strict-transport-security	max-age=15724800; includeSubDomains
vary	Accept-Encoding
via	kong/2.0.4
x-kong-proxy-latency	36
x-kong-upstream-latency	12
x-ratelimit-limit-hour	10000
x-ratelimit-limit-second	5
x-ratelimit-remaining-hour	9995
x-ratelimit-remaining-second	4

```

These are the headers in the response when hitting the service directly, before Kong, where we can see Content-lenght. Thus, Kong must be striping this header out:

```
Content-Length	361
Content-Type	application/json; charset=UTF-8
Date	Tue, 14 Jul 2020 15:20:16 GMT
```

Plugins used for both services are the same rate-limiting, correlation-id and key-auth.

### Steps To Reproduce

1. Deploy service A with rate-limiting, correlation-id and key-auth plugins.
2. Deploy service B with same plugins.
3. Access both services.
4. Content-lenght is showing in service A but not in service B.

### Additional Details & Logs

- Kong version (`2.0.4`)

There are no errors in the log.

**Comment by FelixRodriguezJara** [comment]
I have removed all the plugins and tested again, having the same result.

This is the way I am setting up the Ingress for this particular service. The only difference with respect with the others that are working is the path:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-contents-ingress-v1
  annotations:
    kubernetes.io/ingress.class: kong-api-gateway
    configuration.konghq.com: kong-my-bkms-ingress
    #konghq.com/plugins: api-key-auth
spec:
  rules:
  - host: kong.ext1.business-keeper.com
    http:
      paths:
      - path: /v1/default-contents/.*
        backend:
          serviceName: v1-default-contents
          servicePort: http
```

Do you see any issues with it? 

If you need anything else, don´t hesitate to letting me know.

Thank you very much.
