### ISSUE TITLE
kong 2.1.0 rc, 301 bug

### ISSUE THREAD

**Issue by RyouZhang** [Kong/kong#6132]
kong 2.1.0 rc

whehn http response 301, kong changed the response header Location

for example:
request url: https://xxxxx/api/user/profile

upstream header
Status code: 301
Location: /api/user/profile/

kong response header
Status code:301
Location: /api/user/profile/api/user/profile/

**Comment by carnei-ro** [comment]
This is happening here too, although I could not reproduce with a simple app as you describe. This is happening when I try to call an Apache Airflow eg. I have create this repo to show the error: https://github.com/carnei-ro/kong-bug-location-header

**Comment by gszr** [comment]
@RyouZhang, could you please share more info on your setup - eg, routes/services/upstreams?

**Comment by carnei-ro** [comment]
@gszr using simple service and route it can be reproduced (but I think it depends on the Upstream App too)

Here my conf:
```
_format_version: "1.1"
routes:
  - name: root
    service: airflow
    regex_priority: 1
    hosts: []
    methods: []
    preserve_host: true
    strip_path: false
    paths:
      - /
services:
  - name: airflow
    protocol: http
    host: 10.120.41.69
    port: 8080
    path: /
```

**Comment by carnei-ro** [comment]
Is it possible to be relationed to the `X-Forwarded-Prefix` header?

**Comment by gszr** [comment]
@carnei-ro @RyouZhang Here's what I'm trying:

Kong Config:
```
_format_version: "1.1"
routes:
  - name: root
    service: s1
    regex_priority: 1
    hosts: []
    methods: []
    preserve_host: true
    strip_path: false
    paths:
      - /
services:
  - name: s1
    protocol: http
    host: 127.0.0.1
    port: 8210
    path: /
```

and the mock upstream service listening on port 8210:

```
worker_processes 1;

events{}

http {
	server {
		listen 8210;
		location /redirect {
			content_by_lua_block {
				ngx.status=301
				ngx.header["Location"] = "http://localhost/foo/bar"
			}
		}
	}
}
```

Request/Response:
```
kong $ http :8000/redirect                  
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Type: text/plain
Date: Tue, 21 Jul 2020 18:35:28 GMT
Location: http://localhost/foo/bar
Server: openresty/1.15.8.3
Transfer-Encoding: chunked
Via: kong/2.1.0
X-Kong-Proxy-Latency: 0
X-Kong-Upstream-Latency: 0
```
