### ISSUE TITLE
[kong 2.1.0][DB-less] init_worker phase not ran for plugins configured from /config endpoint

### ISSUE THREAD

**Issue by cciechao** [Kong/kong#6160]
**Summary**

Open the prometheus plugin in DB-less mode to report an error

**Steps To Reproduce**
1.configure kong
```
 sed -i "/^#database/i\database = off" /etc/kong/kong.conf 
```
2.configure routes&services&plugins

```
cat > /tmp/kong.yml <<EOF
_format_version: "1.1"
services:
- name: service-httpbin
    url: http://localhost:8080
    routes:
  - name: v1
    paths:
    - /v1
plugins:
- name: prometheus
EOF
```
3.start kong

4.update declarative config file

```
curl -F  "config=@/tmp/kong.yml" localhost:8001/config
```

5.open a new terminal and send request

```
 curl http://127.0.0.1:8000/v1
```

6.after a while, view logs/error.log
![image](https://user-images.githubusercontent.com/34901092/88627660-3b560900-d0df-11ea-8cf8-82cb1e63ece2.png)

**Additional Details & Logs**

1. Kong version 2.1.0
2. CentOS Linux release 7.6.1810 (Core) 
3. Hardware 8Core16G
