### ISSUE TITLE
terminate-request plugin no enabled option

### ISSUE THREAD

**Issue by debu99** [Kong/kong#6199]
kong config parse failed

```
- name: terminate
  url: https://www.mockbin.org/request/terminate
  routes:
  - name: terminate-request
    strip_path: true
    plugins:
    - name: request-termination
      config:
        enabled: false
        status_code: 200
        body: '{"code":200}'
    paths:
    - /test/terminate
```

```
2020/08/07 08:46:59 [verbose] prefix in use: /usr/local/kong
Error:
/usr/local/share/lua/5.1/kong/cmd/config.lua:104: expected a declarative configuration file; see `kong config --help`
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/config.lua:104: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:50: in function <init_worker_by_lua:48>
	[C]: in function 'xpcall'
	init_worker_by_lua:57: in function <init_worker_by_lua:55>
```

**Comment by debu99** [comment]
fixed by https://github.com/Kong/kong/pull/6200

**Comment by locao** [comment]
Could you share the whole declarative config file so we can try to reproduce the issue, please?

**Comment by debu99** [comment]
_format_version: "1.1"

services:
- name: terminate
  url: https://www.mockbin.org/request/terminate
  routes:
  - name: terminate-request
    strip_path: true
    plugins:
    - name: request-termination
      config:
	enabled: false
        status_code: 200
        body: '{"status":200,"return":"OK"}'
    paths:
    - /test/terminate
  - name: another-request
    strip_path: true
    paths:
    - /test/222



kong config parse ./kong.yml -v
2020/08/08 17:43:45 [verbose] Kong: 2.0.4
2020/08/08 17:43:45 [verbose] prefix in use: /usr/local/opt/kong
2020/08/08 17:43:45 [verbose] reading config file at /usr/local/opt/kong/.kong_env
2020/08/08 17:43:45 [verbose] prefix in use: /usr/local/opt/kong
Error:
/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:40: attempt to index upvalue 'kong' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:40: in function 'is_on'
	/usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:184: in function 'load_subschema'
	...are/lua/5.1/kong/db/schema/others/declarative_config.lua:222: in function 'load_plugin_subschemas'
	...are/lua/5.1/kong/db/schema/others/declarative_config.lua:234: in function 'load_plugin_subschemas'
	...are/lua/5.1/kong/db/schema/others/declarative_config.lua:660: in function 'load'
	/usr/local/share/lua/5.1/kong/db/declarative/init.lua:31: in function 'new_config'
	/usr/local/share/lua/5.1/kong/cmd/config.lua:82: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>

**Comment by gszr** [comment]
Note that `enabled` is not a `config` field, but rather a top-level plugin field. Please try the following:
```
_format_version: "1.1"

services:
- name: terminate
  url: https://www.mockbin.org/request/terminate
  routes:
  - name: terminate-request
    strip_path: true
    plugins:
    - name: request-termination
      enabled: false
      config:
        status_code: 200
        body: '{"status":200,"return":"OK"}'
    paths:
    - /test/terminate
  - name: another-request
    strip_path: true
    paths:
    - /test/222
```
