### ISSUE TITLE
cannot read /usr/local/custom/kong/plugins/myplugin/handler.lua: Bad address

### ISSUE THREAD

**Issue by jkqjkq** [Kong/kong#6220]
### cannot read /usr/local/custom/kong/plugins/myplugin/handler.lua: Bad address

I want to use custom plugins in Kong, but in any case, always report **Bad Address** errors.
:cry::cry::cry:

### Environment

1.postgres:9.6
2.kong:2.1.1

#### Docker-compose
```
...
  kong:
    image: kong:latest
    restart: always
    container_name: kong
    privileged: true
    depends_on:
      - kong-migration
    healthcheck:
      test: "kong health"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_LOG_LEVEL=debug
      - KONG_PG_USER=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_LUA_PACKAGE_PATH=/usr/local/custom/?.lua;;
      - KONG_PLUGINS=bundled,myplugin
    volumes:
      - "/data/kong:/usr/local/custom"
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - kong-net
...
```
#### LOGS
```
2020/08/13 01:37:49 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:625: error loading module 'kong.plugins.myplugin.handler':

error loading module 'kong.plugins.myplugin.handler' from file '/usr/local/custom/kong/plugins/myplugin/handler.lua':

	cannot read /usr/local/custom/kong/plugins/myplugin/handler.lua: Bad address

stack traceback:

	[C]: at 0x7f206d519c20

	[C]: at 0x7f206d5190f0

	[C]: in function 'xpcall'

	/usr/local/share/lua/5.1/kong/tools/utils.lua:616: in function 'load_module_if_exists'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'

	/usr/local/share/lua/5.1/kong/init.lua:485: in function 'init'

	init_by_lua:3: in main chunk

stack traceback:

	[C]: in function 'error'

	/usr/local/share/lua/5.1/kong/tools/utils.lua:625: in function 'load_module_if_exists'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'

	/usr/local/share/lua/5.1/kong/init.lua:485: in function 'init'

	init_by_lua:3: in main chunk

nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:625: error loading module 'kong.plugins.myplugin.handler':

error loading module 'kong.plugins.myplugin.handler' from file '/usr/local/custom/kong/plugins/myplugin/handler.lua':

	cannot read /usr/local/custom/kong/plugins/myplugin/handler.lua: Bad address

stack traceback:

	[C]: at 0x7f206d519c20

	[C]: at 0x7f206d5190f0

	[C]: in function 'xpcall'

	/usr/local/share/lua/5.1/kong/tools/utils.lua:616: in function 'load_module_if_exists'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'

	/usr/local/share/lua/5.1/kong/init.lua:485: in function 'init'

	init_by_lua:3: in main chunk

stack traceback:

	[C]: in function 'error'

	/usr/local/share/lua/5.1/kong/tools/utils.lua:625: in function 'load_module_if_exists'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'

	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'

	/usr/local/share/lua/5.1/kong/init.lua:485: in function 'init'

	init_by_lua:3: in main chunk
```
