### ISSUE TITLE
Kong upstream /upstreams/{{upstream_name}}/health do not return any data when it get request time out

### ISSUE THREAD

**Issue by a2z-ice** [Kong/kong#6254]
### Summary
Hi I'm new on kong and I deployed kong on kubernetes cluster as a ingress controller with postgres. I try to simulate unhealthy status by crushing pod. The kong upstream receiving request time our when it trying to check health status. I'm expecting when I check health status in kong with   /upstreams/{{upstream_name}}/health it will show "health": "UNHEALTHY" in data but unfortunately it shows nothing in data. 

SUMMARY_GOES_HERE

### Steps To Reproduce

1. Configure upstream with followings:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
    name: auth2-keycloak-connector-health-check
    namespace: test-env
upstream:
  slots: 1000
  healthchecks:
    active:
      concurrency: 2
      healthy:
        interval: 60
        successes: 1
      http_path: /actuator/health
      type: http
      unhealthy:
        http_failures: 1
        tcp_failures: 1
        timeouts: 10
        interval: 60
```
2. Configure pods very low memory so that is continuously crashed 
3. Kong upstream getting request timeout
4. Go to `/upstreams/{{upstream_name}}/health` will give following output:
```
{
"next": null,
"data": [], <----- data is empty but expecting  "health": "UNHEALTHY"
"node_id": "2932c73b-0087-4d44-826f-73ed98a41674"
}
```

### Additional Details & Logs

- Kong version (2.1.0)
