### ISSUE TITLE
Kong 2.1.2 to 2.1.3 Upgrade issues

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6284]
### Summary

Was playing with the new 2.1.3 version and did the migrations up from 2.1.2, no issues on that. Tried to spin up new pods on 2.1.3 against the db in its pending pre migrations finish state. I am getting errors on kong starting up, seems like a default config value is needed in the code thats missing?

```
2020/08/31 06:27:25 [error] 45#0: init_by_lua error: ...kong/luarocks/share/lua/5.1/kong/db/declarative/init.lua:760: attempt to index field 'DECLARATIVE_FLIPS' (a nil value)
--
  | stack traceback:
  | ...kong/luarocks/share/lua/5.1/kong/db/declarative/init.lua:760: in main chunk
  | [C]: in function 'require'
  | /usr/local/kong/luarocks/share/lua/5.1/kong/clustering.lua:9: in main chunk
  | [C]: in function 'require'
  | /usr/local/kong/luarocks/share/lua/5.1/kong/init.lua:72: in main chunk
  | [C]: in function 'require'
  | init_by_lua:2: in main chunk
  | nginx: [error] init_by_lua error: ...kong/luarocks/share/lua/5.1/kong/db/declarative/init.lua:760: attempt to index field 'DECLARATIVE_FLIPS' (a nil value)
  | stack traceback:
  | ...kong/luarocks/share/lua/5.1/kong/db/declarative/init.lua:760: in main chunk
  | [C]: in function 'require'
  | /usr/local/kong/luarocks/share/lua/5.1/kong/clustering.lua:9: in main chunk
  | [C]: in function 'require'
  | /usr/local/kong/luarocks/share/lua/5.1/kong/init.lua:72: in main chunk
  | [C]: in function 'require'
  | init_by_lua:2: in main chunk
```

I don't even run in db-less mode either. ENV Variables for my 2.1.3 runtime are:

```
            - name: KONG_UPSTREAM_KEEPALIVE_IDLE_TIMEOUT
              value: '30'
            - name: KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS
              value: '50000'
            - name: KONG_UPSTREAM_KEEPALIVE_POOL_SIZE
              value: '400'
            - name: KONG_WORKER_CONSISTENCY
              value: eventual
            - name: KONG_WORKER_STATE_UPDATE_FREQUENCY
              value: '5'
            - name: KONG_NGINX_PROXY_REAL_IP_HEADER
              value: X-Forwarded-For
            - name: KONG_NGINX_PROXY_REAL_IP_RECURSIVE
              value: 'on'
            - name: KONG_SSL_CIPHER_SUITE
              value: intermediate
            - name: KONG_NGINX_MAIN_WORKER_PROCESSES
              value: '6'
            - name: KONG_BOUNCE_REASON
              value: 'Automated Bounce 20200511-06:58:13.262'
            - name: KONG_HEADERS
              value: latency_tokens
            - name: KONG_DNS_ORDER
              value: 'LAST,SRV,A,CNAME'
            - name: KONG_CASSANDRA_CONTACT_POINTS
              value: 'server1,server2,server3,server4,server5,server6'
            - name: KONG_LOG_LEVEL
              value: notice
            - name: KONG_PROXY_ACCESS_LOG
              value: 'off'
            - name: KONG_ADMIN_ACCESS_LOG
              value: 'off'
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ANONYMOUS_REPORTS
              value: 'off'
            - name: KONG_PROXY_LISTEN
              value: '0.0.0.0:8000, 0.0.0.0:8443 ssl http2 deferred reuseport'
            - name: KONG_ADMIN_LISTEN
              value: '0.0.0.0:8001 deferred reuseport'
            - name: KONG_MEM_CACHE_SIZE
              value: 1024m
            - name: KONG_SSL_CERT
              value: /usr/local/kong/ssl/kongcert.crt
            - name: KONG_SSL_CERT_KEY
              value: /usr/local/kong/ssl/kongprivatekey.key
            - name: KONG_SSL_CERT_DER
              value: /usr/local/kong/ssl/kongcertder.der
            - name: KONG_CLIENT_SSL
              value: 'off'
            - name: KONG_TRUSTED_IPS
              value: '0.0.0.0/0,::/0'
            - name: KONG_CLIENT_MAX_BODY_SIZE
              value: 50m
            - name: KONG_PLUGINS
              value: >-
                kong-siteminder-auth,kong-kafka-log,stargate-waf-error-log,mtls,stargate-oidc-token-revoke,kong-tx-debugger,kong-plugin-oauth,zipkin,kong-error-log,kong-oidc-implicit-token,kong-response-size-limiting,request-transformer,kong-service-virtualization,kong-cluster-drain,kong-upstream-jwt,kong-splunk-log,kong-spec-expose,kong-path-based-routing,kong-oidc-multi-idp,correlation-id,oauth2,statsd,jwt,rate-limiting,acl,request-size-limiting,request-termination,cors
            - name: KONG_CLIENT_BODY_BUFFER_SIZE
              value: 50m
            - name: KONG_ERROR_DEFAULT_TYPE
              value: text/plain
            - name: KONG_DATABASE
              value: cassandra
            - name: KONG_PG_SSL
              value: 'off'
            - name: KONG_CASSANDRA_PORT
              value: '9042'
            - name: KONG_CASSANDRA_KEYSPACE
              value: kong_dev
            - name: KONG_CASSANDRA_TIMEOUT
              value: '5000'
            - name: KONG_CASSANDRA_SSL
              value: 'on'
            - name: KONG_CASSANDRA_SSL_VERIFY
              value: 'on'
            - name: KONG_CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cassandra-secret
            - name: KONG_CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cassandra-secret
            - name: KONG_CASSANDRA_CONSISTENCY
              value: LOCAL_QUORUM
            - name: KONG_CASSANDRA_LB_POLICY
              value: RequestDCAwareRoundRobin
            - name: KONG_CASSANDRA_LOCAL_DATACENTER
              value: DC1
            - name: KONG_DB_UPDATE_FREQUENCY
              value: '5'
            - name: KONG_DB_UPDATE_PROPAGATION
              value: '5'
            - name: KONG_DB_CACHE_TTL
              value: '0'
            - name: KONG_DNS_HOSTSFILE
              value: /etc/hosts
            - name: KONG_DNS_STALE_TTL
              value: '4'
            - name: KONG_DNS_NOT_FOUND_TTL
              value: '30'
            - name: KONG_DNS_ERROR_TTL
              value: '1'
            - name: KONG_DNS_NO_SYNC
              value: 'off'
            - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
              value: /usr/local/kong/ssl/kongcert.pem
            - name: KONG_LUA_SSL_VERIFY_DEPTH
              value: '3'
            - name: KONG_LUA_SOCKET_POOL_SIZE
              value: '30'
            - name: SPLUNK_HOST
              value: gateway-env-zone-dc1.company.com
            - name: KONG_DB_CACHE_WARMUP_ENTITIES
              value: 'services,plugins,consumers'
            - name: LUA_PATH
              value: >-
                /usr/local/kong/luarocks/share/lua/5.1/?.lua;;/usr/local/kong/luarocks/share/lua/5.1/?/init.lua;
            - name: KONG_NGINX_HTTP_SSL_PROTOCOLS
              value: TLSv1.2 TLSv1.3
            - name: KONG_CASSANDRA_REFRESH_FREQUENCY
              value: '0'
```

Ended up leaving my 2.1.2 nodes running in dev on the db as it sits right now since my 2.1.3's failed to fire up. 

cc @bungle 

### Steps To Reproduce

1. Migrate from 2.1.2 to 2.1.3 running Kong with C* in db mode.
2. See if you get the same errors?

### Additional Details & Logs

- Kong version 2.1.3
