### ISSUE TITLE
Kong plugin not being created on all-in-one-db kubernetes installation

### ISSUE THREAD

**Issue by a2z-ice** [Kong/kong#6345]
### Summary

I have installed kong in my k8s cluster with all-in-one-db installation. I'm creating ingress  with plugin key-auth. After applying ingress configuration kong create associated service and route except plugins. 

### Steps To Reproduce

1. Create plugins and its other configuration with following
```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: http-auth
plugin: key-auth

---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: vadal
username: vadal

---
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: vadalcred
consumerRef: vadal
type: key-auth
config:
  key: secretkey
" | kubectl apply -f -
```
2. Create ingress
```
echo "
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: vadal-cluster
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/plugins: http-auth
spec:
  rules:
    - host: vadal.cluster.local
      http:
        paths:
          - path: /echo
            backend:
              serviceName: vadal-echo
              servicePort: 80
" | kubectl apply -f -
```
3. Output:
```
http://k8s-kongadmin:30801/services/default.vadal-echo.80/plugins
{"next":null,"data":[]}

http://k8s-kongadmin:30801/routes/default.vadal-cluster.00/plugins
{"next":null,"data":[]}
```
4. Try to access following url getting successful result without any authentication
```
curl -i http://vadal.cluster.local:kong-proxy-port/echo
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Date: Wed, 16 Sep 2020 05:30:07 GMT    
Server: echoserver
X-Kong-Upstream-Latency: 3
X-Kong-Proxy-Latency: 2
Via: kong/2.1.2
```

### Additional Details & Logs

- Kong version /2.1.2
- Database PostgreSQL 9.5.23 on x86_64-pc-linux-gnu (Debian 9.5.23-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
- Operating system CentOS 7

**Comment by hbagdi** [comment]
@a2z-ice Do you see any errors in the controller logs?

**Comment by emaincourt** [comment]
@hbagdi I am also facing the same issue. Actually, adding the annotations to the underlying `Service` object makes it work as expected but I guess it should be working with `Ingress` resources as well. Please find below the YAML manifest of my `Ingress` resource:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: jwt
spec:
  rules:
  - host: nginx.example.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
```

Am I missing something ? Both the proxy and the ingress-controller do not report errors at all, it just seems to fail silently:

```sh
λ curl http://localhost:8001/services/ae59b76c-2c90-4a31-90db-be594ac8bd90/plugins --silent | jq
{
  "next": null,
  "data": []
}
```

**Kong version /2.1.4**
