### ISSUE TITLE
setting config closing the client response failed

### ISSUE THREAD

**Issue by xichengliudui** [Kong/kong#6367]
### Summary

i wanted to hide the `Response Headers` `Server`, but i found that after I set the `KONG_HEADERS=off` env parameter, i could still see it (i also use the `/etc/kong/kong.conf.default` file but also have no effect)
```
 # Comma-separated list of headers Kong should inject in client responses.
headers = off
```

### Steps To Reproduce
docker-compose
1. 
```yaml
  kong:
    container_name: "kong"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      - TZ=Asia/Shanghai
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_HEADERS=off
    restart: always
    image: kong
```
2. docker-compose up -d

### Additional Details & Logs
```
10.40.30.106 - - [18/Sep/2020:13:52:00 +0800] "GET / HTTP/1.1" 200 9711 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
```
- Kong version (`$ kong version`):  kong `2.1.3` and `1.3.1`
- Operating system: Centos:7

**Comment by xichengliudui** [comment]
![image](https://user-images.githubusercontent.com/40875627/93562058-df5d8180-f9b7-11ea-889d-af6f26e38834.png)

**Comment by bungle** [comment]
So this happens when Kong did not proxy?

**Comment by kikito** [comment]
@xichengliudui could you give us more information with regards to how you are making the tests? In particular:

* A more complete `docker-compose.yml` file, with the postgres settings if possible (anonymized passwords are ok)
* The commands you are using to set up the Services / Routes in your example.
* Any plugins that you are using
* The way you are making requests to the proxy server (is that a browser window?) and the exact requests that are being used.

**Comment by xichengliudui** [comment]
* all contentdocker-compose.yaml
```yaml
version: "3.3"

services:

  postgres:
    container_name: "kong-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - TZ=Asia/Shanghai
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /opt/api-gateway/kong_data:/var/lib/postgresql/data
    restart: always
    image: registry.boms.com:5000/apigateway/postgres:9.6

  migration_kong:
    container_name: "migration_kong"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - TZ=Asia/Shanghai
    depends_on:
      - "postgres"
    image: kong
    command: 'kong migrations up'

  kong:
    container_name: "kong"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      - TZ=Asia/Shanghai
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_HEADERS=off
    depends_on:
      - "postgres"
      - "migration_kong"
    restart: always
    image: kong
```
* i did not create any `Service/Route` and went directly to the Admin API `http://10.20.1.104:8001` after executing `docker-compose up -d`
*  no plugins are used
```
[root@DEV1 docker-release]# curl http://10.20.1.104:8001/plugins
{"next":null,"data":[]}
```
* requests made directly using the Chrome browser
@kikito i hope it was of some help
