### ISSUE TITLE
Broken header with AWS ELB Proxy Protocol and incorrect healthcheck target

### ISSUE THREAD

**Issue by gdraganic** [Kong/kong#6399]
#### SSL Broken header
I have a problem mentioned in the title with Kong deployed on AWS EKS. Proxy protocol works for client access with http, but when trying to access with https, I can see the following in the error log:

```
2020/09/28 00:08:12 [error] 22#0: *3879 broken header: "���Y�F���#�{̹��ܠ9*��������R$�k:�=5��</A
��kj98����g@32ED�(" while reading PROXY protocol, client: X.X.X.X, server: 0.0.0.0:8443
```

This is the same problem as mentioned here: #6323 

With further inspection I can verify that Proxy protocol is working on Kong service ClusterIP, so not really sure what is the origin of this problem. This can be verified by running curl in another pod on the cluster:

```
kubectl run -ti --image curlimages/curl kong-test -- sh
/ $ curl --haproxy-protocol --insecure https://KONG_CLUSTER_IP
```

And I get the expected response: `{"message":"no Route matched with those values"}` and valid nginx access log.

#### Incorrect health check 
The other issue is that an incorrect health check target is set on the ELB with:
`service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl` 
annotation. Health check port is set for TCP port, but protocol is SSL and targets are never healthy until I manually change health check target protocol to TCP.

<img width="937" alt="Screenshot 2020-09-27 at 21 13 17" src="https://user-images.githubusercontent.com/6513388/94380424-c67e6a00-0135-11eb-815f-a2ec1a8b6e62.png">
<img width="316" alt="Screenshot 2020-09-27 at 21 13 00" src="https://user-images.githubusercontent.com/6513388/94380433-cda57800-0135-11eb-8475-5fbe1f54856c.png">

### Steps To Reproduce

1. Install Kong with helm with the following values:

`helm install -f values.yaml kong kong/kong --atomic`

```
ingressController:
  installCRDs: false
  enabled: true
admin:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
env:
  database: postgres
  pg_host: ****
  pg_user: ****
  pg_database: ****
  pg_password:
    valueFrom:
      secretKeyRef:
        key: postgresql-password
        name: ****
  trusted_ips: "0.0.0.0/0,::/0"
  real_ip_recursive: "on"
  real_ip_header: proxy_protocol
  ssl_cipher_suite: modern
  proxy_listen: 0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 ssl proxy_protocol
proxy:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:*********
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```

I have already tried with `ssl_cipher_suite` set to intermediate, modern and custom with a lot of `ssl_ciphers` combinations but nothing worked.

### Additional Details & Logs

- Kong version: 2.1.4
- Helm chart version: 1.10

Client https access works with `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp` but this is not an option because `http_x_forwarded_proto` and `http_x_forwarded_port` headers are incorrect (http, 80).

Mentioned headers work with L7 balancer targets (proxy_protocol disabled in Kong and on the ELB) but I need L4 for Websockets so this is also not an option.

**Comment by rainest** [comment]
Is there a reason that you've configured the proxy listen under `env` manually?

```
proxy_listen: 0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 ssl proxy_protocol
```
That's normally set up via the combined Service+listen configuration, i.e. for the proxy, https://github.com/Kong/charts/blob/kong-1.10.0/charts/kong/values.yaml#L163-L194

`proxy_protocol` and similar go under the `parameters` subsection (note that we add `ssl` automatically for the TLS sections, even though it's not shown).

The manual configuration you've added shouldn't necessarily cause issues, since it looks more or less the same as what the chart would generate anyway (it does disable HTTP/2, but that shouldn't matter in this context). However, that's one thing that does look a bit odd looking at the config alone.

Current versions of the chart allow for easy sidecar injection, so it may make sense to gather a tcpdump: the mangled protocol error suggests something odd that may be more obvious when looking at the actual bytes sent by the ELB/whatever sense Wireshark's dissectors can make of them. You can add that with:

```yaml
  sidecarContainers:
  - name: tcpdump
    securityContext:
      runAsUser: 0
    image: corfr/tcpdump
    command:
      - /bin/sleep
      - infinity
```
That will provide you a `tcpdump` container able to capture traffic from others in the Pod, so once that's up and running you can exec in and run `tcpdump -npi any -s0 -w /tmp/capture.pcap port 8443`, send some requests that trigger the "broken header" error, and then `kubectl copy` to retrieve the dump.

Since that's presumably TLS you'll likely need to [decrypt the capture](https://wiki.wireshark.org/TLS?action=show&redirect=SSL#TLS_Decryption) using the Kong proxy cert to see much of interest--unsure if the ELB will use a PFS suite (it probably won't allow you to dump session keys if so), but if it does you should be able to adjust `ssl_ciphers` to use non-ephemeral suites temporarily.
