### ISSUE TITLE
Client IP missing in X-FORWARDED-FOR 

### ISSUE THREAD

**Issue by rubenhak** [Kong/kong#6448]
### Summary

Client IP present on X-FORWARDED-FOR on HTTP request, but missing in HTTPS request.

The value received in X-FORWARDED-FOR header on HTTP request is "\<the-client-ip\>, \<the-k8s-node-ip\>". 
Yet in case of HTTPS request the value is "\<the-k8s-node-ip\>". The client-ip is lost. 

Running in DigitalOcean environment in case it makes difference. 

### Steps To Reproduce

Kong installation values:
```yaml
proxy:
  enabled: true
  http:
    enabled: true
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
```
Not sure what other steps to include.

### Additional Details & Logs

- Kong version: 2.1
- Kong Helm Chart version: kong-1.11.0
