### ISSUE TITLE
lua_package_path ignored by Kong

### ISSUE THREAD

**Issue by suityou01** [Kong/kong#6461]
There is an overwhelming amount of documentation to read through, and read through it I did. All weekend. I thought I understood everything and that I could sit down this morning and write a simple Hello World plugin. I was wrong.

Here was my plan. Write a simple plugin that logs "Hello World" from the new() constructor method of my plugin. That's it. Nothing more complicated.

So I built a docker-compose file which looks like this :

```
version: "3"
services:
    kong:
        image: kong:latest
        ports:
            - "8000:8000"
            - "8443:8443"
            - "8001:8001"
            - "8444:8444"
        environment:
            - KONG_DATABASE=cassandra
            - KONG_PG_HOST=kongdatabase
            - KONG_PG_USER=kong
            - KONG_PG_PASSWORD=kong
            - KONG_CASSANDRA_CONTACT_POINTS=kongdatabase
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
        depends_on: 
            - kongdatabase
            - nodesoap
        volumes: 
            - ./kong:/home/kong:rw
    kongdatabase:
        image: cassandra:3
        ports:
            - "9042:9042"
        healthcheck:
            test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
            interval: 30s
            timeout: 10s
            retries: 5
```

Note that I just want a super simple setup, where I can keep the code on the host, and have a bind mount. 

I created a folder in the host directory thus : 

src/plugins/restfulSoap

In this folder I placed 2 files
handler.lua
schema.lua

The contents of these files is irrelevant as the module does not load.

I changed the nginx-kong.conf to include this folder in the lua_package_path variable

`lua_package_path       './src/plugins/restfukSoap/?.lua;./?.lua;./?/init.lua;;;;'; `

Then I set the environment variable thusly : 

`export KONG_PLUGINS=restfulSoap`

The I issued the following commands : 

kong prepare
kong reload

In the log file for the docker container I get the following : 

```
2020/10/12 11:59:57 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:483: error loading plugin schemas: on plugin 'restfulSoap': restfulSoap plugin is enabled but not installed;
module 'kong.plugins.restfulSoap.handler' not found:No LuaRocks module found for kong.plugins.restfulSoap.handler
        no field package.preload['kong.plugins.restfulSoap.handler']
        no file './kong/plugins/restfulSoap/handler.lua'
        no file './kong/plugins/restfulSoap/handler/init.lua'
        no file '/usr/local/openresty/site/lualib/kong/plugins/restfulSoap/handler.ljbc'
        no file '/usr/local/openresty/site/lualib/kong/plugins/restfulSoap/handler/init.ljbc'
        no file '/usr/local/openresty/lualib/kong/plugins/restfulSoap/handler.ljbc'
        no file '/usr/local/openresty/lualib/kong/plugins/restfulSoap/handler/init.ljbc'
        no file '/usr/local/openresty/site/lualib/kong/plugins/restfulSoap/handler.lua'
        no file '/usr/local/openresty/site/lualib/kong/plugins/restfulSoap/handler/init.lua'
        no file '/usr/local/openresty/lualib/kong/plugins/restfulSoap/handler.lua'
        no file '/usr/local/openresty/lualib/kong/plugins/restfulSoap/handler/init.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/kong/plugins/restfulSoap/handler.lua'
        no file '/usr/local/share/lua/5.1/kong/plugins/restfulSoap/handler.lua'
        no file '/usr/local/share/lua/5.1/kong/plugins/restfulSoap/handler/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/restfulSoap/handler.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/restfulSoap/handler/init.lua'
        no file '/home/kong/.luarocks/share/lua/5.1/kong/plugins/restfulSoap/handler.lua'
        no file '/home/kong/.luarocks/share/lua/5.1/kong/plugins/restfulSoap/handler/init.lua'
        no file '/usr/local/openresty/site/lualib/kong/plugins/restfulSoap/handler.so'
        no file '/usr/local/openresty/lualib/kong/plugins/restfulSoap/handler.so'
        no file './kong/plugins/restfulSoap/handler.so'
        no file '/usr/local/lib/lua/5.1/kong/plugins/restfulSoap/handler.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/plugins/restfulSoap/handler.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/kong/.luarocks/lib/lua/5.1/kong/plugins/restfulSoap/handler.so'
        no file '/usr/local/openresty/site/lualib/kong.so'
        no file '/usr/local/openresty/lualib/kong.so'
        no file './kong.so'
        no file '/usr/local/lib/lua/5.1/kong.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/kong/.luarocks/lib/lua/5.1/kong.so'
stack traceback:
        [C]: at 0x7f91343620f0
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:616: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:483: in function 'init'
        init_by_lua:3: in main chunk

```
Which tells me that it has looked in every place for my pluging, **apart from** where I configured it to be.

Why does Kong ignore the lua_package_path in the config file?
