### ISSUE TITLE
How to manage secret credentials in Kong

### ISSUE THREAD

**Issue by ElPapi42** [Kong/kong#6467]
### Summary

Im currently using the [JWT plugging](https://docs.konghq.com/hub/kong-inc/jwt/) with Kong in DB-Less and Declarative mode, this is my current `kong.yml`:
```yml
_format_version: "2.1"

services:
  - name: mockbin
    url: http://mockbin.org/request
    plugins:
    - name: jwt
      config:
        claims_to_verify: [exp]
    routes:
    - name: mockbin
      paths:
      - /mockbin

  - name: api-users
    url: https://example.com/us
    routes:
    - name: users
      paths:
      - /users

consumers:
  - username: admin
    custom_id: 7BRAMaf3HHUuEBc6JM8vAq

jwt_secrets:
  - consumer: admin
    key: J9VNPQ6Fra_
    secret: fd9rPLDZQIM:APA91bEpJ9VNPQ6Fra_JAq7zlulw9p5a9l
```

So far, so good, everything is working as expected, but i have a concern:

on `jwt_secrets.secret` im putting the secret key used on the auth API for sign the JWT, this let Kong verify the signatures of the tokens received.

Obviously it is a bad idea to upload this secret to the git repo. How can i manage this type of secrets in Kong? maybe a env var or something like that? or what is the best pattern to face this mainstream problem?

I check the full doc but i dont see anything related to this topic, can someone give me somelight?

Thanks!

Whitman Bohorquez
