### ISSUE TITLE
key-authen plugin - Multi consumers.

### ISSUE THREAD

**Issue by toanpt3** [Kong/kong#6484]
### Summary
I have create two consumer with keyauth_credentials
```
consumers:
- custom_id: SOME_CUSTOM_ID
  username: user123
  keyauth_credentials:
  - key: 93RScDgQM3PuHZNHXOZYjOiySZDAMN3N
- custom_id: SOME_CUSTOM_ID2
  username: user1234
  keyauth_credentials:
  - key: FRHuP1d4yH9O59YLwafT2oz1Jlr1GfHi
```
How to config service A with key-auth plugin will use keyauth_credentials on user123 and  service B with key-auth plugin  will use keyauth_credentials on user1234
