### ISSUE TITLE
Kong / Declarative config / Oauth2

### ISSUE THREAD

**Issue by klems** [Kong/kong#6535]
Hello,

I already searched through the official documentation and Internet, and couldn't find an information for our Kong Install.

We are using :

Kong 2.x + PostgreSQL + Redis + Oauth2 plugin

I have read the documentation about the oauth2 plugin : (https://docs.konghq.com/hub/kong-inc/oauth2/)  
I have read the documentation about the declarative configuration : (https://docs.konghq.com/2.2.x/db-less-and-declarative-config)  

Our Goal is to maintain several YML files as templates for automatic deploys to several Kong clusters across the globe.
We are writing yml files then, we are integrating their content to PostgreSQL with :

`sudo kong config db_import api-xxx.yml`

**Everything work perfectly** but something is unclear to me to say the least.

We don't want to use curl commands on the admin port (8001), so we are using the declarative config way of doing things only.

Let's say i have this definition for a consumer with rate limiting:

```
consumers:
- username: api-user
  custom_id: "1"
  plugins:
  - name: rate-limiting
    config:
      minute: 60
      policy: redis
      redis_host: 127.0.0.1
      redis_port: 6379
```

Is it possible to create the consumer itself, like above, **and its application** within a single / several yml file ?

In the documentation, there are two separate steps/sets of instructions, firstly, you have to create the consumer, then an application :

```
curl -X POST http://kong:8001/consumers/{consumer_id}/oauth2 \
    --data "name=Test%20Application" \
```

Is it possible to include the above definition within the definition of the consumer ? if so, how ?

--> There are no declarative configuration examples for the Oauth2 plugin.
--> I did try to include but was unsuccessful so far

I found this (https://github.com/mybuilder/kongfig) :

There is one example that looks to achieve exactly what i am trying to do :

```
consumers:
  - username: iphone-app
    credentials:
      - name: oauth2
        attributes:
          name:
          client_id: # required
          client_secret:
          redirect_uri: string | [string] # required by kong
```
This repository looks outdated and of course, it's not working anymore because 'credentials' is an unknown key.

So is it possible to achieve this with the latest version of Kong ? How ?

Thanks for your help,

Regards,

**Comment by bungle** [comment]
> Is it possible to create the consumer itself, like above, and its application within a single / several yml file ?

Yes. You can use nesting or flat. Depending what is convenient to you.

Your example can be written as flat:
```
_format_version: "2.1"
_transform: true
consumers:
- username: api-user
  custom_id: "1"
plugins:
- name: rate-limiting
  consumer: api-user
  config:
    minute: 60
    policy: redis
    redis_host: 127.0.0.1
    redis_port: 6379
```

**Comment by bungle** [comment]
On thing to learn how to do this is just to start Kong with DB mode. E.g. here I do your Oauth2 example:

```sh
$ kong start
```

```sh
$ http put :8001/consumers/api-user custom_id=1
```

```sh
$ http post :8001/consumers/api-user/oauth2 name=my-app client_id=client client_secret=secret redirect_uris=http://demo.test/ -f
```

```
$ kong config db_export my.yml
```

And you should have something like this:
```yaml
_transform: false
_format_version: '2.1'
consumers:
- custom_id: '1'
  created_at: 1604514630
  id: 495ee76b-50aa-484c-82c9-7e1067308024
  tags: ~
  username: api-user
oauth2_credentials:
- created_at: 1604514652
  id: 07186945-fcde-4cce-9316-35d51c48318c
  tags: ~
  name: my-app
  client_secret: secret
  client_id: client
  redirect_uris:
  - http://demo.test/
  hash_secret: false
  client_type: confidential
  consumer: 495ee76b-50aa-484c-82c9-7e1067308024
```

**Comment by klems** [comment]
Hi, and thanks for your quick answer,

It's not what i was asking for, so I'll try to rephrase my question as English is not my mother language.

Let's assume the following :

We have a **fresh install** of : Kong 2.x + PostgreSQL + Redis + Oauth2 plugin, **everything works without issues**, the DB is **blank**.

So my question remains :

How can i create a consumer and its application, **using declarative configuration only** ?

--> I don't want to use curl or http post/pull commands.

I can do that with **EVERY plugin** so far, but i can't do that with OAUTH2 as it is not documented within the plugin page.

I want us to be able to manage the installation / configuration / deploy steps using yml files only.

In your previous answer, you are using http post / put to create things and then exporting from the DB to a yml file.

**We want to do the opposite**, let 's say we have a blank DB.

what should be append to this xxx-api.yml file :

```
_format_version: "2.1"
_transform: false

- name: api
  url: http://api.com
  plugins:
  - name: rate-limiting
    config:
      minute: 600
      policy: redis
      redis_host: 127.0.0.1
      redis_port: 6379
  - name: oauth2
    config:
      scopes:
        - email
        - phone
        - address
      mandatory_scope: true
      enable_client_credentials: true
      token_expiration: 7200
  - name: syslog
    consumer: api-user
    service: api
  routes:
  - name: api
    paths:
    - /api
    strip_path: false

consumers:
- username: api-user
  custom_id: "1"
  plugins:
  - name: rate-limiting
    config:
      minute: 60
      policy: redis
      redis_host: 127.0.0.1
      redis_port: 6379
```
to create a consumer and its application with this command :

`sudo kong config db_import xxx-api.yml`

Thanks for your help,

Regards,

**Comment by bungle** [comment]
@klems, I think I understood your question. That `yml` in my example that I gave to you, can be `config dbimport`ed to blank db.

**Comment by klems** [comment]
Sorry to insist, but it seems impossible to generate this configuration from scratch without prior curl or http post/put commands in a fresh kong install unlike all the other existing plugins.

I don't think you read my example, which is perfectly functional and don't have any "id" field, since this field is generated after consumer creation, and is not needed to create a consumer.

You are able to use it only because you did prior curl / http post/put commands, and then an export it to a file.

We are a DevOps team and want to put the entire configuration of Kong APIs as templates for easy deploys, it seems that it is not possible at the moment because of this plugin.

My above configuration with an extra :

```
curl -X POST http://127.0.0.1:8001/consumers/api-user/oauth2 \
    --data "name=ap-useri" \
    --data "client_id=client" \
    --data "client_secret=secret"
```
is valid

and my existing configuration with :

```
consumers:
- username: api-user
  custom_id: "1"
  plugins:
  - name: rate-limiting
    config:
      minute: 60
      policy: redis
      redis_host: 127.0.0.1
      redis_port: 6379

oauth2_credentials:
- name: api-user
  client_id: client
  client_secret: secret
```
is not valid and triggers :

```
Error: 
/usr/local/share/lua/5.1/kong/cmd/config.lua:110: Failed parsing:

in 'oauth2_credentials':
  - in entry 1 of 'oauth2_credentials':
    in 'consumer': required field missing
```

Of course, consumer is not setup as the database is blank ...

Thanks,
