### ISSUE TITLE
How to use kong , consul  and docker local nameserve?

### ISSUE THREAD

**Issue by Millyn** [Kong/kong#6587]
### Summary

I use Docker to run kong , and set the `env`

`- KONG_DNS_RESOLVER=172.20.1.3:8600`

172.20.1.3:8600 is my consul  service.

Then kong can query consul's dns , but can't query docker's local nameserver ,

`example`

```
### Consul ##################################
  consul:
    build:
      context: ./consul
      args:
        - CONSUL_VERSION=${CONSUL_VERSION}
    ports:
      - "8300"
      - "8400"
      - "${CONSUL_PORT}:8500"
      - "53"
    networks:
      backend:
        ipv4_address: 172.20.1.3
    command: agent -server -client=0.0.0.0 -node=consul1 -bootstrap-expect=1 -ui -datacenter=dc1

  ### Kong ################################################
  kong:
    build:
      context: ./kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_CASSANDRA_CONTACT_POINTS=kong-postgres
      - KONG_PG_HOST=172.20.1.4
      - KONG_PG_DATABASE=${KONG_POSTGRES_DB}
      - KONG_PG_USER=${KONG_POSTGRES_USER}
      - KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD}
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_DNS_RESOLVER=172.20.1.3:8600
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      backend:
        ipv4_address: 172.20.1.5
    depends_on:
      - kong-postgres
  app:
    build:
      context: ./hyperfspace
      args:
        - HYPERF_IMAGE_VERSION=${HYPERF_IMAGE_VERSION}
    ports:
      - 9501
    volumes:
      - ../hyperfapp/:/hyperf
    tty:
      true
    networks:
      backend:
        ipv4_address: 172.20.1.100
    command: php /hyperf/bin/hyperf.php start
```

kong can't query the app.

![image](https://user-images.githubusercontent.com/7987563/99543680-66e26380-29ee-11eb-90ec-3f9bd378d5fb.png)
```
{
    "message": "name resolution failed"
}
```
```
2020/11/18 15:05:11 [error] 32#0: *52 [lua] balancer.lua:900: execute(): DNS resolution failed: dns server error: 3 name error.
 Tried: ["(short)app:(na) - cache-miss","app:33 - cache-hit/stale/scheduled/dns server error: 3 name error","app:1 - cache-
hit/stale/scheduled/dns server error: 3 name error","appi:5 - cache-hit/stale/scheduled/dns server error: 3 name error"], 
client: 172.20.1.7, server: kong, request: "GET /btg HTTP/1.0", host: "kong:8000"
```

but it will be succeesful if I use ip or remove `KONG_DNS_RESOLVER`

![image](https://user-images.githubusercontent.com/7987563/99543766-81b4d800-29ee-11eb-88da-e137043996c1.png)

So , my question is `How to use Docker nameserver with DNS_RESOLVER already set`.

Thanks.

### Additional Details & Logs

- Kong version (` 1.4.0`)
- Operating system (centos / docker)
