### ISSUE TITLE
got "name resolution failed" error in k8s

### ISSUE THREAD

**Issue by apodemakeles** [Kong/kong#6678]
Kong version :  both 2.0 / 2.1  db mode
K8s version : v1.16.10

When I making a api call thought Kong，it received 503 error:
`{
    "message": "name resolution failed"
}`

All components are in k8s, db mode, the upstream url is **play.yyy.svc**，while “play” is a k8s Service and "yyy" is the namespace.
It works fine if I changed url to **play.yyy.svc.cluster.local**

logs below:
`2020/12/22 01:47:46 [error] 40#0: *1774724 [lua] balancer.lua:1123: execute(): DNS resolution failed: dns server error: 3 name error. Tried: [
"(short)play.yyy.svc:(na) 
- cache-miss","play.yyy.svc.kube-system.svc.cluster.local.:33 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc.svc.cluster.local.:33 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc.cluster.local.:33 
- cache-miss/scheduled/querying/1:play.yyy.svc.cluster.local removed/33:play.yyy.svc.cluster.local removed/dns client error: 101 empty record received","play.yyy.svc.openstacklocal:33 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc:33 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc.kube-system.svc.cluster.local.:1 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc.svc.cluster.local.:1 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc.cluster.local.:1 
- cache-miss/scheduled/querying/1:play.yyy.svc.cluster.local removed/dns client error: 101 empty record received","play.yyy.svc.openstacklocal:1 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc:1 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc.kube-system.svc.cluster.local.:5 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc.svc.cluster.local.:5 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc.cluster.local.:5 
- cache-miss/scheduled/querying/dns client error: 101 empty record received","play.yyy.svc.openstacklocal:5 
- cache-miss/scheduled/querying/dns server error: 3 name error","play.yyy.svc:5 
- cache-miss/scheduled/querying/dns server error: 3 name error"
],
......`

/etc/resolv.conf file:
`nameserver 10.68.0.2
search kube-system.svc.cluster.local. svc.cluster.local. cluster.local. openstacklocal
options ndots:5`

nslookup:
`nslookup play.yyy.svc 10.68.0.2
Server:         10.68.0.2
Address:        10.68.0.2:53

** server can't find play.yyy.svc: NXDOMAIN

** server can't find play.yyy.svc: NXDOMAIN

...
nslookup play.yyy.svc.cluster.local 10.68.0.2
Server:         10.68.0.2
Address:        10.68.0.2:53

Name:   play.yyy.svc.cluster.local
Address: 10.68.6.36`

Oddly, there is another similar k8s cluster，with exactly the same cofiguration of Kong and upstream application,  and same result of dns resolving, but everything is fine.

Maybe is the dns server's(core dns) fault, but can you guys tell me how to check the problem?

**Comment by apodemakeles** [comment]
I cannot find error log in coredns logs

**Comment by tomalexander** [comment]
I also ran into this issue with these DNS lookups:
```
  "(short)dummyservice-service.default.0.svc:(na) - cache-miss",
  "dummyservice-service.default.0.svc.kong.svc.cluster.local:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.svc.cluster.local:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.cluster.local:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.us-central1-c.c.hip-wharf-319304.internal:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.c.hip-wharf-319304.internal:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.google.internal:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.kong.svc.cluster.local:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.svc.cluster.local:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.cluster.local:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.us-central1-c.c.hip-wharf-319304.internal:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.c.hip-wharf-319304.internal:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.google.internal:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.kong.svc.cluster.local:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.svc.cluster.local:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.cluster.local:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.us-central1-c.c.hip-wharf-319304.internal:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.c.hip-wharf-319304.internal:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc.google.internal:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
  "dummyservice-service.default.0.svc:5 - cache-miss/scheduled/querying/dns server error: 3 name error"
```

whereas removing the `.0.` works. I managed to "fix" it by changing:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: kong
    # konghq.com/plugins: key-auth-mainsite
    # Redirect http to https:
    konghq.com/protocols: https
    konghq.com/https-redirect-status-code: "302"
    # cert-manager
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: demo-cert
      hosts:
        - demo.myrealdomain.app
  defaultBackend:
    service:
      name: dummyservice-service
      port:
        name: flask
```

to

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: kong
    # konghq.com/plugins: key-auth-mainsite
    # Redirect http to https:
    konghq.com/protocols: https
    konghq.com/https-redirect-status-code: "302"
    # cert-manager
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: demo-cert
      hosts:
        - demo.myrealdomain.app
  rules:
    - host: demo.myrealdomain.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummyservice-service
                port:
                  name: flask
```

Kong version 2.5
Kong Ingress Controller version 1.3.1
GKE version 1.19.10-gke.1000
