### ISSUE TITLE
IP Restriction at TCP Level.

### ISSUE THREAD

**Issue by rohank2002** [Kong/kong#6679]
### Summary
I am using Kong IP restriction plugin, according to the documentation its only compatible with HTTP and HTTPs, wanted to apply it at TCP level. Is there such a provision in Kong? Or a work around.

**Comment by bungle** [comment]
That should be doable. PR welcome, or I/we (at Kong) can take a look, but cannot promise exactly when.

**Comment by scrudge** [comment]
We are willing to submit a PR, if someone can point us in the right direction.

**Comment by dndx** [comment]
Hello @scrudge,

If you use the L4 proxy functionalities provided by Kong, It should works at the L3. See: https://docs.konghq.com/2.2.x/proxy/#proxy-tcptls-traffic

The reason why Kong's IP restriction plugin under HTTP mode (and Nginx's own [ngx_http_access_module](http://nginx.org/en/docs/http/ngx_http_access_module.html), for that matter) works in L7 mode is because the client may present headers such as `X-Forwarded-For` which is not available at L3. If we close the connection early, we will have no chance to know if the request contains any of such headers, or if such header should be trusted, etc.

**Comment by Mokto** [comment]
Sorry for reviving this but has anyone managed to use TCPIngress with ip restriction?

```
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: clickhouse
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: ip-restriction
spec:
  rules:
  - host: XXXX-tcp.domain.io
    port: 9443
    backend:
      serviceName: clickhouse-lb
      servicePort: 9000
```

The IP restriction works for HTTP but not TCP.
