### ISSUE TITLE
Stream Listen Not working as expected 

### ISSUE THREAD

**Issue by caryyu** [Kong/kong#6694]
What i'm trying to do is wanting Kong to act like as the same as Nginx stream config below:

```
stream {
  server {
    listen 7000;
    ssl_preread on;
    resolver 8.8.8.8;
    proxy_pass $ssl_preread_server_name:443;
  }
}
```

# Docker Compose Core Part

```

...

  kong-instance:
    image: kong:2.2.0
    links:
      - kong-database:kong-database
    restart: always
    ports:
      - '8000:8000'
      - '7000:7000'
      - '8443:8443'
      - '8001:8001'
    depends_on:
      - kong-database
    environment:
      - KONG_LUA_PACKAGE_PATH=/opt/?.lua;;
      - KONG_NGINX_DAEMON=off
      - KONG_NGINX_WORKER_PROCESSES=1
      - KONG_PLUGINS=bundled
      - KONG_DATABASE=postgres
      - KONG_PROXY_LISTEN=0.0.0.0:8000,0.0.0.0:8443 ssl
      - KONG_STREAM_LISTEN=0.0.0.0:7000 ssl
      - KONG_NGINX_STREAM_SSL_PREREAD=on
      - KONG_NGINX_STREAM_RESOLVER=8.8.8.8
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_STREAM_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_STREAM_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_LOG_LEVEL=debug
```

# Test Steps

```
curl -XPOST http://localhost:8001/services -d name=github-proxy -d url=tcp://github.com:443 -d protocol=tcp
curl -XPOST http://localhost:8001/services/github-proxy/routes -d name=github-proxy -d snis=github.com -d protocols=tls
openssl s_client -connect localhost:7000 -servername github.com
```

The output is:

```
...

    Verify return code: 18 (self signed certificate)
---
```

# Expected 

```
$ openssl s_client -connect github.com:443 -servername github.com

...

    Verify return code: 0 (ok)
---
```

**Comment by locao** [comment]
I don't know a lot about SSL, but it seems to me that it's expected that you don't have a github.com certificate, and that's what `openssl` is telling you, that you are using a self-signed certificate. 

Can you confirm that, @fffonion?

**Comment by caryyu** [comment]
@locao Thanks for replying, I guess the question is more about if Kong supports the stream listen able to help exchange SSL handshake between the client and the the upstream server since the SSL handshake is based on TCP layer, and that's why Nginx did it

**Comment by fffonion** [comment]
@caryyu This is currently not supported by Kong, but can be implemented with trivial change. First you will need to send such request to a non-SSL port of Kong so that Kong doesn't try to terminate the SSL connection (`KONG_STREAM_LISTEN=0.0.0.0:7000`). Then on Kong side, stream router would need to fallback `sni` to `var.ssl_preread_server_name` after https://github.com/Kong/kong/blob/master/kong/router.lua#L1776, since you already set `KONG_NGINX_STREAM_SSL_PREREAD=on`.

**Comment by caryyu** [comment]
@fffonion What did you mean by that is what i only need to do is to remove the `ssl` here (`KONG_STREAM_LISTEN=0.0.0.0:7000`) once Kong has got this covered right?

**Comment by fffonion** [comment]
@caryyu by setting `KONG_STREAM_LISTEN` to `0.0.0.0:7000` and omitting the `ssl` from your configuration, which is `0.0.0.0:7000 ssl`, meaning requests to this port is treated as plain TCP stream instead of SSL encrypted stream. In this case the SSL traffic is "passing through" Kong and only get decrypted by your upstream.

**Comment by caryyu** [comment]
@fffonion Okay, I did what you advised(without `ssl` but `KONG_STREAM_LISTEN=0.0.0.0:7000` ), the error is still persisting, the Kong log output is:

```
2021/01/13 06:39:05 [error] 26#0: *11557 stream [lua] handler.lua:1047: before(): no Route found with those values while prereading client data, client: 172.18.0.1, server: 0.0.0.0:7000
172.18.0.1 [13/Jan/2021:06:39:05 +0000] TCP 500 0 0 0.000
```

# Docker-Compose 

```
version: "2.3"

services:
  kong-database:
    image: postgres:9.6
    restart: always
    command: "-c 'max_connections=300'"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong

  kong-prepare:
    image: kong:2.2.0
    links:
      - kong-database:kong-database
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    command: kong migrations up --force

  kong-instance:
    image: kong:2.2.0
    links:
      - kong-database:kong-database
    restart: always
    ports:
      - '8000:8000'
      - '7000:7000'
      - '8443:8443'
      - '8001:8001'
    depends_on:
      - kong-database
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:8001"]
      #interval: 10s
      #timeout: 5s
      #retries: 3
      #start_period: 5s
    environment:
      - KONG_LUA_PACKAGE_PATH=/opt/?.lua;;
      - KONG_NGINX_DAEMON=off
      - KONG_NGINX_WORKER_PROCESSES=1
      - KONG_PLUGINS=bundled
      - KONG_DATABASE=postgres
      - KONG_PROXY_LISTEN=0.0.0.0:8000,0.0.0.0:8443 ssl
      - KONG_STREAM_LISTEN=0.0.0.0:7000
      - KONG_NGINX_STREAM_SSL_PREREAD=on
      - KONG_NGINX_STREAM_RESOLVER=8.8.8.8
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_STREAM_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_STREAM_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_LOG_LEVEL=debug

```

# Kong Routes and Services Setup

```
curl -XPOST http://localhost:8001/services -d name=github-proxy -d url=tcp://github.com:443 -d protocol=tcp
curl -XPOST http://localhost:8001/services/github-proxy/routes -d name=github-proxy -d snis=github.com -d protocols=tls
openssl s_client -connect localhost:7000 -servername github.com
```

# Openssl Testing Output

```
caryyu@caryyu-pc ~ % openssl version
OpenSSL 1.1.1g  21 Apr 2020

caryyu@caryyu-pc ~ % openssl s_client -connect localhost:7000 -servername github.com
CONNECTED(00000005)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 312 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

# Curl Testing Output

```
caryyu@caryyu-pc ~ % sudo vim /etc/hosts
127.0.0.1 github.com

caryyu@caryyu-pc ~ % curl -XGET https://github.com:7000 -v -I
*   Trying 127.0.0.1:7000...
* Connected to github.com (127.0.0.1) port 7000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl@1.1/cert.pem
  CApath: /usr/local/etc/openssl@1.1/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:7000
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:7000
```
