### ISSUE TITLE
Kong crashing with `missing shared dict` when specifying custom config.memory.dictionary_name in proxy-cache plugin

### ISSUE THREAD

**Issue by cristichiru** [Kong/kong#6703]
### Summary

Kong crashing with `missing shared dict` when specifying custom `config.memory.dictionary_name` in proxy-cache plugin. Previous versions worked fine. Removing `config.memory.dictionary_name` from the plugin config works fine, but... I want to use a dedicated dict with a larger size.

### Steps To Reproduce

1. Set env: `KONG_NGINX_HTTP_LUA_SHARED_DICT=proxy_cache_storage 128m`
2. Set the proxy-cache conf: `config.memory.dictionary_name=proxy_cache_storage`:
    ```yaml
    kong.yml: |-
      _format_version: "1.1"
    
      services:
      - name: aservice
        host: somehost.com
        path: /
        port: 443
        protocol: https
        routes:
        - name: aroute
          hosts:
          - myhost.com
          paths:
          - /
          preserve_host: false
          protocols:
          - https
          strip_path: false
          https_redirect_status_code: 301
        plugins:
        - name: proxy-cache
          config:
            strategy: memory
            memory:
              dictionary_name: proxy_cache_storage
            content_type:
            - text/plain
            - application/json
            - application/json;charset=utf-8
            - application/json; charset=utf-8
            #cache_control: true
            #storage_ttl: 1
            cache_ttl: 1
          enabled: true
          protocols:
          - https
          - http
    ```
3. Pod env:
    ```yaml
    env:
    - name: KONG_ADMIN_ACCESS_LOG
        value: /dev/stdout
    - name: KONG_ADMIN_ERROR_LOG
        value: /dev/stderr
    - name: KONG_ADMIN_GUI_ACCESS_LOG
        value: /dev/stdout
    - name: KONG_ADMIN_GUI_ERROR_LOG
        value: /dev/stderr
    - name: KONG_ADMIN_LISTEN
        value: '0.0.0.0:8001'
    - name: KONG_ANONYMOUS_REPORTS
        value: 'false'
    - name: KONG_CLUSTER_LISTEN
        value: 'off'
    - name: KONG_DATABASE
        value: 'off'
    - name: KONG_DECLARATIVE_CONFIG
        value: /kong_dbless/kong.yml
    - name: KONG_LOG_LEVEL
        value: info
    - name: KONG_LUA_PACKAGE_PATH
        value: /opt/?.lua;/opt/?/init.lua;;
    - name: KONG_MEM_CACHE_SIZE
        value: 2048m
    - name: KONG_NGINX_CLIENT_HEADER_BUFFER_SIZE
        value: 32k
    - name: KONG_NGINX_HTTP_INCLUDE
        value: /kong/servers.conf
    - name: KONG_NGINX_HTTP_LUA_SHARED_DICT
        value: proxy_cache_storage 128m
    - name: KONG_NGINX_HTTP_OUTPUT_BUFFERS
        value: 8 64k
    - name: KONG_NGINX_LARGE_CLIENT_HEADER_BUFFERS
        value: 4 16k
    - name: KONG_NGINX_PROXY_LARGE_CLIENT_HEADER_BUFFERS
        value: 16 128k
    - name: KONG_NGINX_WORKER_PROCESSES
        value: '1'
    - name: KONG_PORTAL_API_ACCESS_LOG
        value: /dev/stdout
    - name: KONG_PORTAL_API_ERROR_LOG
        value: /dev/stderr
    - name: KONG_PORT_MAPS
        value: '80:8000, 443:8443'
    - name: KONG_PREFIX
        value: /kong_prefix/
    - name: KONG_PROXY_ACCESS_LOG
        value: /dev/stdout
    - name: KONG_PROXY_ERROR_LOG
        value: /dev/stderr
    - name: KONG_PROXY_LISTEN
        value: '0.0.0.0:8000, 0.0.0.0:8443 http2 ssl'
    - name: KONG_STATUS_LISTEN
        value: '0.0.0.0:8100'
    - name: KONG_STREAM_LISTEN
        value: '0.0.0.0:5702'
    - name: KONG_NGINX_DAEMON
        value: 'off'
    ```

4. Checked the kong container, my lua_shared_dict is there:
    ```properties
    bash-5.0$ grep -n -B2 -A2 proxy_cache_storage /kong_prefix/nginx-kong.conf
    38-include /kong/servers.conf;
    39-lua_shared_dict prometheus_metrics 5m;
    40=lua_shared_dict proxy_cache_storage 128m;
    41-output_buffers 8 64k;
    42-ssl_prefer_server_ciphers off;
    ```
5. Error:

    ```
    2021/01/05 23:06:42 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:474: error parsing declarative config file /kong_dbless/kong.yml:
    in 'services':
      - in entry 37 of 'services':
        in 'plugins':
          - in entry 1 of 'plugins':
            in '@entity':
              - in entry 1 of '@entity': missing shared dict 'proxy_cache_storage'
    stack traceback:
    	[C]: in function 'error'
    	/usr/local/share/lua/5.1/kong/init.lua:474: in function 'init'
    	init_by_lua:11: in main chunk
    ```

### Additional Details & Logs

- Kong version 2.2.1
- Operating system: docker kong/kong:2.2.1 (Alpine Linux)
- Deployment: Kubernetes using the official chart, version: 1.8.0
