### ISSUE TITLE
The response-transformer plugin config leads to a null error

### ISSUE THREAD

**Issue by rmlodzikowski-nokia** [Kong/kong#6707]
### Summary

The response-transformer plugin doesn't validate null values in its schema and it leads to an error (a'la NullPointerException).

### Steps To Reproduce

It reproduces in both modes, DB and DB-less, so I'll show only DB-less.

1. Apply the following config:

```yaml
_format_version: "2.1"
services:
- name: service1
  url: http://localhost:8001
  routes:
  - name: route1
    paths:
    - /foo
    plugins:
    - name: response-transformer
      config:
        add:
          headers:
          - test:test1234
          json: null
          json_types: null
        append:
          headers: null
          json: null
          json_types: null
        remove:
          headers: null
          json: null
        replace:
          headers: null
          json: null
          json_types: null
        rename:
          headers: null
```

2. Send a proxy request using a path defined in the route.

```bash
$ curl localhost:8000/foo
curl: (52) Empty reply from server
```

### Additional Details & Logs

- Kong version: 2.2.1
- Kong error logs:

```
127.0.0.1 - - [07/Jan/2021:07:18:46 +0000] "GET / HTTP/1.1" 200 9366 "-" "curl/7.58.0"
2021/01/07 07:18:46 [error] 23#0: *108 failed to run header_filter_by_lua*: ...kong/plugins/response-transformer/header_transformer.lua:41: attempt to get length of field 'json' (a nil value)
stack traceback:
	...kong/plugins/response-transformer/header_transformer.lua:41: in function 'is_body_transform_set'
	...kong/plugins/response-transformer/header_transformer.lua:95: in function 'transform_headers'
	...re/lua/5.1/kong/plugins/response-transformer/handler.lua:16: in function <...re/lua/5.1/kong/plugins/response-transformer/handler.lua:15>
	/usr/local/share/lua/5.1/kong/init.lua:249: in function 'execute_plugins_iterator'
	/usr/local/share/lua/5.1/kong/init.lua:1082: in function 'header_filter'
	header_filter_by_lua:2: in main chunk while reading response header from upstream, client: 172.17.0.1, server: kong, request: "GET /foo HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "localhost:8000"
172.17.0.1 - - [07/Jan/2021:07:18:46 +0000] "GET /foo HTTP/1.1" 200 0 "-" "curl/7.58.0"
```

### Where is an issue located?
It's possible to pass null values for schema properties and the following code isn't protected against null:

**kong/plugins/response-transformer/header_transformer.lua**
```lua
local function is_body_transform_set(conf)
  return #conf.add.json     > 0 or
         #conf.remove.json  > 0 or
         #conf.replace.json > 0 or
         #conf.append.json  > 0
end
```

I know this is an edge case and you may ask why someone would pass such values, but IMO it should be handled at a plugin schema level (400 bad request) or a default value (empty array) should be forced anyway or a null value should be considered in the `is_body_transform_set` method and any other places if necessary.
