### ISSUE TITLE
Cors plugin not blocking cross origin request 

### ISSUE THREAD

**Issue by sandeepkumar8713** [Kong/kong#6714]
Following is my yaml declaration. My request header has **Host : def.com**. So as per following declaration, the request should have been blocked, instead the request is successful and request header has **Access-Control-Allow-Origin: https://abc.com**.

```
- name: cors
  service: <serivce_name>
  config:
    origins:
    - https://abc.com
    headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
```

Is there some problem in declaration?
Kong Version : 1.4.2
