### ISSUE TITLE
Cannot setup AWS EC2 instance via Cloudformation from Kong AWS AMI

### ISSUE THREAD

**Issue by jacekdalkowski** [Kong/kong#6745]
### Summary

When creating AWS EC2 instance from AMI 'ami-08f6973b6f079bec4' (https://aws.amazon.com/marketplace/pp/B06WP4TNKL for Frankfurt region, but probably the Region does not matter) using Cloudformation, an error is raised: 'The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems. '

### Steps To Reproduce

1. Create Cloudfromation file with following content:

```
AWSTemplateFormatVersion: "2010-09-09"

Description: Creates Kong API gateway 

Mappings:

  RegionKongAmiMap:
    eu-west-1:
      HVM: ami-0be95b45dd1a21ae7
    eu-west-2:
      HVM: ami-04cca2917129d06c6
    eu-central-1:
      HVM: ami-08f6973b6f079bec4

Resources: 

  GatewayHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ RegionKongAmiMap, !Ref "AWS::Region",  'HVM' ]
      InstanceType: t2.nano
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
```

2. Upload the file to AWS S3 bucket
3. Go to AWS Cloudformation page and create new stack defined by the file in EU Frankfurt region
4. During stack creation and exception is thrown when creating 'GatewayHost' instance: 'The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems. '

### Additional Details & Logs

- Kong AWS AMI 2.1.3 https://aws.amazon.com/marketplace/pp/B06WP4TNKL
