### ISSUE TITLE
How to create ratelimit based on URL/PATH

### ISSUE THREAD

**Issue by gogovan-vincentngai** [Kong/kong#6771]
Hi there ,

I know that if we need config KongPlugin and Plugin [rate-limiting](https://github.com/Kong/kong/tree/master/kong/plugins/rate-limiting)

and it can only bind to either one of ingress, service , consumer 
if we apply to ingress or service it means it globally apply to the whole service
So is that means if one of the url need ratelimt it need to be isolated ingress rules ? 
such as below

```
/abc
/cde <===need ratelimit 
/fgh
```

Below are my testing on path , which is seems not working as expected

### Summary
Installed via Helm Chart
- kong/kong	Chart 1.14.1    App 2.2    

Deploy KongPlugin Rate Limit
limit_by and path not work as expected 

### Steps To Reproduce

Deploy as below
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: demo-rate
config:
  limit_by: path
  path: /foo
  minute: 10
  policy: redis
  redis_host: redis
  redis_port: 6379
plugin: rate-limiting
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/plugins: "demo-rate"
spec:
  rules:
    - host: demo.xyz.dev
      http:
        paths:
          - backend:
              serviceName: echo
              servicePort: 80
            path: /foo
          - backend:
              serviceName: echo
              servicePort: 80
            path: /bar
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
spec:
  ports:
  - port: 8080
    name: high
    protocol: TCP
    targetPort: 8080
  - port: 80
    name: low
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
        name: echo
        ports:
        - containerPort: 8080
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources: {}
```

### Expected Result

Load Test `https://demo.xyz.dev/foo` will be appear 429 
Load Test `https://demo.xyz.dev/bar` will never  appear 429 

### Actual Result
Both appear 429
