### ISSUE TITLE
If final balancer retry fails, that try does not have the failure data recorded

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [Kong/kong#6820]
### Summary

This code records the failure details for the **previous** try:
https://github.com/Kong/kong/blob/2.3.1/kong/init.lua#L926-L928

As such, if the final retry is a failure, those details don't get recorded.

### Steps To Reproduce

1. Add service and route objects with artificial latency to force retries, e.g.
```yaml
routes:
- name: httpbin
  paths:
  - /
  preserve_host: true
  service: httpbin
  strip_path: false

services:
- name: httpbin
  host: httpbin
  protocol: http
  port: 80
  retries: 3
  connect_timeout: 1000
  read_timeout: 1000
  write_timeout: 1000
```

2. Make a request that will timeout, e.g. `/delay/2`

3. You'll see something like this in the logs:
```json
    "tries": [
        {
            "balancer_latency": 1,
            "port": 80,
            "ip": "172.20.0.4",
            "code": 504,
            "balancer_start": 1612821178453,
            "state": "failed"
        },
        {
            "balancer_latency": 0,
            "port": 80,
            "ip": "172.20.0.4",
            "code": 504,
            "balancer_start": 1612821179456,
            "state": "failed"
        },
        {
            "balancer_latency": 0,
            "port": 80,
            "ip": "172.20.0.4",
            "code": 504,
            "balancer_start": 1612821180457,
            "state": "failed"
        },
        {
            "balancer_latency": 0,
            "port": 80,
            "balancer_start": 1612821181457,
            "ip": "172.20.0.4"
        }
    ],
```

### Additional Details & Logs

- Kong version (2.3.1)
