### ISSUE TITLE
Issues configuring headers in http-log plugin

### ISSUE THREAD

**Issue by espeandr** [Kong/kong#6845]
### Summary

I'm unable to configure headers on the `http-log` plugin using the `headers` config option. I've tried several formats, but still Kong refues the configuration. I'm not sure whether I'm not configuring this correctly, or if there's a bug. Can someone provide an example of how to use the option?

I seem to need this functionality to log to splunk, which requires the auth header on the format `Authorization: Splunk -token-`

### Steps To Reproduce

1. Configure the plugin:
```yml
plugins:
  - name: http-log
    service: echo.new-logger
    config:
      http_endpoint: http://mockbin.org/bin/bc1bd4ed-563b-4787-92cd-aed657598d27
      headers:
        - "Headername:headervalue"
#       - Headername: headervalue
```

2. The logoutput:
```
2021/02/18 12:09:37 [verbose] Kong: 2.3.2
2021/02/18 12:09:37 [verbose] prefix in use: /usr/local/kong
Error: 
/usr/local/share/lua/5.1/kong/cmd/config.lua:110: Failed parsing:
in 'plugins':
  - in entry 13 of 'plugins':
    in 'config':
      in 'headers': expected a string
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/config.lua:110: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>
```
### Additional Details

- Kong version 2.3.2, declarative

**Comment by apehkone** [comment]
I had the same problem today and the following format worked for me:

```yaml
plugins:
  - name: http-log
    service: echo.new-logger
    config:
      http_endpoint: http://mockbin.org/bin/bc1bd4ed-563b-4787-92cd-aed657598d27
      headers:
        Headername:
        - headervalue
 ```
