### ISSUE TITLE
Path traversal filtering/denying ( double-dots, %2e )

### ISSUE THREAD

**Issue by cloudziu** [Kong/kong#6851]
### Filtering path traversal in kong-ingress

I have deployed Kong api gataway as ingress controler in my Kubernetes cluster, with JWT authentication plugin.
Lets assume that I have :
**two roles:**
- app_admin
- app_operator

**two endpoint hosted by one application ( one kubernetes pod ):**
- /api/admin (this one is allowed only for app_admin)
- /api/operator (this one is allowed only for app_operator)

While making "normal" requests, JWT plugin correctly evaluates which endpoint is assigned to whitch role. Example:
```
GET /api/operator
Authorization: (operator token)
```
**But** while sending malformed request 
```
GET /api/operator/../admin
Authorization: (operator token)
```
It will also give `OK 200` response. The same way it is working with encoded dots

```
GET /api/operator/%2e%2e/admin
Authorization: (operator token)
```
**IMPORTANT** : to achive this, I had to test endpoint via postman. (curl, and webbrowsers automaticly stripe the dots)
Example ingress resources:
**ADMIN ENDPOINT**
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: admin-api
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "false"
    plugins.konghq.com: kong-oidc,app-admin
    konghq.com/protocols: "https"
spec:
  tls:
    - hosts: []
      secretName: kong-key-pair
  rules:
  - http:
      paths:
      - path: /api/admin
        backend:
          serviceName: api-service
          servicePort: 80
```
**OPERATOR ENDPOINT**
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: operator-api
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "false"
    plugins.konghq.com: kong-oidc,app-operator
    konghq.com/protocols: "https"
spec:
  tls:
    - hosts: []
      secretName: kong-key-pair
  rules:
  - http:
      paths:
      - path: /api/operator
        backend:
          serviceName: api-service
          servicePort: 80
```

### Expected behaviour
Kong will deny all requests or strip the malformed part of it `../`, `%2e%2e/`.

AFAIK Kong matches here the url prefix. Everything that is after the match it will send to the specyfied service.
So my question is, is it possible to manage it in Kong configuration ? Stripping dots, or blocking those types of request based on regexp globaly, any ideas sugestions ??

Second question, is that behaviour desired? 

**Kong Ingress controller version**
kong-ingress-controller:0.9.0

**Kong or Kong Enterprise version**
Kong

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Bare metal**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- **Kernel** (e.g. `uname -a`): 
Linux ubuntu 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: bitnami helm chart
