### ISSUE TITLE
correlation-id plugin - "replace existing value" parameter

### ISSUE THREAD

**Issue by jzyinq** [Kong/kong#6856]
### Summary
As [correlation-id plugin documentation](https://docs.konghq.com/hub/kong-inc/correlation-id/#how-it-works) states:

> If a header bearing the same name is already present in the client request, it is honored and this plugin will not temper with it.

I have a case, where I don't want to trust/allow any correlation-id header that comes from an outside network and generate a new header value despite its previous value, which could be corrupted.

Generally, it is doable by using `request-transformer` plugin globally by which I'm removing any existing correlation-id header before processing such request further. 

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: remove-external-correlation-id-header
  namespace: example
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  remove:
    headers:
      - kong-request-id
plugin: request-transformer

---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: correlation-id
  namespace: example
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  generator: uuid
  echo_downstream: true
plugin: correlation-id
```

But this approach has a downside because of [plugin precedense](https://docs.konghq.com/gateway-oss/2.0.x/admin-api/#precedence) and fact that **a plugin will always be run once and only once per request**, therefore I have to repeat this `remove correlation-id header` definition for every `request-transformation` plugin usage, for example, when I want to rewrite path of internal API.

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-service-rewrite
config:
  remove: # This section have to copied along every request-transformer usage
    headers:
      - x-request-id
  replace:
    uri: /legacy-url/v1$(uri_captures[1])
plugin: request-transformer
```

That wouldn't be an issue if the correlation-id plugin has some flag that could force generating new value even for existing header e.g `config.replace` that would be by default disabled to maintain existing documentation assumption.  

And that's my feature request - Consider adding an additional configuration parameter that could force generating a new correlation-id value even when there's already an existing correlation-id header.

```yaml
config:
  generator: uuid
  echo_downstream: true
  replace: true 
```

I'm waiting patiently for your feedback :crossed_fingers: 

Source reference: 
https://github.com/Kong/kong/blob/master/kong/plugins/correlation-id/handler.lua#L56-L57
