### ISSUE TITLE
Chinese string in param which encoded in path been changed [2.3.2]

### ISSUE THREAD

**Issue by DG-Wangtao** [Kong/kong#6861]
### Summary

Chinese string in param which encoded in path been changed in version 2.3.2.
Param in path can be encoded because of PR https://github.com/Kong/kong/pull/6821, but not support chinese.
For example : my param is `%E4%B8%AD%E5%9B%BD` whith can be decode to with `decodeURIComponent` to `中国`, but I got `ä¸­å½` after decode in kong.

### Steps To Reproduce

1. use a chinese string which is encoded with `encodeURIComponent` as param , such as '%E4%B8%AD%E5%9B%BD'
2. got `ä¸­å½` after decode in kong.

### Additional Details & Logs

- Kong version (`2.3.2`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by fffonion** [comment]
Hi @DG-Wangtao, the original text is in UTF-8, `ä¸­å�½` is what you will get if you decode it with single byte charset like ISO-8859-1. AFAIK lua itself doesn't specially treat multibyte charset like UTF-8, so it's likely your code is not handling the text properly. Could you share a code snippet how you are using the "decoded" text?

**Comment by DG-Wangtao** [comment]
Hi @fffonion, thanks for the reply. kong is used as ingress in k8s.  An HTTP server and an ingress rule exist in k8s. The HTTP server gets `ä¸­å�½` in param without any custom code before. This situation only accrued with `2.3.2` but work fine with version `2.3.1`. So I think there is a problem that exists in kong while transferring params after it decodes. Maybe kong encodes params in the wrong way in this situation.

**Comment by bungle** [comment]
This is our normalization and escaping code:
```
local uri = require "kong.tools.uri"


print(("/%E4%B8%AD%E5%9B%BD/dog"))
print((uri.normalize("/%E4%B8%AD%E5%9B%BD/dog")))
print((uri.escape(uri.normalize("/%E4%B8%AD%E5%9B%BD/dog"))))
```

When I ran this I get:

```
/%E4%B8%AD%E5%9B%BD/dog
/中国/dog
/%E4%B8%AD%E5%9B%BD/dog
```
```

**Comment by bungle** [comment]
@DG-Wangtao,

you said:
> got ä¸­å�½ after decode in kong.

What did you do to get that?

**Comment by DG-Wangtao** [comment]
O~ maybe there is something wrong with my pipeline. I will write a test case later to confirm this weekend. Thanks for applying.

**Comment by javierguerragiraldez** [comment]
Closing this issue as it seems the original problem was outside of Kong.  Feel free to reopen if the issue persists.

**Comment by DG-Wangtao** [comment]
Recently I find out why this issue exists. 
## Step:
1. I create a kong `request-transformer` plugin :
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: strip-path
config:
  replace:
    uri: /$(uri_captures[1])
plugin: request-transformer
```
2. I create a kong ingress witch path look like this: `/(.*)`
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: strip-path
    kubernetes.io/ingress.class: in-kong
  name: nginx
spec:
  rules:
  -  http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /kong-debug/(.*)
```
3. and then I put encode string in the path of my request like this: `http://{ip-host}/%E5%8C%97%E4%BA%AC%E5%9F%8E%E5%8C%BA`
4. then kong decode the `%E5%8C%97%E4%BA%AC%E5%9F%8E%E5%8C%BA` to `北京城区`
5. the encoded string will keep encoded if it exists in param after `?`.

## All resources defines:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: strip-path
config:
  replace:
    uri: /$(uri_captures[1])
plugin: request-transformer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          name: config
          readOnly: true
      volumes:
      - configMap:
          items:
          - key: "nginx.conf"
            path: "nginx.conf"
          name: nginx-config
        name: config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: api-port
    port: 80
    protocol: TCP
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    user    root;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;

    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }


    http {
        default_type  text/plain;

        server {
            listen 80;
            location / {
                return 200 $request_uri;
            }
        }
    }
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: strip-path
    kubernetes.io/ingress.class: in-kong
  name: nginx
spec:
  rules:
  -  http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /kong-debug/(.*)

```

The reason why I don't use `konghq.com/strip-path: true` is that this annotation trip all path prefix but I need a part of the prefix.
I create an ingress : 
```yaml
  - host: {{.Values.domain}}
    http:
      paths:
      - backend:
          serviceName: server1
          servicePort: 80
        path: /api/(path1/.*)
  - host: {{.Values.domain}}
    http:
      paths:
      - backend:
          serviceName: server2
          servicePort: 80
        path: /api/(path2/.*)
```
server1 wants request path `path1/.*` while server2 wants  path `path2/.*`.
Maybe this is not recommended and now my solution is just to move the encoded string to param after `?` from the path.

Is there any plan to change the behavior that decodes string in `request-transformer`plugin?

Thanks for your help.
