### ISSUE TITLE
Plugin name in Kong Manager is wrong when using declarative yaml

### ISSUE THREAD

**Issue by eladbs** [Kong/kong#6876]
### Summary

When configuring a plugin with declarative yaml, the name that is showing in the Kong Manager is wrong - it shows the plugin type instead of plugin name.

### Steps To Reproduce

1. Let's say we have a plugin called "my-plugin". Let's configure a yaml file for it:
```
# vim my-plugin.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: plugin-name
config:
  key_ex: value_ex
plugin: my-plugin
```
2. kubectl apply -f my-plugin.yaml
3. Log in to Kong Manager and under "Plugins" check that the plugin is loaded
![image](https://user-images.githubusercontent.com/1691671/109424908-8ece6380-79ee-11eb-8835-2972f4ab94e4.png)

4. Expected: behavior
![image](https://user-images.githubusercontent.com/1691671/109424957-c1785c00-79ee-11eb-9cb8-dc60f98108ce.png)

### Additional Details & Logs

- Kong version 2.1.4.2
