### ISSUE TITLE
KONG_DECLARATIVE_CONFIG configuration template

### ISSUE THREAD

**Issue by cobolbaby** [Kong/kong#6911]
### Summary

What are the optional configuration items in the `KONG_DECLARATIVE_CONFIG` configuration file? Where should I find it? 

In addition, the configuration of version 1.5.x as follows show that the relationship between route and service is declared twice? Is that right?

```
_format_version: "1.1"
services:
- name: adminapi
  url: http://127.0.0.1:8808
  routes:
  - name: adminapi-route
    paths:
    - /
- name: nocache
  host: 10.191.4.85
  port: 8000
  protocol: http
  routes:
  - name: nocache-route
    paths:
    - /

routes:
- name: adminapi-route
  service: adminapi
  paths: ["/adminapi"]
- name: nocache-route
  service: nocache
  hosts: ["itcnd-nocache.te"]
```
