### ISSUE TITLE
double access_log entries when using KONG_NGINX_PROXY_ACCESS_LOG variable

### ISSUE THREAD

**Issue by vladimir259** [Kong/kong#6915]
### Summary

Running kong in k8s i try to use my custom "access_log" format.
The definition of that custom format works fine, however when i use the KONG_NGINX_PROXY_ACCESS_LOG variable to enable its (custom log format) usage, the rendered configuration contains TWO access_log format entries - one which comes from the lua-template(https://github.com/Kong/kong/blob/master/kong/templates/nginx_kong.lua#L80), and one that comes from my custom variable.

As a result i have TWO log entries for each request.
One with the default log_format and one with my custom log_format.

### Steps To Reproduce

1. create following, declarative kong.yml
```
_format_version: "2.1"
_transform: true
services:
  - name: google-api
    url: https://api.google.com
    routes:
      - name: googleapi
        paths:
          - /google
```
2. create following docker-compose.yml
```
version: '3.7'

services:
  kong-dev:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_STATUS_LISTEN: "0.0.0.0:8100"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001 reuseport backlog=16384"
      KONG_TRUSTED_IPS: "10.0.0.0/8"
      # NGINX directives injection
      # https://docs.konghq.com/gateway-oss/2.1.x/configuration/#nginx-injected-directives-section
      # The resulting generated config is /usr/local/kong/nginx-kong.conf inside of the container.
      KONG_NGINX_HTTP_PROXY_BUFFER_SIZE: "32k"
      KONG_NGINX_HTTP_PROXY_BUFFERS: "4 32k"
      KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE: 10m
      KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE: 200m
      # in case of docker-compose the variables have to have escaped by using double $$.
      # when launched in k8s - use a single $
      KONG_NGINX_HTTP_LOG_FORMAT: |
        custom_format '$$remote_addr $$http_x_request_id $$remote_user [$$time_local] \"$$request\" $$status $$body_bytes_sent \"$$http_referer\" \"$$http_user_agent\" some_foo_field'
      KONG_NGINX_PROXY_ACCESS_LOG: "logs/access.log custom_format"

    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    ports:
      - 18000:8000
    restart: on-failure
```
3. in the first terminal - start the container
```
docker-compose -f docker-compose.yml up
```
4. in a second terminal - do a curl request to it
```
curl "localhost:18000/google/foo?bar"
```
5. in the first terminal - observe TWO log entries

### Additional Details & Logs

Here a summary as screenshot:
![image](https://user-images.githubusercontent.com/79702343/110825864-c9f55000-8294-11eb-9873-818abd3b2ebf.png)

- Kong version 2.3.0
- Kong debug-level startup logs: [startup.log](https://github.com/Kong/kong/files/6124669/startup.log) (yes, "Address in use", sure - im launching a second instance inside of the container. But you do see the preflight output)
- Kong error logs: none
- Kong configuration: kong.yml from above
- Operating system: official kong:latest docker image

The root cause is the file

https://github.com/Kong/kong/blob/master/kong/templates/nginx_kong.lua#L80

which should imho have a variable PROXY_ACCESS_LOG_FORMAT 

![image](https://user-images.githubusercontent.com/79702343/110827410-53f1e880-8296-11eb-863e-8cadd3eff804.png)

and respect it; thus the line 80 could look like
```
    access_log ${{PROXY_ACCESS_LOG}} ${{PROXY_ACCESS_LOG_FORMAT}};
```
where the variable $PROXY_ACCESS_LOG_FORMAT would fallback to kong's default proxy_access log_format.

**Comment by thspinto** [comment]
@vladimir259 I didn't notice this issue in my tests. Do you think PR #6900 would help in your case?

**Comment by vladimir259** [comment]
@thspinto i think not, as far i can see your PR refers to STREAM portion of the proxy but not to HTTP-proxy of kong

**Comment by vladimir259** [comment]
Hi,

yes, having a

```
KONG_PROXY_ACCESS_LOG
```
set to
```
"logs/access.log custom_format"
```

worked.

Here a complete docker-compose.yml:
```
version: '3.7'

services:
  kong-dev:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_STATUS_LISTEN: "0.0.0.0:8100"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001 reuseport backlog=16384"
      KONG_TRUSTED_IPS: "10.0.0.0/8"
      # NGINX directives injection
      # https://docs.konghq.com/gateway-oss/2.1.x/configuration/#nginx-injected-directives-section
      # The resulting generated config is /usr/local/kong/nginx-kong.conf inside of the container.
      KONG_NGINX_HTTP_PROXY_BUFFER_SIZE: "32k"
      KONG_NGINX_HTTP_PROXY_BUFFERS: "4 32k"
      KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE: 10m
      KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE: 200m
      # in case of docker-compose the variables have to have escaped by using double $$.
      # when launched in k8s - use a single $
      KONG_NGINX_HTTP_LOG_FORMAT: |
        custom_format '$$remote_addr $$http_x_request_id $$remote_user [$$time_local] \"$$request\" $$status $$body_bytes_sent \"$$http_referer\" \"$$http_user_agent\" some_foo_field'
      # wrong logging behavior - produces duplicate log entries
      #KONG_NGINX_PROXY_ACCESS_LOG: "logs/access.log custom_format"
      # correct logging behavior - one log entry per request
      KONG_PROXY_ACCESS_LOG: "logs/access.log custom_format"

    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    ports:
      - 18000:8000
    restart: on-failure
```

However i'm confused. Since this is a nginx-directive/variable, according to my understanding of https://docs.konghq.com/gateway-oss/2.3.x/configuration/ it has to be prepended with
```
KONG_NGINX_
```
and not with
```
KONG_
```
But, well, great that it worked. 

Thanks for the hint @dndx !
