### ISSUE TITLE
YAML Anchors not working on kong 2.3 declarative config

### ISSUE THREAD

**Issue by hrodic** [Kong/kong#6923]
### Summary

YAML Anchors that worked in kong 1.x do no longer work on kong 2.x

Anchors and aliases are a core feature for YAML that allows DRY and improve maintainability and file sizing.

### Steps To Reproduce

1. in your declarative configuration define an anchor for reusing configuration blocks.
```
RedisRateLimitDefaultConfig: &redisRateLimitDefaultConfig
  policy: redis
  redis_host: redis
  redis_port: 6379
  redis_timeout: 2000
  redis_database: 1
  limit_by: consumer
  fault_tolerant: true

```

2. then use this anchor somewhere, for instance in a consumer.
```
 plugins:
      - name: rate-limiting
        config:
          <<: *redisRateLimitDefaultConfig
          second: 10

```

run kong parsing of the config and see the error
`kong config parse /etc/kong/declarative.yml`

```
Error: Failed parsing:
in 'RedisRateLimitDefaultConfig': unknown field
```

In Kong 1.4 it does work. In kong 2.3 it doesn't (i suspect is related with _format_version: "2.1" of the declarative YML file.)

### Additional Details & Logs

- Kong version: 2.3.3  (docker)
- Vanilla with dbless declarative.

**Comment by dndx** [comment]
Need to verify if `lyaml` which we use for parsing YAML file even supports anchors.

**Comment by dndx** [comment]
Hello,

I have verified and YAML anchors are working correctly in 2.x. The reason for the failure is that you can not define a top level object just for anchoring because it changes the config structure and in Kong 2.x we do check for unknown entries in the declarative config and error out if we find one instead of silently dropping them.

Here is an example that I have confirmed to be working in 2.x:

```
_transform: false
_format_version: '2.1'

services:
- name: s1
  url: http://127.0.0.1:9000/s1

- name: s2
  url: http://127.0.0.1:9000/s2

plugins:
- name: rate-limiting
  service: s1
  config: &redisRateLimitDefaultConfig
    second: 5
    hour: 10000
    policy: local

- name: rate-limiting
  service: s2
  config:
    <<: *redisRateLimitDefaultConfig
    second: 10
```

Note in this case the addition of anchors did not change the config schema, and therefore passes Kong's validator as expected.
