### ISSUE TITLE
Upstream Keepalive Max Request not respected

### ISSUE THREAD

**Issue by james-dexter** [Kong/kong#7041]
### Summary
Given an increased KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS values
When HTTP requests from a single client exceeds 100 requests
Then the connection is closed by the server  

Verifying the issue with wireshark capturing the request to kong, and at the 100th request kong replies with FIN/ACK.
### Steps To Reproduce

1. Set env.KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS: 150 
2. Start Kong in Docker
3. initiate 101 HTTP GET requests towards Kong (using curl)
4. Request 100 is followed by a connection close

### Additional Details & Logs
Docker-compose is used for this effort.

```
version: '3.5'
networks:
  kong-net:
services:
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    container_name: kong
    volumes:
      - ${PWD}:/etc/kong/config
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/config/formated.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS: 150
      KONG_LOG_LEVEL: debug
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
  helloworld:
    image: nginx:latest
    container_name: helloworld
    ports:
      - '9091:80'
    networks:
      - kong-net
```

Kong.yml with upstream defined.
```
_format_version: "1.1"
services:
  - host: helloworld
    name: helloworld
    port: 80
    protocol: http
    read_timeout: 30000
    retries: 5
    routes:
      - name: doc
        paths:
          - /
          - /broken
        protocols:
          - http
          - https
        regex_priority: 0
        strip_path: true
upstreams:
  - algorithm: consistent-hashing
    hash_fallback: none
    hash_on: ip
    hash_on_cookie_path: /
    healthchecks:
      active:
        concurrency: 10
        healthy:
          http_statuses:
            - 200
          interval: 30
          successes: 2
        http_path: /
        https_verify_certificate: true
        timeout: 1
        type: http
        unhealthy:
          http_failures: 2
          http_statuses:
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
          interval: 2
          tcp_failures: 2
          timeouts: 2
      passive:
        healthy:
          http_statuses:
            - 200
            - 400
            - 404
          successes: 2
        unhealthy:
          http_failures: 1
          http_statuses:
            - 500
            - 503
          tcp_failures: 1
          timeouts: 1
      threshold: 0
    name: helloworld
    slots: 10000
    targets:
      - target: helloworld:80
        weight: 100
`


````172.22.0.1 - - [14/Apr/2021:21:16:54 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.54.0"
2021/04/14 21:16:54 [debug] 27#0: *730 [lua] consistent_hashing.lua:161: getPeer(): [upstream:helloworld 1] trying to get peer with value to hash: [172.22.0.1]
2021/04/14 21:16:54 [debug] 27#0: *730 [lua] init.lua:1002: balancer(): setting address (try 1): 172.22.0.2:80
2021/04/14 21:16:54 [debug] 27#0: *730 [lua] init.lua:1031: balancer(): enabled connection keepalive (pool=172.22.0.2|80, pool_size=300, idle_timeout=60, max_requests=150)
172.22.0.1 - - [14/Apr/2021:21:16:54 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.54.0"
2021/04/14 21:16:54 [info] 27#0: *730 client 172.22.0.1 closed keepalive connection
`

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
