### ISSUE TITLE
Kong 2.4.0 Cannot load kong.tools.timestamp in sandbox

### ISSUE THREAD

**Issue by tingeltangelthomas** [Kong/kong#7062]
Hi,

I'm not able to convert unix timestamp to a human readable format with new custom_fields_by_lua logic of file-log plugin.

Plugin configuration and lua code:
```
    plugins:
      - name: file-log
        config:
          path: /dev/stdout
          custom_fields_by_lua:
            timestamp: |
              local tools = require "kong.tools.timestamp"
              return tools.get_timetable(tools.get_utc_ms()):rfc_3339()
```

Regarding ENV variables:
```
        - name: KONG_UNTRUSTED_LUA_SANDBOX_REQUIRES
          value: kong.tools.timestamp
        - name: KONG_PLUGINS
          value: zipkin,prometheus,mtls-lua,file-log-extended,file-log
```

Error:
``` 
2021/04/19 14:11:29 [error] 24#0: *594 failed to run log_by_lua*: /usr/local/share/lua/5.1/kong/tools/kong-lua-sandbox.lua:170: /usr/local/share/lua/5.1/luatz/tzfile.lua:59: attempt to call method 'rep' (a nil value)
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/tools/kong-lua-sandbox.lua:170: in function </usr/local/share/lua/5.1/kong/tools/kong-lua-sandbox.lua:154>
        /usr/local/share/lua/5.1/kong/plugins/file-log/handler.lua:79: in function </usr/local/share/lua/5.1/kong/plugins/file-log/handler.lua:75>
        /usr/local/share/lua/5.1/kong/init.lua:265: in function 'execute_plugins_iterator'
        /usr/local/share/lua/5.1/kong/init.lua:1300: in function 'log'
        log_by_lua(nginx-kong.conf:112):2: in main chunk while logging request, client: 192.168.18.1, server: kong, request: "POST /reqcb/c HTTP/1.1", upstream: xxxx
``` 

Regarding sandbox documentation the function string.rep is unsafe. 

**Buf if I add "bundled" to KONG_PLUGINS, it works without any errors.**

Why it is working, if I load bundled plugins?
How to convert timestamps to a human readable format without using unsafe functions?
If there is no way, what do I need to add to KONG_UNTRUSTED_LUA_SANDBOX_REQUIRES variable to get it running?

Thank you!

Regards
Thomas

**Comment by tingeltangelthomas** [comment]
Hi @kikito 
thanks for your quick answer.

> at least oauth2, response-ratelimiting and rate-limiting

If I load any of them, it works.

Adding `string.rep` to `KONG_UNTRUSTED_LUA_SANDBOX_ENVIRONMENT` doesn't work as expected.
I get still the same error `attempt to call method 'rep' (a nil value)`.

Any other idea except enabling `KONG_UNTRUSTED_LUA`?

**Comment by kikito** [comment]
Hello, I have done several tests locally and KONG_UNTRUSTED_LUA seems to be enabling `string.rep` for me. Perhaps there is a difference in our infrastructure setup.

Could you tell me more about how your setup? I see that there is some declarative config. How are the environment variables set in your system?

**Comment by tingeltangelthomas** [comment]
It works with setting `KONG_UNTRUSTED_LUA=on`, yes!
But `KONG_UNTRUSTED_LUA_SANDBOX_ENVIRONMENT=string.rep` does not change the result.

I just tried it with my local docker. It seems the only way is to enable untrusted lua at all?
```
docker run --rm --name kong \
     --mount type=bind,source="$(pwd)"/conf,target=/usr/local/kong/declarative \
     -e "KONG_DATABASE=off" \
     -e "KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
     -e "KONG_PLUGINS=file-log" \
     -e "KONG_UNTRUSTED_LUA_SANDBOX_REQUIRES=kong.tools.timestamp" \
     -e "KONG_UNTRUSTED_LUA_SANDBOX_ENVIRONMENT=string.rep" \
     -p 8000:8000 \
     -p 8443:8443 \
     -p 127.0.0.1:8001:8001 \
     -p 127.0.0.1:8444:8444 \
     --network my-net \
     --name kong \
     docker.io/kong:2.4.0
``` 

```
_format_version: "2.1"
_transform: true

plugins:
- name: file-log
  config:
    path: /dev/stdout
    custom_fields_by_lua:
      timestamp: |
        local tools = require "kong.tools.timestamp"
        return tools.get_timetable(tools.get_utc_ms()):rfc_3339()

services:
- name: my-service
  host: httpbin
  port: 80
  routes:
  - name: my-route
    paths:
    - /
```
