### ISSUE TITLE
Unable to proxy postgres traffic with TCPIngress

### ISSUE THREAD

**Issue by landorg** [Kong/kong#7073]
### Summary
I setup a TCPIngress to forward postgres traffic (setup tls on the postgres directly as its using some application level tls) and I'm getting this error:
```
2021/04/21 13:37:43 [error] 27#0: *1002863 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/init.lua:657: body must be a nil or a string
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/pdk/response.lua:849: in function 'after'
	/usr/local/share/lua/5.1/kong/init.lua:657: in function 'preread'
	preread_by_lua(nginx-kong-stream.conf:94):2: in main chunk while prereading client data, client: x.x.x.x, server: 0.0.0.0:9000
x.x.x.x [21/Apr/2021:13:37:43 +0000] TCP 500 0 0 0.017
```

### Steps To Reproduce
```yaml
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: terraform-state
  namespace: terraform
spec:
  rules:
  - backend:
      serviceName: terraform-postgres-cluster.terraform.svc.cluster.local
      servicePort: 5432
    port: 9000
```
values.yml
```yaml
...
  stream:
  - containerPort: 9000
    servicePort: 9000
    hostPort: 9000
```

1. `psql -h y.y.y.y -p 9000 -U postgres`
