### ISSUE TITLE
key-auth plugin always return 401 in Kubernetes cluster

### ISSUE THREAD

**Issue by sergio-margale** [Kong/kong#7101]
### Summary

I'm kind of new to Kong, and I'm battling for the last few days to secure one endpoint of a service with the key-auth plugin. However I always get a 401 when requesting it no matter the apikey is correct or not.
```json
{
  "message":"Invalid authentication credentials"
}
```
When no apikey is added in the request I also get a 401 but with the correct body
```json
{
  "message":"No API key found in request"
}
```

Here is my configuration under Kong 2.2.2:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: xxx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
  selector:
    app: my-service
    #    version: 0.0.0
    heritage: Helm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  namespace: xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
      heritage: Helm
  #      version: 0.0.0
  template:
    metadata:
      labels:
      annotations:
    spec:
      containers:
        - name: my-service
          image: <the-image>
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: TCP
          env:
            - name: AWS_METADATA_SERVICE_TIMEOUT
              value: "5"
            - name: AWS_METADATA_SERVICE_NUM_ATTEMPTS
              value: "20"
      terminationGracePeriodSeconds: 60
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: xxx
  name: "my-service"
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: "my-service.dev.my-org.com"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "my-service"
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: xxx
  name: my-service-secure
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: my-service-creds
spec:
  rules:
    - host: "api.dev.my-org.com"
      http:
        paths:
          - path: "/my-service/my-endpoint"
            backend:
              serviceName: "my-service"
              servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: my-service-consumer
  namespace: xxx
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: my-service-creds
username: my-service-user
credentials:
  - my-service-apikey
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: key-auth
metadata:
  name: my-service-creds
  namespace: xxx
config:
  key_names:
    - apikey
```

The apikey was created via kubectl 
```
kubectl create secret generic my-service-apikey --from-literal=kongCredType=key-auth --from-literal=key=the-literal-key  --namespace xxx
```

**Comment by sergio-margale** [comment]
When having only one Ingress everything works fine, but then every endpoint (such as `/ready` or `/healthy`) requires the apikey, and I would like to avoid that.

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: xxx
  name: my-service
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: my-service-creds
spec:
  rules:
    - host: "api.dev.my-org.com"
      http:
        paths:
          - path: "/my-service/my-endpoint"
            backend:
              serviceName: "my-service"
              servicePort: 80
    - host: "my-service.dev.my-org.com"
        http:
          paths:
            - path: "/"
              backend:
                serviceName: "my-service"
                servicePort: 80
```
