### ISSUE TITLE
Kong 2.4 Auth Bugs OAuth2.0 , JWT. 

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#7105]
### Summary

Seeing some unexplainable behavior out of my Kong Dev nodes post upgrade to 2.4, Sometime attempting to generate an OAuth2.0 token fails with an error in a given datacenter, while the other DC succeeds to generate a token(and each DC may be able to flip flop after redeployments.. and sometimes I think I have seen moments where both DC deployments can work at the same time too, its very odd and not fully predictable). I also may have seen a similar issue with JWT Auth plugin telling me the error (No credentials found for given 'iss') found for given JWT token the gateway received on a proxy request but figured we take this one at a time and see if we can see what may cause the OAuth2.0 behavior, might fix the common core component that also made JWT auth seemingly fail... Nothing in the SRC code of OAuth2.0 in the version bump changes make sense for how they could be the culprit for this behavior, + I remember testing the changes in the OAuth2.0 plugin on earlier versions of Kong to improve the edge cases and OAuth2.0 worked fine then so I think its something indirectly related that has done this...

Example:

Fail case:

```
POST https://gateway-dev-network-zone-dc2.company.com/auth/oauth2/token

{
 "client_id": "6RE9IXHWgBbfybOXCqxZkUZnCQPKEuIV",
 "client_secret": "C1nnQ0wmwgT2PkUunUhs8NfkMQLNM7CA",
 "grant_type": "client_credentials"
}
```

Response:

```
Status: 400

{
    "error": "invalid_client",
    "error_description": "Invalid client authentication"
}
```

And Success Case:

```
POST https://gateway-dev-network-zone-dc1.company.com/auth/oauth2/token

{
 "client_id": "6RE9IXHWgBbfybOXCqxZkUZnCQPKEuIV",
 "client_secret": "C1nnQ0wmwgT2PkUunUhs8NfkMQLNM7CA",
 "grant_type": "client_credentials"
}
```

Response:

```
Status: 200

{
    "expires_in": 3600,
    "access_token": "PcH8nuM7MSI1SHAHVv4QrK8psIq75c8X",
    "token_type": "bearer"
}
```

OAuth2.0 Plugin configured on the Gateway endpoint Kong 2.4:
```
{
  "name": "oauth2",
  "route": {
    "id": "ab469dbf-3806-4b22-8a32-246d7b158360"
  },
  "created_at": 1528309696,
  "tags": null,
  "id": "50a3fcfa-a660-425b-b181-698e8d1a196d",
  "config": {
    "enable_client_credentials": true,
    "enable_password_grant": false,
    "enable_authorization_code": false,
    "auth_header_name": "authorization",
    "reuse_refresh_token": false,
    "enable_implicit_grant": false,
    "token_expiration": 3600,
    "accept_http_if_already_terminated": false,
    "hide_credentials": false,
    "anonymous": null,
    "scopes": null,
    "provision_key": "function",
    "refresh_token_ttl": 3600,
    "global_credentials": true,
    "pkce": "lax",
    "mandatory_scope": false
  },
  "service": null,
  "consumer": null,
  "enabled": true,
  "protocols": [
    "http",
    "https"
  ]
}
```

Data of our user above from the DB for further evidence from C*, first their credential pair as seen above:
```
kongdba@cqlsh:kong_dev> select * from oauth2_credentials WHERE client_secret='C1nnQ0wmwgT2PkUunUhs8NfkMQLNM7CA';

 id                                   | client_id                                                             | client_secret                    | client_type  | consumer_id                          | created_at                      | hash_secret | name   | redirect_uris         | tags | ws_id
--------------------------------------+-----------------------------------------------------------------------+----------------------------------+--------------+--------------------------------------+---------------------------------+-------------+--------+-----------------------+------+--------------------------------------
 16093f3c-c51d-4523-ab10-1fa91464d443 | 7e175ef7-c50d-49d1-a648-0091156e2b4c:6RE9IXHWgBbfybOXCqxZkUZnCQPKEuIV | C1nnQ0wmwgT2PkUunUhs8NfkMQLNM7CA | confidential | 092798fd-5055-4b14-a699-4f915d874695 | 2019-02-22 18:59:48.000000+0000 |       False | oauth2 | {'https://optum.com'} | null | 7e175ef7-c50d-49d1-a648-0091156e2b4c

(1 rows)
```

And their consumer table data:
```
kongdba@cqlsh:kong_dev> select * from consumers WHERE id=092798fd-5055-4b14-a699-4f915d874695;

 id                                   | created_at                      | custom_id | tags | username                                                | ws_id
--------------------------------------+---------------------------------+-----------+------+---------------------------------------------------------+--------------------------------------
 092798fd-5055-4b14-a699-4f915d874695 | 2019-02-22 18:59:48.000000+0000 |      null | null | 7e175ef7-c50d-49d1-a648-0091156e2b4c:stargate.testsuite | 7e175ef7-c50d-49d1-a648-0091156e2b4c

(1 rows)
```

Workspace table just for reference, thought that could be the culprit but nah just 1 entry that is in sync w the above tables:
```
kongdba@cqlsh:kong_dev> select * from workspaces;

 id                                   | comment | config | created_at                      | meta | name
--------------------------------------+---------+--------+---------------------------------+------+---------
 7e175ef7-c50d-49d1-a648-0091156e2b4c |    null |   null | 2020-07-21 20:21:51.000000+0000 | null | default
```

Note just for sanity I even was querying the local 3 node cluster in the DC thats currently throwing the oauth2 token gen error just to prove the actual raw data seems to be there and in place.. Why Kong seemingly does not resolve the db data consistently to recognize our user here and their token gen request creds I am not sure.

I am assuming since this is the client credential grant flow we are failing right here(but I will try to confirm where in code its doing it later today):
https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/access.lua#L680

Worth noting Kong logs do no good here, no DB connectivity or error reports. I will likely start hacking some debug log print lines to figure out which of the error blocks we fell into.

Our functional test libs that hit the gateway regularly consistently flakey fails due to poor token generation capabilities in dev now as well calling the 2.4 gateways while still succeeding every time in stage/prod against our Kong 2.1.4 nodes.

Some ideas are some kinda poisoned cache or lookup issue. Bug is very persistent once the issue presents itself, basically the working datacenter will continue to work proper it seems and the dysfunctional datacenter calls will continue to throw that 400 error like that users creds didn't exist. 

Definitely gonna be a blocker for deploying Kong 2.4 into customer facing environments for now until we get to the bottom of this. Worth noting I was testing Kong 2.3.3 in dev at one point(after upgrading from 2.1.4) and this kinda behavior was not presenting itself. So likely if there is some component of Kong not directly related to the plugin functional code itself that changed its likely somewhere between 2.3.3 to 2.4 caused it. I believe there were not even any db migration schema changes from 2.3 to 2.4 looking at core schema_meta so likely not a db schema/data related issue either hmm.

Lemme know if you have any debug code snippets you want me to drop into the plugins or whatever, would like to get this fixed.

### Steps To Reproduce

1. Stand up multi DC Kong(2) w 6 node C* cluster, 3 per DC
2. Test OAuth2.0 endpoint above with your produced creds by a consumer.
3. See if you see flakey behavior out of the global token gen endpoint too?

### Additional Details & Logs

- Kong version 2.4

ENV:
```
        - env:
            - name: KONG_ADMIN_SSL_ENABLED
              value: 'off'
            - name: KONG_CASSANDRA_DATA_CENTERS
              value: 'DC1:3,DC2:3'
            - name: KONG_CASSANDRA_REPL_STRATEGY
              value: NetworkTopologyStrategy
            - name: KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT
              value: '30000'
            - name: KONG_UPSTREAM_KEEPALIVE_IDLE_TIMEOUT
              value: '30'
            - name: KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS
              value: '50000'
            - name: KONG_UPSTREAM_KEEPALIVE_POOL_SIZE
              value: '400'
            - name: KONG_WORKER_CONSISTENCY
              value: eventual
            - name: KONG_WORKER_STATE_UPDATE_FREQUENCY
              value: '5'
            - name: KONG_NGINX_PROXY_REAL_IP_HEADER
              value: X-Forwarded-For
            - name: KONG_NGINX_PROXY_REAL_IP_RECURSIVE
              value: 'on'
            - name: KONG_SSL_CIPHER_SUITE
              value: intermediate
            - name: KONG_NGINX_MAIN_WORKER_PROCESSES
              value: '6'
            - name: KONG_BOUNCE_REASON
              value: 'Automated Bounce 20200511-06:58:13.262'
            - name: KONG_HEADERS
              value: latency_tokens
            - name: KONG_DNS_ORDER
              value: 'LAST,SRV,A,CNAME'
            - name: KONG_CASSANDRA_CONTACT_POINTS
              value: 'server8171,server8176,server8180,server8172,server8173,server8175'
            - name: KONG_LOG_LEVEL
              value: notice
            - name: KONG_PROXY_ACCESS_LOG
              value: 'off'
            - name: KONG_ADMIN_ACCESS_LOG
              value: 'off'
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ANONYMOUS_REPORTS
              value: 'off'
            - name: KONG_PROXY_LISTEN
              value: '0.0.0.0:8000, 0.0.0.0:8443 ssl http2 deferred reuseport'
            - name: KONG_ADMIN_LISTEN
              value: '0.0.0.0:8001 deferred reuseport'
            - name: KONG_MEM_CACHE_SIZE
              value: 1024m
            - name: KONG_SSL_CERT
              value: /usr/local/kong/ssl/kongcert.crt
            - name: KONG_SSL_CERT_KEY
              value: /usr/local/kong/ssl/kongprivatekey.key
            - name: KONG_SSL_CERT_DER
              value: /usr/local/kong/ssl/kongcertder.der
            - name: KONG_CLIENT_SSL
              value: 'off'
            - name: KONG_TRUSTED_IPS
              value: '0.0.0.0/0,::/0'
            - name: KONG_CLIENT_MAX_BODY_SIZE
              value: 50m
            - name: KONG_CLIENT_BODY_BUFFER_SIZE
              value: 50m
            - name: KONG_ERROR_DEFAULT_TYPE
              value: text/plain
            - name: KONG_DATABASE
              value: cassandra
            - name: KONG_PG_SSL
              value: 'off'
            - name: KONG_CASSANDRA_PORT
              value: '9042'
            - name: KONG_CASSANDRA_KEYSPACE
              value: kong_dev
            - name: LAST_AUTOMATED_RESTART
              value: '20210426_0533'
            - name: KONG_CASSANDRA_TIMEOUT
              value: '8000'
            - name: KONG_PLUGINS
              value: >-
                kong-siteminder-auth,kong-kafka-log,stargate-waf-error-log,mtls,stargate-oidc-token-revoke,kong-tx-debugger,kong-plugin-oauth,zipkin,kong-error-log,kong-oidc-implicit-token,kong-response-size-limiting,request-transformer,kong-service-virtualization,kong-cluster-drain,kong-upstream-jwt,kong-splunk-log,kong-spec-expose,kong-path-based-routing,kong-oidc-multi-idp,correlation-id,oauth2,statsd,jwt,rate-limiting,acl,request-size-limiting,request-termination,cors
            - name: KONG_CASSANDRA_SSL
              value: 'on'
            - name: KONG_CASSANDRA_SSL_VERIFY
              value: 'on'
            - name: KONG_CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cassandra-secret
            - name: KONG_CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cassandra-secret
            - name: KONG_CASSANDRA_CONSISTENCY
              value: LOCAL_QUORUM
            - name: KONG_CASSANDRA_LB_POLICY
              value: RequestDCAwareRoundRobin
            - name: KONG_CASSANDRA_LOCAL_DATACENTER
              value: CTC
            - name: KONG_DB_UPDATE_FREQUENCY
              value: '5'
            - name: KONG_DB_UPDATE_PROPAGATION
              value: '5'
            - name: KONG_DB_CACHE_TTL
              value: '0'
            - name: KONG_DNS_HOSTSFILE
              value: /etc/hosts
            - name: KONG_DNS_STALE_TTL
              value: '4'
            - name: KONG_DNS_NOT_FOUND_TTL
              value: '30'
            - name: KONG_DNS_ERROR_TTL
              value: '1'
            - name: KONG_DNS_NO_SYNC
              value: 'off'
            - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
              value: /usr/local/kong/ssl/kongcert.pem
            - name: KONG_LUA_SSL_VERIFY_DEPTH
              value: '3'
            - name: KONG_LUA_SOCKET_POOL_SIZE
              value: '30'
            - name: SPLUNK_HOST
              value: gateway-dev-dmz-dc1.company.com
            - name: KONG_DB_CACHE_WARMUP_ENTITIES
              value: 'services,plugins,consumers'
            - name: LUA_PATH
              value: >-
                /usr/local/kong/luarocks/share/lua/5.1/?.lua;;/usr/local/kong/luarocks/share/lua/5.1/?/init.lua;
            - name: KONG_NGINX_HTTP_SSL_PROTOCOLS
              value: TLSv1.2 TLSv1.3
            - name: KONG_CASSANDRA_REFRESH_FREQUENCY
              value: '0'
```
