### ISSUE TITLE
What are the configs needed in kong helm chart for X-Forwarded-For header to appear? Ref: #7134

### ISSUE THREAD

**Issue by Sereneee** [Kong/kong#7140]
Currently, I am able to see that the backend services are receiving x-real-ip header only, no sign of X-Forwarded-For header which is what I'm looking for.

These are the current kong parameters I have in my helm chart:

```
# -----------------------------------------------------------------------------
# Kong parameters
# -----------------------------------------------------------------------------
env:
  database: xxx
  nginx_worker_processes: xxx
  proxy_access_log: xxx
  admin_access_log: xxx
  admin_gui_access_log: xxx
  portal_api_access_log: xxx
  proxy_error_log: xxx
  admin_error_log: xxx
  admin_gui_error_log: xxx
  portal_api_error_log: xxx
  prefix: xxx
  pg_host: xxx
  pg_user: xxx
  pg_password: xxx
  proxy_listen: xxx
  ssl_cert: xxx
  ssl_cert_key: xxx
  headers: xxx
  nginx_proxy_proxy_buffering: xxx
  nginx_proxy_chunked_transfer_encoding: xxx
  nginx_proxy_proxy_set_header: xxx
  nginx_proxy_proxy_cache: xxx
  nginx_proxy_proxy_http_version: xxx

```
