### ISSUE TITLE
[rate-limiting plugin] How can we add multiple `limit_by` conditions for the same entity?

### ISSUE THREAD

**Issue by TVenuMadhav** [Kong/kong#7142]
The rate limit plugin [documentation](https://docs.konghq.com/hub/kong-inc/rate-limiting/) isn't very clear in suggesting if it is possible to have multiple `limit_by` conditions configured for the rate limiting plugin.

Example:

Let's say that I want to rate limit incoming requests to service with  `x / min (by ip)` and `y/ min (by header)`. To do this, should we configure two separate rate limiting plugins for each different conditions for the service like for example: 

```
 - name: rate-limiting
    config:
      day: null
      fault_tolerant: true
      hide_client_headers: false
      hour: null
      limit_by: header
      header_name: X-Consumer-Account-ID
      second: null
      minute: 30
      month: null
      policy: local
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_timeout: 2000
      year: null
    enabled: true
    protocols:
    - grpc
    - grpcs
    - http
    - https
- name: rate-limiting
    config:
      day: null
      fault_tolerant: true
      hide_client_headers: false
      hour: null
      limit_by: ip
      second: null
      minute: 80
      month: null
      policy: local
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_timeout: 2000
      year: null
    enabled: true
    protocols:
    - grpc
    - grpcs
    - http
    - https

```

I know that this gives `entity exists error` while  performing `deck validate` . How can we get the intended functionality?
