### ISSUE TITLE
custom plugin schema support "table"

### ISSUE THREAD

**Issue by NICK-DUAN** [Kong/kong#7174]
I want to return a dict from plugin config. like this:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: test
plugin: json-plugin
config:
{{ (.Files.Glob "files/json/*").AsConfig | indent 2 }}
```
There is a json file In json directory. content like this:
```json
{
    "username": "nick",
    "gender": "male"
}
```

And handler.lua will return conf.json

This plugin looks ok, but the response has a lot escape characters, this problem would have been avoided if schema support table.
