### ISSUE TITLE
2.4 regression in http-log headers support

### ISSUE THREAD

**Issue by jam01** [Kong/kong#7416]
### Summary
- Kong version 2.4.1.1-alpine
- The `headers` config option is no longer functional. The headers are not added to the log request

### Steps To Reproduce

1.  Setup the following config
```
config:
  http_endpoint: http://mockbin.org/bin/:some-id
  method: POST
  headers:
    foo: ['Basic 1234567890']
```
2. Check mockbin for headers in request
