### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'dump_info'

### ISSUE THREAD

**Issue by mpromny** [Kong/kong#7460]
### Summary
- Kong version (`2.4`) - customized
- external plugins - Python
- Unable to start each plugin as a microservice
      - unable to migrate from old approach (single process for many plugins) to the new one (each plugin has his own server)
      - I'm able to load those plugins using "single server"

### Steps To Reproduce

1. Create docker image
```
ARG KONG_BASE=kong:2.4

FROM ${KONG_BASE}
ENV PATH="/home/kong/.local/bin:${PATH}"

USER root
RUN apk update
RUN apk add python3 python3-dev make git g++ gcc libc-dev libffi-dev

USER kong
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install kong-pdk

USER root
RUN pip3 install kong-pdk

RUN cp /home/kong/.local/bin/* /usr/local/bin/
RUN chmod 777 /usr/local/bin/* && chown kong /usr/local/bin/*

USER kong
```
2. Load plugins as configmap via helm or add directly to the docker image
   - I used py-hello plugin
   - Example has been slightly modified: 
     py-hello plugin:
        Line 19:
               From: ` def access(self, kong: kong.kong):`
               To: ` def access(self, kong: kong):`
   
3. Modify kong configuration 
```
  plugins: bundled, py-hello
  pluginserver_names: py

  pluginserver_py_socket: /usr/local/kong/py.socket
  pluginserver_py_start_cmd: /opt/test/py-hello.py
  pluginserver_py_query_cmd: /opt/test/py-hello.py -d
```

4. Use helm to deploy service

### Additional Details & Logs
- Error:
```
Traceback (most recent call last):
File "/opt/test/py-hello.py", line 33, in <module>
start_dedicated_server("py-hello", Plugin, version, priority)
File "/home/kong/.local/lib/python3.8/site-packages/kong_pdk/cli.py", line 95, in start_dedicated_server
args = parse(dedicated=True)
File "/home/kong/.local/lib/python3.8/site-packages/kong_pdk/cli.py", line 51, in parse
if (not args.dump_info and not args.dump_all_info) and not os.path.exists(args.prefix):
AttributeError: 'Namespace' object has no attribute 'dump_info

2021/06/16 13:07:00 [error] 1#0: init_by_lua error: ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:159: Not a plugin info table:
/opt/test/py-hello.py -d`
```
- Plugin used for tests:
  [py-hello](https://github.com/Kong/kong-python-pdk/blob/master/examples/py-hello.py)
- Kong configuration:
```
  plugins: bundled, py-hello
  pluginserver_names: py

  pluginserver_py_socket: /usr/local/kong/py.socket
  pluginserver_py_start_cmd: /opt/test/py-hello.py
  pluginserver_py_query_cmd: /opt/test/py-hello.py -d
```
- Operating system
  Kubernetes:
    - Version: v1.19.11
    - OS-IMAGE: Ubuntu 20.04.2 LTS
    - KERNEL-VERSION: 5.4.0-1045-aws
  
- Helm configuration:
```
  userDefinedVolumes:
  - name: py-scripts
    configMap:
      name: py-scripts
      defaultMode: 0777
      items:
        - key: py-hello
          path: py-hello
        - key: py-test
          path: py-test
  userDefinedVolumeMounts:
    - name: py-scripts
      mountPath: /opt/test/py-hello.py
      subPath: py-hello
    - name: py-scripts
      mountPath: /opt/test/py-test.py
      subPath: py-test

---
```
- Working configuration - single server
```

  plugins: bundled, py-hello, py-test
  pluginserver_names: py

  pluginserver_py_socket: /usr/local/kong/python_pluginserver.sock
  pluginserver_py_start_cmd: kong-python-pluginserver -kong-prefix /usr/local/kong/ -plugins-directory /opt/test
  pluginserver_py_query_cmd: kong-python-pluginserver -dump-all-plugins -plugins-directory /opt/test

```
>
