### ISSUE TITLE
Conflicting paths

### ISSUE THREAD

**Issue by Bishop19** [Kong/kong#7504]
Hi everyone, hope you’re all good.

### Summary
I’m new to Kong and I’m experimenting generating a declarative yaml file for Kong based on an OpenAPI documentation file.

The problem i’m trying to solve occurs when there are overlapping paths. In my case:

1. /pets/{id}
2. /pets/{id}/name/{name}

When I make a request for the endpoint 2, Kong proxies the request as it was for endpoint 1. For example, when I make a request to `http://127.0.0.1:8000/pets/1/name/random` the backend responds for `http://127.0.0.1:3001/pets/1` instead of `http://127.0.0.1:3001/pets/1/name/random`.

I've the following configuration:
```
_format_version: "2.1"
_transform: true

services:
- name: pets
  url: http://127.0.0.1:3001/pets
  routes:
  - name: route-3-3
    methods:
    - GET
    paths:
    - /pets/(?<id>\d+)
    plugins:
    - name: request-transformer
      config:
        replace:
          uri: /pets/$(uri_captures["id"])

  - name: route-3-6
    methods:
    - GET
    paths:
    - /pets/(?<id>\d+)/name/(?<name>[^/]*)
    plugins:
    - name: request-transformer
      config:
        replace:
          uri: /pets/$(uri_captures["id"])/name/$(uri_captures["name"])
```
From the docs: "When proxying with path prefixes, the longest paths get evaluated first. This allow you to define two Routes with two paths: `/service` and `/service/resource`, and ensure that the former does not “shadow” the latter". But the only way to go to the endpoint 2 is by removing the endpoint 1 from the configuration.

Another thing I noticed is that if I send a request to `http://127.0.0.1:8000/pets/a/name/john` it gets proxied to `http://127.0.0.1:3001/pets/a/name/john` despite the regex in the path that only allows digits.

Also, is my approach with the `request-transformer` plugin correct, or should I be following another approach?

Thank you all in advance!
