### ISSUE TITLE
Kong Pods are getting restarted after adding oauth2 credentials to consumer

### ISSUE THREAD

**Issue by anup-krai** [Kong/kong#7517]
### Summary
- Kong version - Kong - 2.4.1, ingress-controller - 1.2
- A concise summary of the bug.
I have created a Kong consumer and oauth2 secret. After adding oauth2 secret in Kong consumer credentials ingress container is getting restart frequently.

Kong Consumer -
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: test-consumer
  annotations:
    kubernetes.io/ingress.class: kong
username: test-consumer
credentials:
  - test-consumer-oauth2
```
Secret -
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-consumer-oauth2
type: Opaque
data:
  kongCredType: b2F1dGgy
  client_id: Y2xpZW50aWQtZ2VuZXJhdGVkLWZvci1vYXV0aDI=
  client_secret: Y2xpZW50c2VjcmV0LWdlbmVyYXRlZC1mb3Itb2F1dGgy
  redirect_uris: aHR0cHM6Ly9sb2NhbGhvc3Qv
  hash_secret: dHJ1ZQ==
```

### Steps To Reproduce

1. Create oauth2 secret and deploy.
2. Create Kong consumer and attach oauth2 secret in Kong consumer credentials.
3. Deploy Kong consumer.
4. Kong pods will start getting restarted.

### Additional Details & Logs
Kong ingress controller logs -
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15647ce]

goroutine 356 [running]:
github.com/kong/deck/state.(*Oauth2Credential).Console(0xc000446230, 0x1a54cc6, 0x6)
	/go/pkg/mod/github.com/kong/deck@v1.5.0/state/types.go:929 +0x4e
github.com/kong/deck/solver.Solve.func2(0x1a54cc6, 0x6, 0x1a599f4, 0xb, 0x19809e0, 0xc000446230, 0x0, 0x0, 0x16021e670040ba4a, 0x60dd56a4, ...)
	/go/pkg/mod/github.com/kong/deck@v1.5.0/solver/solver.go:46 +0x816
github.com/kong/deck/diff.(*Syncer).handleEvent.func1(0xc000b9d080, 0xc000b9d080)
	/go/pkg/mod/github.com/kong/deck@v1.5.0/diff/diff.go:460 +0xaf
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc00028be28, 0x1c6e050, 0xc000b9d080, 0x0, 0x1c90ef8, 0xc000498c88, 0x0, 0x0)
	/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55 +0x102
github.com/cenkalti/backoff/v4.RetryNotify(...)
	/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34
github.com/cenkalti/backoff/v4.Retry(...)
	/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:28
github.com/kong/deck/diff.(*Syncer).handleEvent(0xc000c844b0, 0xc000c88960, 0x1a54cc6, 0x6, 0x1a599f4, 0xb, 0x19809e0, 0xc000446230, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/kong/deck@v1.5.0/diff/diff.go:459 +0xfa
github.com/kong/deck/diff.(*Syncer).eventLoop(0xc000c844b0, 0xc000c88960, 0xc000101260, 0x1b114e8)
	/go/pkg/mod/github.com/kong/deck@v1.5.0/diff/diff.go:449 +0x165
github.com/kong/deck/diff.(*Syncer).Run.func1(0xc000c844b0, 0xc000c88960, 0xc000a0b0d0)
	/go/pkg/mod/github.com/kong/deck@v1.5.0/diff/diff.go:386 +0x39
created by github.com/kong/deck/diff.(*Syncer).Run
	/go/pkg/mod/github.com/kong/deck@v1.5.0/diff/diff.go:385 +0x185
```
