### ISSUE TITLE
Stupid Question regarding gRPC-Gateway

### ISSUE THREAD

**Issue by DarthJonathan** [Kong/kong#7536]
Hi, 

I'm trying to use gRPC-Gateway for my microservice, but when I follow the usage tutorial here 

https://docs.konghq.com/hub/kong-inc/grpc-gateway/

The route is working fine, but got an error of

```
transcoding requests require a .proto file defining the service
```

Tried including it using githubraw. Doesn't work. I deployed kong in kubernetes as ingress-controller. Can someone help me? Thanks before!

**Comment by bungle** [comment]
@DarthJonathan, did you try to point it to URI or upload the raw content?

**Comment by DarthJonathan** [comment]
I did, but it's on a private repository, so it has token id in the end, that might be the issue?

**Comment by DarthJonathan** [comment]
Maybe adding option to add binary descriptors of the protobuf is a nice step forward

**Comment by fffonion** [comment]
@DarthJonathan The error seems to be that `proto` field is missing. Did you configure the plugin's `proto` field? 
It expect the path of `.proto` file, we doesn't support passing the content of .proto file now.

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: some-name
plugin: grpc-gateway
config:
  proto: /path/to/proto/file
```
