### ISSUE TITLE
Unable to make work a simple plugin

### ISSUE THREAD

**Issue by MatteoInfi** [Kong/kong#7565]
First of all, the documentation is very messy and seems like there are multiple way to do the same thing and no one knows which one is which.

For example what is the difference between this: 

```
pluginserver_names = my-plugin,other-one

pluginserver_my_plugin_socket = /usr/local/kong/my-plugin.socket
pluginserver_my_plugin_start_cmd = /usr/local/bin/my-plugin
pluginserver_my_plugin_query_cmd = /usr/local/bin/my-plugin -dump
```

and this?

```
pluginserver_names = go,python

pluginserver_go_socket = /usr/local/kong/go_pluginserver.sock
pluginserver_go_start_cmd = go-pluginserver -kong-prefix /usr/local/kong/ -plugins-directory /usr/local/kong/go-plugins
pluginserver_go_query_cmd = go-pluginserver -dump-all-plugins -plugins-directory /usr/local/kong/go-plugins

pluginserver_python_socket = /usr/local/kong/python_pluginserver.sock
pluginserver_python_start_cmd = kong-python-pluginserver
pluginserver_python_query_cmd = kong-python-pluginserver --dump-all-plugins
```

- `For example, you could set Go and Python plugins like this (assuming an hypothetical Python plugin server called pypluginserver.py)` but then there are different names? 

- `plugins = bundled, go-hello, js-hello, py-hello` where are those are coming from??.

- `pluginserver_<NAME>_query_cmd | Command to dump available plugins’ info | /usr/local/bin/query_<NAME>` So it has a `_query` prefix or not?

----

This is my docker-compose

```
  apiGateway:
    image: kong/kong-gateway:2.4.1.0-alpine
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml
      - ./ratelimiter:/usr/local/kong/ratelimiter
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yaml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PLUGINS=bundled,ratelimiter
      - KONG_PLUGINSERVER_NAMES=ratelimiter
      - KONG_PLUGINSERVER_RATELIMITER_SOCKET=/usr/local/kong/ratelimiter.socket
      - KONG_PLUGINSERVER_RATELIMITER_START_CMD=/usr/local/bin/ratelimiter
      - KONG_PLUGINSERVER_RATELIMITER_QUERY_CMD=/usr/local/bin/ratelimiter -dump
``` 

this is my plugin:

```
package main

import (
	"github.com/Kong/go-pdk"
	"github.com/Kong/go-pdk/server"
	"log"
)

type Config struct {}

func New() interface{} {
	return &Config{}
}

func (c Config) Access(kong *pdk.PDK) {
	log.Println("hello custom plugin")
}

func main() {
	err := server.StartServer(New, "1.1", 1000)
	if err != nil {
		log.Fatal(err)
	}
}

```

and I get this error:

```
apiGateway_1  | 2021/07/14 06:37:53 [notice] 1#0: [lua] license_helpers.lua:123: read_license_info(): [license-helpers] could not decode license JSON: No license found
apiGateway_1  | 2021/07/14 06:37:53 [notice] 1#0: [lua] license_helpers.lua:123: read_license_info(): [license-helpers] could not decode license JSON: No license found
apiGateway_1  | sh: /usr/local/kong/ratelimiter: not found
apiGateway_1  | 2021/07/14 06:37:54 [error] 1#0: init_by_lua error: ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:166: Not a plugin info table: 
apiGateway_1  | /usr/local/kong/ratelimiter -dump
apiGateway_1  | 
apiGateway_1  | stack traceback:
apiGateway_1  | 	[C]: in function 'error'
apiGateway_1  | 	...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:166: in function 'ask_info'
apiGateway_1  | 	...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:202: in function 'get_plugin_info'
apiGateway_1  | 	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:269: in function 'get_plugin'
apiGateway_1  | 	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:277: in function 'load_plugin'
apiGateway_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:146: in function 'load_plugin_handler'
apiGateway_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:234: in function 'load_plugin'
apiGateway_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:286: in function 'load_plugin_schemas'
apiGateway_1  | 	/usr/local/share/lua/5.1/kong/init.lua:578: in function 'init'
apiGateway_1  | 	init_by_lua:3: in main chunk
apiGateway_1  | nginx: [error] init_by_lua error: ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:166: Not a plugin info table: 
apiGateway_1  | /usr/local/kong/ratelimiter -dump
apiGateway_1  | 
apiGateway_1  | stack traceback:
apiGateway_1  | 	[C]: in function 'error'
apiGateway_1  | 	...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:166: in function 'ask_info'
apiGateway_1  | 	...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:202: in function 'get_plugin_info'
apiGateway_1  | 	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:269: in function 'get_plugin'
apiGateway_1  | 	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:277: in function 'load_plugin'
apiGateway_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:146: in function 'load_plugin_handler'
apiGateway_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:234: in function 'load_plugin'
apiGateway_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:286: in function 'load_plugin_schemas'
apiGateway_1  | 	/usr/local/share/lua/5.1/kong/init.lua:578: in function 'init'
apiGateway_1  | 	init_by_lua:3: in main chunk

```
