### ISSUE TITLE
Admin API Does Not Properly List Plugins Created Using YAML Anchors

### ISSUE THREAD

**Issue by bforbis** [Kong/kong#7620]
### Summary
- **Kong version** 2.5.0

The `/plugins` admin API does not list out all enabled plugins for services when using YAML anchors with declarative config. These plugins sill seem to be active when configured with anchors, however the admin API is only aware of the LAST service in the list of services which references the YAML anchor. 

### Steps To Reproduce
Start kong with the following declarative config

```yaml
_format_version: "1.1"
services:
  - name: service1
    url: http://example.com
    plugins:
      - &correlation-plugin
        name: correlation-id
        config:
          header_name: X-Request-Id
          generator: uuid
          echo_downstream: true
      - &rate-limiting-plugin
        name: rate-limiting
        config:
          second: 5
          policy: local
    routes:
      - name: foo
        strip_path: false
        paths:
          - /foo
  - name: service2
    url: http://example.com
    plugins:
      - *correlation-plugin
      - *rate-limiting-plugin
    routes:
      - name: bar
        strip_path: false
        paths:
          - /bar
```

Hit both service 1 and service 2, notice that both the correlation-id and rate-limiting plugins are functioning appropriately for each of the services. This can be verified by looking for the appropriate response headers.

Finally, hit the `/plugins` Admin API and notice that only 2 plugins are reported as active, all associated with service 2

If this same configuration is setup without using YAML anchors, then there will be 4 plugins listed in the `/plugins` admin API.
