### ISSUE TITLE
Lua VM crashed using Docker on MacBook M1

### ISSUE THREAD

**Issue by vitor-l** [Kong/kong#7635]
Hello! I'm using an Apple MacBook M1 and when I try to use the latest kong image (2.5.0), I get this error:

> nginx: lua atpanic: Lua VM crashed, reason: not enough memory

Here is my _docker-compose.yml_ for kong:

```yml
  kong:
    platform: linux/x86_64
    image: kong:latest
    user: "${KONG_USER}"
    depends_on:
      database:
        condition: service_healthy
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: '${KONG_PROXY_LISTEN:-0.0.0.0:8000}'
      KONG_ADMIN_LISTEN: '${KONG_ADMIN_LISTEN:-0.0.0.0:8001}'
      KONG_DATABASE: postgres
      KONG_CASSANDRA_CONTACT_POINTS: ${KONG_PG_HOST}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_DATABASE: ${KONG_PG_DATABASE}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
    networks:
      - my-net
    ports:
      - '${KONG_INBOUND_PROXY_LISTEN:-0.0.0.0}:8000:8000/tcp'
      - '${KONG_INBOUND_SSL_PROXY_LISTEN:-0.0.0.0}:8443:8443/tcp'
      - '127.0.0.1:8001:8001/tcp'
      - '127.0.0.1:8444:8444/tcp'
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
    deploy:
      restart_policy:
        delay: 50s
        condition: on-failure
        max_attempts: 5
        window: 10s
      resources:
        limits:
          cpus: 2
          memory: 2g
    security_opt:
      - no-new-privileges
```
