### ISSUE TITLE
Failure to renew certificates(automatically or manually)

### ISSUE THREAD

**Issue by DrPyser** [Kong/kong#7643]
Hi! Having issues renewing certificates.

```
$ curl -d host=kio.to -d test_http_challenge_flow=true http://localhost:8002/acme
{"message":"problem found running sanity check for kio.to: timeout"}
```

Running the renewal:

```
 curl -XPATCH -d host=kio.to http://localhost:8002/acme
```

From the error logs:
```
2021/07/14 15:08:54 [error] 27#0: *1176768 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: kong,
 request: "GET /.well-known/acme-challenge/QqLNrnK_Ng7HYg8_Y_HIbKsjp9ttmI9KvTFMIAwaGns HTTP/1.1", upstream: "http://127.0.0.1:65535/.well-known/acme-challenge/QqLNrnK_Ng7HYg8_Y_HIbKsjp9ttmI9KvTFMIAwaGns", host: "pip.kio.to"
```
Seems the plugin is not catching the request for `/.well-known/acme-challenge`.

My routing config:
```
[...]
- connect_timeout: 60000
  name: acme-dummy
  url: http://127.0.0.1:65535
  protocol: http
  read_timeout: 60000
  retries: 0
  write_timeout: 60000
  tags:
    - declarative
  routes:
  - hosts:
      - kio.to
      - registry.kio.to
      - pip.kio.to
      - alpha.kio.to
      - prod.kio.to
      - www.kio.to
    name: acme-dummy
    paths:
    - /.well-known/acme-challenge
    preserve_host: true
    protocols:
    - http
    regex_priority: 0
    strip_path: false
    tags:
      - declarative
[...]

plugins:
- name: acme
  tags:
    - declarative
  enabled: true
  config:
    account_email: kioteam@accenture.com
    domains:
      - www.kio.to
      - "kio.to"
      - "registry.kio.to"
      - "pip.kio.to"
      - "alpha.kio.to"
      - "prod.kio.to"
    tos_accepted: true
    storage: kong
    fail_backoff_minutes: 1
[...]
 ```

Thanks!
