### ISSUE TITLE
Using unix sockets + declarative config: "host" and "protocol" fields not acquired

### ISSUE THREAD

**Issue by David-Lor** [Kong/kong#7688]
## Summary

Kong version: 2.5.0 (docker)

Experimenting with Unix Sockets, when a service has its "url" directing to an Unix Socket, Kong gives the following output (error in last few lines):

```
fastapi-unixsocket-kong | 2021/08/09 08:16:47 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
fastapi-unixsocket-kong | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
fastapi-unixsocket-kong | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:525: error parsing declarative config file /kong.yml:
fastapi-unixsocket-kong | in 'services':
fastapi-unixsocket-kong |   - in entry 1 of 'services':
fastapi-unixsocket-kong |     in 'protocol': expected one of: grpc, grpcs, http, https, tcp, tls, udp
fastapi-unixsocket-kong |     in 'host': required field missing
fastapi-unixsocket-kong | stack traceback:
fastapi-unixsocket-kong | 	[C]: in function 'error'
fastapi-unixsocket-kong | 	/usr/local/share/lua/5.1/kong/init.lua:525: in function 'init'
fastapi-unixsocket-kong | 	init_by_lua:3: in main chunk
fastapi-unixsocket-kong | 2021/08/09 08:16:48 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:525: error parsing declarative config file /kong.yml:
fastapi-unixsocket-kong | in 'services':
fastapi-unixsocket-kong |   - in entry 1 of 'services':
fastapi-unixsocket-kong |     in 'protocol': expected one of: grpc, grpcs, http, https, tcp, tls, udp
fastapi-unixsocket-kong |     in 'host': required field missing
fastapi-unixsocket-kong | stack traceback:
fastapi-unixsocket-kong | 	[C]: in function 'error'
fastapi-unixsocket-kong | 	/usr/local/share/lua/5.1/kong/init.lua:525: in function 'init'
fastapi-unixsocket-kong | 	init_by_lua:3: in main chunk
fastapi-unixsocket-kong exited with code 1
```

However, "protocol" and "host" fields are defined within the service object defined (see declarative config below).

## Context

These are the minimal files that will trigger the error, but I uploaded here the whole scenario: [fastapi-unixsocket+kong.zip](https://github.com/Kong/kong/files/6952967/fastapi-unixsocket%2Bkong.zip)

### docker-compose.yml used (missing the API part, which makes no difference in getting the error):

```
version: "3"

services:
    kong:
        container_name: fastapi-unixsocket-kong
        image: kong:2.5.0
        environment:
            KONG_DECLARATIVE_CONFIG: "/kong.yml"
            KONG_DATABASE: "off"
            KONG_MEM_CACHE_SIZE: "128m"
            KONG_PLUGINS: "bundled"
            KONG_PROXY_ACCESS_LOG: "/dev/stdout"
            KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
            KONG_PROXY_ERROR_LOG: "/dev/stdout"
            KONG_ADMIN_ERROR_LOG: "/dev/stdout"
        volumes:
            - ./kong.yml:/kong.yml:ro
#            - /tmp/fastapi-unixsockets:/sockets
        network_mode: host
```

### kong.yml (declarative config):

```
_format_version: "1.1"

services:
  - name: fastapi-unixsocket-api
    url: unix:/sockets/fastapi.sock
    host: localhost
    protocol: http
    routes:
      - name: root
        paths: ["/"]
        strip_path: true
```
