### ISSUE TITLE
custom go plugin add successfully but not working in Kong 2.5.0

### ISSUE THREAD

**Issue by SaneHe** [Kong/kong#7726]
### Summary
- Kong version 2.5.0
- A concise summary of the bug.

### Steps To Reproduce

1.  go plugin demo
```go
package main

import (
	"fmt"
	"github.com/Kong/go-pdk"
	"github.com/Kong/go-pdk/server"
)

// Version 定义版本
var Version = "0.1"

// Priority 优先级
var Priority = 777

func main() {
	server.StartServer(New, Version, Priority)
}

type Config struct {
	Message string
}

func New() interface{} {
	return &Config{}
}

func (conf Config) Access(kong *pdk.PDK) {
	host, _ := kong.Request.GetHeader("host")

	message := conf.Message
	if message == "" {
		message = "hello"
	}

	kong.Response.SetHeader("x-rbac-from-go", fmt.Sprintf("Go says %s to %s", message, host))
}
 ```
2. Dockerfile
```
FROM kong/go-plugin-tool:2.0.4-alpine-latest AS builder

RUN mkdir -p /tmp/go-plugins/

COPY ./kong-rbac-plugin /tmp/go-plugins/

RUN cd /tmp/go-plugins/ && \
    go env -w GOPROXY=https://goproxy.cn && \
    go get -d -v github.com/Kong/go-pluginserver && \
    apk add make && \
    make all && \
    chmod +x rbac rbac.so  

FROM kong:latest

COPY --from=builder  /tmp/go-plugins/go-pluginserver /usr/local/bin/go-pluginserver
COPY --from=builder  /tmp/go-plugins/rbac.so /usr/local/bin/rbac.so
COPY --from=builder  /tmp/go-plugins/rbac /usr/local/bin/rbac
RUN /usr/local/bin/go-pluginserver -version && /usr/local/bin/rbac -dump
```
3. Makefile
```makefile
.PHONY: all

all: rbac rbac.so go-pluginserver

rbac: rbac.go
	go build -o rbac rbac.go

rbac.so: rbac.so
	go build -buildmode=plugin -o rbac.so rbac.go

go-pluginserver:
	go get -d -v github.com/Kong/go-pluginserver && go build github.com/Kong/go-pluginserver
```
4. kong - docker-compose.yml (part)
```yml

  kong:
    # image: "${KONG_DOCKER_TAG:-kong:latest}"
    build: 
      context: .
    container_name: kong
    user: "${KONG_USER:-root}"
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_PLUGINS: bundled,rbac
      KONG_LOG_LEVEL: info
      KONG_HEADERS: server_tokens,latency_tokens
      KONG_PLUGINSERVER_NAMES: rbac,go
      # KONG_PLUGINSERVER_RBAC_SOCKET: /var/run/kong/rbac.sock
      # KONG_PLUGINSERVER_RBAC_START_CMD: /usr/local/bin/rbac
      KONG_PLUGINSERVER_RBAC_QUERY_CMD: /usr/local/bin/rbac -dump
      # KONG_PLUGINSERVER_GO_SOCKET: /var/run/kong/go_pluginserver.sock
      KONG_PLUGINSERVER_GO_START_CMD: /usr/local/bin/go-pluginserver -kong-prefix /usr/local/kong -plugins-directory /etc/kong/go_plugins
      KONG_PLUGINSERVER_GO_QUERY_CMD: /usr/local/bin/go-pluginserver -dump-all-plugins -plugins-directory /etc/kong/go_plugins
      KONG_GO_PLUGINS_DIR: /etc/kong/go_plugins
```
5. docker-compose up -d --build 
6. I added this plugin successfully, the interface will always be loading
![image](https://user-images.githubusercontent.com/28290710/129826340-d563afc2-54d3-4f8a-9772-3b1735518abc.png)

### Additional Details & Logs
- ![docker logs](https://user-images.githubusercontent.com/28290710/129826120-4835cd21-95e8-477e-9b4a-9f9b62d906a1.png)
- ![plugins add successfully](https://user-images.githubusercontent.com/28290710/129826185-4d618ee9-1cab-45fd-9c63-b5447cd87916.png)
- win10 wsl2
