### ISSUE TITLE
OPA Plugin - failed to connect to OPA server

### ISSUE THREAD

**Issue by daniwk** [Kong/kong#7808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.4.1.1

### Current Behavior

When I try to follow the [guide](https://docs.konghq.com/hub/kong-inc/opa/) to enable to the OPA Plugin, Kong fails to connect to OPA to fetch a policy as it fails to connect to the OPA server. Kong and OPA are running locally with docker-compose. Both the Kong Gateway and OPA are available on localhost, but Kong arent able to connect to the OPA server. This is both true for the 2.4.1.0 version and the 2.5 version of the Kong Gateway.

**Steps to reproduce:** 
 1. Fire up the following docker-compose file:
 
```yaml
version: '3.7'
services:
  postgres:
    image: postgres:10.17
    container_name: kong-ee-database
    restart: on-failure
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: kong ##admin user password
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpwd
    # volumes: 
    # - ./curity/curity-opa-kong-config.xml:/opt/idsvr/etc/init/curity-opa-kong-config.xml
  kong-migrations:
    depends_on: 
     - postgres
    image: kong/kong-gateway:2.4.1.1-alpine
    container_name: kong-ee-migrations
    restart: on-failure
    environment:
     - KONG_DATABASE=postgres
     - KONG_PG_HOST=kong-ee-database
     - KONG_PG_DATABASE=kong
     - KONG_PG_USER=kong
     - KONG_PG_PASSWORD=kongpwd
    command: kong migrations bootstrap --v
  kong:
    depends_on: 
     - kong-migrations
    image: kong/kong-gateway:2.4.1.1-alpine
    container_name: kong-ee
    restart: on-failure
    # volumes:
    #   - ./kong-image/kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
     - "8000:8000"
     - "8001:8001"
     - "8002:8002"
     - "8003:8003"
     - "8004:8004"
     - "8442:8443"
     - "8444:8444"
     - "8445:8445"
    environment:
     - KONG_DATABASE=postgres
     - KONG_PG_HOST=kong-ee-database
     - KONG_PG_DATABASE=kong
     - KONG_PG_USER=kong
     - KONG_PG_PASSWORD=kong2004
    #  - KONG_PLUGINS=bundled,phantom-token,opa
    #  - KONG_LOG_LEVEL=debug
     - KONG_PROXY_ACCESS_LOG=/dev/stdout
     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
     - KONG_PROXY_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_ERROR_LOG=/dev/stderr
     - KONG_PROXY_LISTEN=0.0.0.0:8000
     - KONG_ADMIN_LISTEN=0.0.0.0:8001
     - KONG_PORTAL_APP_AUTH=external-oauth2
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    ports:
    - "8181:8181"
    volumes:
      - ./opa/policies/:/records
    command: "run --server --addr :8181 /records"
```
In the `./opa/policies` we have the following file:
```
package example

default allow = false

allowBoolean {
  header_present
}

header_present {
  input.request.http.headers["my-secret-header"] == "open-sesame"
}

allowDetailed = response {
  header_present
  response := {
    "allow": true,
    "headers": {
      "header-from-opa": "accepted",
    },
  }
}

allowDetailed = response {
  not header_present
  response := {
    "allow": false,
    "status": 418,
    "headers": {
      "header-from-opa": "rejected",
    },
  }
}
```

2. Add enterprise license
```
http POST :8001/licenses \
  payload='{"license":{}}
```
3. Add dummy service and route
```
http POST :8001/services \
  name=example_service \
  url='http://mockbin.org'

http :8001/services/example_service/routes \
  paths:='["/mock"]' \
  name=mocking
```
4. Add the OPA Plugin
```
curl -X POST http://127.0.0.1:8001/services/example_service/plugins \
    --data "name=opa"  \
    --data "config.opa_path=/v1/data/example/allowBoolean" \
    --data "config.opa_host=localhost" \
    --data "config.opa_port=8181"
```
5. Try out the mock service
```
http :8000/mock
```
6. Response:
```
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 42
Content-Type: application/json; charset=utf-8
Date: Fri, 03 Sep 2021 14:43:03 GMT
Server: kong/2.4.1.0-enterprise-edition
X-Kong-Response-Latency: 44

{
    "message": "An unexpected error occurred"
}
```
7. Kong log:
```
kong-ee            | 2021/09/03 14:43:03 [error] 25#0: *1904 [kong] handler.lua:122 [opa] failed to get decision from OPA: failed to connect to OPA server(localhost:8181): connection refused, client: 172.25.0.1, server: kong, request: "GET /mock HTTP/1.1", host: "localhost:8000"
```
