### ISSUE TITLE
grpc-web trailers not being sent (no grpc-status)

### ISSUE THREAD

**Issue by samelie** [Kong/kong#7891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.5

### Current Behavior

My grpc application is returning with an `OK` on a unary request.

When the transport chunks are received in the javascript client-side, there is only one, the `MESSAGE` , type `1`

This means there is no `grpc-status` available. I should note that the data _is available_ but the grpc-web javascript code isnt working properly.

> here is the cors and grpc-web kong plugin

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-cors-plugin
config:
  origins:
  - "https://frontend.domain.com"
  - "https://grpc.domain.com"
  methods:
  - GET
  - POST
  headers:
   - Accept
  - Accept-Version
  - Content-Length
  - Access-Control-Allow-Origin
  - origin
  - keep-alive
  - user-agent
  - cache-control
  - content-type
  - content-transfer-encoding
  - custom-header-1
  - x-accept-content-transfer-encoding
  - x-accept-response-streaming
  - x-user-agent
  - x-grpc-web
  - grpc-timeout
  - access-control-request-method
  - access-control-expose-headers
  - Access-Control-Allow-Credentials
  - Content-MD5
  - Authorization
  - Content-Type
  - Date
  - TE
  - trailers
  - trailer
  - grpc-status
  - grpc-message
  - grpc-timeout
  - X-Auth-Token
  exposed_headers:
  - Content-Type
  - X-Auth-Token
  - origin
  - access-control-allow-credentials
  - date
  - TE
  - trailers
  - trailer
  - vary
  - authorization
  - grpc-accept-encoding
  - Access-Control-Allow-Origin
  - grpc-status
  - grpc-timeout
  - grpc-message
  credentials: true
  max_age: 3600
  preflight_continue: false
plugin: cors
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-grpc-web-plugin
plugin: grpc-web
```

### Expected Behavior

There should be another transport chunk sent of type `2`  (TRAILERS) where the `grpc-status` would be

### Anything else?

I'm on GKE and installed kong with Helm
