### ISSUE TITLE
JWT Plugin does not accept valid public key

### ISSUE THREAD

**Issue by jjacob27** [Kong/kong#7906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.4

### Current Behavior

I am following https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/guides/configure-acl-plugin/ to the letter.

I have:
- Created the JWT plugin
- Created the K8s secret with the public key
- Applied the JWT Plugin to a service
- Created the consumer and associated this with the secret
- Now when I present a JWT token to the service with the issuer ```https://auth.flexnetoperations.com/oauth```. It says "No credentials found for given 'iss'

I have validated that:
- Public key presented is a valid public key in PEM format. I used openssl to validate
- I have matched the issuer in the JWT token with the key field in secret

I have been breaking my head with various solutions from google for the past 4 days.

The logs show this line
```
time="2021-09-28T13:56:02Z" level=error msg="failed to update kong configuration: posting new config to /config: HTTP status 400 (message: \"declarative config is invalid: {consumers={[2]={jwt_secrets={{[\\\"@entity\\\"]={\\\"failed conditional validation given value of field 'algorithm'\\\"},rsa_public_key=\\\"invalid key\\\"}}}}}\")"
```

Only lingering doubt that I have got is "May be my public key is in ASN 1 format and Kong does not like it"

### Expected Behavior

Public keys should be accepted regardless of format. and token should be validated.

### Steps To Reproduce

```markdown
Secret definition

apiVersion: v1
kind: Secret
metadata:
  name: auth-api-public-key
  namespace: kube-system
type: Opaque
data:
  kongCredType: and0
  key: aHR0cHM6Ly9hdXRoLmZsZXhuZXRvcGVyYXRpb25zLmNvbS9vYXV0aA==
  algorithm: UlMyNTY=
  rsa_public_key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS1NSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXM2eHZ5OHNxZHBKWTJnWDJ2OGI0Vmh3aHIweXVyWitzUk1JbFdvVXpIdnRmdmp2Z0VHMm1XWHlwOWRrTElmbEdsM0NsbTFFNUxrVXJDdy9nUmY5TjZPVTJubllISC9FK2huMEtzelNoUjM5MUEzWlRhd0JJQ1hUcEpSek5udGE0K2pkZnlYQjQxdFdZWHhnYzJ0QU1BSCtob1dYSzB0NnF2NUd0ekhwZmlKckEvRzlaVFFFY3FZcDduZ3U0YUhzQTJkZlFia2tlc25XdHpkbjJDZkREM2o4OTRHdHVOZ25Cd3RlclZoQkc0dXNoRHI3Z1VVcTVaNnpFODUrMWlKVkZmM3FYTS9OM08yVUY4QWhTYlhnYTg3bUFzVklYamNlM1gwKzZEQ3k3b29YUEZHRnFGaUtpWHZoWDdqaGVQeGlFWHFQYmx0L0FUek1KbkR1elgzZnUzUUlEQVFBQi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
```

I have a Kong JWT plugin defined as
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: sample-auth-jwt
  annotations:
    kubernetes.io/ingress.class: kong
plugin: jwt
```
And I have my consumer as
```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: auth-api-sample-consumer
  annotations:
    kubernetes.io/ingress.class: kong
username: auth-api-sample-user
credentials:
  - auth-api-public-key
```
All of these are in the same namespace
```


### Anything else?

Public key file
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs6xvy8sqdpJY2gX2v8b4
Vhwhr0yurZ+sRMIlWoUzHvtfvjvgEG2mWXyp9dkLIflGl3Clm1E5LkUrCw/gRf9N
6OU2nnYHH/E+hn0KszShR391A3ZTawBICXTpJRzNnta4+jdfyXB41tWYXxgc2tAM
AH+hoWXK0t6qv5GtzHpfiJrA/G9ZTQEcqYp7ngu4aHsA2dfQbkkesnWtzdn2CfDD
3j894GtuNgnBwterVhBG4ushDr7gUUq5Z6zE85+1iJVFf3qXM/N3O2UF8AhSbXga
87mAsVIXjce3X0+6DCy7ooXPFGFqFiKiXvhX7jhePxiEXqPblt/ATzMJnDuzX3fu
3QIDAQAB
-----END PUBLIC KEY-----
```
