### ISSUE TITLE
Http redirect to https using annotations doesn't work

### ISSUE THREAD

**Issue by trhumphries** [Kong/kong#7935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.5

### Current Behavior

I have an ingress controller that uses the annotations for force http to https redirect. Its defined as:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-api
  namespace: test
  annotations:
    konghq.com/https-redirect-status-code: '302'
    konghq.com/protocols: https
    konghq.com/snis: api-ci.test.com
    kubernetes.io/ingress.class: kong
spec:
  tls:
    - hosts:
        - api-ci.test.com
      secretName: test-tls-csi
  rules:
    - host: api-ci.test.com
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-api
                port:
                  number: 80
```
Note in this example sensitive data is obfuscated.

Using http://api-ci.test.com from a browser results in a response of:
`{"message":"no Route matched with those values"}`

While changing to https://api-ci.test.com results in the page being loaded via https

### Expected Behavior

When I use http:// it should redirect to https://

### Steps To Reproduce

```markdown
See the Ingress example above
```
