### ISSUE TITLE
Unable to set datadog hostname or port with environment variables

### ISSUE THREAD

**Issue by chazdnato** [Kong/kong#7954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6

### Current Behavior

When I try to use `KONG_DATADOG_AGENT_HOST`, the Datadog plugin uses the default `localhost`.

### Expected Behavior

When I use `KONG_DATADOG_AGENT_HOST`, that value should be used for the Datadog host

### Steps To Reproduce

1. Configured the plugin as follows (note that it is `host: ` to create a `null`, but the behaviour is the same if I omit the `host:` entry, or use `host: null` or `host: ""`). We are using this as a global, but the same behaviour appears when used as non-global

```
 apiVersion: configuration.konghq.com/v1
 kind: KongClusterPlugin
 metadata:
  name: datadog
  annotations:
     kubernetes.io/ingress.class: kong
   labels:
     global: "true"
 config:
   host: 
   port: 8125
   metrics:
   prefix: api-gateway
```

2. The helm chart is setup as follows, to get the latest upstream Kong with this datadog plugin enhancement, and set the env var:

```
image:
  repository: kong
  tag: "2.6"

env:
  datadog_agent_host:
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
```

3. We see that `KONG_DATADOG_AGENT_HOST` is set, and `KONG_VERSION` is correctL:

```
❯ kubectl exec -it pod/api-gateway-v1-kong-6cf47678f6-rvdpt -c proxy -n kong -- bash
$ set | grep -e DATADOG -e VERSION
bash-5.1$ set | grep -e DATADOG -e VERSION
BASH_VERSION='5.1.4(1)-release'
KONG_DATADOG_AGENT_HOST=192.168.64.26
KONG_VERSION=2.6.0
```

4. When traffic is sent, the proxy tries to send datadog metrics to `localhost`:

```
❯ kubectl logs -f pod/api-gateway-v1-kong-6cf47678f6-rvdpt -n kong -c proxy
<some logs truncated for brevity>
172.17.0.1 - - [12/Oct/2021:18:28:22 +0000] "GET / HTTP/1.1" 200 402 "-" "curl/7.64.1"
2021/10/12 18:28:22 [error] 1099#0: *3632 send() failed (111: Connection refused), context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:8000
2021/10/12 18:28:22 [error] 1099#0: *3632 [kong] statsd_logger.lua:81 failed to send data to localhost:8125: connection refused, context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:8000
2021/10/12 18:28:22 [error] 1099#0: *3632 send() failed (111: Connection refused), context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:8000
2021/10/12 18:28:22 [error] 1099#0: *3632 [kong] statsd_logger.lua:81 failed to send data to localhost:8125: connection refused, context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:8000
2021/10/12 18:28:22 [error] 1099#0: *3632 send() failed (111: Connection refused), context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:8000
2021/10/12 18:28:22 [error] 1099#0: *3632 [kong] statsd_logger.lua:81 failed to send data to localhost:8125: connection refused, context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:8000
```

### Anything else?

My lua is non-existent, but it seems that this will set the `host` to `localhost` if there is no `host` set (i.e. if it's `""` or `null`):

https://github.com/Kong/kong/blob/master/kong/plugins/datadog/schema.lua#L77

Therefore, the env var will never be used here, as `conf.host` will always have some value:

https://github.com/Kong/kong/blob/master/kong/plugins/datadog/statsd_logger.lua#L27

**Comment by conman2305** [comment]
Same for me. We're working around this by hard-coding in the agent IP but the `use_env` design was better, IMO.

**Comment by chardo** [comment]
I'm also having this problem. Would love for this plugin to be fixed so that we can actually use it - as is, we have to manually set an IP address in the plugin, which won't work if our kong proxy deployment ever scales across more than one node (something that will definitely be an issue for us before long). Anyone have a reasonable fix for this besides cloning/manually updating the plugin code?

**Comment by stpierre** [comment]
The workaround we used:

* Update to Kubernetes 1.21
* Set the `ServiceInternalTrafficPolicy` feature gate to `true`
* In your Datadog helm chart, set `agents.localService.forceLocalServiceEnabled=true`

Or, if you upgrade to k8s 1.22, you can skip the other steps; the `ServiceInternalTrafficPolicy` gate defaults to True, as does the DD helm chart flag.

This creates a Service for Datadog that you can reference in your Datadog plugin config. For instance, we have DD installed into its own `datadog` namespace, so we have:

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: datadog
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  host: datadog.datadog.svc.cluster.local  # this is the part that is made possible by this workaround
  port: 8125
```

If you can't get to k8s 1.21 or newer, I think you're still hosed.

**Comment by chardo** [comment]
@stpierre whoaaa thanks for jumping in! Just tested this out on a cluster running 1.22 and it really does just work out of the box. Really appreciate the tip! Now just to upgrade the cluster that's actually hosting all my apps.... 😬

**Comment by rileyrohloff** [comment]
I'm also having this issue and I can't get any monitoring to work at all with k8s v1.19. Upgrading k8s isn't an option at this time and I'm struggling to find any documentation on requirements for k8s version. We're in the process of evaluating Kong as our API gateway solution, but if we can't get any metrics into DD...pretty useless.


Info:

K8s version: v1.19

Kong version: 2.7


Plugin config:

```yaml

apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: datadog-monitor
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  port: 8125
  metrics:
  prefix: kong
plugin: datadog

```


Logs from kong-proxy container:

`1097#0: *35621 [kong] statsd_logger.lua:82 failed to send data to localhost:8125: connection refused`


DD template config (helm):

```yaml

dogstatsd:
    originDetection: true
    useSocketVolume: true
    useHostPort: true
    nonLocalTraffic: true
  confd: 
    kong.yaml: |-
      ad_identifiers:
        - kong
      init_config:
      instances:
        - openmetrics_endpoint: http://%%host%%:8001/metrics
          kong_status_url: http://%%host%%:8001/status/
       
```

I've spent most of my day trying to get this working and would really appreciate any help or info!

**Comment by thecraftman** [comment]
> The workaround we used:
> 
> * Update to Kubernetes 1.21
> * Set the `ServiceInternalTrafficPolicy` feature gate to `true`
> * In your Datadog helm chart, set `agents.localService.forceLocalServiceEnabled=true`
> 
> Or, if you upgrade to k8s 1.22, you can skip the other steps; the `ServiceInternalTrafficPolicy` gate defaults to True, as does the DD helm chart flag.
> 
> This creates a Service for Datadog that you can reference in your Datadog plugin config. For instance, we have DD installed into its own `datadog` namespace, so we have:
> 
> ```
> apiVersion: configuration.konghq.com/v1
> kind: KongClusterPlugin
> metadata:
>   name: datadog
>   annotations:
>     kubernetes.io/ingress.class: kong
>   labels:
>     global: "true"
> config:
>   host: datadog.datadog.svc.cluster.local  # this is the part that is made possible by this workaround
>   port: 8125
> ```
> 
> If you can't get to k8s 1.21 or newer, I think you're still hosed.

@stpierre thanks for this, pls where did you set the `ServiceInternalTrafficPolicy` feature gate from?

**Comment by stpierre** [comment]
[Feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) are enabled/disabled with kubelet command-line arguments.

**Comment by thecraftman** [comment]
> 

Thanks @stpierre for the swift response. currently, I'm running kong on staging and prod, the service configuration

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: datadog
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  host: datadog.datadog.svc.cluster.local  # this is the part that is made possible by this workaround
  port: 8125
```

will it be created in the file path?
