### ISSUE TITLE
KongIngress is applied to all Ingress resources at once

### ISSUE THREAD

**Issue by sgrzemski** [Kong/kong#7967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.1

### Current Behavior

I have multiple applications deployed on my GKE cluster. Some of the applications have a dedicated Ingress object to expose a path through Kong (all Ingresses are in one namespace). For example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service1
spec:
  ingressClassName: kong
  rules:
    - host: my.api.com
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: service1
              port:
                number: 8080
```
and the other service like:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service2
spec:
  ingressClassName: kong
  rules:
    - host: my.api.com
      http:
        paths:
        - path: /my-super-path
          pathType: ImplementationSpecific
          backend:
            service:
              name: service2
              port:
                number: 8080
```
When I create a KongIngress object like:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: service1-customization
route:
  methods:
  - POST
  regex_priority: 0
```
and I am annotating the first ingress with `konghq.com/override: service1-customization` all paths are messed up.Requests to `/my-super-path` are redirected to `/`, so wrong service. I have started a discussion thread at the first place, but no luck there: https://discuss.konghq.com/t/cannot-disable-http-get-on-route/9144

In parallel to `service1-customization` I have deployed another KongIngress objects in the same namespace, e.g.:
```
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: default-kongingress
route:
  regex_priority: 100
 ```
 and when querying the admin api it showed that all routes have regex_priority set to 100, without setting any annotation on the ingress level!

### Expected Behavior

KongIngress does not mess up other Ingress objects when they are not annotated.

### Steps To Reproduce

```markdown
Deploy multiple ingresses, one with path `/`, another with paths `/something` and create a KongIngress disabling GET method. Annotate the `/` Ingress with KongIngress name and see.
```
