### ISSUE TITLE
Loading data into Kong for performance testing takes too long

### ISSUE THREAD

**Issue by shettyh** [Kong/kong#7998]
### Discussed in https://github.com/Kong/kong/discussions/7992

<div type='discussions-op-text'>

<sup>Originally posted by **shettyh** October 25, 2021</sup>
Hi,

I am using declarative config and doing `kong config db_import` to load the data into kong before starting the performance tests. 

Sample config looks like this

```yaml
_format_version: "1.1"
consumers:
  - id: bae7583c-e9dc-4fa1-88cd-a3e433843abd
    username: test1
    tags:
      - tenant~test1
      - owner_type~test1

basicauth_credentials:
  - consumer: bae7583c-e9dc-4fa1-88cd-a3e433843abd
    username: test1
    password: dummy_1
    tags:
      - t~l
```

So that actual yaml file will contain 100K consumers and credentials. To import this, Kong is taking around ~60mins with Cassandra as the backend DB. 

Is there anyway to optimise this import ?

Thanks </div>
