### ISSUE TITLE
Kong accepts plugins that lack required fields, but validation rejects them

### ISSUE THREAD

**Issue by seh** [Kong/kong#8093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.5

### Current Behavior

Per Kong/docs.konghq.com#3368, if we create a _KongClusterPlugin_ or _KongPlugin_ manifest using an authentication-related plugin that defines a "config.hide_credentials" field in its schema, but our manifest omits that field, the validating admission Webhook rejects the proposed object as invalid—due to it lacking that field—but if we bypass the Webhook, Kong accepts the same proposed object and supplies a default value for the omitted field.

This example is about this set of plugins whose schema treats this "hide_credentials" field as required—as of Kong/kong#6785—but supplies a default value, but I suspect that the problem is more general, applying to any plugins with schema fields with this same required-but-with-default arrangement.

It would be clearer for users if either the validating admission Webhook accepts what Kong ultimately accepts, or if Kong would reject proposed _KongClusterPlugin_ and _KongPlugin_ objects that lack such a required field. In other words, the Webhook and Kong should be equally fastidious.

Why does this matter? We have _KongPlugin_ manifests that lack this required "config.hide_credentials" field, and everything was working fine for us until we put the validating admission Webhook into service. That Webhook blocks our use of these same manifests—perhaps rightly so. However, we would have preferred if Kong would have been rejecting these manifests long before we starting using the Webhook. At present, if we disable the Webhook, we can use these same manifests without any apparent problem.

### Expected Behavior

Either Kong's validating admission Webhook should accept proposed _KongClusterPlugin_ and _KongPlugin_ objects lacking fields that are required but have a default value in the schema, or Kong should reject such proposed objects because they lack this required field.

### Steps To Reproduce

```markdown
1. Write a KongPlugin manifest for a plugin like "key-auth" that lacks the "config.hide_credentials" field.
2. Disable Kong's validating admission Webhook.
3. Apply that manifest to the target cluster.
4. Confirm that Kong's proxy container accepted the plugin.
5. Delete the KongPlugin Kubernetes object.
6. Enable Kong's validating admission Webhook.
7. Apply that manifest to the target cluster.
8. Observe that the Webhook rejects the creation request.
```

### Anything else?

We see this with KIC version 2.0.5.

**Comment by seh** [comment]
For now, we're working around this problem via this Kyverno policy:

<details>
<summary>Kyverno "kong-plugin-fields" policy</summary>

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kong-plugin-fields
spec:
  rules:
  - name: populate-missing-required-fields
    match:
      resources:
        kinds:
        - configuration.konghq.com/v1/KongClusterPlugin
        - configuration.konghq.com/v1/KongPlugin
    preconditions:
      all:
      - key: "{{ request.object.plugin }}"
        operator: In
        value:
        - basic-auth
        - hmac-auth
        - key-auth
        - ldap-auth
        - oauth2
      any:
      # NB: This case isn't strictly necessary, as the second case
      # will still evaluate to true if the field is missing, but it
      # aids in clarity.
      - key: "{{ contains(keys(request.object.config), `\"hide_credentials\"`) }}"
        operator: Equals
        value: false
      - key: "{{ request.object.config.hide_credentials == `null` }}"
        operator: Equals
        value: true
    mutate:
      patchStrategicMerge:
        config:
          # Of all the plugins, only the OAuth2 plugin uses true as
          # its default value for this field.
          hide_credentials: "{{ request.object.plugin == `\"oauth2\"` }}"
```
</details>

**Comment by hbagdi** [comment]
cc @Kong/team-k8s

**Comment by rainest** [comment]
Can you share an example plugin manifest that's rejected by this and the admission error that comes back? I'm not able to replicate:

```
15:48:36-0800 esenin $ kubectl apply -f /tmp/kvalid.yaml 
kongclusterplugin.configuration.konghq.com/key-auth-valid created
15:48:39-0800 esenin $ kubectl delete -f /tmp/kvalid.yaml  
kongclusterplugin.configuration.konghq.com "key-auth-valid" deleted
15:48:43-0800 esenin $ kubectl apply -f /tmp/kinvalid.yaml
Error from server: error when creating "/tmp/kinvalid.yaml": admission webhook "validations.kong.konghq.com" denied the request: plugin failed schema validation: schema violation (config.garbage: unknown field)
15:48:47-0800 esenin $ kubectl apply -f /tmp/knohide.yaml 
kongclusterplugin.configuration.konghq.com/key-auth-nohide created
15:48:55-0800 esenin $ cat /tmp/knohide.yaml 
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: key-auth-nohide
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  key_in_header: true
plugin: key-auth
```
That part of plugin validation is just sending a `POST /schemas/plugins/validate` with the proposed plugin to the admin API and regurgitating whatever it returns. The controller has no logic to validate plugin config of its own, only for the parts of the manifest it understands (e.g. ensuring that you have a `name` and `plugin` set. Kong and the controller should already be equally fastidious for config validation, but all indications are that Kong is just okay validating without those fields when I test.

**Comment by seh** [comment]
The error we see when trying to create such an object lacking the "config.hide_credentials" field looks like this:

> admission webhook "validations.kong.konghq.com" denied the request: plugin failed schema validation: schema violation (config.hide_credentials: required field missing)

Here is an example manifest that includes the field, but with a null value:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth
  annotations:
    kubernetes.io/ingress.class: kong
plugin: basic-auth
config:
  hide_credentials:
```
If I recall correctly, we see the same behavior with one completely lacking the field.
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth
  annotations:
    kubernetes.io/ingress.class: kong
plugin: basic-auth
```

**Comment by rainest** [comment]
It looks like it only happens when it's present but empty. I need to check exactly what this ends up serializing to, but I wouldn't expect that to work regardless:

```
17:38:44-0800 esenin $ kubectl apply -f /tmp/basicnull.yaml
Error from server: error when creating "/tmp/basicnull.yaml": admission webhook "validations.kong.konghq.com" denied the request: plugin failed schema validation: schema violation (config.hide_credentials: required field missing)
17:38:50-0800 esenin $ kubectl apply -f /tmp/basicnothing.yaml 
kongclusterplugin.configuration.konghq.com/basic-auth created
17:38:54-0800 esenin $ cat /tmp/basicnull.yaml /tmp/basicnothing.yaml 
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: basic-auth
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: basic-auth
config:
  hide_credentials:
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: basic-auth
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: basic-auth
```

**Comment by seh** [comment]
Thank you for sussing that out. The manifests in question within my company aren't ones I've written, or even _seen_ in most cases. I was on the receiving end of a bunch of complaints after I activated the Webhook, and focused first on disabling the Webhook temporarily, then writing that Kyverno policy to fix up the malformed _KongPlugin_ manifests that are in play.

I agree that the field being present with a null value is weird. However, from what I hear, Kong accepts it. Maybe that's not true after all.

**Comment by rainest** [comment]
Yep, so the actual request to Kong when the field is present but not set includes it with value `null`:
```
POST /schemas/plugins/validate HTTP/1.1
Host: localhost:8001
User-Agent: Go-http-client/1.1
Content-Length: 56
Content-Type: application/json
Accept-Encoding: gzip

{"name":"basic-auth","config":{"hide_credentials":null}}
```

Omitting it omits it:
```
POST /schemas/plugins/validate HTTP/1.1
Host: localhost:8001
User-Agent: Go-http-client/1.1
Content-Length: 21
Content-Type: application/json
Accept-Encoding: gzip

{"name":"basic-auth"}
```
The Kong admin API normally interprets `null` value fields as an instruction to delete that field. If you have a plugin with some optional field (e.g. `anonymous` for basic-auth) set, sending a PATCH with `field=null` edits the plugin to remove that configuration. That behavior is kinda meaningless for POST, but I don't think it's unexpected.

I don't think there's anything else to do here, but will leave that up to the core team.

**Comment by seh** [comment]
Thank you for the thorough investigation.

Not that we were trying to accomplish this, but I can imagine a user wanting to delete a field in order to "set it back to its default value," which is again difficult to reason about for fields that are both required and have a default value.

**Comment by rainest** [comment]
That does appear to be the de facto behavior I get when _editing_ a plugin, though I'm not sure entirely what's going on there: if I start with `hide_credentials: true` and `key_in_body: true` (to see what happens with non-required fields) and then edit (or `kubectl apply`) to use empty fields, I get a POST to `/validate` that omits them, and a PUT after that restores the defaults.

There appears to be a bit different behavior in kubectl itself when creating a new object versus editing an existing one, and the latter is more or less what we want.

**Comment by skylt** [comment]
I appear to have stumbled upon the same issue, with a different plugin, due to [the kong chart enabling the webhook by default](https://github.com/Kong/charts/commit/1c5242fd3a7375c61f005d88d757fa37ed5c02aa).
The plugin is https://docs.konghq.com/hub/kong-inc/http-log/
Here is the kongClusterPlugin, for reference:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
  name: kong-http-log-plugin
config:
  http_endpoint: "http://logs.cloud.internal:2000/indexes.kong"
  method: "POST"
  timeout: 1000
  keepalive: 1000
  flush_timeout: 2
  retry_count: 15
  custom_fields_by_lua:
    request.headers: 'return {["user-agent"]=kong.request.get_header("user-agent")}'
    request.querystring: 'return nil'
plugin: http-log
```
We get the following error when trying to apply / edit this plugin:
```
cannot patch "kong-http-log-plugin" with kind KongClusterPlugin: admission webhook "validations.kong.konghq.com" denied the request: plugin failed schema validation: schema violation (config.custom_fields_by_lua: expected a string)
```
Where the admitionWebhook requires the field to be a string, when the docs state this field is a map. As such, the webhook will reject it, but kong accepts it without issue.
