### ISSUE TITLE
Way to disable tracing on specific routes?

### ISSUE THREAD

**Issue by bforbis** [Kong/kong#8120]
I currently want tracing to be enabled globally except for some very specific routes that are extremely noisy. If I was to do this given the current configuration option, I would have to enumerate all routes and configure this plugin specifically for each route except for the one route that I want zipkin disabled on. This ends up being a ton of configuration which is hard to manage.

Instead, I would like to configure zipkin globally, but add in a small config list of matched routes to disable tracing on.

Example with db-less config:
```
services:
  - name: foo
    url: foo.com
    routes:
      - /foo
  - name: bar
    url: bar.com
    routes:
      - /bar
...etc...
plugins:
  - name: zipkin
    config:
      http_endpoint: http://zipkin:9411/api/v2/spans
      sample_ratio: 1
      ignore_routes:
        - path: /foo/health
          method: GET
```
