### ISSUE TITLE
Trouble generating anonymous consumer for DB-Less kong

### ISSUE THREAD

**Issue by ChilloManiac** [Kong/kong#8629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.6

### Current Behavior

We are creating a single configuration and sending it to kong which is running in a DBless environment. Currently we are in need of multiple authentication on some endpoints. 

The trouble starts as we are in need of a anonymous consumers id to use as a fallback consumer in our auth plugins. Since we need the ID, and not the custom_id we are not able to create the configuration in one go as the anonymous user must be created before everything else

### Expected Behavior

You should be able to use the custom_id of the consumer as a fallback as well as the ID

### Steps To Reproduce

```markdown
Create a single configuration with an anonymous user fallback in a auth plugin.
```

**Comment by ADD-SP** [comment]
@ChilloManiac Thanks for your report. We have created a ticket to track this issue.

**Comment by vm-001** [comment]
@ChilloManiac Kong is planning to support `config.anonymous` to be configured as the username of Consumer.

```
# kong.yaml

_format_version: "1.1"

consumers:
- username: foo

services:
- name: example-service
  host: mockbin.org
  port: 80
  protocol: http
  routes:
  - name: 1-route
    paths:
    - /1
    plugins:
    - name: oauth2
      config:
        enable_authorization_code: true
        provision_key: AlwUnOW6GgYd4DULt6PRrHzJfY46K5DB
        anonymous: foo
  - name: 2-route
    paths:
    - /2
    plugins:
    - name: basic-auth
      config:
        hide_credentials: false
        anonymous: foo
```

Could this solve your problem?
