### ISSUE TITLE
Imports in .proto don't work as expected in kong-grpc-gateway

### ISSUE THREAD

**Issue by dmitrysleptsov** [Kong/kong#8725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

I use separate .proto files for messages and service. When use them in local grpc server - everything is working fine. When I use them with grpc-gateway - I got an error 

```
google/api/annotations.proto: No such file or directory
        ./google/api/annotations.proto: No such file or directory
        /usr/include/google/api/annotations.proto: No such file or directory
        /usr/local/opt/protobuf/include//google/api/annotations.proto: No such file or directory
        /usr/local/kong/lib//google/api/annotations.proto: No such file or directory
        kong/google/api/annotations.proto: No such file or directory
        kong/include/google/api/annotations.proto: No such file or directory
        spec/fixtures/grpc/google/api/annotations.proto: No such file or directory
        /google/api/google/api/annotations.proto: No such file or directory, client: 10.254.6.1, server: kong, request: "GET /grpc-service/v1/users HTTP/1.1", host: "localhost:8000"
```

Directory structure:
```
grpc-service/
    google/
        api/
            annotations.proto
            http.proto
    user_messages.proto
    user_service.proto
kong.yaml
```

Content of `user_service.proto`:

```
syntax = "proto3";

import "google/api/annotations.proto";
import "user_messages.proto";

package user_service;

service UserService {
  rpc GetUser(GetUserRequest) returns (GetUserResponse) {
    option (google.api.http) = {
      get: "/grpc-service/v1/users/{id}"
    };
  }
}
```

Content of `kong.yaml`:

```
_format_version: "2.1"
_transform: true

services:
  - url: grpc://grpc-service-prototype:50051
    name: grpc-service-v1
    routes:
      - protocols:
          - http
        name: grpc-service-route-v1
        paths:
          - /
        plugins:
          - name: grpc-gateway
            config:
              proto: /kong/declarative/grpc-service/user_service.proto
```

Content of `user_messages.proto`:

```
syntax = "proto3";

message GetUserRequest {
  string id = 1;
}

message GetUserResponse {
  User data = 1;
}

message User {
  string id = 1;
  string username = 2;
  string created_at = 3;
  string updated_at = 4;
}
```

Everything running in docker. I use command from kong tutorial. The only thing that matter from it (as I think) is 
`-v "$(pwd):/kong/declarative/"`

### Expected Behavior

According to [this issue, ](https://github.com/Kong/kong/issues/6572) directory with the main .proto file (`user_service.proto` in my case) should be treated as import root. But looks like it's not.

### Steps To Reproduce

Create project with the same structure, run kong, make a request to `http://localhost:8000/grpc-service/v1/users/{anything}`

### Anything else?

If you need any extra info - please ask, would be glad to provide. I tried to use different paths in `kong.yaml`. When I use relative path - I get an error that `user_service.proto` can't be found. If I remove `annotations.proto` import - I get the same error for `user_messages.proto`.
