### ISSUE TITLE
Environment Variables Vault : error parsing declarative config file

### ISSUE THREAD

**Issue by kdubuc** [Kong/kong#8726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

When using vault env reference in kong declarative config file like this :

```
_format_version: "1.1"

services:

- url: http://microservice-a
  plugins:
  - name: loggly
    config:
      key: {vault://env/loggly-config/key}
  routes:
  - strip_path: false
    paths:
    - /
```

I get 

```
2022/04/26 09:22:16 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file kong.yml:
in 'services':
  - in entry 1 of 'services':
    in 'plugins':
      - in entry 1 of 'plugins':
        in 'config':
          in 'key': expected a string
```

### Expected Behavior

The key value should be retrieved in vault.

However, when using CLI, the value can be retrieved with no problem :
```
$ kong vault get env/loggly-config/key
keyvalue
```

### Steps To Reproduce

```markdown
With Kong 2.8
> KONG_DATABASE off
> KONG_DECLARATIVE_CONFIG kong.yml
> KONG_VAULTS bundled
> LOGGLY_CONFIG={"key":"keyvalue"}
```

**Comment by kdubuc** [comment]
I got it : The reference must be set between double quotes. So, the error message "expected a string" make sense.

```
_format_version: "1.1"

services:

- url: http://microservice-a
  plugins:
  - name: loggly
    config:
      key: "{vault://env/loggly-config/key}"
  routes:
  - strip_path: false
    paths:
    - /
```
