### ISSUE TITLE
Problem with SSL/TLS Termination on Kong API Gateway

### ISSUE THREAD

**Issue by rbessembe** [Kong/kong#8731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.7.1

### Current Behavior

I got a problem with SSL/TLS Termination on Kong API Gateway. HTTPS Requests using curl and Insomnia got response that **SSL certificate problem: unable to get local issuer certificate.** 
**Certificate is valid** and issued by well known issuer, so CA certificate is already in the clients known CA list. **In Browser HTTPS requests works fine.**

**docker-compose.yaml** configured in next way:
```
version: "3.7"

# Create docker volume as persistant storage
volumes:
  kong-postgres-volume:
    name: kong-postgres-volume
  kong-volume:
    name: kong-volume
  kong-volume-conf:
    name: kong-volume-conf

# Create Network docker network create --gateway 172.16.1.1 --subnet 172.16.1.0/24 kong-net
networks:
  kong-net:
    external: true

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    container_name: kong-postgres
    restart: always
    networks:
      kong-net:
        ipv4_address: 172.16.1.10
    volumes:
      - kong-postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${KONG_PG_USER}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD}
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2000M"
    logging:
      driver: "json-file"
      options:
          max-file: "3"
          max-size: "10M"

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:2.7.1
    container_name: kong-migration
    command: kong migrations bootstrap
    networks:
      kong-net:
        ipv4_address: 172.16.1.8
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
    depends_on:
      - kong-database
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "250M"

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:2.7.1
    container_name: kong-api-gw
    restart: always
    networks:
      kong-net:
        ipv4_address: 172.16.1.11
    volumes:
      - kong-volume:/etc/kong
      - kong-volume-conf:/usr/local/kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_SSL: "on"
      KONG_SSL_CERT: /etc/kong/ssl/kong.crt
      KONG_SSL_CERT_KEY: /etc/kong/ssl/kong.key
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stdout
      KONG_ADMIN_SSL_CERT: /etc/kong/ssl/kong.crt
      KONG_ADMIN_SSL_CERT_KEY: /etc/kong/ssl/kong.key
    depends_on:
      - kong-database
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8543:8443"
      - "8444:8444"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4000M"
    logging:
      driver: "json-file"
      options:
          max-file: "3"
          max-size: "10M"
```

Certificate was added using Admin API and also did it with Konga UI, i tried pem and crt, both of them.
`curl -X POST http://127.0.0.1:8001/certificates -H 'Content-Type: multipart/form-data' -F cert=@./kong.pem -F key=@./kong.key -F snis[]=example.com`

Plus inside docker container i put kong.crt and kong.key to /etc/kong/ssl/, but nothing helped and there are no errors in logs.

Response from GET Request to https://example.com:8444/certificates (when disable SSL Validation in Insomnia)
```
{
    "data": [
        {
            "key_alt": null,
            "created_at": 1650871124,
            "cert_alt": null,
            "key": "-----BEGIN RSA PRIVATE KEY-----\cert-key-example\n-----END RSA PRIVATE KEY-----",
            "id": "7ebdca61-4598-4e17-bdf8-2239c41ce09b",
            "tags": null,
            "snis": [
                "example.com"
            ],
            "cert": "-----BEGIN CERTIFICATE-----\cert-example\n-----END CERTIFICATE-----"
        }
    ],
    "next": null
}
```

Curl example
```
curl -i -v https://example.com:8543/api
*   Trying ip:8543...
* TCP_NODELAY set
* Connected to example.com (ip) port 8543 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### Expected Behavior

Successful HTTPS response from Kong without disabling SSL Validation in insomnia and without option -k using curl. 

### Steps To Reproduce

```markdown
Use docker-compose.yaml that i provided and cert from well known issuer.
```

### Anything else?

I used both kong images 2.7.1 and 2.8.0, nothing changed.
