### ISSUE TITLE
AWS lambda local testing

### ISSUE THREAD

**Issue by augusto-queirantes** [Kong/kong#8739]
### Discussed in https://github.com/Kong/kong/discussions/8737

<div type='discussions-op-text'>

<sup>Originally posted by **augusto-queirantes** April 28, 2022</sup>
Hey! I'm having trouble when trying to test api gateway with a lambda function locally

# Sumary

I'm trying to test api gateway with a lambda function that's written in go, but, when I follow the [aws-lambda plugin doccumentation](https://docs.konghq.com/hub/kong-inc/aws-lambda/) I got this error message on browser

![image](https://user-images.githubusercontent.com/25928091/165860387-b1019a27-135b-4426-82ab-b1d8e32517f6.png)

And this one on docker console

![image](https://user-images.githubusercontent.com/25928091/165860462-23b4b7e4-5d24-4ac6-9e8a-85558241fad7.png)

# Api gateway configuration

```
- name: test-api
  host: localhost
  routes:
  - name: test
    paths:
    - '/lambda'
    methods: ['GET']
    plugins:
    - name: aws-lambda
      config:
        host: localhost
        function_name: hello
        forward_request_body: true
        forward_request_headers: true
        forward_request_uri: true
```

# Additional info

kong version: 2.8.1

Is there a way to test api gateway locally? What's the correct way to do this? Am I missing something? I would really appreciate some help here</div>
