### ISSUE TITLE
Batch queue throws 404

### ISSUE THREAD

**Issue by antaka1** [Kong/kong#8808]
### Discussed in https://github.com/Kong/kong/discussions/8744

<div type='discussions-op-text'>

<sup>Originally posted by **antaka1** May  2, 2022</sup>
Hello,

I have a question regarding configuration of Kong retry mechanism / batch queue as my logs are full of warns and 404s.

The setup i have is 
Istio Ingress ( api.dev.com ) routes the request to Kong and then Kong proxy the request to another Istio ingress ( api.local.dev.com ) which then proxy the request to microservices.

If the request is 200 everything works fine but in case some of the calls are failing I think Kong has a retry mechanism or something called batch queue ( tbh I don't really find too many information about this on the docs ) .

Here's the service I have in Kong:
```   
services:
      - name: auth-api-service
        retries: 0
        url: https://api.local.dev.com
        routes:
          # ============================================================
          - name: auth-apis
            strip_path: false
            preserve_host: false
            protocols:
              - http
            methods:
              - POST
            paths:
              - /v1.0/users
          # ============================================================
      - name: api-service
        retries: 0
        url: https://api.local.dev.com
        routes:
          # ============================================================
          - name: core-apis
            strip_path: false
            preserve_host: false
            protocols:
              - http
            paths:
              - /v1.0
          # ============================================================`
```

And in the logs I see:
`dev-gateway-5cff954756-nvbcw kong-proxy 2022/05/02 11:05:26 [warn] 1113#0: *188505 [lua] batch_queue.lua:183: failed to process entries: request to api.local.dev.com:443 returned status code 404 and body , context: ngx.timer, client: x.x.x.x, server: 0.0.0.0:8000`
and then
`dev-gateway-5cff954756-nvbcw kong-proxy 2022/05/02 11:07:09 [error] 1116#0: *191399 [lua] batch_queue.lua:187: entry batch was already tried 10 times, dropping it, context: ngx.timer, client: x.x.x.x, server: 0.0.0.0:8000`

As you can see the retry is happening even if we configured retries: 0 . Anything we have missed ?

We start from latest kong version available ( 2.8.1 )

Thank you for any help !</div>
