### ISSUE TITLE
err in creating new ratelimit namespace

### ISSUE THREAD

**Issue by spirrello** [Kong/kong#8865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong:2.8.1.0-alpine

### Current Behavior

Hello,

When we perform a deck sync, we get the following error message in our Kong logs.  Rate-limiting does appear to work but I wanted to check if this is something to be concerned with.

```
[error] 2110#0: *20349 [kong] handler.lua:160 err in creating new ratelimit namespace: .../lua/5.1/kong/plugins/rate-limiting-advanced/handler.lua:111: attempt to index field 'dictionary_name' (a nil value), context: ngx.timer
```

**Versions**

decK v1.1.0 
kong:2.8.1.0-alpine **(without enterprise subscription)**

### Expected Behavior

To not see the reported errors after doing a deck sync.

### Steps To Reproduce

- This happens in all environments.

- Command and config: 
```markdown

deck sync -s /tmp/test/configs --kong-addr https://kongadmin.mysite.com --skip-consumers
```

**Example config:**

```
_format_version: "1.1"
_plugin_configs:
  jwt-config:
    claims_to_verify:
      - exp
    key_claim_name: sub
services:
- connect_timeout: 60000
    host: mysite.com
    name: mypage
    path: /myroute/api/v1/coolapi
    port: 443
    protocol: https
    read_timeout: 60000
    retries: 5
    write_timeout: 60000
    tags:
      - my-app
    routes:
      - name: my-app
        methods:
          - POST
          - OPTIONS
        paths:
          - /api/v1/coolapi
        preserve_host: false
        protocols:
          - https
        regex_priority: 0
        strip_path: true
        tags:
          - my-app
        https_redirect_status_code: 426
    plugins:
      - name: rate-limiting
        config:
          day: null
          fault_tolerant: true
          header_name: null
          hide_client_headers: true
          hour: null
          limit_by: ip
          minute: 100
          month: null
          policy: cluster
          redis_database: 0
          redis_host: null
          redis_password: null
          redis_port: 6379
          redis_timeout: 2000
          second: null
          year: null
        enabled: true
        protocols:
          - https
```

**Error messages we see in the Kong logs**

```
[error] 2110#0: *20349 [kong] handler.lua:160 err in creating new ratelimit namespace: .../lua/5.1/kong/plugins/rate-limiting-advanced/handler.lua:111: attempt to index field 'dictionary_name' (a nil value), context: ngx.timer
```
