### ISSUE TITLE
client_certificate docs vs declarative API inconsistency

### ISSUE THREAD

**Issue by meesvandongen** [Kong/kong#8881]
### Kong version (`$ kong version`)

2.8

### Current Behavior

The `client_certificate` in the docs suggest that an object should be sent with an `id` key.
```json
"client_certificate": {"id":"c97b1292-b5b0-4d51-95ee-cbcfaf104a3a"}
```
But in the declarative config I am not able to use this.
```yaml
_format_version: '1.1'
services:
  - client_certificate:
      id:  c97b1292-b5b0-4d51-95ee-cbcfaf104a3a
```

### Expected Behavior

I would expect the declarative API (using DecK) and the Admin API to behave the same.

### Anything else?

It does work when omitting the `id` attribute.

```yaml
_format_version: '1.1'
services:
  - client_certificate: c97b1292-b5b0-4d51-95ee-cbcfaf104a3a
```

So in the end it is not really a problem for me. I am submitting this issue though as I have not seen this behavior documented elsewhere.
