### ISSUE TITLE
OpenTelemetry invalid parent span IDs=XXX; skipping clock skew adjustment

### ISSUE THREAD

**Issue by mayocream** [Kong/kong#9458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.0

### Current Behavior

Jaeger throws errors on the UI:
```
invalid parent span IDs=ef4ab56c325b2b0a; skipping clock skew adjustment
```

Some of the spans seem to be missing or cannot be parsed.

This happens sometime, not always.

### Expected Behavior

No errors were thrown.

### Steps To Reproduce

1. Docker compose:

```yaml
version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.38.0
    ports:
    - "16686:16686"
    # - "4317:4317"
    # - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: true

  postgres:
    image: postgres:13
    command: -c max_connections=5000
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong

  kong:
    image: kong/kong-gateway:3.0
    command: sh -c "kong migrations bootstrap && kong start"
    ports:
    - "8000:8000"
    - "8001:8001"
    environment:
      KONG_LOG_LEVEL: debug
      KONG_PG_HOST: postgres
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ERROR_LOG: /dev/stderr
      # KONG_NGINX_WORKER_PROCESSES: 1
    volumes:
    - "./kong.conf:/etc/kong/kong.conf"
    restart: always
    depends_on:
    - postgres
```

2. Setup script (`start.sh`):

```bash
#!/bin/bash

set -ex

http DELETE :8001/upstreams/mockbin
http PUT :8001/upstreams/mockbin host_header=mockbin.org
http POST :8001/upstreams/mockbin/targets target=mockbin.org:80
http PUT :8001/services/mockbin host=mockbin
http PUT :8001/services/mockbin/routes/mockbin paths:='["/"]'

# cascade routes
http PUT :8001/services/cascade-1 url=http://localhost:8000/
http PUT :8001/services/cascade-1/routes/cascade-1 paths:='["/cascade-1"]'

http PUT :8001/services/cascade-2 url=http://localhost:8000/cascade-1
http PUT :8001/services/cascade-2/routes/cascade-2 paths:='["/cascade-2"]'

http PUT :8001/services/cascade-3 url=http://localhost:8000/cascade-2
http PUT :8001/services/cascade-3/routes/cascade-3 paths:='["/cascade-3"]'

http PUT :8001/services/cascade-4 url=http://localhost:8000/cascade-3
http PUT :8001/services/cascade-4/routes/cascade-4 paths:='["/cascade-4"]'

http PUT :8001/services/cascade-5 url=http://localhost:8000/cascade-4
http PUT :8001/services/cascade-5/routes/cascade-5 paths:='["/cascade-5"]'

# create opentelemetry plugin
# the endpoint must be OTLP/HTTP compatible backend
# e.g. http://localhost:4318/v1/traces
http PUT :8001/plugins/f53fa56d-7d08-4f6e-8e00-99ad73b9eb86 \
  name=opentelemetry \
  config:='{"endpoint":"http://jaeger:4318/v1/traces", "batch_span_count": 10000, "batch_flush_delay": 10}'
  # config:='{"endpoint":"http://jaeger:4318/v1/traces"}'

# wrk -t5 -c10 -d10s http://localhost:8000/
for i in {1..5}; do http http://localhost:8000/cascade-5; done
# http http://localhost:8000/cascade-5
```

3. Test

```bash
docker compose up -d
bash start.sh
```

View http://localhost:16686 to verify.

### Anything else?

Related issues:
- https://github.com/jaegertracing/jaeger/issues/3084
- https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1023
