### ISSUE TITLE
Plugins | Response transformer broken on Kong 2.8.1.4

### ISSUE THREAD

**Issue by PalAditya** [Kong/kong#9461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1.4

### Current Behavior

The response transformer plugin breaks on Kong 2.8.1.4 if there's a string response.

Sample:

```yaml
- name: response-transformer
  config:
    remove:
       json:
          - "xyz"
```
Same issue does not occur with response-transformer-advanced

### Expected Behavior

The plugin shouldn't crash kong, as the response is plain string and not json.

### Steps To Reproduce

```markdown
- Use Kong 2.8.1.4 in DBLess Mode
- Create any route which points to an upstream that returns a plain string (e.g: "Hello, World")
- Apply response-transformer on the plugin with above config
- Kong will crash.
```

### Anything else?

OS: Rhel8
