### ISSUE TITLE
Longest prefix match is not happening

### ISSUE THREAD

**Issue by akshayubale1** [Kong/kong#9462]
**We have two routes**
```
1)/lmbs/v7/accounts/account/(?<iid>\d{1,10})/accounts
2)/lmbs/v7/accounts/account/(?<iid>\d{1,10})
```

**kong  version** - 2.3.3
When i hit  the api /lmbs/v7/accounts/account/11112/accounts
it hits route 2
it is not prefering longest prefix match as mentioned in kong documentation so please help me in case if i am wrong anywhere and i also tried with the latest kong version 3.0.0
and i cant add $ at the end as the api has optional parameters and if i give [^/]*$ at the end it might consider everything

**kong route example**
  ```
# Get details 
  - name: get_details
    paths:
    - /lmbs/v7/accounts/account/(?<iid>\d{1,10})
    methods:
    - GET
    - OPTIONS
    path_handling: v0
    preserve_host: true
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: false
    https_redirect_status_code: 426
    request_buffering: true
    response_buffering: true
```
