### ISSUE TITLE
When the k8s pod is updated and restarted, there is a probability that a 502 error will occur when accessing services that pass through kong

### ISSUE THREAD

**Issue by crypto-archer** [Kong/kong#9524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.0.5

### Current Behavior

When the k8s pod is updated and restarted

kong config
```
{
  "host": "xxxx.svc.cluster.local",
  "created_at": 1631518721,
  "connect_timeout": 60000,
  "id": "xxxxxxxxxxxx",
  "protocol": "http",
  "name": "xxxx.test.local",
  "read_timeout": 60000,
  "port": 80,
  "path": null,
  "updated_at": 1658755812,
  "retries": 5,
  "write_timeout": 60000,
  "client_certificate": null,
  "extras": {}
}

```

access this service:

```
 while true
do
curl -i http://xxxx.test.local ;sleep 1
done
```

there is a probability that a 502 error will occur when accessing services that pass through kong

```
staus:502
An invalid response was received from the upstream server
```

1. I have set readinessProbe and  livenessProbe , 
```
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8000
            initialDelaySeconds: 50
            successThreshold: 2
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8000
            initialDelaySeconds: 50
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
```
2. When I access the pod's service directly, there will be no 502 issues
```
curl http://xxxx.svc.cluster.local
```
