### ISSUE TITLE
Kuma mesh with kong gateway - multiple ingress rules result in error

### ISSUE THREAD

**Issue by raxtorDD** [Kong/kong#9540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.0

### Current Behavior

**System Architecture:**
Kuma Service Mesh with delegated Kong Gateway.

When I am deploying more then one ingress rule (same or different port,  different path) the following error is thrown in the kong gateway pod:

`2022/10/11 12:24:52 [error] 1113#0: *16687 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.224.0.6, server: kong, request: "GET /inspector HTTP/2.0", upstream: "http://10.0.181.253:80/inspector", host: "testing.example.net"`

When disabling mTls in the Service Mesh the error changes to:

`2022/10/12 08:27:41 [error] 1113#0: *53214 upstream prematurely closed connection while reading response header from upstream, client: 10.224.0.6, server: kong, request: "GET /inspector HTTP/2.0", upstream: "http://10.0.220.141:443/inspector", host: "testing.example.net"`

After removing the second ingress rule the error is gone.

**This is one ingress and service rule which is deployed:**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inspector-ingress
  namespace: testing
  annotations:
    cert-manager.io/cluster-issuer: acme-http01-cert-issuer
spec:
  ingressClassName: kong
  tls:
  - hosts:
    - testing.example.net
    secretName: acme-http01-cert-issued
  rules:
  - host: testing.example.net
  - http:
      paths:
      - path: /inspector
        pathType: ImplementationSpecific
        backend:
          service:
            name: inspector
            port:
              number: 80
      - path: /inspector
        pathType: ImplementationSpecific
        backend:
          service:
            name: inspector
            port:
              number: 443
```

```
apiVersion: v1
kind: Service
metadata:
  name: inspector
  namespace: testing
  labels:
    app: inspector
spec:
  selector:
    app: inspector
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
```

These are my basic kuma service mesh settings:
```
# Basic values.yaml configuration for Kong for Kubernetes (with the ingress controller)

image:
  repository: kong
  tag: "3.0"

env:
  prefix: /kong_prefix/
  database: "off"
  log_level: "debug"

ingressController:
  enabled: true
  installCRDs: false
  image:
    tag: "2.7"

podAnnotations:
  kuma.io/gateway: enabled
  kuma.io/sidecar-injection: enabled
```

### Expected Behavior

I would expect that all routes that have been declared in the ingress manifest are working.

### Steps To Reproduce

```markdown
1. Add one ingress rule --> All is working as expected
2. Add second ingress rule --> None of both routes are working
3. Remove second ingress rule --> All is working as expected again
```

### Anything else?

- Kubernetes Service on Azure (1.23.12)
