### ISSUE TITLE
Zipkin: Global sample ratio overrides route-specific

### ISSUE THREAD

**Issue by taind772** [Kong/kong#9812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

I'm facing the same problem as https://github.com/Kong/kong-plugin-zipkin/issues/106

Configure:
```YAML
# global plugin
apiVersion: configuration.konghq.com/v1
config:
  default_header_type: b3
  header_type: b3
  sample_ratio: 0
kind: KongClusterPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
  name: global-zipkin
plugin: zipkin
---
# route plugin
apiVersion: configuration.konghq.com/v1
config:
  default_header_type: b3-single
  header_type: b3-single
  sample_ratio: 0.5
kind: KongPlugin
metadata:
  name: rt-echo-service-api-zipkin
  namespace: taind-lab
plugin: zipkin
```
After configuring my service like this, I always get a **b3-single** ( not b3) trace id header with sample bit equals 0.
