### ISSUE TITLE
Kong plugin request-transformer doesn't add header to upstream target

### ISSUE THREAD

**Issue by ew-kislov** [Kong/kong#9872]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

2.6

### Current Behavior

I'm trying to add customer header when kong is redirecting request to upstream target but that header is not added.
Here is kong.yml file I'm using:
```
_format_version: "1.1"

_transform: true

upstreams:
- name: game_upstream
  targets:
  - target: some-microservice.com:80


services:
- name: game_service
  host: game_upstream
  path: /api/
  routes:
  - paths:
    - /game/


plugins:
- name: request-transformer
  config: 
    add:
      headers:
      - a:b
      querystring:
      - a:b
```

I print headers for each request in my upstream microservice and I don't see there header "a" with value "b", although according to documentation it must be.

I've tried everything(changing kong version, changing format version, removing path param from service, etc) but nothing works.

However!!! If I change config in such way that it contains only service, without upstream, then header "a": "b" is added to microservice.
Here is the kong.yml for this case:
```
_format_version: "1.1"

_transform: true

services:
- name: game
  url: https://some-microservice.com/
  routes:
  - name: game
    paths:
    - /game

plugins:
- name: request-transformer
  config: 
    add:
      headers:
      - a:b
      querystring:
      - a:b
```

Please fix this bug or tell me what I'm doing wrong.

### Anything else?

It's not a problem with request-transformer plugin, because when I replaced this plugin with my custom plugin that adds headers to request, I still got the same behaviour
