### ISSUE TITLE
invalid "configuration_hash" despite valid configuration

### ISSUE THREAD

**Issue by epikur-io** [Kong/kong#9879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.1

### Current Behavior

When I provide a valid (e.g. minimal Kong declarative configuration as yaml file in Kong DB-less mode), and call the `/status` Admin API endpoint, I get a invalid "configuration_hash", e.g.:

```
"configuration_hash": "00000000000000000000000000000000",
```

### Expected Behavior

As the documentation states (https://docs.konghq.com/gateway/latest/admin-api/#health-routes see section "configuration_hash") : "The special return value “00000000000000000000000000000000” means Kong does not currently have a valid configuration loaded."

I expected a valid configuration_hash value.

### Steps To Reproduce

Example kong config for step 1:
```yaml
_format_version: "3.0"

services:
  - name: test-service01
    url: http://httpbin/get
    routes:
      - name: my-route
        paths:
          - /route01
```

```markdown
1. Start a Kong 3.0.1 docker container with a minimal config (like 1 service + 1 route)
2. Request the Admin API `/status` 
3. Configuration_hash value will be "00000000000000000000000000000000"
```
