### ISSUE TITLE
Route matching is not 'matches the most rules'

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#9914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.1

### Current Behavior

Suppose I have configured the services/routes below and do the request and got the response:

Request: `/foo/bar`
Response:
`{
	"msg": "you entered /foo"
}`

The expected result should be `{
	"msg": "you entered /foo/bar"
}` which is what Kong 2.8 do.

I modified the route `~/any$` to a non-regular expressed route, like `/any`, then I can get the expected result which is 
`{
	"msg": "you entered /foo/bar"
}`

```yaml
services:
- name: foo-bar-service
  url: http://localhost/
  routes:
    - name: foo-bar
      paths:
        - "~/foo/bar$"
      plugins:
        - name: request-termination
          config:
            status_code: 200
            body: '{"msg":"you entered /foo/bar"}'

- name: foo-service
  url: http://localhost/
  plugins:
  routes:
    - name: foo
      paths:
        - "/foo"
        - "~/any$"
      plugins:
        - name: request-termination
          config:
            status_code: 200
            body: '{"msg":"you entered /foo"}'
```

### Expected Behavior

Routing policy should matches the most rules, to get `{
	"msg": "you entered /foo/bar"
}` if the request is `/foo/bar`

### Steps To Reproduce

```markdown
List in Current Behavior
```

### Anything else?

```
------------- Unexpected result 3.0.1 -----------------
kong@localhost:kong> select name, paths from routes;
+-------------+--------------------+
| name        | paths              |
|-------------+--------------------|
| foo         | ['/foo', '~/any$'] |
| foo-bar     | ['~/foo/bar$']     |
+-------------+--------------------+

curl http://localhost:8080/foo/bar
{"msg":"you entered /foo"}


------------- Expected result 2.8.3 -----------------
-------------------------------
kong@localhost:kong> select name, paths from routes;
+-------------+------------------+
| name        | paths            |
|-------------+------------------|
| foo-bar     | ['~/foo/bar$']   |
| foo         | ['/foo', '/any'] |
+-------------+------------------+
 curl http://localhost:8080/foo/bar
{"msg":"you entered /foo/bar"}

```
