### ISSUE TITLE
Custom Go plugin .socket failed (111: Connection refused) on kong-gateway:3.1.X.X

### ISSUE THREAD

**Issue by louistwiice** [Kong/kong#9981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong-gateway:3.1.1.1

### Current Behavior

kong-gateway    | nginx: [warn] [kong] [C]:-1 [Penlight 1.13.1] the contents of module 'pl.xml' has been deprecated, please use a more specialized library instead (deprecated after 1.11.0, scheduled for removal in 2.0.0)
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: using the "epoll" event method
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: openresty/1.21.4.1
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: built by gcc 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: OS: Linux 5.15.49-linuxkit
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: start worker processes
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: start worker process 2178
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: start worker process 2179
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: start worker process 2180
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: start worker process 2181
kong-gateway    | 2022/12/20 09:30:44 [notice] 1#0: start worker process 2182
kong-gateway    | 2022/12/20 09:30:50 [notice] 2182#0: *5 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2181#0: *4 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2178#0: *1 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2179#0: *2 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2180#0: *3 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2178#0: *1 [lua] warmup.lua:111: single_dao(): Preloading 'services' into the core_cache..., context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2181#0: *4 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2180#0: *3 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2178#0: *1 [lua] warmup.lua:152: single_dao(): finished preloading 'services' into the core_cache (in 39ms), context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2179#0: *2 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2181#0: *4 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2180#0: *3 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2178#0: *1 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2179#0: *2 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2178#0: *1 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2182#0: *5 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2178#0: *309 [lua] warmup.lua:43: warming up DNS entries ..., context: ngx.timer
kong-gateway    | 2022/12/20 09:30:50 [notice] 2182#0: *5 [lua] license_helpers.lua:155: read_license_info(): [license-helpers] could not decode license JSON: No license found, context: init_worker_by_lua*
kong-gateway    | 2022/12/20 09:30:50 [notice] 2178#0: *595 [kong] process.lua:259 Starting go-auth, context: ngx.timer
kong-gateway    | 2022/12/20 09:30:50 [error] 2178#0: *596 connect() to unix:/usr/local/kong/go-auth.socket failed (111: Connection refused), context: ngx.timer
kong-gateway    | 192.168.208.1 - - [20/Dec/2022:09:30:50 +0000] "GET /graphql/ HTTP/1.1" 404 48 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"

### Steps To Reproduce

```markdown
1. Create go file `go-auth.go`

go mod init custom-auth
go get -u github.com/Kong/go-pdk
go get -u github.com/golang-jwt/jwt/v4
go get -u github.com/lib/pq
go get -u github.com/Kong/go-pdk/server


package main

import (
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/Kong/go-pdk"
	"github.com/Kong/go-pdk/server"
	"github.com/golang-jwt/jwt/v4"
	_ "github.com/lib/pq"
)

type AuthDBConfig struct {
	DBHost 		string `json:"db_host"`
	DBPort 		int     `json:"db_port"`
	DBUser		string  `json:"db_user"`
	DBPassword	string  `json:"db_password"`
	DBName		string  `json:"db_name"`
}

const Version = "1.0.0"
const Priority = 1

func New() interface{} {
	return &AuthDBConfig{}
}

func IsTokenValid(bearerToken string) (string, error) {
	if len(strings.Split(bearerToken, " ")) != 2 {
		return "", errors.New("token in wrong format")
	}
	tokenString := strings.Split(bearerToken, " ")[1]

	token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return []byte("secret_1234567899"), nil
	})

	if err != nil {
		return "", err
	}
	if claim, ok := token.Claims.(jwt.MapClaims); ok && token.Valid {
		return claim["sub"].(string), nil
	}
	return "", err
}

func (config *AuthDBConfig) Access(kong *pdk.PDK){
	var username string
	var email string
	respHeaders := make(map[string][]string)

	respHeaders["Content-Type"] = append(respHeaders["Content-Type"], "application/json")

	authorization, err := kong.Request.GetHeader("authorization")

	if err != nil {
		kong.Response.Exit(401, "Unauthorized: authorization header is missing", respHeaders)
	}

	user_id, err := IsTokenValid(authorization)
	if err != nil {
		kong.Response.Exit(400, fmt.Sprintf("Token error: %s", err.Error()), respHeaders)
	}
	db_setting := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable", config.DBHost, config.DBPort, config.DBUser, config.DBPassword, config.DBName)
	db, err := sql.Open("postgres", db_setting)

	if err != nil {
		kong.Response.Exit(400, fmt.Sprintf("DB error: %s", err.Error()), respHeaders)
	}
	defer db.Close()

	sqlStatement := `SELECT username, email FROM users WHERE id=$1;`
	result := db.QueryRow(sqlStatement, user_id)
	switch err := result.Scan(&username, &email); err {
	case sql.ErrNoRows:
		kong.Response.Exit(401, "Unauthorized: User not found", respHeaders)
	default:
		kong.Response.Exit(401, fmt.Sprintf("Unknown error: %s", err.Error()), respHeaders)
	}

	kong.Response.SetHeader("Authorization", authorization)
}

func main() {
	server.StartServer(New, Version, Priority)
}
```

2. Build the go file
GOOS=linux GOARCH=amd64 go build . 

3. Create the docker-compose file

```
# https://docs.konghq.com/gateway/latest/install/docker/#install-kong-gateway-with-a-database
# https://github.com/Kong/docker-kong/blob/master/compose/docker-compose.yml
version: '3.9'

services:
  db:
    container_name: kong-db
    hostname: kong-db
    image: postgres:alpine
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: passer1234

  kong-bootstrap:
    container_name: kong-bootstrap
    hostname: kong-bootstrap
    image: kong/kong-gateway:3.1.1.1
    command: "kong migrations bootstrap"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: passer1234
      KONG_PASSWORD: test
    depends_on:
      - db

  kong-gateway:
    container_name: kong-gateway
    hostname: kong-gateway
    image: kong/kong-gateway:3.1.1.1
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: passer1234
      KONG_PLUGINS: go-auth # add for custom plugin management
      KONG_PLUGINSERVER_NAMES: go-auth # add for custom plugin management
      #KONG_PLUGINSERVER_GO_AUTH_SOCKET: /usr/local/kong/go-auth.socket # add for custom plugin management
      KONG_PLUGINSERVER_GO_AUTH_START_CMD: /usr/local/bin/go-auth # add for custom plugin management
      KONG_PLUGINSERVER_GO_AUTH_QUERY_CMD: "/usr/local/bin/go-auth -dump" # add for custom plugin management
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_ADMIN_GUI_URL: http://localhost:8002
    depends_on:
      - kong-bootstrap
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    volumes:
      - ./go-auth:/usr/local/bin/go-auth

networks:
  default:
    name: kong-net
```
```


### Anything else?

_No response_

**Comment by louistwiice** [comment]
Hello guyz! 

Do you know how I can make this thing work please ?

**Comment by StarlightIbuki** [comment]
Hi. We've confirmed that this is caused by #9507.
When the gateway tries to check if the socket is ready (and for the first few times it's very likely not ready), this Message is generated by the connect call to the socket.
Though the message is of error level, it should be harmless. We are considering the fix.

**Comment by StarlightIbuki** [comment]
We have configured `ngx.socket` to not emit error logs, but it does not take effect on `connect`. This is considered an issue of OpenResty: https://github.com/openresty/lua-nginx-module/issues/2138

**Comment by louistwiice** [comment]
Hi, thank you for your reply

I feel like the socket is never ready. Because when I link the plugin to a route I receive the following

`
kong-gateway    | 2023/01/02 18:09:36 [warn] 2181#0: *832 [lua] process.lua:292: handle_event(): plugin server is not ready, go-auth will not be executed in this request, client: 172.24.0.1, server: kong, request: "GET /auth/ HTTP/1.1", host: "localhost:8000"
`

The plugin is created successfully. I have set it up. But I try to request any service linked to the plugin I got this

**Comment by StarlightIbuki** [comment]
> 

You may check if the process is running with the PS command. And maybe you need to make sure that the socket file path is correct. You can do that by starting the go plugin server manually and it should print the path that it listens to.

**Comment by louistwiice** [comment]
Thank you for the fast reply @StarlightIbuki 

As ps is not install in the docker container I have started the plugin manually. It seems there is no error. Even with a basic hello-wold plugin, I have the same result

`
kong@kong-gateway:/$ /usr/local/bin/go-auth -dump
{"Protocol":"ProtoBuf:1","SocketPath":"/usr/local/kong/go-auth.socket","Plugins":[{"Name":"go-auth","Phases":["access"],"Version":"1.0.0","Priority":1,"Schema":{"name":"go-auth","fields":[{"config":{"type":"record","fields":[{"db_host":{"type":"string"}},{"db_port":{"type":"integer"}},{"db_user":{"type":"string"}},{"db_password":{"type":"string"}},{"db_name":{"type":"string"}},{"jwt_secret_key":{"type":"string"}}]}}]}}]}
kong@kong-gateway:/$ 
kong@kong-gateway:/$ 
kong@kong-gateway:/$ /usr/local/bin/go-auth
2023/01/03 11:17:28 Listening on socket: /usr/local/kong/go-auth.socket
`

**Comment by louistwiice** [comment]
Hello guyz!!

Does anybody have an idea about this please? Or maybe I am missing some part in my settings

**Comment by StarlightIbuki** [comment]
> Hello guyz!!
> 
> Does anybody have an idea about this please? Or maybe I am missing some part in my settings

Hi. We are investigating the issue. This could be a bug.

**Comment by StarlightIbuki** [comment]
It seems that you are using an enterprise image (4 digits version). The correct tag for the community image should be `kong/kong` instead of `kong/kong-gateway`.
And this is a known issue of EE that we are fixing.

**Comment by louistwiice** [comment]
Hi @StarlightIbuki 

Oh, thanks. I got it now. i'll test with the community image and come back to you within an hour.

Thanks again

**Comment by louistwiice** [comment]
Hi all,

I tried to create a simple custom golang plugin with the community image (kong:latest) as recommanded by following those steps

**1. Golang plugin code**

```
package main

import (
	"github.com/Kong/go-pdk"
	"github.com/Kong/go-pdk/server"
)


type Config struct {
	Name 		    string  `json:"name"`
	Age 		    int     `json:"age"`
}

func New() interface{} {
	return &Config{}
}

func (conf *Config) Access (kong *pdk.PDK) {
	kong.Log.Info("Access DB: go-auth")
	_ = kong.Response.SetHeader("This-Is-It", "Set by custom go plugin - Good Job")
}


func main () {
	Version := "1.1"
	Priority := 1000
	_ = server.StartServer(New, Version, Priority)
}
```

**2. Build the plugin**
`GOOS=linux GOARCH=amd64 go build .`

**3. Prepare the docker compose file**
I have cloned the [docker-kong repo](https://github.com/Kong/docker-kong) and added lines to parse the custom plugin into my container

`cd <repo>/compose`
`nano docker-compose.yml`

```
version: '3.9'

x-kong-config: &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-off}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: db
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password

volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
     type: tmpfs
     device: tmpfs
  kong_tmp_vol:
    driver_opts:
     type: tmpfs
     device: tmpfs

networks:
  kong-net:
    external: false

services:
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    profiles: ["database"]
    depends_on:
      - db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    profiles: ["database"]
    depends_on:
      - db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
      KONG_PLUGINS: go-test  # <=== New line added
      KONG_PLUGINSERVER_NAMES: go-test  # <=== New line added
      KONG_PLUGINSERVER_GO_TEST_START_CMD: /usr/local/bin/go-test  # <=== New line added
      KONG_PLUGINSERVER_GO_TEST_QUERY_CMD: "/usr/local/bin/go-test -dump"  # <=== New line added
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    ports:
      # The following two environment variables default to an insecure value (0.0.0.0)
      # according to the CIS Security test.
      - "${KONG_INBOUND_PROXY_LISTEN:-0.0.0.0}:8000:8000/tcp"
      - "${KONG_INBOUND_SSL_PROXY_LISTEN:-0.0.0.0}:8443:8443/tcp"
      # Making them mandatory but undefined, like so would be backwards-breaking:
      # - "${KONG_INBOUND_PROXY_LISTEN?Missing inbound proxy host}:8000:8000/tcp"
      # - "${KONG_INBOUND_SSL_PROXY_LISTEN?Missing inbound proxy ssl host}:8443:8443/tcp"
      # Alternative is deactivating check 5.13 in the security bench, if we consider Kong's own config to be enough security here

      - "127.0.0.1:8001:8001/tcp"
      - "127.0.0.1:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
      - ./config:/opt/kong
      - ./go-test:/usr/local/bin/go-test  # <=== New line added
    security_opt:
      - no-new-privileges

  db:
    image: postgres:9.5
    profiles: ["database"]
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data

secrets:
  kong_postgres_password:
    file: ./POSTGRES_PASSWORD
```

After running it with `docker-compose up`
```
[+] Running 4/4
 ⠿ Network compose_kong-net          Created                                                                                                       0.1s
 ⠿ Volume "compose_kong_prefix_vol"  Created                                                                                                       0.0s
 ⠿ Volume "compose_kong_tmp_vol"     Created                                                                                                       0.0s
 ⠿ Container compose-kong-1          Created                                                                                                       0.2s
Attaching to compose-kong-1
compose-kong-1  | 2023/01/09 11:55:58 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /var/run/kong/nginx.conf:6
compose-kong-1  | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /var/run/kong/nginx.conf:6
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1#0: using the "epoll" event method
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1#0: openresty/1.21.4.1
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1#0: built by gcc 6.4.0 (Alpine 6.4.0) 
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1#0: OS: Linux 5.19.0-26-generic
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1#0: start worker processes
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1#0: start worker process 1131
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1131#0: *1 [lua] init.lua:240: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1131#0: *1 [lua] init.lua:240: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1131#0: *1 [kong] init.lua:493 declarative config loaded from /opt/kong/kong.yaml, context: init_worker_by_lua*
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1131#0: *148 [kong] process.lua:252 Starting go-test, context: ngx.timer
compose-kong-1  | 2023/01/09 11:55:59 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1131#0: signal 17 (SIGCHLD) received from 1132
compose-kong-1  | 2023/01/09 11:55:59 [notice] 1131#0: *148 [kong] process.lua:268 external pluginserver 'go-test' terminated: exit 0, context: ngx.timer
compose-kong-1  | 2023/01/09 11:55:59 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:55:59 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [notice] 1131#0: *148 [kong] process.lua:252 Starting go-test, context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [notice] 1131#0: signal 17 (SIGCHLD) received from 1136
compose-kong-1  | 2023/01/09 11:56:00 [notice] 1131#0: *148 [kong] process.lua:268 external pluginserver 'go-test' terminated: exit 0, context: ngx.timer
compose-kong-1  | 2023/01/09 11:56:00 [crit] 1131#0: *149 connect() to unix:/usr/local/kong/go-test.socket failed (2: No such file or directory), context: ngx.timer
```

I have tried to go inside the container to run it manually but I receive `read-only file system`

```
home@computer:~$ docker exec -it compose-kong-1 bash
bash-5.1$ /usr/local/bin/go-test --dump
{"Protocol":"ProtoBuf:1","SocketPath":"/usr/local/kong/go-test.socket","Plugins":[{"Name":"go-test","Phases":["access"],"Version":"1.1","Priority":1000,"Schema":{"name":"go-test","fields":[{"config":{"type":"record","fields":[{"name":{"type":"string"}},{"age":{"type":"integer"}}]}}]}}]}
bash-5.1$ /usr/local/bin/go-test
2023/01/09 11:58:16 removing "/usr/local/kong/go-test.socket": remove /usr/local/kong/go-test.socket: read-only file system
bash-5.1$ 
```

It's like kong can not create the socket file, so the server can not find it and does not run. There is no permission on my file
```
bash-5.1$ ls -l /usr/local/bin/
total 10132
-rwxr-xr-x    1 1000     1000      10357974 Jan  6 17:08 go-test
-rwxr-xr-x    1 kong     root           238 Dec  9 23:59 kong
-rwxr-xr-x    1 1000     1000           460 Dec  9 23:59 lapis
lrwxrwxrwx    1 root     root            38 Dec 12 20:41 lua -> /usr/local/openresty/luajit/bin/luajit
lrwxrwxrwx    1 root     root            38 Dec 12 20:41 luajit -> /usr/local/openresty/luajit/bin/luajit
-rwxr-xr-x    1 1000     1000          1482 Dec  9 23:16 luarocks
-rwxr-xr-x    1 1000     1000           964 Dec  9 23:16 luarocks-admin
lrwxrwxrwx    1 root     root            37 Dec 12 20:41 nginx -> /usr/local/openresty/nginx/sbin/nginx
lrwxrwxrwx    1 root     root            30 Dec 12 20:41 resty -> /usr/local/openresty/bin/resty
```

I even try to set my plugin file to kong user but it doesn't help. It gives the same result
