### ISSUE TITLE
Kong Ingress controller 2.8 doesn't recognize named backend service port 

### ISSUE THREAD

**Issue by balagopalan40** [Kong/kong#9997]
## Bug description

We recently upgraded to Kong Helm chart version [2.14.0](https://github.com/Kong/charts/releases/tag/kong-2.14.0)
The charts uses kubernetes-ingress-controller:2.8

We see the following error in KIC.

> time="2022-12-21T17:17:56Z" level=error msg="resource processing failed: can't find port for backend kubernetes service: no suitable port found" GVK="/v1, Kind=Service" name=tex-caddy namespace=development
> 
> time="2022-12-21T17:17:56Z" level=error msg="resource processing failed: can't find port for backend kubernetes service: no suitable port found" GVK="networking.k8s.io/v1, Kind=Ingress" name=tex-caddy namespace=development
> 
> time="2022-12-21T17:17:56Z" level=info msg="no targets found to create upstream" service_name=development.tex-caddy.tex-caddy.0

## Expected behavior

We solved the error by changing our ingress config to `service.port.number`

https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  ingressClassName: kong
  rules:
  - host: my-host.com
    http:
      paths:
      - backend:
          service:
            name: tex-caddy
            port:
              #name: http
              number: 80 # Using `service.port.number` instead of `service.port.name` solves the error.
        path: /
        pathType: ImplementationSpecific
```

FYI : @dhpalan

**Comment by dhpalan** [comment]
Hey @czeslavo The service does have a port named http. See the yaml.

Please note that KIC 2.7 works fine with the ingress with `service.port.name`.
Once we updated to KIC 2.8, we see the error and we were able to make it work by using `service.port.number`

Let me know if you would like to get some details from our K8s and i can help you with it.

kubectl get svc tex-caddy -o yaml
```yaml
apiVersion: v1
kind: Service
spec:
  clusterIP: 10.0.234.121
  clusterIPs:
  - 10.0.234.121
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    ...
  sessionAffinity: None
  type: ClusterIP

```
